### ISSUE TITLE
module 'pyproj' has no attribute 'CRS'

### ISSUE THREAD

**Issue by SilverLyan** [pyproj4/pyproj#1000]
I am using MacOS, python 3.6.3

Here are my libs and their version:
appnope (0.1.0)
attrs (21.2.0)
certifi (2016.2.28)
click (6.7)
click-plugins (1.0.3)
cligj (0.7.2)
cycler (0.10.0)
decorator (4.1.2)
descartes (1.1.0)
Fiona (1.8.13.post1)
GDAL (3.0.2)
geopandas (0.4.0)
ipykernel (4.6.1)
ipython (6.1.0)
ipython-genutils (0.2.0)
jedi (0.10.2)
jupyter-client (5.1.0)
jupyter-core (4.3.0)
kiwisolver (1.3.1)
matplotlib (3.3.1)
mkl-fft (1.3.0)
mkl-random (1.1.1)
mkl-service (2.3.0)
munch (2.2.0)
numpy (1.19.2)
olefile (0.44)
pandas (0.20.3)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (8.3.1)
pip (9.0.1)
prompt-toolkit (1.0.15)
psycopg2 (2.6.2)
ptyprocess (0.5.2)
Pygments (2.2.0)
pyparsing (2.2.0)
pyproj (3.0.0)
PySAL (1.13.0)
python-dateutil (2.6.1)
pytz (2017.2)
pyzmq (16.0.2)
Rtree (0.9.7)
scipy (1.5.2)
setuptools (36.4.0)
Shapely (1.7.1)
simplegeneric (0.8.1)
six (1.10.0)
SQLAlchemy (1.1.13)
tornado (4.5.2)
traitlets (4.3.2)
wcwidth (0.1.7)
wheel (0.29.0)

**Comment by snowman2** [comment]
Mind filling this out?
 - Installation method (conda, pip wheel, from source, etc...)
 - How did you install PROJ? Where is it installed?
 - Please provide all commands/steps you used to install pyproj and PROJ.

**Comment by snowman2** [comment]
I also want to note that pyproj supports Python 3.8+ (#930). I recommend upgrading your Python version and pyproj version.

**Comment by SilverLyan** [comment]
> I also want to note that pyproj supports Python 3.8+ (#930). I recommend upgrading your Python version and pyproj version.

Dear Alan, I solve this problem by directly create a new env with installing geopandas 0.9.0.
Thanks very much!

**Comment by snowman2** [comment]
Glad to hear that you were able to resolve the issue 👍
