### ISSUE TITLE
bugs, the same epsg output different values

### ISSUE THREAD

**Issue by Mon-ius** [pyproj4/pyproj#1008]
'''
from pyproj import CRS
from pyproj import Transformer

x = (17.888058560281515)
y = (46.89226406700879)
WGS84 = CRS.from_epsg(4326)
EPSG_23700 = CRS.from_epsg(23700)

print(Transformer.from_crs(WGS84, EPSG_23700).transform(x,y))
print(Transformer.from_crs(CRS.from_proj4(WGS84.to_proj4()), EPSG_23700).transform(x,y))
'''

Currently, I tried to write code related to proj4, when I compared pyproj and proj4dart, I found some values are quite different. Here , I choose a typical example.

**Comment by snowman2** [comment]
The `always_xy=True` option in `Transformer.from_crs` should make the output consistent.

Useful references:
- https://pyproj4.github.io/pyproj/stable/gotchas.html#what-are-the-best-formats-to-store-the-crs-information
- https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6

**Comment by snowman2** [comment]
Closing as I believe this has been resolved. Feel free to ask more questions if you need clarification.
