### ISSUE TITLE
RuntimeError: b"no options found in 'init' file

### ISSUE THREAD

**Issue by mohmad-null** [pyproj4/pyproj#101]
pyproj-1.9.5.1

If I try and convert from EPSG:404000 to epsg:4326, I get:
```
post_process_xml - ERROR - Coordinate changing raised an exception
Traceback (most recent call last):
  File "E:/X_Dev/ogc__xml_to_es/src\post_process_xml.py", line 219, in change_coords
    start = pyproj.Proj(init=start_proj)
  File "C:\Python35\lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 122, in _proj.Proj.__cinit__ (_proj.c:1578)
RuntimeError: b"no options found in 'init' file"
```

I'm reasonably confident that this is because the given EPSG (404000) isn't in the proj file (that's what pywps suggests anyway - http://wiki.rsg.pml.ac.uk/pywps/Mapserver ).

However, I'd like to suggest that if that's the case, the exception raised should make this clear, ideally with a unique exception so it can be handled separately from exceptions where the install is bad or bad data is sent to it which also seem to raise a RuntimeError.

**Comment by micahcochran** [comment]
> I'm reasonably confident that this is because the given EPSG (404000) isn't in the proj file 

It is the [epsg file](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/data/epsg),  and you are correct that EPSG:404000 (or <404000> in this case) isn't in there.

> However, I'd like to suggest that if that's the case, the exception raised should make this clear, ideally with a unique exception so it can be handled separately from exceptions where the install is bad or bad data is sent to it which also seem to raise a RuntimeError.

My initial thought is to like the idea of distinguishing between a bad proj string, and an improper installation.  My quick look at PROJ.4 suggests that this might be hard to change in pyproj.  

If you try to do what you described from PROJ.4's cs2cs command,  you'd have a command line like this which gives an errors like this:
```
C:\Users\mcochran\Desktop>cs2cs +init=epsg:4326 +to +init=epsg:404000
Using to definition: init=epsg:404000
Rel. 4.9.3, 15 August 2016
<cs2cs>:
projection initialization failure
cause: Unknown error
program abnormally terminated
```

Thus where the "init" part of the error comes from.  There are also esri numeric codes, which are in the esri file. "+init=esri:26916"

That error ["no options found in 'init' file"](https://github.com/OSGeo/proj.4/blob/44c611c574f001267cd39c904c081e8f1f0d8c96/src/pj_strerrno.c#L10) code come from PROJ.4.  

I'm not sure that PROJ.4 knows if epsg and related files are installed.  If that is true,  it would be very cumbersome to make pyproj know if PROJ.4 has access to those file.

**Comment by KyriakosZantis** [comment]
Hello,
I am trying to run this Proj(init='epsg:6312'). 

the console prints me this message

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    outProj = Proj(init='epsg:6312')
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1170)
RuntimeError: no options found in 'init' file


but the system 6312  exist at line https://github.com/jswhit/pyproj/blob/78540f5ff40da92160f80860416c91ee74b7643c/lib/pyproj/data/epsg#L6103
I am doing something wrong?

**Comment by mayanksuman** [comment]
In my case, the conversion to or from `EPSG:54032` leads to this runtime error on `pyproj: 1.9.6`, however my system `PROJ.4 (5.2.0)` can use this crs. For instance
```
echo 55.2 12.2 | proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
```
produces `6039191.49	1581288.50`. The proj string is obtained from `gdalsrsinfo epsg:54032`.

So, this error in `pyproj` do not come from system PROJ.4 but from included older version PROJ.4 source file ([this line](https://github.com/jswhit/pyproj/blob/17051a28457abd24466201e70eb5e0e97ad9d16a/src/pj_init.c#L412)). 

Why do pyproj ship its own version of PROJ.4? System PROJ.4 is usually more updated with crs code and other enhancements.

**Comment by micahcochran** [comment]
@mayanksuman Your example of using the longer verson of the proj string with proj isn't a good example.

EPSG:54032 is not in the [data/epsg file](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/data/epsg) for pyproj, so therefore it doesn't recognize the projections sting.  (Nor is it in the Proj 5.2.0 data/epsg file.)

When I use Proj 5.2.0 with the equivalent command line argument.  It gives an error.
```
C:\Users\mcochran\Desktop>echo 55.2 12.2 | proj +init=epsg:54032
Rel. 5.2.0, September 15th, 2018
<proj>:
projection initialization failure
cause: invalid projection system error (-9999)
program abnormally terminated
```

Still, you can use `Proj("+proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs")`

>Glad to hear that removing PROJ.4 is being considered.

I'm glad, too.  The datum grid files should also be a github link to the [newish repository for those](https://github.com/OSGeo/proj-datumgrid), too.

**Comment by snowman2** [comment]
Current version (pyproj==2.1.0) error message seems to be a little more clear:
```python
>>> p1 = pyproj.Proj("EPSG:404000")
proj_create: crs not found
Traceback (most recent call last):
...
pyproj.exceptions.CRSError: Invalid projection: epsg:404000
```

**Comment by snowman2** [comment]
Closing as the error messages are more clear now. Thanks for the report!
