### ISSUE TITLE
Inverse of transform_bounds?

### ISSUE THREAD

**Issue by Langdi** [pyproj4/pyproj#1016]
I am running the following code, to transform coordinates and then transform back:

```python
from pyproj import Transformer  # pip install pyproj

transformer = Transformer.from_crs('epsg:31287', 'epsg:4326', always_xy=True)

xy = (20000, 220000, 720000, 620000)

latlon_calc = transformer.transform_bounds(*xy)
# (8.098133748352293, 45.77222010581118, 17.742270413233744, 49.478175684609575)
print(latlon_calc)

xy_calc = transformer.transform_bounds(*latlon_calc, direction='INVERSE')
# (-6886.507570019981, 208026.8559271988, 742834.1097974807, 632792.5705761225)
print(xy_calc)
```

Unfortunately, the values in `xy` and `xy_calc` don't match. Especially the first value seems striking to me, because it's originally positive, but negative after the two transformations. The other values seem similar, however the difference is still more than I would expect due to rounding etc. 

Am I doing something wrong or can someone explain, why these values don't match? Or is it a bug?

**Comment by snowman2** [comment]
The images in this question are useful to demonstrate as well: https://gis.stackexchange.com/questions/413816/mask-raster-with-bounding-box-from-a-different-crs/413823
