### ISSUE TITLE
CRS.from_user_input does not accept numpy-integers

### ISSUE THREAD

**Issue by raphaelquast** [pyproj4/pyproj#1026]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
from pyproj import CRS
import numpy as np

crs_input = 4326
crs_numpy_input = np.array([4326])[0]


crs1 = CRS.from_user_input(crs_input )

crs2 = CRS.from_user_input(crs_numpy_input)
```

```python
>>> CRSError: Invalid CRS input: 4326
```

#### Problem description

The (really nice) `CRS.from_user_input` function does not accept numpy-integers...
I guess it should be an easy fix to include `np.integer` as possible dtype.

#### Expected Output

I'd expect numpy-integers to be treated similar to python integers.

#### Environment Information

 - Output from: `pyproj -v`

pyproj info:
    pyproj: 3.2.1
    PROJ: 8.2.0

System:
    python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:37:49) [MSC v.1916 64 bit (AMD64)]
executable: D:\miniconda\envs\...\python.exe
   machine: Windows-10-10.0.17763-SP0

Python deps:
   certifi: 2021.10.08
       pip: 22.0.2
setuptools: 59.8.0
    Cython: None

**Comment by snowman2** [comment]
Since pyproj doesn't have a dependency on numpy, it probably needs a check like this:

https://github.com/pyproj4/pyproj/blob/8f0e1f7ddc5ba5a1992f939f91bb9ea023316219/pyproj/utils.py#L117
