### ISSUE TITLE
Unable to install pyproj on mac pro m1

### ISSUE THREAD

**Issue by junaidq1** [pyproj4/pyproj#1027]
#### Code Sample, a copy-pastable example if possible

Not being able to install pyproj on an m1 mac using pip install pyproj

Here's the error

```python
Building wheels for collected packages: pyproj
  Building wheel for pyproj (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyproj (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      PROJ_DIR is set, using existing PROJ installation..
      
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'pyproj._geod' extension
      pyproj/_geod.c:704:10: fatal error: 'geodesic.h' file not found
      #include "geodesic.h"
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyproj
Failed to build pyproj
ERROR: Could not build wheels for pyproj, which is required to install pyproject.toml-based projects
```
#### Problem description

I was successfully able to install proj using brew but can't seem to get this to work

#### Installation method
 - pip

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ junaidq1@gmail.com

```
</details>

**Comment by snowman2** [comment]
Probably need to install from source: https://pyproj4.github.io/pyproj/stable/installation.html#installing-from-source

**Comment by rgreinho** [comment]
> Probably need to install from source: https://pyproj4.github.io/pyproj/stable/installation.html#installing-from-source

This does not seem to be possible:
- https://github.com/python-poetry/poetry/issues/365
- https://github.com/python-poetry/poetry/issues/1316

**Comment by snowman2** [comment]
Probably related to generating universal osx wheels on Python 10: https://github.com/pyproj4/pyproj-wheels/issues/46

Side note: Due to the issues referenced, I don't use poetry for any geospatial python projects. Instead, I use pipenv as it allows installing from source.

**Comment by rgreinho** [comment]
You're probably right. The install works with `poetry`, but it picks the wrong architecture for the `.so` library and fails at runtime:

```bash
from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: dlopen(~/projects/PeopleForBikes/measure/.venv/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so, 0x0002): tried: '~/projects/PeopleForBikes/measure/.venv/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_network.cpython-310-darwin.so' (no such file), '/usr/lib/_network.cpython-310-darwin.so' (no such file)
```

The workaround for this issue is the following:

```bash
rm -fr .venv/lib/python3.10/site-packages/pyproj*
poetry run pip install pyproj --no-binary pyproj

**Comment by NicHub** [comment]
I had the same problem and here is what worked for me:

```bash
rm $HOME/venv/bin/proj
rm $HOME/venv/bin/pyproj

cd your_project_path
curl -sSL https://install.python-poetry.org | python3 -
poetry init # Accept all defaults
poetry run pip install pyproj --no-binary pyproj
rm pyproject.toml
```

**Comment by jannismain** [comment]
Installing with poetry and the `--no-binary` option, as some of the workarounds above suggest, doesn't work for me:

```
❯ poetry run pip install pyproj --no-binary pyproj
Collecting pyproj
  Using cached pyproj-3.3.0.tar.gz (217 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Will try to build from source next.

**Comment by snowman2** [comment]
`pyproj==3.3.1` was just released and wheels shouldn't be downloaded for Mac M1 anymore.

This should work:
```
brew install proj
python -m pip install pyproj
```
If it doesn't please let us know.

**Comment by snowman2** [comment]
See: #1064

**Comment by songololo** [comment]
The above installation methods are not working for me on an M1, any advice?

Here is the error message I get, whether attempting to install via `pip install pyproj` or if trying to build from source per `pip install pyproj --no-binary pyproj`. (I use brew for `proj`):
```bash
 2 warnings generated.
      ld: warning: dylib (/opt/homebrew/lib/libproj.dylib) was built for newer macOS version (12.0) than being linked (11.0)
      ld: warning: dylib (/opt/homebrew/lib/libunwind.dylib) was built for newer macOS version (12.0) than being linked (11.0)
      ld: warning: dylib (/opt/homebrew/lib/libunwind.dylib) was built for newer macOS version (12.0) than being linked (11.0)
      ld: warning: ignoring file /opt/homebrew/lib/libproj.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
      ld: in '/opt/homebrew/lib/libunwind.dylib', building for macOS-x86_64 but attempting to link with file built for macOS-arm64
      clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by songololo** [comment]
This ended up working for me:
```bash
export PROJ_DIR=/opt/homebrew/Cellar/proj/9.0.0_1
 pip install pyproj --no-binary pyproj 
```

**Comment by snowman2** [comment]
If you have time to try out these wheels, that would be very helpful: https://github.com/pyproj4/pyproj/issues/1064#issuecomment-1184574399

Please upvote the comment if you have a positive experience and comment in #1064 if you get an opportunity to try it out and run into any issues.
