### ISSUE TITLE
BUG: get_data_dir support for conda Windows enviroments

### ISSUE THREAD

**Issue by Stophface** [pyproj4/pyproj#1029]
#### Installation method/steps
I freshley installed PyProj according to the [docs][1]

    conda config --prepend channels conda-forge
    conda config --set channel_priority strict
    conda create -n pyproj_env pyproj
    conda activate pyproj_env

When I try

    from pyproj import CRS

I get

> PyProj: pyproj unable to set database path. _pyproj_global_context_initialize()

Whats going on there?

  [1]: https://pyproj4.github.io/pyproj/stable/installation.html

#### Environment Information
 - pyproj version you are attempting to install
 - PROJ version: Rel. 8.2.1, January 1st, 2022
 - Python version: Python 3.9.7
 - Operation System Information: Windows-10-10.0.19042-SP0

**Comment by snowman2** [comment]
What is the value of the PROJ_LIB environment variable?

**Comment by Stophface** [comment]
@snowman2 Its: C:\Program Files\PostgreSQL\13\share\contrib\postgis-3.1\proj

**Comment by Stophface** [comment]
@snowman2 Thanks for the link. It seems like this is the problem. However, I am not sure how to fix it.

_To get data directory being used: [pyproj.datadir.get_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.get_data_dir)_

    import pyproj
    pyproj.datadir.get_data_dir()

> 'C:\\Program Files\\PostgreSQL\\13\\share\\contrib\\postgis-3.1\\proj'

_The order for searching for the data directory can be found in the docstrings of [pyproj.datadir.get_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.get_data_dir)_

    pyproj.datadir.get_data_dir()

> 'C:\\Program Files\\PostgreSQL\\13\\share\\contrib\\postgis-3.1\\proj'


How to know in which folder `pyproj` should look instead for the `database`? If I know the path to the folder, I set it via
`[pyproj.datadir.set_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.set_data_dir)`, right?

**Comment by Stophface** [comment]
This is how I found the `PATH` to `PROJ`

I looked into this file ...Miniconda3\envs\<ENV>\conda-meta\proj-<VERSION>-h1cfcee-<VERSION>.json and searched for \pkgs\\proj. Once found, I checked the versins of PROJ installed in this folder C:...\Miniconda3\pkgs\. There are folder named something like proj-<VERSION>-h1cfcee-<VERSION>. Make sure the folder name is the exact same name you found this file links to: ...Miniconda3\envs\<ENV>\conda-meta\proj-<VERSION>-h1cfcee-<VERSION>.json. Finally I set my environment variable to the version needed ...Miniconda3\pkgs\proj-<VERSION>-h1cfcee-<VERSION\Library\share\proj.

**Comment by snowman2** [comment]
https://github.com/pyproj4/pyproj/blob/8f0e1f7ddc5ba5a1992f939f91bb9ea023316219/pyproj/datadir.py#L75

It might not be a bad idea to better support for the Windows prefix search path. Maybe something like:
```python
conda_windows_prefix_datadir = Path(sys.prefix, "Library", "share", "proj")
```

@Stophface are you able to share the value of `sys.prefix` after activating your conda environment?

**Comment by snowman2** [comment]
Looks like adding the windows Library prefix search would be useful here: https://github.com/conda-forge/proj.4-feedstock/blob/9bf81fff5781b937f601a9f1b372f5a819f5bb38/recipe/scripts/activate.sh#L14

**Comment by Stophface** [comment]
@snowman2 Sure, I am not sure how to get it thoug. Any hints?

**Comment by snowman2** [comment]
Thanks @Stophface, that was helpful. This is something that I think should be added to the logic in pyproj to find the data directory on Windows conda environments.
