### ISSUE TITLE
CI: vcpkg for Windows on Actions

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#1033]
See: https://github.com/geopandas/pyogrio/issues/48

Probably something like this:
```
vcpkg install proj:x64-windows
```
Would probably be useful to have setup.

**Comment by jorisvandenbossche** [comment]
Is this for testing CI, or for wheels? 
For testing already have windows coverage through conda, which I think is fine (I don't think using vcpkg would give much added value over that)

**Comment by snowman2** [comment]
The main thinking is redundancy. Conda is great and the plan is to continue to be use it moving forward. However, there can, on rare occasions, be transitional phases when things break. In those scenarios, having an alternative to run tests in CI would be nice to have if it is simple enough to setup & maintain.

It is also nice to have a sanity check that everything works in both systems.

The reasoning is similar for #1014.

**Comment by snowman2** [comment]
Sounds like we are going to need this for Windows wheels:
- https://github.com/geopandas/geopandas/issues/2465
- https://github.com/pyproj4/pyproj-wheels/issues/3

I believe this is something we are gong to need for the next release.

**Comment by snowman2** [comment]
Thanks for the work y'all put in to pave the way 👍
