### ISSUE TITLE
Add definition_string() to github and pip release

### ISSUE THREAD

**Issue by andrewyushkevich** [pyproj4/pyproj#104]

**Comment by micahcochran** [comment]
The `definition_string` function is in the GitHub repository master copy.

I'm assuming that you want an official release of the repository copy.  It is probably a good time to release version 1.9.6.

**Comment by egorf** [comment]
@micahcochran 

Hi!

Is it possible for this to happen? Or maybe you have a planned release date? `definition_string()` is an extremely useful method, especially, when user is not using pyproj directly. Using  current `master` is sometimes hard due to cython dependency.

**Comment by micahcochran** [comment]
This made it into version 1.9.6.
