### ISSUE TITLE
Test underlying PROJ version, complain if unsupported

### ISSUE THREAD

**Issue by dsjstc** [pyproj4/pyproj#1043]
Although there is a documented requirement for PROJ v8, the currently available package version on Ubuntu is supplied by libproj-dev v7.2.  This causes inexplicable failures without informative error messages when using a `pip install`'d version rather than conda.

I'd suggest that at import time, there should be a test of the underlying PROJ version, throw a version mismatch error if an unsupported version of PROJ is found.

**Comment by snowman2** [comment]
I don't think that there is a good way to do what you are suggesting. The errors from using an invalid version of PROJ would prevent pyproj from checking the PROJ version and getting a helpful error message to the user.

This is currently handled at build time to prevent pyproj from being compiled against an invalid version:
https://github.com/pyproj4/pyproj/blob/b8bc61ca2924ef0cff18d19e4dbd6398c8882421/setup.py#L29-L36
