### ISSUE TITLE
Issues running test from fresh repo clone

### ISSUE THREAD

**Issue by iboates** [pyproj4/pyproj#1048]
I am looking to address a couple issues but I cannot even get the test suite to run after a fresh install. After installing `requirements.dev.txt` and `requirements-test.txt`, I get:

```
ImportError while loading conftest '/home/isaac/PycharmProjects/pyproj/test/conftest.py'.
conftest.py:8: in <module>
    import pyproj
../pyproj/__init__.py:49: in <module>
    import pyproj.network
../pyproj/network.py:8: in <module>
    import certifi
E   ModuleNotFoundError: No module named 'certifi'
```

After running `pip install certifi` and trying again, I get:

```
ImportError while loading conftest '/home/isaac/PycharmProjects/pyproj/test/conftest.py'.
conftest.py:8: in <module>
    import pyproj
../pyproj/__init__.py:49: in <module>
    import pyproj.network
../pyproj/network.py:10: in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
E   ModuleNotFoundError: No module named 'pyproj._network'
```

I am on this Ubuntu distro:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

And using a virtual environment of this Python 3.8.6.

I also tried changing the work directory from `./test` to the repository root but that also generates the 2nd error above.

Any ideas? Have I missed an install step?

**Comment by snowman2** [comment]
Did you read this?
https://github.com/pyproj4/pyproj/blob/main/CONTRIBUTING.md

**Comment by iboates** [comment]
It was my fault, it turns out it failed when doing `pip install -e .` and I just didn't notice, it was because I was missing build dependencies.
