### ISSUE TITLE
Geod f setting sign

### ISSUE THREAD

**Issue by Richard-Sims** [pyproj4/pyproj#1062]
Hi pyproj team,
I'm not totally sure this is a bug but it isn't clear how geod is operating when trying to calculate gridded areas with polygon_area_perimeter. See my test case to find the area of a 1x1 degree grid at the equator. The six different calls to geod below give two different answers, it isn't clear from the documentation why these inputs would give different results. This might be the intended behaviour but it might be worth looking at as this can create a non trivial difference that is hard to verify.  I believe the answer is around 12391 km^2 based on three independent methods which are also copied below.
All the best
Richard

**Pyproj solution using geod.polygon_area_perimeter**

from pyproj import Geod
geod = Geod('+a=6378137 polar axis radius=6356752')                    #gives ->12391714368.859478
#geod = Geod('+a=6378137 -f=0.0033528106647475126')               #gives ->12391714368.859478 
#geod = Geod('+a=6378137 ')                                                             #gives ->12391714368.859478 
#geod = Geod('+a=6378137 +b=6356752')                                        #gives ->12308777144.780497
#geod = Geod('+a=6378137 +f=0.0033528106647475126')              #gives -> 12308778361.469454
#geod = Geod(ellps='WGS84')                                                            #gives -> 12308778361.469452

lats = [0, 0, 1, 1, 0]
lons = [39, 40, 40, 39,39]
poly_area, poly_perimeter = geod.polygon_area_perimeter(lons, lats)
print("area: {} , perimeter: {}".format(poly_area, poly_perimeter))

**Alternative method for verification 1**

#Calculate the area inside of any GeoJSON geometry. This is a port of Mapbox's geojson-area for Python.
#https://github.com/scisco/area
from area import area
obj = {'type':'Polygon','coordinates':[[[39,0],[39,1],[40,1],[40,0],[39,0]]]}
area(obj)
#12391399902.071121

**Alternative method for verification 2**

    def get_grid_area_1deg(latDegrees):
       # area of a 1x1 degree box at a given latitude in radians
       latRadians = latDegrees * dtor
       cosLat, sinLat = cos(latRadians), sin(latRadians)
       rc, rs = re * cosLat, rp * sinLat
       r2c, r2s = re * re * cosLat, rp * rp * sinLat
       earth_radius = sqrt((r2c * r2c + r2s * r2s) / (rc * rc + rs * rs))
       erd = earth_radius * dtor
       return erd * erd * cosLat
    # Define constants
    #Earth equatorial and polar radii in km
    re, rp = 6378.137,6356.7523
    dtor = radians(1.)
    from math import sqrt, cos, sin, radians
    get_grid_area_1deg(0)
    #12392.029030473717

**Alternative method for verification 3**

#https://stackoverflow.com/questions/4681737/how-to-calculate-the-area-of-a-polygon-on-the-earths-surface-using-python
        
def reproject(latitude, longitude):
      #Returns the x & y coordinates in meters using a sinusoidal projection
      from math import pi, cos, radians
      earth_radius = 6378137 # in meters
      lat_dist = pi * earth_radius / 180.0
      y = [lat * lat_dist for lat in latitude]
      x = [long * lat_dist * cos(radians(lat)) 
                  for lat, long in zip(latitude, longitude)]
      return x, y
        
        
def area_of_polygon(x, y):
      #Calculates the area of an arbitrary polygon given its verticies
      area = 0.0
      for i in range(-1, len(x)-1):
          area += x[i] * (y[i+1] - y[i-1])
      return abs(area) / 2.0

latitude = [0, 0, 1, 1, 0]
longitude = [39, 40, 40, 39,39]
x,y=reproject(latitude, longitude)
area_of_polygon(x, y)
#12391085347.451996

**Comment by snowman2** [comment]
Thanks @cffk :+1:. @Richard-Sims, if you have more information indicating that this is a bug, please let us know.
