### ISSUE TITLE
ModuleNotFoundError: No module named 'pyproj._network'

### ISSUE THREAD

**Issue by projmaysucks** [pyproj4/pyproj#1070]
My answers begin with "--".

Error is that, I got : "ModuleNotFoundError: No module named 'pyproj._network'"

1. I install pyproj as follows, in Windows shell:
> pip install pyproj
Requirement already satisfied: pyproj in c:\users\mirouser\appdata\local\programs\python\python37\lib\site-packages (3.2.1)
Requirement already satisfied: certifi in c:\users\mirouser\appdata\local\programs\python\python37\lib\site-packages (from pyproj) (2021.5.30)

2. After import pyproj, I've got:
> import pyproj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mirouser\AppData\Local\Programs\Python\Python37\Lib\site-packages\pyproj\__init__.py", line 49, in <module>
    import pyproj.network
  File "C:\Users\Mirouser\AppData\Local\Programs\Python\Python37\Lib\site-packages\pyproj\network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ModuleNotFoundError: No module named 'pyproj._network'

#### Installation method/steps
 - Installation method:
 -- pip
 - How did you install PROJ? Where is it installed?
 -- on Windows, via CMD (shell)
 - Please provide all commands/steps you used to install pyproj and PROJ
 -- pip install pyproj

#### Environment Information
 - pyproj version you are attempting to install
 -- 3.2.1
 - PROJ version (Execute `proj` command and give version here.)
 -- NameError: name 'proj' is not defined
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 -- 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
 -- Windows-10-10.0.19041-SP0

**Comment by projmaysucks** [comment]
Update: I successfully installed 'proj'. But the problem with the 'pyproj._network' still persists, nonetheless, the 'pyproj'

**Comment by snowman2** [comment]
From: https://pyproj4.github.io/pyproj/stable/installation.html

Windows wheels are from: https://www.lfd.uci.edu/~gohlke/pythonlibs/

> Many binaries depend on [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) and the current [Microsoft Visual C++ Redistributable for Visual Studio 2015-2022](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist) for Python 3, or the Microsoft Visual C++ 2008 Redistributable Package [x64](https://www.microsoft.com/en-us/download/details.aspx?id=15336), [x86](https://www.microsoft.com/en-us/download/details.aspx?id=29), and [SP1](https://www.microsoft.com/en-us/download/details.aspx?id=26368) for Python 2.7.

**Comment by snowman2** [comment]
I think you are likely missing this: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

**Comment by projmaysucks** [comment]
OK, Many Thanks! 
Will try it out with Your recommendations and will write again.

**Comment by snowman2** [comment]
Closing as I believe this issue has been resolved.
