### ISSUE TITLE
Negative geodesic area

### ISSUE THREAD

**Issue by zxdawn** [pyproj4/pyproj#1082]
#### Code Sample, a copy-pastable example if possible

```python
from pyproj import Geod

geod = Geod(ellps="WGS84")
lons = [-180.,  -180.,  -179.9, -179.9]
lats = [60.,  60.1, 60.1, 60.]
proj_area = geod.polygon_area_perimeter(lons, lats)[0]
print(proj_area)
```
#### Problem description

The area is negative: -62074670.43413544

#### Expected Output

Here's the output using package called [area](https://github.com/scisco/area):

```
from area import area
obj = {'type':'Polygon','coordinates':[[[-180,60],[-180,60.1],[-179.9,60.1],[-179.9,60]]]}
print(area(obj))
```

61866460.992676206

#### Environment Information

```
pyproj info:
    pyproj: 3.3.0
      PROJ: 8.2.0
  data dir: /home/xin/miniconda3/share/proj
user_data_dir: /home/xin/.local/share/proj
PROJ DATA (recommended version): 1.8
PROJ Database: 1.2
EPSG Database: v10.038 [2021-10-21]
ESRI Database: ArcMap 12.8 [2021-05-06]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0]
executable: /home/xin/miniconda3/bin/python
   machine: Linux-5.11.0-40-generic-x86_64-with-glibc2.31

Python deps:
   certifi: 2021.10.08
       pip: 22.0.3
setuptools: 59.8.0
    Cython: 0.29.28
```

**Comment by snowman2** [comment]
https://pyproj4.github.io/pyproj/stable/api/geod.html#pyproj.Geod.polygon_area_perimeter

> The area returned is signed with counter-clockwise traversal being treated as positive.

https://pyproj4.github.io/pyproj/stable/api/geod.html#pyproj.Geod.geometry_area_perimeter

> The area returned is signed with counter-clockwise (CCW) traversal being treated as positive. For polygons, holes should use the opposite traversal to the exterior (if the exterior is CCW, the holes/interiors should be CW). You can use shapely.ops.orient to modify the orientation.
