### ISSUE TITLE
Error converting WGS84 LLA to ECEF?

### ISSUE THREAD

**Issue by nickponline** [pyproj4/pyproj#109]
I'm trying to convert a WGS84 lon, lat and alt to ECEF and Pyproj is giving me really weird results. My code is simply:

```
lon, lat, alt = 49.74761271 -113.2179781 0
ecef = pyproj.Proj(proj='geocent', ellps='WGS84', datum='WGS84')
lla = pyproj.Proj(proj='latlong', ellps='WGS84', datum='WGS84')    
x, y, z = pyproj.transform(lla, ecef, lon, lat, alt, radians=False)
print x, y, z

```
which prints

inf inf 0.0

Does anyone know what is wrong?

If I implement it myself it works:

```
def lla_to_ecef_alt(lat, lon, alt):
    rad = np.float64(6378137.0)        # Radius of the Earth (in meters)
    f = np.float64(1.0/298.257223563)  # Flattening factor WGS84 Model
    np.cosLat = np.cos(lat)
    np.sinLat = np.sin(lat)
    FF     = (1.0-f)**2
    C      = 1/np.sqrt(np.cosLat**2 + FF * np.sinLat**2)
    S      = C * FF

    x = (rad * C + alt)*np.cosLat * np.cos(lon)
    y = (rad * C + alt)*np.cosLat * np.sin(lon)
    z = (rad * S + alt)*np.sinLat
    return x, y, z
```

What's the difference between them?

**Comment by micahcochran** [comment]
Tangentially related question about ENU in proj4, https://github.com/OSGeo/proj.4/issues/500

There were (are?) some issues with [3D support in proj4](https://github.com/OSGeo/proj.4/issues/394), and I'm just don't know if the situation has improved, since last year.

**Comment by anisayr** [comment]
@nickponline **your latitude is not in WGS84 coordinates .** 
You give -113.2179781 , when the minimum is -90.

In your code there are no exception for this verification.  pyproj should have one , it's should why you get inf.
Anyone can confirm ?

**Comment by micahcochran** [comment]
If you swap `lat` and `long` for the conversion works the function works for pyproj, but the answers differ wildly.

```Python
>>> lat, lon, alt = 49.74761271, -113.2179781, 0

In [11]: lla_to_ecef_alt(lat,lon,alt)
Out[11]: (5506045.7590333037, -667505.09162232606, -3138810.3229058362)

In [13]: print(pyproj.transform(lla, ecef, lon, lat, alt, radians=False))
(-1627906.5148085926, -3794901.435518741, 4844697.278296873)
```

**Comment by anisayr** [comment]
I have the same difference between the function ` lla_to_ecef_alt(lat,lon,alt)` provided by @nickponline and pyproj on some other points. 
I run a couple of test and the ouput from pyproj appear to be exact.
So I assume that pyproj is the gold value and ` lla_to_ecef_alt(lat,lon,alt)`  function from @nickponline could be wrong.

**Comment by altrouge** [comment]
In your implementation @nickponline, you give your latitude/longitude in degrees while cos/sin expect radians. 

In `lla_to_ecef_alt` You should replace your `lat` by `np.radians(lat)` and your `lon` by `np.radians(lon)`. or directly give the lat/lon in radians.

**Comment by snowman2** [comment]
Results are still the same for pyproj==2.1.2 & PROJ 6.0.0 with improved 3D transformation support.
Note, I also swapped lat/lon like @micahcochran for this example.
```python
>>> import pyproj
>>> pyproj.__version__
'2.1.2'
>>> lat, lon, alt = 49.74761271, -113.2179781, 0
>>> ecef = pyproj.Proj(proj='geocent', ellps='WGS84', datum='WGS84')
>>> lla = pyproj.Proj(proj='latlong', ellps='WGS84', datum='WGS84')
>>> pyproj.transform(lla, ecef, lon, lat, alt, radians=False)
(-1627906.5148085926, -3794901.435518741, 4844697.278296873)
```
@nickponline is this what you expect the results to be?

**Comment by snowman2** [comment]
Feel free to reopen if you would like to continue this discussion.

**Comment by flow2k** [comment]
@snowman2 When I use `transform`, I get
`DeprecationWarning: This function is deprecated.`

**Comment by snowman2** [comment]
That is correct. Using the Transformer class is recommended now. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/pull/2444
