### ISSUE TITLE
Pyproj import error

### ISSUE THREAD

**Issue by erev-84** [pyproj4/pyproj#1112]
Although I have pyproj installed, I am getting the error message seen in the screenshot below. What is the reason of this error?

python version ==> 3.10
Pyptoj installation method ==> pip install pyproj

![689195DB-58C9-4FFF-A8F6-1141E469FC44](https://user-images.githubusercontent.com/82845085/180821921-79ee3eae-cf83-42b5-980f-a23e41a4d140.jpeg)

**Comment by snowman2** [comment]
It looks like your Python path and the path the program is running under are different.

**Comment by micahcochran** [comment]
I agree with @snowman2 .  I suspect that you might have multiple python installations on your Windows machine.
Does running:
```
C:..\> python tileGet.py -n osm.net.xml -t 10
```
fix that problem?

**Comment by erev-84** [comment]
Hello,

Thank you very much for the replys ( @micahcochran  & @snowman2 ) 

My problem solved with your suggestions again thank you.
