### ISSUE TITLE
Segmentation Fault on pyproj.transform

### ISSUE THREAD

**Issue by Scolymus** [pyproj4/pyproj#1119]
I'm trying to convert a shapely polygon to a different CRS using a transformer:

```python
import pyproj
from shapely.ops import transform
import shapely.wkt

poly = shapely.wkt.loads("POLYGON((11.32494067504356 48.81382282568276,10.760727610912785 48.03424052262582,12.501645259614333 47.67215127486503,13.38216064327573 48.133953565438105,11.32494067504356 48.81382282568276,11.32494067504356 48.81382282568276))")

transformer = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:32631", always_xy=True)
img_poly = transform(transformer.transform, poly)
```
However, this is giving me a segmentation fault, without being able to know anything else. When I activated faulthandler following this old bug https://github.com/pyproj4/pyproj/issues/8, i obtained:

```
  File "/opt/homebrew/lib/python3.9/site-packages/shapely/geometry/polygon.py", line 54 in __init__
  File "/opt/homebrew/lib/python3.9/site-packages/shapely/ops.py", line 304 in transform
  File "/Users/me/Documents/test.py", line 197 in <module>
zsh: segmentation fault  python3 test.py
```

#### Environment Information
(I'm using M1 Mac, just in case)
pyproj info:
    pyproj: 3.3.1
      PROJ: 8.2.0
  data dir: /opt/homebrew/lib/python3.9/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /Users/me/Library/Application Support/proj
PROJ DATA (recommended version): 1.8
PROJ Database: 1.2
EPSG Database: v10.038 [2021-10-21]
ESRI Database: ArcMap 12.8 [2021-05-06]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.9.13 (main, May 24 2022, 21:13:51)  [Clang 13.1.6 (clang-1316.0.21.2)]
executable: /opt/homebrew/opt/python@3.9/bin/python3.9
   machine: macOS-12.3.1-arm64-arm-64bit

Python deps:
/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
   certifi: 2022.06.15
    Cython: None
setuptools: 62.3.2
       pip: 22.1.1

**Comment by snowman2** [comment]
@Scolymus, I updated your example to no longer require the input raster and it runs without issue on my end. Do you still see the issue with the updated example above?

**Comment by Scolymus** [comment]
So like that it works charmly. However, I just saw that if I add:

`import rasterio as rio`

on top of the code it starts giving me the segmentation fault.... In fact, the import only makes the segmentation fault if rasterio is imported before than:

` from shapely.ops import transform`

Therefore, if you import like this:
```
import rasterio as rio
from shapely.ops import transform
```
it will fail, but if you do:
```
from shapely.ops import transform
import rasterio as rio
```

it won't give segmentation fault. And the line making the segmentation is just:

`img_poly = transform(transformer.transform, poly)`

Looks like quite weird...

**Comment by snowman2** [comment]
Interesting, sounds like it may be a better fit for the issue to be in the shapely repo?

**Comment by Scolymus** [comment]
Let's see!

https://github.com/shapely/shapely/issues/1491

**Comment by snowman2** [comment]
Looks like they have a similar issue without pyproj. Going to close this as I believe it is a better fit in shapely.

**Comment by sgillies** [comment]
I think I've found the problem: https://github.com/shapely/shapely/issues/1449#issuecomment-1219582201
