### ISSUE TITLE
transformer.transform return -inf

### ISSUE THREAD

**Issue by KarenChen9999** [pyproj4/pyproj#1144]
I am trying to replace pyproj 1 style with pyproj 2 style by following this link: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1. With pyproj 2, it doesn't give me the right values rather than "inf"

#### Code Sample, a copy-pastable example if possible

```
#pyproj 1 style works
from functools import partial
from pyproj import Proj, transform
proj_4326 = Proj(init="epsg:4326")
proj_3577 = Proj(init="epsg:3577")
transformer = partial(transform, proj_4326, proj_3577)
transformer(140, -35)
```

```
#pyproj 2 style doesn't work
from pyproj import Transformer
transformer = Transformer.from_crs("epsg:4326", "epsg:3577")
transformer.transform(140, -35)
```

#### Problem description

I am expecting pyproj 2 style to return the same values as pyproj 1. But it gives "inf"

#### Expected Output

(727791.2111690434, -3844914.116686288)

#### Environment Information
3.0.0.post1

**Comment by snowman2** [comment]
See: https://pyproj4.github.io/pyproj/stable/examples.html#transformations-from-crs-to-crs

With the new version, axis order is now taken into account. The `always_xy` kwarg is likely what you are looking for.

**Comment by KarenChen9999** [comment]
oh, got it now. thanks so much!

**Comment by snowman2** [comment]
Glad to hear that you were able to find a resolution 👍
