### ISSUE TITLE
Missing dist-info breaks project on version 3.4.0

### ISSUE THREAD

**Issue by Scoppio** [pyproj4/pyproj#1155]
The new version 3.4.0 requires the presence of the METADATA file on dist-info folder, otherwise the project breaks and is unable to load.

https://github.com/pyproj4/pyproj/blob/bc7805ccc813b40ab28099ef305821300f149aad/pyproj/__init__.py#L70
This is the only place where this information is ever looked and in no way it is important or vital for the correct operation of the application.

This is a breaking change for all applications where the deployment strips metadata and other files to reduce size.

**Comment by snowman2** [comment]
Related to:
- #1129
- #1137

One potential path forward: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html

In `__init__.py` convert the version to a string and copy the version from `setup.cfg`.

In `setup.cfg`:
```
version = attr: pyproj.__version__
```

A PR with the fix is welcome.
