### ISSUE TITLE
Lack of consistency between `fwd` and `fwd_intermediate` azimuth output

### ISSUE THREAD

**Issue by stephenwinn16** [pyproj4/pyproj#1163]
#### Problem description

I've noticed an inconsistency between the azimuth output of `fwd` and `fwd_intermediate`. In the example below, I compute the lon/lat/azi  when moving 1km from London with an initial forward azimuth of 45 degrees with the both methods.  As expected from the documentation, `fwd` returns the backward azimuth whereas `fwd_intermediate` returns the forward azimuth of the terminus point. For consistency and to avoid confusion, I suggest `fwd_intermediate` also return the backward azimuth.

#### Code Sample

```python
from pyproj import Geod, enums

wgs84 = Geod(ellps="WGS84")

# Inputs 
london = (-0.118092, 51.509865) #lon/lat
dist = 1e3  # m
bearing = 45  # deg
flags = enums.GeodIntermediateFlag(0).AZIS_KEEP  # get fwd_intermediate to return azimuths

# fwd
lon, lat, azi = wgs84.fwd(*london, bearing, dist)

# fwd_intermediate (return first and last point)
res = wgs84.fwd_intermediate(*london, bearing, 2, dist, flags=flags, terminus_idx=0, initial_idx=0)

print("lon, lat, azimuth from fwd             :", lon, lat, azi)
print("lon, lat, azimuth from fwd_intermediate:", res.lons[-1], res.lats[-1], res.azis[-1])
```

which outputs:

```console
lon, lat, azimuth from fwd             : -0.10790547005142687 51.51622011204643 -134.99202649526126
lon, lat, azimuth from fwd_intermediate: -0.10790547005142687 51.51622011204643 45.007973504738736
```

#### Environment Information

pyproj info:
    pyproj: 3.4.0
     PROJ: 9.1.0

#### Installation method

Installed via pip

**Comment by snowman2** [comment]
cc: @idanmiara

**Comment by snowman2** [comment]
Related #841

**Comment by idanmiara** [comment]
Hi,
As we don't want to break backwards compatibility, I've added this option as a non-default argument.
Hope it helps :)

**Comment by stephenwinn16** [comment]
Hi @idanmiara, 
Thanks for the changes. I understand the argument for backward compatibility. However, wouldn't it make more sense for the default behaviour of 'fwd' and 'fwd_intermediate' to be the same? You could have 'return_back_azimuth' is True by default and a note in the next release warning prior user.

**Comment by idanmiara** [comment]
Hi @stephenwinn16,
I really don't mind or have any strong opinion. 
I guess it should be @snowman2 's call.

**Comment by idanmiara** [comment]
Hi @stephenwinn16, @snowman2 
I've added `return_back_azimuth` to `fwd()` as well.
I would have made the default to return forward azimuth for both, but it doesn't make sense to change the default behavior of `fwd` so I'm not sure if we would prefer to preserve backwards compatibility with `fwd_intermediate` or to make the default value of  `return_back_azimuth=True` for the sake of compatibility with `fwd`.
WDYT ?

**Comment by snowman2** [comment]
I see this comment in the code:

>                # back azimuth needs to be flipped 180 degrees
>                # to match what PROJ geod utility produces.

This makes me think that the default return should be the back azimuth for consistency with PROJ. Thoughts?

**Comment by idanmiara** [comment]
> I see this comment in the code:
> 
> > ```
> >            # back azimuth needs to be flipped 180 degrees
> >            # to match what PROJ geod utility produces.
> > ```
> 
> This makes me think that the default return should be the back azimuth for consistency with PROJ. Thoughts?

makes sense, but I guess that the comment should be fixed:
`by default, forward azimuth needs to be flipped 180 degrees to match the output of PROJ geod utilities (back azimuth).`

**Comment by idanmiara** [comment]
> Hi @idanmiara, Thanks for the changes. I understand the argument for backward compatibility. However, wouldn't it make more sense for the default behaviour of 'fwd' and 'fwd_intermediate' to be the same? You could have 'return_back_azimuth' is True by default and a note in the next release warning prior user.

@snowman2 agrees with you, so I've changed the default. 
I added this parameter to `fwd`, `inv`, `fwd_intermediate`, `inv_intermediate,

**Comment by stephenwinn16** [comment]
> This makes me think that the default return should be the back azimuth for consistency with PROJ. Thoughts?

Agreed. 

> @snowman2 agrees with you, so I've changed the default.

Great, this should make everything consistent. Thank you both!
