### ISSUE TITLE
WHL: win32 wheels

### ISSUE THREAD

**Issue by molinav** [pyproj4/pyproj#1168]
#### Problem description

Until version 3.3.1, it is possible to find `win32` wheels on PyPI for the supported Python versions, see:
https://pypi.org/project/pyproj/3.3.1/#files

Since version 3.4.0, the `win32` wheels are not available anymore, see:
https://pypi.org/project/pyproj/3.4.0/#files

These means that for Python 3.11 there is no `win32` wheel for any `pyproj` version, and any library installation depending on `pyproj` will fail for Python 3.11 on `win32` due to lack of precompiled wheels (e.g. [`basemap`](https://github.com/matplotlib/basemap)).

#### Expected Output

I would expect `win32` wheels for `pyproj` 3.4.0 for the supported Python versions on PyPI.

I am not sure if this support drop was actually intended, since I saw some slight reorganisation in the `.github/workflows` folder. I can provide some support to fix this if desired.

#### Environment Information

- pyproj version: 3.4.0
- Python version: 3.11.0
- OS information: Windows-10-10.0.22621-SP0

#### Installation method
 - pip wheel

**Comment by snowman2** [comment]
See #1033
