### ISSUE TITLE
tolerance condition error for pyproj.transform(in_proj, output_proj, int(-180), int(-90))

### ISSUE THREAD

**Issue by murdav** [pyproj4/pyproj#117]
Dear All,

Why I should get a "tolerance condition error" if I execute:
```
in_proj = pyproj.Proj(init='EPSG:4326')
output_proj = pyproj.Proj(init='EPSG:3857')
bbox_minx, bbox_miny = pyproj.transform(in_proj, output_proj, int(-180), int(-90))

```
while
`bbox_minx, bbox_miny = pyproj.transform(in_proj, output_proj, int(-180), int(-89.99999))` works `<class 'tuple'>: (-20037508.342789244, -88985946.57792848)`.

Thanks,

D

**Comment by snowman2** [comment]
Related to #202

**Comment by snowman2** [comment]
Closing this issue as it is answered in the above issue. Feel free to reopen if you have further questions.
