### ISSUE TITLE
GDA2020 to WGS84 best transformation

### ISSUE THREAD

**Issue by yurithefury** [pyproj4/pyproj#1174]
I just noticed that the output remains shifted when transforming a vector file from `EPSG:4326` to `EPSG:7850` and back. 

After digging a bit into `pyproj` I noticed that the output of the "best" `EPSG:4326` to `EPSG:7850` transformation:
`TransformerGroup("EPSG:4326", "EPSG:7850", always_xy=True).transformers[0]` is
`proj=pipeline step proj=unitconvert xy_in=deg xy_out=rad step proj=push v_3 step proj=cart ellps=WGS84 step proj=helmert x=0.06155 y=-0.01087 z=-0.04019 rx=-0.0394924 ry=-0.0327221 rz=-0.0328979 s=-0.009994 convention=coordinate_frame step inv proj=cart ellps=GRS80 step proj=pop v_3 step proj=utm zone=50 south ellps=GRS80`

However, the output of the "best" inverse transformation (i.e. `EPSG:7850` to `EPSG:4326`)
`TransformerGroup("EPSG:7850", "EPSG:4326", always_xy=True).transformers[0]` is
`proj=pipeline step inv proj=utm zone=50 south ellps=GRS80 step proj=unitconvert xy_in=rad xy_out=deg`

This behavior leads to a vector file in `EPSG:4326` that was reprojected to `EPSG:7850` and then back to `EPSG:4326` being shifted with respect to the original file in `EPSG:4326`. The use of `TransformerGroup("EPSG:7850", "EPSG:4326", always_xy=True).transformers[1]` leads to the expected result though. This behavior mainly affects geopandas `to_crs()` method that probably uses `transformers[0]` by default.

Here I assume that the "best" transformation is stored in `transformers[0]` as opposed to `transformers[1]`. Please correct me if I'm wrong. 

Tested using pyproj: 3.3.1, PROJ: 9.0.1, geopandas: 0.11.0 on Ubuntu 20.04 in WSL2

**Comment by snowman2** [comment]
This may be helpful to read: https://proj.org/operations/operations_computation.html

I recommend raising the issue upstream as this logic is handled by PROJ: https://github.com/OSGeo/PROJ
