### ISSUE TITLE
Report errors when projection operation fails

### ISSUE THREAD

**Issue by sxwebster** [pyproj4/pyproj#1176]
Referencing closed feature request [721](https://github.com/pyproj4/pyproj/issues/721)

When a projection fails pyproj returns an ```inf``` due to upstream ```proj```. There is seemingly a flag that can change this to a NaN, if the user has dug deep enough into the notes to understand what is happening.

It would be very worthwhile if, on a projection operaiton failure, that an error message is presented. Some users have expressed that they do not want a message as they find them annoying, so perhaps this could be addressed by adding a ```suppress-errors``` flag of some variety. As it stands locating the source of an ```inf``` in the output, particularly when it's an intermittent result, can be infuriating. This has taken up multiple days of development time to hunt down in the past. 

Does ```proj``` throw any information that can be captured and forwarded on?

**Comment by snowman2** [comment]
There is an `errcheck` argument for the transform: https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.transform

Also see: https://pyproj4.github.io/pyproj/stable/advanced_examples.html#debugging-internal-proj

**Comment by snowman2** [comment]
I believe this has been addressed. If not, please comment.
