### ISSUE TITLE
Incorrect `LICENSE_proj` filename in setup.cfg

### ISSUE THREAD

**Issue by xylar** [pyproj4/pyproj#1200]
I copied this line from setup.cfg when updating the conda-forge recipe:
https://github.com/pyproj4/pyproj/blob/main/setup.cfg#L12
But the actual filename is `LICENSE_proj4`.  These should be made consistent.

**Comment by snowman2** [comment]
Thanks for the report. Probably best to rename the license file the `LICENSE_proj`.
