### ISSUE TITLE
Python Egg Extraction Error When Trying to Use pyproj in Pyspark

### ISSUE THREAD

**Issue by unif2** [pyproj4/pyproj#122]
I have pyproj installed in my conda environment on my local machine (MacBook Pro).  Everything works properly.  I am able to use pyproj within the pyspark installation on my local machine.  However, I mainly work on a Linux machine I SSH to and I have shipped my conda environment from that Linux machine to an HDFS cluster so that I can use pyproj (and pyspark) on a large dataset.

When I try to run the same rdd.map() code on that HDFS cluster in which some pyproj stuff is inside the .map(), I get the following error:

ExtractionError: (ExtractionError("Can't extract file(s) to egg cache\n\nThe following error occurred while trying to extract file(s) to the Python egg\ncache:\n\n  [Errno 13] Permission denied: '/home/.cache'\n\nThe Python egg cache directory is currently set to:\n\n  /home/.cache/Python-Eggs\n\nPerhaps your account does not have write access to this directory?  You can\nchange the cache directory by setting the PYTHON_EGG_CACHE environment\nvariable to point to an accessible directory.\n",).

The '/home/.cache/Python-Eggs' is a directory on the Linux machine I SSH to, not in HDFS, nor my local machine (MacBook Pro).

I have no idea how to solve this issue and would appreciate any assistance.  Have a good day!

**Comment by micahcochran** [comment]
Is this happening during installation of `pyproj`?

**Comment by unif2** [comment]
No.  It happens when I try to run a Spark job in which an RDD is being mapped from elements consisting of lat/long points to buffers using shapely.  I use pyproj to transform to a coordinate system to get accurate distance measurements.  The code works fine on my Mac using my Mac's spark and pyproj installations.  It also works fine during non-Spark jobs when SSHed into a Linux machine.  But when trying to use HDFS & Spark, it fails with that error.  I shipped my Conda environment to HDFS so it can use it and all the packages I have installed (including pyproj).

**Comment by akki10** [comment]
I tried the same stuff and worked for me using the following configuration:
    ```
pyspark/spark-submit 
    --conf spark.executorEnv.PYTHON_EGG_CACHE="./.python-eggs/" 
    --conf spark.executorEnv.PYTHON_EGG_DIR="./.python-eggs/" 
    --conf spark.driverEnv.PYTHON_EGG_CACHE="./.python-eggs/" 
    --conf spark.driverEnv.PYTHON_EGG_DIR="./.python-eggs/"
```
But now I'm getting the following error:
```
 File "build/bdist.linux-x86_64/egg/pyproj/__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1170)
RuntimeError: no system list, errno: 20
```

On doing some R&D on this error. I got to know that if I don't have the ownership of the egg file being used even in normal Python (using sys.path.append("/path/to/pyprog.egg")) I'm facing the exact same issue. But I'm not aware of who/which user exactly have the ownership of the file being used by spark-submit. Also, the same exact code is working with pyspark shell but not with spark-submit.

**Comment by snowman2** [comment]
Can you try pyproj==2.1.0 and see if the issue persists?

**Comment by snowman2** [comment]
Thanks for the report! Feel free to reopen if this issue persists.
