### ISSUE TITLE
LAEA projection converts NaN to 0

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#1239]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
from pyproj import Transformer
import numpy as np

# LAEA target CRS
t = Transformer.from_crs('EPSG:4326', 'EPSG:3572')
t.transform(np.nan, np.nan)
# (0.0, 0.0)

# Mercator target CRS
t = Transformer.from_crs('EPSG:4326', 'EPSG:3857')
t.transform(np.nan, np.nan)
# (nan, nan)

```

#### Problem description

I'm sure this is a PROJ bug, but I'm not sure the easiest way to generate a reproducible example in C/C++ to file a bug there. Basically, I have some data converting lon/lat coordinates to LAEA x/y coordinates and some of the lon/lat values are NaN. This is the first time I've ever encountered this with a projection and I don't think it existed in older versions of pyproj/PROJ.

I have an old version of my code with pyproj 2.4.2.post1 installed and it doesn't seem to do this.

#### Expected Output

`(nan, nan)` for all projections receiving NaN as input.

#### Environment Information

 - Output from: `pyproj -v`
 - 
```
pyproj info:
    pyproj: 3.3.1
      PROJ: 9.0.0
  data dir: /home/davidh/miniconda3/envs/polar2grid_py310/share/proj
user_data_dir: /home/davidh/.local/share/proj
PROJ DATA (recommended version): 1.9
PROJ Database: 1.2
EPSG Database: v10.054 [2022-02-13]
ESRI Database: ArcMap 12.9 [2022-02-18]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]
executable: /home/davidh/miniconda3/envs/polar2grid_py310/bin/python
   machine: Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35

Python deps:
/home/davidh/miniconda3/envs/polar2grid_py310/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
   certifi: 2022.12.07
    Cython: None
setuptools: 62.3.2
       pip: 22.1.1
```

#### Installation method
 - conda via conda-forge

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by djhoese** [comment]
It very likely is this line:

https://github.com/OSGeo/PROJ/blob/f7e88839589d6ce7f858adbd049676a4dd297539/src/projections/laea.cpp#L85-L87

**Comment by djhoese** [comment]
Inverse works:

```
In [8]: t.transform(np.nan, np.nan, direction='INVERSE')
Out[8]: (nan, nan)

In [9]: t.transform(np.nan, np.nan, direction='FORWARD')
Out[9]: (0.0, 0.0)
```

**Comment by djhoese** [comment]
```
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
```

Really old environment with ^ results in infinity being returned.

**Comment by snowman2** [comment]
I recommend using the cs2cs took to create a reproducible example.

**Comment by djhoese** [comment]
Any idea how to pass NaN to the command line tools:

```
$ echo nan nan | cs2cs +init=epsg:4326 +to +init=epsg:3572
4504982.38      7802858.37 0.00an nan
```

**Comment by snowman2** [comment]
> Any idea how to pass NaN to the command line tools

😂 I didn't think of that. Maybe try wrapping it with quotes?

**Comment by djhoese** [comment]
I couldn't get it to work, but filed a bug with what I could make up: https://github.com/OSGeo/PROJ/issues/3596

**Comment by snowman2** [comment]
Thanks for fixing this 👍
