### ISSUE TITLE
Unexpected Oblique Mercator (omerc) inverse result when +alpha is between 90 and 270

### ISSUE THREAD

**Issue by rich9403** [pyproj4/pyproj#1247]
I searched for existing issues for "omerc" projections or problems in general with handling "+alpha" variables on pyroj as well as the OSGeo/proj repository.  I found this issue in the proj bug reports, (https://github.com/OSGeo/PROJ/issues/331), but this issue was marked as completed and closed in 2016.  Looks like it is still not fixed.

Is this a pyproj issue or an issue inherited from proj?

#### Code Sample
```
from pyproj import CRS, Transformer
import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
    
    # initial value for alpha (degrees)
    alphaStart = 0
    alphaStop = 359
    
    alphas = np.arange(alphaStart,alphaStop)
    
    lat = np.empty(len(alphas))
    lon = np.empty(len(alphas))
    
    # WGS84 coordinate system definition
    crs_4326 = CRS.from_epsg(4326)    
    
    # iterate over range of alpha values in omerc crs
    for i, alpha in enumerate(alphas):
        # Oblique Mercator Transform
        omerc = CRS.from_proj4("+proj=omerc +lat_0=0 +lonc=0 +alpha={} +x_0=0 +y_0=0 +gamma=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0".format(alpha))
        
        # transform omerc to wgs84
        omerc_to_wgs84 = Transformer.from_crs(omerc, crs_4326)
        
        lat[i], lon[i] = omerc_to_wgs84.transform(1000,0)
        
    plt.scatter(lon, lat)
    plt.show()
```
#### Problem description
I would expect a constant X/Y coordinate converted to lat/lon to rotate about the origin of the Oblique Mercator Transform as the "+alpha" value is increased.  My current experience is "+alpha" angles between 90 and 270 degrees are 

#### Expected Output
I would expect a constant X/Y coordinate converted to lat/lon to rotate about the origin of the Oblique Mercator Transform as the "+alpha" value is increased.  Plotting "+alpha" angles from 0-359 degrees should create a circular or elliptical pattern depending on your crs viewpoint.
#### Environment Information

 - pyproj version 3.4.1
 - PROJ version 9.1.0
 - Python version 3.10.4
 - Operation System Windows 10

#### Installation method
 - WinPython

**Comment by snowman2** [comment]
Are you able to use [cs2cs](https://proj.org/apps/cs2cs.html) to check if this is a PROJ related issue?

**Comment by rich9403** [comment]
I will look into it.  On vacation this week, so at least next week until I
have the time.  Thank you for the follow-up.

James

**Comment by rich9403** [comment]
I was able to recreate the problem on a windows 10 machine using the OSGeo Shell.  Using the command:

`cs2cs +init=epsg:4326 +to +proj=omerc +lat_0=0 +lonc=0 +alpha=260 +x_0=0 +y_0=0 +gamma=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0`

and varying the +alpha value an equal offset from the 90 or 270 degrees provides the same coordinate transform.  Looks like this is a PROJ issue not a pyproj issue.

**Comment by snowman2** [comment]
Thanks for looking into it 👍
