### ISSUE TITLE
Chaining multiple projections is not always equal to direct calculations

### ISSUE THREAD

**Issue by elunty** [pyproj4/pyproj#1254]
#### Code Sample

```python
import pyproj
p1 = "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +units=m"
p2 = "+proj=longlat +ellps=WGS84 +datum=NAD83"
p3 = "+proj=geocent +ellps=WGS84 +datum=NAD83"
point = [4499057.5, 5326922.5, 0]

lonlat = pyproj.Transformer.from_proj(p1, p2).transform(*point)
geocent = pyproj.Transformer.from_proj(p2, p3).transform(*lonlat)
geocent_direct = pyproj.Transformer.from_proj(p1, p3).transform(*point)

print(lonlat)
print(geocent)
print(geocent_direct)

(11.987348822336118, 48.08128533764809, 0.0)
(4175904.875069951, 886652.3089621743, 4722919.304531313)
(4175397.269363811, 886544.5311787103, 4722440.326485002)
```
#### Problem description

For certain projections, the value you get going [proj1 --> proj2 --> proj3] is not the same as [proj1 --> proj3]. My guess is that the direction calculaton of projection-->geocentric is using the wrong a/f values for non-standard ellipsoids (+ellps=bessel), but that is just my guess.

#### Expected Output

The result for [proj1 --> proj2 --> proj3] should be the same value as [proj1 --> proj3]

#### Environment Information
pyproj==3.4.1, but also tested on 3.2.1

#### Installation method
pip wheel

**Comment by snowman2** [comment]
> The result for [proj1 --> proj2 --> proj3] should be the same value as [proj1 --> proj3]

It may happen sometimes, but not always. It is not something you should depend on. Related: https://github.com/geopandas/geopandas/issues/2787

**Comment by snowman2** [comment]
Side note: If you are confident that this particular case should be the same, I recommend opening an issue here: https://github.com/OSGeo/PROJ/
