### ISSUE TITLE
Transformer.transform - ProjError: x, y, z, and time must be same size

### ISSUE THREAD

**Issue by visionvardhman** [pyproj4/pyproj#1286]
The error I am getting after running the line of code :

PLACE_NAME = "Milan, Lombardy, Italy"

graph = ox.graph_from_place(PLACE_NAME)

is (Traceback):
Traceback (most recent call last):

Cell In[3], line 1
graph = ox.graph_from_place(PLACE_NAME)

File ~\miniconda3\envs\spyder-env\lib\site-packages\osmnx\graph.py:340 in graph_from_place
G = graph_from_polygon(

File ~\miniconda3\envs\spyder-env\lib\site-packages\osmnx\graph.py:414 in graph_from_polygon
poly_proj, crs_utm = projection.project_geometry(polygon)

File ~\miniconda3\envs\spyder-env\lib\site-packages\osmnx\projection.py:42 in project_geometry
gdf_proj = project_gdf(gdf, to_crs=to_crs, to_latlong=to_latlong)

File ~\miniconda3\envs\spyder-env\lib\site-packages\osmnx\projection.py:98 in project_gdf
gdf_proj = gdf.to_crs(utm_crs)

File ~\miniconda3\envs\spyder-env\lib\site-packages\geopandas\geodataframe.py:1364 in to_crs
geom = df.geometry.to_crs(crs=crs, epsg=epsg)

File ~\miniconda3\envs\spyder-env\lib\site-packages\geopandas\geoseries.py:1124 in to_crs
self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name

File ~\miniconda3\envs\spyder-env\lib\site-packages\geopandas\array.py:779 in to_crs
new_data = vectorized.transform(self.data, transformer.transform)

File ~\miniconda3\envs\spyder-env\lib\site-packages\geopandas_vectorized.py:1114 in transform
new_coords_z = func(coords_z[:, 0], coords_z[:, 1], coords_z[:, 2])

File ~\miniconda3\envs\spyder-env\lib\site-packages\pyproj\transformer.py:430 in transform
self._transformer._transform(

File pyproj/_transformer.pyx:459 in pyproj._transformer._Transformer._transform

ProjError: x, y, z, and time must be same size

Version of:
python - 3.8.16
spyder - 5.4.3
spyder-kernels - 5.4.3
proj - 6.2.1
pyproj - 2.6.1.post1
geopandas - 0.8.2
osmnx - 1.0.1
pygeos - 0.9
numpy - 1.23.5

I am not sure but this error particularly started showing up when I installed the hvplot 0.8.2 and it updated some packages.

Also, in conda when I try to update proj, it doesnt. the same for pyproj. Even removing and re-installing gives the same current version

I have checked errors of this type and found that maybe some changes are required in the history.rst, transformer.pyx, test_transformer.py file but I cant find them in the folder of pyproj.

**Comment by snowman2** [comment]
I don't think this is a pyproj issue. The error raised is likely correct. I would raise an issue on osmnx or geopandas with a simple and re-producible code example with relevant input files.

**Comment by jorisvandenbossche** [comment]
If it's a bug, that seems likely to be on the geopandas side. As @snowman2 mentioned, opening an issue at https://github.com/geopandas/geopandas/issues with a reproducible example would be welcome. 
Maybe first try with updating the geopandas and pyproj versions, though, since you are using relatively old versions (geopandas 0.8 and pyproj 2.6)
