### ISSUE TITLE
Expected cf latitude_of_projection_origin is missing using polar stereographic from to_cf()

### ISSUE THREAD

**Issue by TAlonglong** [pyproj4/pyproj#1292]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
import pyproj
# using EPSG:3995 as an example as this has polar_stereographic
# https://epsg.io/3995
pyproj.CRS(3995).to_cf()
```
#### Problem description

Out from this is:
```
{'crs_wkt': 'PROJCRS["WGS 84 / Arctic Polar Stereographic",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],MEMBER["World Geodetic System 1984 (G2139)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Arctic Polar Stereographic",METHOD["Polar Stereographic (variant B)",ID["EPSG",9829]],PARAMETER["Latitude of standard parallel",71,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8832]],PARAMETER["Longitude of origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8833]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["easting (X)",south,MERIDIAN[90,ANGLEUNIT["degree",0.0174532925199433]],ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",south,MERIDIAN[180,ANGLEUNIT["degree",0.0174532925199433]],ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["Polar research."],AREA["Northern hemisphere - north of 60°N onshore and offshore, including Arctic."],BBOX[60,-180,90,180]],ID["EPSG",3995]]', 'semi_major_axis': 6378137.0, 'semi_minor_axis': 6356752.314245179, 'inverse_flattening': 298.257223563, 'reference_ellipsoid_name': 'WGS 84', 'longitude_of_prime_meridian': 0.0, 'prime_meridian_name': 'Greenwich', 'geographic_crs_name': 'WGS 84', 'horizontal_datum_name': 'World Geodetic System 1984 ensemble', 'projected_crs_name': 'WGS 84 / Arctic Polar Stereographic', 'grid_mapping_name': 'polar_stereographic', 'standard_parallel': 71.0, 'straight_vertical_longitude_from_pole': 0.0, 'false_easting': 0.0, 'false_northing': 0.0}

```
#### Expected Output

Somewhere in here should be `latitude_of_projection_origin`as far as I understand the https://cfconventions.org/cf-conventions/cf-conventions.html#polar-stereographic

like this: 
```
pyproj.CRS(3995).to_cf()['latitude_of_projection_origin']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'latitude_of_projection_origin'
```

#### Environment Information

pyproj info:
    pyproj: 3.5.0
      PROJ: 9.1.1
  data dir: /home/trygveas/miniconda3/envs/python/share/proj
user_data_dir: /home/trygveas/.local/share/proj
PROJ DATA (recommended version): 1.12
PROJ Database: 1.2
EPSG Database: v10.076 [2022-08-31]
ESRI Database: ArcGIS Pro 3.0 [2022-07-09]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
executable: /home/trygveas/miniconda3/envs/python/bin/python
   machine: Linux-5.19.0-38-generic-x86_64-with-glibc2.35

Python deps:
   certifi: 2023.5.7
    Cython: None
setuptools: 65.6.3

#### Installation method
 - conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj
# packages in environment at /home/trygveas/miniconda3/envs/python:
#
# Name                    Version                   Build  Channel
proj                      9.1.1                h8ffa02c_2    conda-forge
pyproj                    3.5.0           py310h15e2413_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by djhoese** [comment]
Looks like only one variant of that projection uses that key:

https://github.com/pyproj4/pyproj/blob/49e330de9c476ac57494fe2b86dd8a0795e398cf/pyproj/crs/_cf1x8.py#L542-L562

**Comment by snowman2** [comment]
http://cfconventions.org/cf-conventions/cf-conventions.html#polar-stereographic

> The standard_parallel variant corresponds to EPSG Polar Stereographic (Variant B) (EPSG dataset coordinate operation method code 9829), while the scale_factor_at_projection_origin variant corresponds to EPSG Polar Stereographic (Variant A) (EPSG dataset coordinate operation method code 9810).

**Comment by snowman2** [comment]
- [PolarStereographicAConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#pyproj.crs.coordinate_operation.PolarStereographicAConversion)
- [PolarStereographicBConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#pyproj.crs.coordinate_operation.PolarStereographicBConversion)

**Comment by djhoese** [comment]
@snowman2 I'm a little confused by that snippet from the CF page. That paragraph doesn't refer to `latitude_of_projection_origin` at all. I guess are we saying that `latitude_of_projection_origin` can only ever be -90 or +90 so if we have `standard_parallel` then we can tell by the sign of that value whether `latitude_of_projection_origin` is +90 or -90?

In the case of 3995 (`+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs`) we see `lat_ts=71` so `lat_0` (`latitude_of_projection_origin`) can only be +90. I guess?

**Comment by TAlonglong** [comment]
Thank you for your quick response.

I don't follow all of this, but I think I get that I have a model B, and that does not have `latitude_of_projection_origin` where as model A has that. And different formulas are used for the two models.

Then I need to understand why my application does not understand which model are used. But that's definitely not for this issue.

**Comment by snowman2** [comment]
> I'm a little confused by that snippet from the CF page.

I would go with the parameters listed at epsg.org:

- https://epsg.org/coord-operation-method_9810/Polar-Stereographic-variant-A.html
- https://epsg.org/coord-operation-method_9829/Polar-Stereographic-variant-B.html

**Comment by autydp** [comment]
From issue #1363:

I do feel this amplifies the issue a bit as we have use-cases here which do not behave well in e.g., Panoply.  While adding latitude_of_projection_origin is not strictly necessary from a functional perspective, including latitude_of_projection_origin in the provided grid_mapping data can simplify downstream usage, and avoid misinterpretation.  Note that the proj4 string has both the lat_ts as well as lat_0.

If Projection-Type (Grid_Mapping_Name) is ***polar_stereographic***, and in the case that ***latitude_true_scale*** is defined, the CF attributes is missing the attribute: ***latitude_of_projection_origin***.

While the ***latitude_of_projection_origin*** for ***polar_stereographic*** might be inferred by the ***latitude_true_scale***, when that is defined, this suggests the ***latitude_of_projection_origin*** is not critical and should be left off. There are, however, end-user applications, such as Panoply, that do not work correctly without this attribute.

It is recommended that ***latitude_of_projection_origin*** always be included for ***polar_stereographic*** projection in the conversion of a CRS to CF grid_mapping attributes. When converting to CF, this is known and can be provided correctly, without conflict.

Attached (see zip archive) are two images and two NetCDF files. The NetCDF files have a grid_mapping variable generated from ***CRS . to_CF()***, for a ***polar_stereographic*** projection, with ***latitude-true-scale*** set to 70° - one supplemented with ***latitude_of_projection_origin***, and the other as-generated without ***latitude_of_projection_origin***. There are also two image files that show the output of Panoply for these two cases - but shown without the spatial subsetting for better visual reference. (The data files themselves are subset to minimize their size).

While Panoply’s behavior is perhaps not exemplary, it shows what can happen when ***latitude_of_projection_origin*** is missing. It is better if ***CRS.To_CF()*** can always include this attribute to avoid any confusion.

For PyProj (**pyproj**/pyproj/crs/**\_cf1x8.py#\_polar_stereographic\_\_to_cf)**:

```
def _polar_stereographic__to_cf(conversion):
    """
    http://cfconventions.org/cf-conventions/cf-conventions.html#polar-stereographic
    """
    params = _to_dict(conversion)
    if conversion.method_name.lower().endswith("(variant b)"):
        return {
            "grid_mapping_name": "polar_stereographic",
            ***"latitude_of_projection_origin":***
            ***   -90 if params["latitude_of_standard_parallel"] < 0 else 90,***
            "standard_parallel": params["latitude_of_standard_parallel"],
            "straight_vertical_longitude_from_pole": params["longitude_of_origin"],
            "false_easting": params["false_easting"],
            "false_northing": params["false_northing"],
        }
    return {
        "grid_mapping_name": "polar_stereographic",
        "latitude_of_projection_origin": params["latitude_of_natural_origin"],
        "straight_vertical_longitude_from_pole": params["longitude_of_natural_origin"],
        "false_easting": params["false_easting"],
        "false_northing": params["false_northing"],
        "scale_factor_at_projection_origin": params["scale_factor_at_natural_origin"],
    }

```
[LatPrjOrigin.zip](https://github.com/pyproj4/pyproj/files/13620838/LatPrjOrigin.zip)

**Comment by djhoese** [comment]
> It is recommended

@autydp Recommended by who? CF? You? PROJ? Panoply?

From a pyproj point of view, unless I'm misunderstanding something, pyproj is producing what the CF standard says to produce. If you disagree with what the CF standard says and that one or more of these attributes should be required then I'd suggest filing an issue with them. As you point out though this primarily seems a limitation of Panoply which should maybe be patched to address the issue.

Even if pyproj were to add this attribute to the "to CF" conversion (ignoring actual minimized CF compatibility), it doesn't mean that Panoply will work with any other CF standard grid mappings of these projections. Additionally, there may be some CF file checkers that would now fail with files generated from pyproj's CF output depending on how strict they are.

Again, I may not be understanding all of this so feel free to correct me where my understanding is lacking.

**Comment by autydp** [comment]
This would be my own recommendation, but it is not, to my knowledge, counter to the CF standard.  As of CF 1.9 ([http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#polar-stereographic](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#polar-stereographic)), this reference shows both the latitude_of_projection_origin and either standard_parallel or scale_factor_at_projection_origin.  The latitude_of_projection_origin is not stated as specific to just the variant B of the projection.

I’ll note that there is a difference between a method or specification of formulas, with the parameters to compute the projection, versus the metadata to describe a projection applied. It is true that the latitude_of_projection_origin is not strictly required for variant B formulas for Polar Stereographic.  However, for the CF metadata of the projection, it is useful to provide this additional attribute.

**Comment by djhoese** [comment]
@autydp That CF description looks the same as for CF 1.7 so I'm not sure @snowman2's opinion will change. If you feel very strongly about it, maybe a pull request with the change would restart the discussion.

**Comment by snowman2** [comment]
You can see the expected parameters for Variant B here:

- https://epsg.org/coord-operation-method_9829/Polar-Stereographic-variant-B.html
- [PolarStereographicBConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#pyproj.crs.coordinate_operation.PolarStereographicBConversion)

The `latitude_of_projection` origin is not used anywhere in Variant B. To prevent confusion with Variant A, I think that it would be a good idea to not include it. I suggest filing an issue with Panoply instead.
