### ISSUE TITLE
Noob Question, How to Install?

### ISSUE THREAD

**Issue by aaronstar** [pyproj4/pyproj#13]
Hi there, I have very little experience with python or anything similar.
I have  a .gz file from https://pypi.python.org/pypi/pyproj?, which I extracted using 7zip then opened cmd (Windows) with Administrator privileges and entered

cd C:\Users\username\Desktop\pyproj-1.9.4
setup.py install

I don't get it, in step by step instructions how do I install this to a functioning state?

**Comment by KAMI911** [comment]
Linux:

wget https://github.com/jswhit/pyproj/archive/v1.9.4rel.zip
unzip v1.9.4rel.zip
cd pyproj-v1.9.4rel
python setup.py build
sudo python setup.py install


Windows

Download:

http://www.lfd.uci.edu/~gohlke/pythonlibs/
<http://www.lfd.uci.edu/%7Egohlke/pythonlibs/#numpy>

One of these files:

pyproj-1.9.4-cp27-none-win_amd64.whl for 64 bit version

http://www.lfd.uci.edu/%7Egohlke/pythonlibs/3i673h27/pyproj-1.9.4-cp27-none-win_amd64.whl

pyproj‑1.9.4‑cp27‑none‑win32.whl for 32 bit version

http://www.lfd.uci.edu/~gohlke/pythonlibs/3i673h27/pyproj-1.9.4-cp27-none-win32.whl

And install it:
C:\Python27\Scripts\pip.exe install "pyproj-1.9.4-cp27-none-win_amd64.whl"




Üdvözlettel / Best Regards:

Kálmán (KAMI) Szalai

2015-08-16 9:46 GMT+02:00 aaronstar <notifications@github.com>:

**Comment by WlaKom** [comment]
I can't do it. 
C:\Utility\Python27\Scripts\pip.exe install "pyproj-1.9.5-cp27-none-win_amd64.whl"
Give me:
Fatal error in launcher: Unable to create process using '"'

Also, when I installed od Windows 10/64
PIL-1.1.7.win32-py2.7.exe
it stopped with:
"Setup has stopped working because of a problem."

**Comment by micahcochran** [comment]
pyproj version 1.9.5 has issues when compiling the internal version of PROJ on some Windows machines.  Did you get the installation of pyproj to work?  If it did not work, could you copy and paste the output of pip install?

**Comment by WlaKom** [comment]
I had to remove the 64 (Problem with pypro for Win64.) and re-install version 32.
Problem with pypro for Win64.

So, we need:
python-2.7.10.msi
PIL-1.1.7.win32-py2.7.exe
pyproj-1.9.5-cp27-none-win32.whl

C:\Python27\Scripts\pip.exe install "pyproj-1.9.5-cp27-none-win32.whl"

Now everything works correctly even JOSM plug-in Scanaerial.

**Comment by micahcochran** [comment]
The wheel binary files of pyproj on the website http://www.lfd.uci.edu/~gohlke/pythonlibs/ are not supported by the project.  I'm glad you had better experiences with the 32-bit version of the Windows binary wheels.  

The project only supports installing from setup.py, which requires a C compiler even if PROJ4 is installed on your system.

**Comment by malikaben** [comment]
I have a problem installing pyproj in my mac computer, I am using spyder in anaconda.
I used pip installation and this is what I get as an error:

!pip install pyproj
Collecting pyproj
  Using cached https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    using bundled proj4..
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/br/2nxyz8j521jgjqmzszzjlrwh0000gn/T/pip-install-tns_1rrq/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/br/2nxyz8j521jgjqmzszzjlrwh0000gn/T/pip-install-tns_1rrq/pyproj/


I will really appreciate your help
Thanks

**Comment by snowman2** [comment]
Related to #216
