### ISSUE TITLE
Binary wheels for pyproj?

### ISSUE THREAD

**Issue by sgillies** [pyproj4/pyproj#130]
I'd love to see macosx (primarily, maybe manylinux1, too) binary wheels on PyPI as with Pillow ([PyPI](https://pypi.python.org/pypi/Pillow/5.0.0#downloads), [GitHub](https://github.com/python-pillow/Pillow)), and I am willing to help. Is this something the project would be interested in doing?

I'm making analogy to Pillow (formerly PIL) because it includes C sources and C extension modules (see https://github.com/python-pillow/Pillow/tree/master/src) much like pyproj's copy of PROJ (https://github.com/jswhit/pyproj/tree/master/src). Binary wheels would let most Python users on OS X install and use pyproj without needing to download and install Xcode.

**Comment by fenchu** [comment]
Same request for windows. The smallest semi working installation of visual studio I've managed to set up is 8GB.

**Comment by ocefpaf** [comment]
:+1: @jswhit is this something you would be interested? I don't really have experience with wheels (I'm a big advocate of conda/conda-forge) but I'd love to see this too. Pip users are hurting without it.

**Comment by ngoldbaum** [comment]
You may be interested in https://github.com/matthew-brett/multibuild to set up building wheels.

I've been pretty happy using it for other projects.

**Comment by tomkralidis** [comment]
+1 for wheels.  Would be very helpful!

**Comment by jswhit** [comment]
@matthew-brett, would you be willing to create a pyproj-wheels project under MacPython?

**Comment by matthew-brett** [comment]
Yes, no problem.  There actually nothing special about the MacPython organization, the only advantage is that I have write access so I can push directly, if necessary, but if you want that, you can add me as a collaborator to your own repo.   The extra moving part is the access to Rackspace for upload, but I can do that with a PR to a repository you own, if you prefer.

**Comment by jswhit** [comment]
@matthew-brett, I added you as a collaborator.  I'd say whichever way is easier for you (MacPython project, or PR for this repo).

**Comment by jswhit** [comment]
pull request #155 adds the ability to build binary wheels (thanks to @snowman2).  @matthew-brett, can you add the ability to upload to rackspace to that PR?

**Comment by matthew-brett** [comment]
Do you mind merging, and then I'll do another PR adding the Rackspace stuff?

**Comment by jswhit** [comment]
Sure, will do.

**Comment by snowman2** [comment]
Binary wheels are working for osx and Linux. Should be included in the 2.0.1 release. Currently working on windows wheels [here](https://github.com/pyproj4/pyproj-wheels/issues/3). Any assistance with this would be appreciated.

**Comment by snowman2** [comment]
I am calling this issue resolved. Thanks for the report/idea!
