### ISSUE TITLE
numpy 1.25 warning on 1-element array input

### ISSUE THREAD

**Issue by greglucas** [pyproj4/pyproj#1307]
#### Code Sample, a copy-pastable example if possible

```python
import time

import numpy as np
from pyproj import Transformer


transformer = Transformer.from_crs(2263, 4326)

# Repeat the calculation a bunch of times
t0 = time.time()
for i in range(2000000):
    transformer.transform(np.array([0]), np.array([1]))
    # transformer.transform(0, 1)

t1 = time.time()
print(t1 - t0)

```
#### Problem description

Numpy 1.25 is now issuing a warning on auto-conversion of 1-element arrays to double. We have recently added a try-except for a fast-path on the transformer that tries the conversion and then catches the exception. However, this now _also_ throws a warning, which we actually don't care about, but if running with `python -Werror script.py` it will raise.

We can add the following filter to ignore these warnings within that block, but this adds a significant slowdown of ~5x for the single-point case.
`single-point: ~10s`
```python
warnings.filterwarnings("ignore", message="Conversion of an array with ndim > 0")
```

Another option is to catch all exceptions and then do the comparison test and re-raise within the exception block.
`single-point: ~2s`
```python
        except (TypeError, Exception) as e:
            if not (isinstance(e, TypeError) or
                    str(e).startswith("Conversion of an array with ndim > 0")):
                raise e
```

I'm raising this issue to get thoughts and ideas on what would be the best way to handle this (maybe something other than those two ideas above). The patch should go in `geod` and `transformer`, I haven't looked in detail at other locations. This was originally raised over in Cartopy: https://github.com/SciTools/cartopy/pull/2194 but seems like it should probably be addressed in Pyproj

cc @neutrinoceros

#### Expected Output

No warnings using Numpy 1.25

#### Installation method
`pip install -e .`

**Comment by greglucas** [comment]
Thinking more about the extra `except:` conditional. That actually won't help hide the plain warnings, it only helps the case when we've converted the warnings to errors with `-Werror`. I am not entirely sure there is a great solution here, other than to tell users to ignore the warning for this single version of numpy if they pass in a 1-element array... The 5x slowdown seems like a big price to pay to minimize a downstream warning.

**Comment by snowman2** [comment]
I agree that no code change and recommend users apply a warning filter sounds like the best course of action.

Side note: Mind making an issue to remove the hacks we put in place due to the current numpy conversion to double in a future version of pyproj?

**Comment by greglucas** [comment]
Opened the new issue.

Lets close this issue then and move the conversation back to Cartopy @neutrinoceros. Sorry for pointing you all over the place here!

**Comment by neutrinoceros** [comment]
no worries ! I understand this issue is more subtle than most :-)

**Comment by felixdivo** [comment]
For others: The new issue is #1309

**Comment by raphaelquast** [comment]
Quick question just to be absolutely sure how to deal with this warning since I'm still a bit confused... 

Am I right that the recommendation here is to simply ignore this warning since upcoming releases of `pyproj` will properly handle 1-element arrays? 

...Or in other words:  
Will `transformer.transform(np.array([0]), np.array([1]))` work (without warnings) with with `numpy 2.x` or should I implement a workaround to avoid future errors?

**Comment by snowman2** [comment]
```bash
python -m pip install numpy --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --pre
python -m pip install pyproj
```
```python
>>> import numpy
>>> import pyproj
>>> numpy.__version__
'2.0.0.dev0+git20240203.5c34c87'
>>> pyproj.__version__
'3.6.1'
>>> transformer = Transformer.from_crs(4326, 3857, always_xy=True)
>>> transformer = pyproj.Transformer.from_crs(4326, 3857, always_xy=True)
>>> transformer.transform(numpy.array([0]), numpy.array([0]))
(array([0.]), array([0.]))

```

**Comment by djhoese** [comment]
@snowman2 I could be doing something wrong, but this does not seem to be fixed in modern pyproj versions:

```python
In [9]: warnings.simplefilter("always")

In [10]: transformer.transform(numpy.array([0]), numpy.array([0]))
/home/davidh/miniforge3/envs/satpy_py312/lib/python3.12/site-packages/pyproj/transformer.py:817: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return self._transformer._transform_point(
/home/davidh/miniforge3/envs/satpy_py312/lib/python3.12/site-packages/pyproj/transformer.py:817: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return self._transformer._transform_point(
Out[10]: (array([0.]), array([0.]))
```

**Comment by djhoese** [comment]
Ah but I do see in the related #1309 that numpy 1.x support can/should be dropped this September. Sorry, I had misunderstood the advice in your last comment.
