### ISSUE TITLE
BUG: Cython 3 Compatibility

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#1321]
```
Error compiling Cython file:
------------------------------------------------------------
...

cdef void pyproj_context_initialize(PJ_CONTEXT* context) except *:
    """
    Setup the context for pyproj
    """
    proj_log_func(context, NULL, pyproj_log_function)
                                 ^
------------------------------------------------------------

pyproj/_datadir.pyx:148:33: Cannot assign type 'void (void *, int, const char *) except * nogil' to 'PJ_LOG_FUNCTION'
```

**Comment by snowman2** [comment]
https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept

**Comment by pritish-ranjan01** [comment]
Same problem with our docker build. 

BASE_IMAGE=python:3.9-alpine3.16
pyproj = "~=2.6.1"

poetry = 1.2.2

**Comment by richieho-chownow** [comment]
It does not work for projects that still use `setup.py`.

`ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml`

Seems like you have the fix in v3.6.1. If so, when will will it be released?

**Comment by snowman2** [comment]
> Seems like you have the fix in v3.6.1. If so, when will will it be released?

Here is the 3.6.1 milestone: https://github.com/pyproj4/pyproj/milestone/11. With current dependencies, it is expected to arrive sometime at the end of September or beginning of October.

**Comment by richieho-chownow** [comment]
> 

I see Python 3.12 as a dep. Will projects that use pyproj also need to be on Python 3.12?

**Comment by snowman2** [comment]
https://pypi.org/project/pyproj/3.6.1/
