### ISSUE TITLE
Transformer: EPSG:27700 to EPSG:4978 (3D) not returning PROJ string

### ISSUE THREAD

**Issue by romaintha** [pyproj4/pyproj#1324]
```python
from pyproj.transformer import Transformer, CRS
transformer = Transformer.from_crs(CRS(27700).to_3d(), CRS(4978).to_3d())
transformer.to_proj4()  # return None in 3.6.0
```
#### Problem description
So far with pyproj 3.2.1, running transformer.to_proj4()  would return the proj string. Now in 3.6.0, it returns None

#### Environment Information
pyproj info:
    pyproj: 3.6.0
      PROJ: 9.2.1
  data dir: /home/romain/Envs/xxx/lib/python3.10/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /home/romain/.local/share/proj
PROJ DATA (recommended version): 1.14
PROJ Database: 1.2
EPSG Database: v10.088 [2023-05-13]
ESRI Database: ArcGIS Pro 3.1 [2023-19-01]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
executable: /home/romain/Envs/xxx/bin/python
   machine: Linux-5.19.0-46-generic-x86_64-with-glibc2.35

Python deps:
   certifi: 2023.5.7
    Cython: 0.29.36
setuptools: 59.8.0
       pip: 23.1.2

#### Installation method
pip

**Comment by romaintha** [comment]
It means that we have to upgrade our codebase? Everywhere we were using 
```python
transformer = Transformer.from_crs(CRS(27700).to_3d(), CRS(4978).to_3d())
```

We need to do:
```python
transformer = TransformerGroup.from_crs(CRS(27700).to_3d(), CRS(4978).to_3d()).transformers[0]
```

**Comment by snowman2** [comment]
Closing as the behavior is expected.

**Comment by snowman2** [comment]
Also see: https://proj.org/en/9.2/operations/operations_computation.html
