### ISSUE TITLE
pip install pyproj

### ISSUE THREAD

**Issue by samsammurphy** [pyproj4/pyproj#133]
* Pip version: pip 9.0.1
* Python version: Python 3.6.4
* Operating system: Linux Mint 18.1 Serena

### Description:

I am trying to install pyproj using pip. It looks for libpython3.6m.so.1.0 but does not find it, which was not expected.

### What I've run:

```
$ mkvirtualenv pyproj --python=python3
$ pip install pyproj
$ python
>>> import pyproj
#from pyproj import _proj
#ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

 I was able to install from [source](https://pypi.python.org/pypi/pyproj/1.9.5.1) following the README,  reporting here in case helpful.

**Comment by snowman2** [comment]
Can you try pyproj==2.0.1 and see if it works?

**Comment by snowman2** [comment]
Feel free to reopen if this issue persists. Thanks for the report!
