### ISSUE TITLE
"no arguments in initialization list" runtime error

### ISSUE THREAD

**Issue by rgommers** [pyproj4/pyproj#134]
Hi, I'm running into a cryptic error. My CRS in the geopandas dataframe seems to be properly set, however I cannot convert it to any other CRS. 
```
>>> print(gdf_PLU.crs)
epsg:2193
>>>gdf_PLU.to_crs(epsg=4326)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-92-46b32e6c8012> in <module>()
      1 print(gdf_PLU.crs)
----> 2 gdf_PLU.to_crs(epsg=4326)

~/anaconda3/envs/hthf/lib/python3.6/site-packages/geopandas/geodataframe.py in to_crs(self, crs, epsg, inplace)
    384         else:
    385             df = self.copy()
--> 386         geom = df.geometry.to_crs(crs=crs, epsg=epsg)
    387         df.geometry = geom
    388         df.crs = geom.crs

~/anaconda3/envs/hthf/lib/python3.6/site-packages/geopandas/geoseries.py in to_crs(self, crs, epsg)
    283             except TypeError:
    284                 raise TypeError('Must set either crs or epsg for output.')
--> 285         proj_in = pyproj.Proj(self.crs, preserve_units=True)
    286         proj_out = pyproj.Proj(crs, preserve_units=True)
    287         project = partial(pyproj.transform, proj_in, proj_out)

~/anaconda3/envs/hthf/lib/python3.6/site-packages/pyproj/__init__.py in __new__(self, projparams, preserve_units, **kwargs)
    356         # on case-insensitive filesystems).
    357         projstring = projstring.replace('EPSG','epsg')
--> 358         return _proj.Proj.__new__(self, projstring)
    359 
    360     def __call__(self, *args, **kw):

_proj.pyx in _proj.Proj.__cinit__ (_proj.c:1170)()

RuntimeError: b'no arguments in initialization list'
```

I can't find this error message in any other issue. From similar issues it seems some data files could be missing (if so, how can I install them; I'm using the binary that is dragged in by conda-forge geopandas). Or is it something else?

**Comment by rgommers** [comment]
A bit of digging found that the data file for all EPSG codes is in `site-packages/pyproj/data/epsg`. That does contain the code I'm using:
```
# NZGD2000 / New Zealand Transverse Mercator 2000
<2193> +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ell      ps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs  <>
```
So that seems fine. Still unclear what the problem here is.

**Comment by ocefpaf** [comment]
Can you share the data or a simple example that reproduces the error?

**Comment by micahcochran** [comment]
@rgommers Try this code in the Python console.
```python
>>> from pyproj import Proj
>>> Proj('+init=epsg:2193', preserve_flags=True)
```
Does it produce an error?

This is what should be passed in that line, please try it, too.
```python
>>> Proj({'init': 'epsg:2193', 'no_defs': True}, preserve_flags=True)
```
Does that error?

**Comment by rgommers** [comment]
@micahcochran both of those work fine.

**Comment by micahcochran** [comment]
@rgommers That's exactly what that line should be doing in Python 3.6.

Unless you are having problems with Fiona (doubtful):
```python
>>> from fiona.crs import from_epsg
>>> from_epsg(2193)
{'init': 'epsg:2193', 'no_defs': True}
```

**Comment by rgommers** [comment]
Okay here's a standalone example that managed to isolate the problem; with @micahcochran's suggestions things work as expected.

I'd say this is still a valid issue - a clearer error would have allowed finding the problem more easily. If you agree, I can send a PR for that.

```
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point


def df_to_gdf(input_df, crs='epsg:2193'):
    """
    Convert a DataFrame with longitude and latitude columns
    to a GeoDataFrame.
    """
    df = input_df.copy()
    geometry = [Point(xy) for xy in zip(df.easting, df.northing)]
    return gpd.GeoDataFrame(df, crs=crs, geometry=geometry)


northing = [6.095531e+06, 5.681031e+06]
easting = [1.675638e+06, 2.020215e+06]
some_data = [1, 2]
df = pd.DataFrame(data=np.asarray([northing, easting, some_data]).T,
                  columns=['northing', 'easting', 'somedata'])
try:
    gdf = df_to_gdf(df)
    gdf.to_crs(epsg=4326)
except RuntimeError:
    print('epsg:2193 didnt work')

gdf = df_to_gdf(df, crs='+init=epsg:2193')
gdf2 = gdf.to_crs(epsg=4326)
print(gdf2.crs)

gdf = df_to_gdf(df, crs={'init': 'epsg:2193', 'no_defs': True})
gdf3 = gdf.to_crs(epsg=4326)
print(gdf3.crs)
```
gives
```
epsg:2193 didnt work
{'init': 'epsg:4326', 'no_defs': True}
{'init': 'epsg:4326', 'no_defs': True}
```

**Comment by micahcochran** [comment]
I'd accept a PR for an improved error message.

**Comment by iboates** [comment]
I'm encountering this error still and nothing in this thread has helped. I have tried:

```
p2 = pyproj.Proj("epsg:26910")
p2 = pyproj.Proj(init="epsg:26910")
p2 = pyproj.Proj('+init=epsg:26910', preserve_flags=True)
p2 = pyproj.Proj({'init': 'epsg:26910', 'no_defs': True}, preserve_flags=True)
```

Every single one of them returns `RuntimeError: b'no arguments in initialization list'`

Python version is 3.6 and pyproj version is 1.9.5.1, installed with anaconda

**Comment by Jens-R-Pedersen** [comment]
I'm also facing the same issue, but comments above by Eskapp make no sense to me.  I also use Anaconda.  Can you clarify what exactly needs to be done to clear this error?

**Comment by Eskapp** [comment]
Trying to clarify @Jens-R-Pedersen :
I copied the data folder (located here: `https://github.com/jswhit/pyproj/tree/master/lib/pyproj/`) in `C:\Anaconda3\Lib\site-packages\pyproj\` (which I am not sure is useful or not because after that, the error was still there)

Then, I realized that Cython was not installed in the environment I was working in. So I installed it and after that the error disappeared and everything works perfectly. I would suggest checking that Cython is installed, the first thing to try.

**Comment by Jens-R-Pedersen** [comment]
Thank you for the response.

I have verified that Cython is installed.  Still get the error.

I looked at your reference to the data folder below, but I don’t see any way to copy this???  Please excuse my ignorance on how to use Github.

Thanks again,
Jens

**Comment by Eskapp** [comment]
@Jens-R-Pedersen You can clone the repo or download it as a zip file.

**Comment by kaandogusoy** [comment]
I am also having the same problem. Basically, I try to change crs of a dataframe by the following line and it is not been working for the last week: dataframe2 = dataframe1.to_crs(epsg='4326')
It was working about 10 days ago, so I do not know why it is not working now. Any help would be appreciated

**Comment by QuLogic** [comment]
We seem to be triggering this in the [initial Cartopy AppVeyor setup](https://github.com/SciTools/cartopy/pull/1224), but only on Python 3.6 and not 2.7. Note that the 2.7 build also pins Cython 0.17 and proj4 4.9.1, among others, and then ends up with pyproj 1.9.4. The 3.6 build uses the latest of everything, ending up with pyproj 1.9.5.1.

**Comment by QuLogic** [comment]
OK, I actually figured out the issue we were having. We activate the environment and then install everything other than Python in it. But latest proj builds set `PROJ_LIB` and we need to activate the environment after installing it. Easiest fix was to request _all_ needed packages when creating the environment, and then activate it.

So for anyone else hitting this, make sure you a) are installing in an environment, not the root, and; b) activate after installing proj (or pyproj).

**Comment by jfnk** [comment]
I experienced the same Error (using an anaconda python 3.6 and pyproj 1.9.5.1) and fixed it by manually downloading the data directory as suggested by @Eskapp and then set the `PROJ_LIB` environment variable to point to the data directory. 

This fixed the issue. 

Maybe this is due to an error in the conda recipe?

**Comment by iboates** [comment]
@jfnk: I think so, I was also missing the data directory with an anaconda install, and downloading it manually and sticking it where it was expected to be fixed the issue.

**Comment by forkozi** [comment]
I was having the same issue in a 32-bit miniconda Python 2.7 environment.  I did the same thing @jfnk did, and everything worked great.  Thanks!

**Comment by svilella** [comment]
Hi, I am experiencing the same issue but nothing proposed in this topic helps. I am running Python 3.7.2, without Anaconda, on OsX Mojave. I should have everything installed, the 'data' folder in pyproj is there (I downloaded and overwrote it again just to be sure).

I find really strange that the same code, on my old laptop (same kind of Python installation, without conda) and on the very same files, worked flawlessly. Now it's not working, it returns this error when I try to set the crs, but I really don't understand what's the matter here.

**Comment by geo-py** [comment]
Hello Guys. I'm really new to Python and am running into the same error. I've been trying to work through this introductory course to Python for remote sensing purposes

https://github.com/patrickcgray/open-geo-tutorial

I get the issue in the following Jupyter notebook: 

chapter_4_vector.ipynb

I get the following runtime error:

RuntimeError: b'no arguments in initialization list'

Would anyone be willing to walk me through?

**Comment by ouyangkid** [comment]
Hi, guys.
I meet the problem on Win7 and anaconda.  My code run well on ubuntu, but get the above problem.
I have a simple solution, just uninstall the pyproj from anaconda and use **pip install instead**.
It works on my win7.

**Comment by ibrahimhersi3** [comment]
hey guys !

thank you so much for the help and suggestions.
i had the same exact problem as @rgommers after following @Eskapp and @iboates steps everything seem to work fine. I will briefly explain what i did for those who are still facing problems.

1. I downloaded the whole pyproj folder from (https://github.com/jswhit/pyproj/tree/master/lib/) and replaced that with my old pyproj folder in my directory (C:\Anaconda3\Lib\site-packages)
2. Try to run your code (hope it works !)
3. If step 2 is not working then try  pip installing Cython by going to terminal and type in "pip install Cython"

**Comment by antonia-had** [comment]
@ibrahimhersi3's solution worked for me also. (Python 3.6, using anaconda, Windows 10)

**Comment by zhuang-hao-ming** [comment]
I tried @ibrahimhersi3 solution, but replacing the old folder directly with the new folder is not effective. You cannot delete the pyd file in the original directory.

**Comment by ibrahimhersi3** [comment]
@zhuang-hao-ming just rename the old pyproj folder (pyprojOld e.g) and move the new pyproj folder you have downloaded inside site-packages directory

**Comment by rickantonais** [comment]
Just had the same trouble after re-installing all my packages and the solution of @jfnk worked perfect for me : just put the following code in order to make it work : 
`os.environ['PROJ_LIB']=r"C:\Users\[...replace accordingly...]\Anaconda3\Library\share"`

**Comment by ycebear** [comment]
Thanks a lot for all the helpful comments ! The solution of @rickantonais worked for me too:

    1. no additional download necessary, but introduce the following code:
    2. import os
    3. os.environ['PROJ_LIB']=r"C:[... _path to_ ….]\Anaconda3\Library\share"

**Comment by daniellobrunello** [comment]
@rgommers checked for the current CRS in the first line of his provided code, but as many other people (probably), I was just looking quickly for the 'thumbs-up'-post. 
It turned out that  
`> df.crs`
`> {}`
my data frame had no CRS set... that results in the same error message.

**Comment by snowman2** [comment]
Can y'all try pyproj==2.1.0 and see if it resolved this issue. You can install it with:
`pip install pyproj==2.1.0` to use binary wheels
or with:
`conda install -c conda-forge pyproj=2.1.0`

**Comment by asif-rehan** [comment]
@snowman2 Just upgraded to 2.1.0. Still seeing almost similar error as in the previous version of 1.9.6. 

```
/s/anaconda/users/arehan2/miniconda2/lib/python2.7/site-packages/geopandas/geoseries.pyc in to_crs(self, crs, epsg)
    283             except TypeError:
    284                 raise TypeError('Must set either crs or epsg for output.')
--> 285         proj_in = pyproj.Proj(self.crs, preserve_units=True)
    286         proj_out = pyproj.Proj(crs, preserve_units=True)
    287         project = partial(pyproj.transform, proj_in, proj_out)

/s/anaconda/users/arehan2/miniconda2/lib/python2.7/site-packages/pyproj/__init__.pyc in __new__(self, projparams, preserve_units, **kwargs)

_proj.pyx in _proj.Proj.__cinit__()

RuntimeError: no arguments in initialization list
```

**Comment by snowman2** [comment]
That still appears to be the old version. Can you please verify that you have the correct version installed?

**Comment by mullenkamp** [comment]
Just fyi, this issue has gone away for me with the 2.1.* versions.

**Comment by snowman2** [comment]
Thanks for the reports and for looking into this! If this issue still persists, feel free to reopen.

**Comment by christhiz** [comment]
Same observation. Issue is gone with upgrading to 2.1.* version.

**Comment by ToddEmonster** [comment]
Had the same issue. Tried a lot of the solutions proposed here 

Now the link to the repository on this thread is dead, so I downloaded the source code at https://github.com/pyproj4/pyproj

And @hahakid 's solution, which is `pip install pyproj` , worked for me.

I have Windows10, I initially installed geopandas with Anaconda 1.7.2 / conda 4.7.5, and I work with Python 3.7.3

**Comment by kp6689** [comment]
> ```python
> Proj({'init': 'epsg:2193', 'no_defs': True}, preserve_flags=True)
> ```

I am facing exactly the same issue and it turns out that this code throws an error. How do I proceed?

**Comment by snowman2** [comment]
Can you provide this information: 
```python
- pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
```

**Comment by snowman2** [comment]
Also, I haven't seen `preserve_flags` before. Do you mean `preserve_units`?

**Comment by jessedhenderson** [comment]
> Thanks a lot for all the helpful comments ! The solution of @rickantonais worked for me too:
> 
> ```
> 1. no additional download necessary, but introduce the following code:
> 2. import os
> 3. os.environ['PROJ_LIB']=r"C:[... _path to_ ….]\Anaconda3\Library\share"  
> ```

This solution worked for me as well. Installed pyproj with conda. Windows 7.

**Comment by prasunkgupta** [comment]
It was working till yesterday. Today I booted up my system, started the notebook and now it is not working :(

@snowman2 

> ```python
> - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
>  - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
>  - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
>  - Operation System Information (`python -c "import platform; print(platform.platform())"`)
> ```

1.9.6
0.5.20
3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17763-SP0


@jessedhenderson - This does not work for me. 

> ```
> 1. no additional download necessary, but introduce the following code:
> 2. import os
> 3. os.environ['PROJ_LIB']=r"C:[... _path to_ ….]\Anaconda3\Library\share"  
> ```

**Comment by prasunkgupta** [comment]
@snowman2 

> Can y'all try pyproj==2.1.0 and see if it resolved this issue. You can install it with:
> `pip install pyproj==2.1.0` to use binary wheels
> or with:
> `conda install -c conda-forge pyproj=2.1.0`

gives:
```
(geo_env) C:\>conda install -c conda-forge pyproj=2.1.0
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal
  - pyproj=2.1.0
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by prasunkgupta** [comment]
_This will definitely churn some stomachs._
Case1: Open the jupyter notebook with correponding environment (geo_env) directly and call the method to_crs --- Error "RuntimeError: b'no arguments in initialization list'"
![image](https://user-images.githubusercontent.com/7839690/61767692-adc44700-ae02-11e9-9ba2-2c51b9b074de.png)


Case2: I open anaconda prompt, activate my environment (geo_env), start my jupyter notebook and call the method to_crs --- No Errors!!!
![image](https://user-images.githubusercontent.com/7839690/61767877-39d66e80-ae03-11e9-8851-b27cbc6b2ef2.png)

**Comment by AlexandraKapp** [comment]
so I had the same problem. Using conda uninstall pyproj and then pip install pyproj worked to run the code 

> from pyproj import Proj
> Proj('+init=epsg:2193', preserve_flags=True)

With pip version 2.2.1 is installed, so that workes, but conda uses Version 1.9.6.

But once I installed geopandas, conda would install pyproj with Version 1.9.6 again and then my code would also crashed again. 

It worked, once I manually deleted the pyproj folder in anaconda\Lib\site-packages  instead of using conda uninstall. And then use pip install pyproj.

**Comment by calbaker** [comment]
I have this same problem in a Jupyter Notebook, but it works fine in Visual Studio Code.  Any ideas as to how this could be?

**Comment by AlexandraKapp** [comment]
Maybe your running the code in a different env in the jupyter notebook?

**Comment by calbaker** [comment]
I have only the one base environment.  What's also weird is that if I export the python script from VSCode as a Jupyter Notebook, VSCode launches the Jupyter Notebook, and the Jupyter Notebook works!  This is not, however, a great solution as it involves extra steps.

**Comment by calbaker** [comment]
Interestingly, if I launch either JupyterLab or Jupyter Notebook from Anaconda Navigator, rather than from an Anaconda Powershell Prompt, I get no errors!   Shouldn't these all be the same?

**Comment by smcateer** [comment]
I encountered this error when I tried to run:
```
from pyproj import Proj
Proj({'init': 'epsg:2193', 'no_defs': True}, preserve_flags=True)
```
On the following setup:
```
C:\...> conda list anaconda$
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
anaconda                  2019.07                  py37_0

pyproj.__version__:
	1.9.6
pyproj.proj_version_str:
	 0.5.20
sys.version.replace('\n', ' '):
	 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
platform.platform()
	 Windows-10-10.0.16299-SP0
```
I fixed the error by editing the file `datadir.py`
changed `.../Anaconda3\share\proj`
to `...\Anaconda3\Library\share`

**Comment by samcollie** [comment]
@smcateer 's solution works for me as well! Although, I have the same specs but the path is 

pyproj_datadir="C:\Anaconda3\Lib\site-packages\pyproj\data"

Thanks @smcateer !!

**Comment by ratnanil** [comment]
@smcateer's answer (https://github.com/pyproj4/pyproj/issues/134#issuecomment-521846924) worked for me as well.. and for all those who somehow missed where to look for the file `datadir.py` (like I did), it's located here in the folder  `\Lib\site-packages\pyproj` of the environment in question.

**Comment by arc12** [comment]
+1 for comment #134

**Comment by kaimoxuan123** [comment]
>  import os
> 3. os.environ['PROJ_LIB']=r"C:[... _path to_ ….]\Anaconda3\Library\share"

it reaally works for me !!! Thanks a lot.

**Comment by zuzhaoye** [comment]
1. Delete the folder 'pyproj' from 'site-package' (somewhere at ...\Anaconda\Lib\site-packages\pyproj, if you use Anaconda)
2. then 'pip install pyproj'
I faced the same problem and it worked for me. The root cause turned out to be Anaconda didn't install enough files.

**Comment by Nuwan-UWA** [comment]
> 1. Delete the folder 'pyproj' from 'site-package' (somewhere at ...\Anaconda\Lib\site-packages\pyproj, if you use Anaconda)
> 2. then 'pip install pyproj'
>    I faced the same problem and it worked for me. The root cause turned out to be Anaconda didn't install enough files.

it really works..as simple as it is. Thanks @zuzhaoye

**Comment by Tokusei** [comment]
Hi, I tried the most recent post. Replacing pyproj installed from anaconda and installing it with pip. It no longer gives an error, However the function has unexpected behaviour.

`
crs = {'init' :'epsg:3395'}
provinces_GPDF.plot()
print(provinces_GPDF.crs)
provinces_GPDF.to_crs(crs)
print(provinces_GPDF.crs)`

**Comment by 19950** [comment]
I had the same problem with pycharm. And I didnt have most of the folders that u guys mentioned above in my pyproj folder. And its version was 1.9. So I updated it to version 2... using conda. I think u should do it with conda rather than pip. 

During the installation, I found out that when I was installing geopandas it hadn't install MKL-2020.0 properly. When I updadet pyproj, MKL-2020.0 installed as well. And after that everything worked well and I had the needed folders in pyproj folder!

**Comment by hafez-ahmad** [comment]
gdf.to_crs('epsg = 4682')
Traceback (most recent call last):

  File "<ipython-input-36-a4588c0c5ce5>", line 1, in <module>
    gdf.to_crs('epsg = 4682')

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\geopandas\geodataframe.py", line 534, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\geopandas\geoseries.py", line 423, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 129, in _proj.Proj.__cinit__

RuntimeError: b'no arguments in initialization list'

**Comment by answerquest** [comment]
@zuzhaoye 's solution:
> 1. Delete the folder 'pyproj' from 'site-package' (somewhere at ...\Anaconda\Lib\site-packages\pyproj, if you use Anaconda)
> 2. then 'pip install pyproj'

Worked for me, but it throws up a warning message, documenting it here:
```
C:\Users\nsheth3\AppData\Local\Continuum\anaconda3\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning:'+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
```

**Comment by arckay88** [comment]
> 
> 
> After a bit of frigging around I was able to figure out the problem. I downloaded the repo source code and copied the folder `pyproj-master.zip\pyproj-master\lib\pyproj\data` and copied to the location indicated in `site-packages/pyproj/data/epsgdatadir.py` (making sure the names lined up, I had to rename the folder from `data` to `proj`
> 
> After that, the library worked perfectly. Perhaps it is a problem with using Anaconda to install it, but this extremely crucial data folder was simply not copied, or was possibly copied to the wrong location.

this one fixed mine
