### ISSUE TITLE
error installl pyproj==3.2.1 on debian:12

### ISSUE THREAD

**Issue by heriipurnama** [pyproj4/pyproj#1347]
hey, i getting error to installl pyproj==3.2.1 on debian:12

Collecting pyproj==3.2.1
  Using cached https://files.pythonhosted.org/packages/02/48/9d64166dfbb98d515655c3d28bce68f4b984a96c3bfe5ce81b160f16c763/pyproj-3.2.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-ys89f0uc/pyproj/setup.py:9: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      from pkg_resources import parse_version
    proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ys89f0uc/pyproj/

**Comment by snowman2** [comment]
Welcome!

Due to limited availability with our team, we only support the latest version of pyproj. I recommend upgrading and seeing if that works for you.

**Comment by djhoese** [comment]
I'd like to add that it looks like pip (or however you are installing this) is using the source tarball (`.tar.gz`) for this older version of pyproj. There should be binary wheels available for Python 3.7 to 3.9 for most 64-bit systems. If you have a newer version of Python then you must upgrade to a newer version of pyproj...or you must install the PROJ C library on your system before installing pyproj as that's what your error is about.

**Comment by heriipurnama** [comment]
thanks, I managed to solve this problem by upgrading pip3 to a newer version
