### ISSUE TITLE
Support for deprecated and non-deprecated objects

### ISSUE THREAD

**Issue by mwtoews** [pyproj4/pyproj#1367]
Initially from https://github.com/OSGeo/spatialreference.org/issues/3#issuecomment-1881859037 by @rouault it would be helpful to have support to see deprecated objects, and provide lists to non-deprecated objects.

For instance, here is a prototype of possible behavior to add a `.is_deprecated` property and a `get_non_deprecated` function:

```python
import pyproj
from pyproj import CRS

crs1 = CRS.from_epsg(28473)
assert crs1.is_deprecated
crs1_nondep = pyproj.get_non_deprecated(crs1)
assert len(crs1_nondep) == 1
assert crs1_nondep[0] == CRS.from_epsg(2503)

crs2 = CRS.from_epsg(4326)
assert not crs2.is_deprecated
assert len(pyproj.get_non_deprecated(crs2)) == 0
```

Relevant PROJ C API:

- [`proj_get_non_deprecated`](https://proj.org/en/9.3/development/reference/functions.html#c.proj_get_non_deprecated)
- [`proj_is_deprecated`](https://proj.org/en/9.3/development/reference/functions.html#c.proj_is_deprecated)

**Comment by snowman2** [comment]
Sounds reasonable. I think that adding a  `get_non_deprecated` method to each object that supports would be a good strategy.

**Comment by jjimenezshaw** [comment]
I was thinking on developing it. But I have some questions.

- `get_non_deprecated` is a method of the class `CRS`, or it is a free function that takes a CRS? For the former, it would be similar to `sub_crs_list`. For the later, where should be this function?
- `proj_get_non_deprecated` so far is only done for CRS (looking at the documentation).

**Comment by snowman2** [comment]
I recommend adding a class method. Thank you!
