### ISSUE TITLE
Invert lat lon "Transformer"

### ISSUE THREAD

**Issue by Runak33** [pyproj4/pyproj#1368]
Hello, using the "Transform" function, I realized that the input parameters were reversed, if you enter "x1, x2" the output positions do not match, while reversing the order of the inputs, "y1, y2", the output positions match the input positions (as you can see in the figure, the coordinates are different by changing the order of the inputs)

from pyproj import Transformer

inProj = 'epsg:4326'
outProj = 'epsg:32632'
x1, y1 = 12.48497983, 41.91058812

transformer = Transformer.from_crs(inProj, outProj)
lon, lat = transformer.transform(x1, y1)
print("bug_lon :", lon, "bug lat :", lat)

transformer_corr = Transformer.from_crs(inProj, outProj)
lon_corr, lat_corr = transformer.transform(y1, x1)

print("lon_correct :", lon_corr, "lat_correct :", lat_corr)

![image](https://github.com/pyproj4/pyproj/assets/114090484/d3ffa835-94f4-4df5-bc7d-7ace9d0c6ec1)

**Comment by muggenhor** [comment]
The documentation for migrating from pyproj 1 to pyproj 2 doesn't mention this at all and it's suggested code modification leads to bugs. Specifically the current example gives the example that the order of input parameters and output coordinates is the same as before. It is not.

I suggest updating that example to pass named variables as inputs and capture the outputs in named variables too for clarity.

https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1

**Comment by snowman2** [comment]
Good suggestion. A PR with that addition is welcome.
