### ISSUE TITLE
muslinux wheel missing

### ISSUE THREAD

**Issue by jrauschenbusch** [pyproj4/pyproj#1382]
## Expected behavior and actual behavior.

There should be a wheel for `musllinux`, to speed up CI build times significantly when using Alpine-based Python base images.

## Steps to reproduce the problem.

pip install pyproj => Builds from source instead of using a pre-built wheel for musllinux

## Operating system

Alpine Linux, x86_64 and aarch64

**Comment by snowman2** [comment]
The wheel builds are disabled here due to failures: https://github.com/pyproj4/pyproj/blob/70851a5888d29694d71616c2729dcf7033faff73/.github/workflows/release.yaml#L120

Contributions welcome to get the builds working.
