### ISSUE TITLE
Pyproj Update needed for windows 10 64 and python

### ISSUE THREAD

**Issue by FrancoisMoolman51** [pyproj4/pyproj#141]
To Whom it May Concern:.

Please could somebody update and fix issues for pyproj as it now complete out dated !!

As i needed it for project and pip can't install it !!

![screenshot_4](https://user-images.githubusercontent.com/6871602/45488823-e87d3d80-b762-11e8-8c51-a43edafc4e30.png)

**Comment by ocefpaf** [comment]
There are no binaries wheels on PyPI for `pyproj`. You'll have to use Gohlke's binaries,

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj

of `conda` to get a compiled version. The alternative is to compile it yourself but I do not recommend that on Windows.

**Comment by snowman2** [comment]
Refer to #216
