### ISSUE TITLE
Error: Input is not a transformation.

### ISSUE THREAD

**Issue by DevReduct** [pyproj4/pyproj#1434]
Hi,

I hope this is the right place to raise this issue. I'm not an experienced programmer but i believe I've found an issue.

I wrote a script that receives XY-coordinates and a PROJCS parameter in ESRI WKT / PRJ format as input (downloaded from https://epsg.io). Using PyProj, I transform these coordinates from the local coordinate system to WGS84.

The following error appears when providing the parameters for EPSG code 31466:
```
Traceback (most recent call last): 
  File "xxx\017 Python\PRJ to WGS84\prj_to_wgs84.py", line 21, in <module> 
    proj = pyproj.Transformer.from_crs(prj_parameters, 4326, always_xy=True) 
  File "pyproj\transformer.py", line 625, in from_crs 
  File "pyproj\transformer.py", line 337, in __init__ 
  File "pyproj\transformer.py", line 105, in __call__ 
  File "pyproj\\_transformer.pyx", line 583, in pyproj._transformer._Transformer.from_crs 
  File "pyproj\\_transformer.pyx", line 653, in pyproj._transformer._Transformer._init_from_crs 
  File "pyproj\\_transformer.pyx", line 359, in pyproj._transformer._Transformer._initialize_from_projobj 
pyproj.exceptions.ProjError: Input is not a transformation.: (Internal Proj Error: pipeline: Pipeline: Bad step definition: proj=hgridshift (File not found or invalid)) 
[PYI-3356:ERROR] Failed to execute script 'prj_to_wgs84' due to unhandled exception! 
```
Been looking all over the internet for a solution and after some time i found that the PROJCS string contains a parameter called "EXTENSION". If I remove this parameter from the string, my program works.

I can check if the string contains this parameter and then remove it, but that is not the cleanest option.
Is this a bug or am i doing something wrong here?

code:
```
# import libraries
import pyproj, csv, sys, pathlib, numpy as np

prj_parameters = 'PROJCS["DHDN_3_Degree_Gauss_Zone_2",GEOGCS["GCS_Deutsches_Hauptdreiecksnetz",DATUM["D_Deutsches_Hauptdreiecksnetz",SPHEROID["Bessel_1841",6377397.155,299.1528128],EXTENSION["PROJ4_GRIDS","BETA2007.gsb"]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",2500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",6.0],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'
coordinates = np.asarray([
	[2570512.975,5647780.839],
	[2570546.938,5648022.633]])
proj = pyproj.Transformer.from_crs(prj_parameters, 4326, always_xy=True)
fx, fy = proj.transform(coordinates[:,0],coordinates[:,1])
result = np.dstack([fy, fx])[0]
result = result.tolist()
print("\n".join(",".join(str(el) for el in row) for row in result))
```

Looking forward to a response.

Daan.

Sidenote: I load the actual parameters instead of using the EPSG code lookup, because that way I do not have to maintain the EPSG parameters. If a systems is updated, the user just loads these new parameters and I do not have to recompile with a new version of pyproj/EPSG list.
For example, in Maylasia, they use new versions of their coordinate system, but the ones that you find online are all old versions.

#### Environment Information
```
pyproj info:
    pyproj: 3.6.1
      PROJ: 9.3.0
  data dir: c:\users\daant.reduct\appdata\local\programs\python\python39\lib\site-packages\pyproj\proj_dir\share\proj
user_data_dir: C:\Users\DaanT.REDUCT\AppData\Local/proj
PROJ DATA (recommended version): 1.15
PROJ Database: 1.2
EPSG Database: v10.094 [2023-08-08]
ESRI Database: ArcGIS Pro 3.1 [2023-19-01]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
executable: c:\users\daant.reduct\appdata\local\programs\python\python39\python.exe
   machine: Windows-10-10.0.26100-SP0

Python deps:
   certifi: 2021.5.30
    Cython: None
setuptools: 56.0.0
       pip: 24.2
```

#### Installation method
I use pyinstaller to create an exe, runing that to verify the program.

#### Conda environment information (if you installed with conda):
No Conda

**Comment by jjimenezshaw** [comment]
epsg dot io is not an official reference.
I suggest using https://spatialreference.org/ as a better reference, because it is based on PROJ.
That CRS https://spatialreference.org/ref/epsg/31466/ in particular is using a grid file. It is available in PROJ-data, and used automatically when it is found.
You should enable the network functionality via https://pyproj4.github.io/pyproj/stable/api/network.html , PROJ_NETWORK, or install the grid files locally.

**Comment by DevReduct** [comment]
Thank you for your reply, noted that https://spatialreference.org/ is preferred. I use the epsg dot io website because it's more visually pleasing and and also allows for manual point conversion. A good way to verify that the CRS found is indeed the correct one. When I receive coordinates, I never get a clear answer about the coordinate system and when I ask for the ESPG code, they always look at me like I'm speaking some foreign language.

Network functionality can not be used as it must work offline as well.

Besides all the above, shouldn't this package be able to work even is their is an unexpected extra parameter in the PROJCS string?
I'm now going to handle it manually.

Daan.

**Comment by jjimenezshaw** [comment]
> Network functionality can not be used as it must work offline as well.

You can install the grid files in your computer

 
> Besides all the above, shouldn't this package be able to work even if their is an unexpected extra parameter in the PROJCS string? I'm now going to handle it manually.

The message says `(File not found or invalid)`. Using that "extension" is forcing the usage of the file, that is not found. You can either install it or remove the extension.
Even better you can use just the id `EPSG:31466`, and PROJ will automatically try to use the file if it is installed.
