### ISSUE TITLE
transform - meridian convergence support?

### ISSUE THREAD

**Issue by snowNath** [pyproj4/pyproj#144]
Hi,

I use pyproj to convert coordinates from several frame to WGS84. Some of the original coordinates have a several-degree angle convergence.
I read on the doc that the transform function "can take care of datum shifts". Does that mean that the grid north and meridian convergence are taken into acount during the transformation or do I need additional calculs to obtain the real heading?

**Comment by snowman2** [comment]
@kbevers @rouault, are you able to provide insight into this question?

**Comment by rouault** [comment]
> are you able to provide insight into this question?

I would need a more concrete example of how this concept of angle convergence translates in PROJ terms...

**Comment by snowman2** [comment]
@snowNath, are you able to provide an example?

**Comment by kbevers** [comment]
Grid north and meridian convergence are properties of projections and does not as such affect datum shifts. `proj -V +proj=...` or `proj_factors()` gives you the meridian convergence of a given projection.

**Comment by snowNath** [comment]
Thanks @kbevers, I mixed up the two notions. proj_factors() could indeed give me the meridian convergence I was looking for.

**Comment by snowman2** [comment]
Sounds like something that may be useful to add to the pyproj interface.
