### ISSUE TITLE
pip install fails in fresh environment on macos

### ISSUE THREAD

**Issue by m-albert** [pyproj4/pyproj#1459]
Hi, I just wanted to quickly report this here:

I ran into the following installation problem after these steps on macos:
- `conda create -n spatialdata python=3.10`
- `pip install spatialdata`

I got the following error:

```
Collecting pyproj>=3.3.0 (from geopandas>=0.14->spatialdata)
  Using cached pyproj-3.7.0.tar.gz (225 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

#### Installation method/steps
 - Installation method (conda, pip wheel, from source, etc...)
    - pip
 - How did you install PROJ? Where is it installed?
 - Please provide all commands/steps you used to install pyproj and PROJ.

    - `conda create -n spatialdata python=3.10`
    - `pip install spatialdata`

#### Environment Information
 - pyproj version you are attempting to install
     - 3.7
 - PROJ version (Execute `proj` command and give version here.)
     - 
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
     - 3.10
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
     - macOS-12.6-arm64-arm-64bit

**Comment by snowman2** [comment]
https://pyproj4.github.io/pyproj/stable/installation.html
```
conda config --prepend channels conda-forge
conda config --set channel_priority strict
conda create -n spatialdata python=3.10 pyproj
```
```
python -m pip install spatialdata
```

**Comment by snowman2** [comment]
Due to the runners available in GitLab, only x86_64 wheels are available for MacOS 12. arm64 wheels are available for MacOS 14. It is recommended to install pyproj via conda for your situation.
 
See: https://pypi.org/project/pyproj/#files
