### ISSUE TITLE
installation errors :_proj.c:4:20: fatal error: Python.h:没有那个文件或目录（No directory.）

### ISSUE THREAD

**Issue by storyofblue** [pyproj4/pyproj#147]
install on ubuntu and python 3.6

PROJ_DIR is set, using existing proj4 installation..
running build
running build_py
copying lib/pyproj/datadir.py -> build/lib.linux-x86_64-3.6/pyproj
running build_ext
building 'pyproj._proj' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/share/proj/include -I/usr/include/python3.6m -c _proj.c -o build/temp.linux-x86_64-3.6/_proj.o
_proj.c:4:20: fatal error: Python.h: 没有那个文件或目录
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by weatherfrog** [comment]
I don't know what `没有那个文件或目录` means in English :-)
But I suspect you are lacking Python header files. Have you tried `apt install libpython3-dev`?

**Comment by snowman2** [comment]
Can you try pyproj==2.0.1 and see if it works?

**Comment by snowman2** [comment]
Feel free to reopen if this issue persists. Thanks for the report!
