### ISSUE TITLE
whether it can transform GCS_Beijing_1954 to CGCS2000

### ISSUE THREAD

**Issue by Chenghui123** [pyproj4/pyproj#148]
I want to know whether it can transform GCS_Beijing_1954 to CGCS2000?
when i have a transformation, the result coordinates become very big, like 
![image](https://user-images.githubusercontent.com/33248072/47633756-13441980-db8a-11e8-94f2-ab081dd7c013.png)

who can help me? thank you very much!

**Comment by snowman2** [comment]
Can you try pyproj==2.0.1 and see if it works?

**Comment by snowman2** [comment]
Feel free to reopen if this issue persists. Thanks for the report!
