### ISSUE TITLE
hypot already defined in hypot.obj / One or more multiply defined symbols found

### ISSUE THREAD

**Issue by DefiniteBears** [pyproj4/pyproj#149]
I am attempting to build PyProj from the GitHub repository and are receiving an error.

Building with: pip install git+https://github.com/jswhit/pyproj.git

Receive error: 

ucrt.lib(api-ms-win-crt-math-l1-1-0.dll) : error LNK2005: hypot already defined in hypot.obj
       Creating library build\temp.win-amd64-3.7\Release\src\_proj.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\src\_proj.cp37-win_amd64.exp
    build\lib.win-amd64-3.7\pyproj\_proj.cp37-win_amd64.pyd : fatal error LNK1169: one or more multiply defined symbols found

This is with Python 3.7 installed via Anaconda on Windows 10. I have Cython version 0.29 installed. 

According to [https://github.com/jswhit/pyproj/issues/136](url), an install via GitHub should work on Python 3.7.

ucrt.lib is located in C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt_enclave\x64, not sure if this is part of my Visual Studio 2017 installation, or Windows 10 SDK.

**Comment by kennylawww** [comment]
I believe that was caused by the `hypot` function introduced in c++11. Because `./src/hypot.c` contains only one function `hypot`, deleting this file solves the problem for me and the installation continues.

Perhaps you can add a preprocessor that is able to prevents `hypot` from compiling in c++11.

**Comment by leekenjen2328** [comment]
@DefiniteBears Hey I was facing the same issue and managed to install an older version, try this
 `pip install pyproj==1.9.5.1
`
Saw this solution from here: https://www.bountysource.com/issues/68123827-1-9-6-does-not-build-on-windows-10-python-3-6-1

**Comment by snowman2** [comment]
Did you try installing pyproj with conda? `conda install -c conda-forge pyproj`?

**Comment by snowman2** [comment]
Refer to #216
