### ISSUE TITLE
1.9.6. fails unittests if nose2 not available

### ISSUE THREAD

**Issue by jdkloe** [pyproj4/pyproj#157]
the unittest/test.py tests fail when nose2 is not installed.
If I build and install the module and then run the unittests I get this error:
```
python2  unittest/test.py
Traceback (most recent call last):
  File "unittest/test.py", line 146, in <module>
    class ForwardInverseTest(unittest.TestCase):
  File "unittest/test.py", line 147, in ForwardInverseTest
    @nose2.tools.params(*pj_list.keys())
NameError: name 'nose2' is not defined
```
The same happens for python3.
From some debug prints it becomes clear that the HAS_NOSE2 switch is correctly set to False,
The problem is that the @unittest.skipUnless decorator works differently than expected.
Looking at the skip function in /usr/lib64/python2.7/unittest/case.py this decorator only sets some switches to skip the test cases during a unittest run, but the test class definition itself is still returned unchanged and executed and since nose2 is used inside it, this triggers the error.

**Comment by jswhit** [comment]
Anyone have any thoughts on how to fix this?

**Comment by cjmayo** [comment]
A possible solution here #223.

Another idea would be to copy the params function into test.py, it isn't many lines.

**Comment by snowman2** [comment]
Thanks @cjmayo!
