### ISSUE TITLE
pyproj on android (and iOS?) (thru kivy?)

### ISSUE THREAD

**Issue by caver456** [pyproj4/pyproj#158]
Greetings, thanks for this excellent project.  I'd like to use pyproj to convert between WGS84 lat/lon and WGS84 UTM in a smartphone app that I'm building with kivy.  What is the latest suggestion on how to accomplish this?

I was able to install pyproj on windows with the wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj (since I had some link.exe errors when trying easy_install and pip install) but I'm not clear on how you would install it for a smartphone.

**Comment by jswhit** [comment]
Sorry, I've got nothing.  If you do figure out please do post your solution here.

**Comment by snowman2** [comment]
I wonder if you would have better luck posting this on one or both of these sites?
- gis.stackexchange.com
- stackoverflow.com

**Comment by snowman2** [comment]
https://github.com/kivy/python-for-android

**Comment by snowman2** [comment]
Looks like they have a pyproj recipe:
https://github.com/kivy/python-for-android/blob/392d57f18ced01b30823320ef42030e35d170dcd/pythonforandroid/recipes/pyproj/__init__.py

**Comment by snowman2** [comment]
@caver456 It seems like `python-for-android` has an android recipe for `pyproj`(although it is outdated). I think they would be better suited to assist you with this process. So, I am going to close this issue and recommend that you raise an issue for them to update the `pyproj` recipe here: https://github.com/kivy/python-for-android
