### ISSUE TITLE
Converting between WGS84 longlat and geocent produces invalid data

### ISSUE THREAD

**Issue by KAMI911** [pyproj4/pyproj#16]
When I converting coordinates from:
+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs
to:
+proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs
projection I got this wit pyproj:

1.4405084639 103.8377068722 15.271
inf, inf, 15.271

1.3678260389 103.8449220306 23.822
inf, inf, 23.822

Checking with cs2cs command:
cs2cs +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs -r
provides the right data:
1.4405084639 103.8377068722 15.271  
-1524999.86 6191095.61 159267.12

1.3678260389 103.8449220306 23.822
-1525828.66 6191103.04 151232.86

Do you have idea what causes this problem? I tried with Pyproj 1.9.4 (master) that I downloaded today (5c18eefed6ce0a8cd6d05ca3bc4136130b72b922).

**Comment by luzhskij** [comment]
Hi! In the pj_transform it is necessary to transfer coordinates in radians.

**Comment by snowman2** [comment]
Can you verify this issue still exists with pyproj>=2.1.1?

**Comment by snowman2** [comment]
I am pretty sure it has to do with the order of your arguments as 103 is out of range for latlon in the y(lat)-direction:
```python
>>> import pyproj
>>> pyproj.__version__
'2.1.2'
>>> from pyproj import Transformer
>>> trans = Transformer.from_proj("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", "+proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
>>> trans.transform(1.4405084639, 103.8377068722, 15.271)
(inf, inf, inf)
>>> trans.transform(yy=1.4405084639, xx=103.8377068722, zz=15.271)
(-1524999.862888969, 6191095.609069525, 159267.121032734646)
>>> trans.transform(yy=1.3678260389, xx=103.8449220306, zz=23.822)
(-1525828.6577437809, 6191103.040502722, 151232.86472945704)
```
Feel free to reopen if you have further questions or issues.

Related to #26
