### ISSUE TITLE
pyproj.Proj(..) raising RuntimeError: 'Invalid argument'

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#17]
I have problems with the latest version of pyproj:

```
>>> import pyproj
>>> pyproj.__version__
'1.9.4'
>>> pyproj.Proj('+init=epsg:4326 +no_defs=True')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\test_pyproj3\lib\site-packages\pyproj\__init__.py", lin
e 347, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: b'Invalid argument'
```

I am on Windows and installed `pyproj` using conda. I was wondering if this was an error in the conda package, but I tried several different packages (the default channel + [ioos](https://anaconda.org/IOOS/pyproj) and [JimInCO](https://anaconda.org/JimInCO/pyproj) channels), but got the same error for all. 
When downgrading to 1.9.3 (available in the JimInCO channel for win64), the error was gone.

The above was with python 3.4. On python 2.7, I see the same error with the default package of 1.9.4 (but it works for 1.9.2), and here, the ioos package of 1.9.4 also works.

**Comment by antoinetri** [comment]
I have the same problem for Proj and transform functions ! (same config as jorisvandenbossche btw)

**Comment by micahcochran** [comment]
Run this:
```python
import pyproj, os.path
os.path.exists(pyproj.pyproj_datadir + '/epsg')
```
This returns `True` for mine, which works when I put in the offending epsg snippet.

What is the value of `pyproj.pyproj_datadir`?  That is suppose to be the location of the epsg file (among others).  If Proj.4 library can't find that file, it shouldn't work.

**Comment by johngonzalez** [comment]
How I get epsg dir?

**Comment by micahcochran** [comment]
epsg is a text file with PROJ.4 codes for projections.  Here is the [location of epsg on github folder for this project](https://github.com/jswhit/pyproj/tree/master/lib/pyproj/data).

**Comment by jorisvandenbossche** [comment]
It returns False for me (tested in a fresh conda environment):

```
>>> import pyproj, os.path
>>> os.path.exists(pyproj.pyproj_datadir + '/epsg')
False
```

and it gives a strange value for `pyproj_datadir`:

```
>>> pyproj.pyproj_datadir
'C:\x07root\\stage\\Library\\share\\proj'
```

**Comment by jorisvandenbossche** [comment]
As I said in the original issue, I was able to get a working version on python 3.4 by downgrading to 1.9.3 and using the JimInCO channel for win64 (https://anaconda.org/JimInCO/pyproj). The output is then:

```
>>> import pyproj
>>> pyproj.__version__
'1.9.3'
>>> pyproj.Proj('+init=epsg:4326 +no_defs=True')
<pyproj.Proj object at 0x00000000020A9348>
>>> import pyproj, os.path
>>> os.path.exists(pyproj.pyproj_datadir + '/epsg')
True
>>> pyproj.pyproj_datadir
'C:\\Anaconda\\envs\\test_pyproj_py3\\lib\\site-packages\\pyproj\\data'
```

**Comment by aadityadar** [comment]
I had a similar issue. Thanks for your help!

**Comment by mtreiber** [comment]
I had the same issue and resolved it by installed the conda package from anaconda.org as follows:

conda install -c https://conda.anaconda.org/ioos pyproj

**Comment by bidhya** [comment]
Using the following install for windows with 32-bit python 2.7 solved my problem too

conda install -c https://conda.anaconda.org/ioos pyproj

**Comment by slava-kerner** [comment]
Another option is adding environment variable 'PROJ_DIR', set to position of pyproj\data (where the 'epsg' file resides), i.e. \Anaconda2\Lib\site-packages\pyproj\data (and, possibly, restarting to update env. vars).
After that running 'print pyproj.pyproj_datadir' shold give correct location, and 'os.path.exists(pyproj.pyproj_datadir + '/epsg')' should return true.

**Comment by gaberosser** [comment]
I ran into this problem in 64 bit Windows 10, Python 2.7. I had installed pyproj from the ioos channel as others have suggested and received version 1.9.4. This did not work for me - I got the same error mentioned in the original post.

I went with a different solution: upgrade pyproj to 1.9.5 using the .whl file available on [Christoph Gohlke's website](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj). It's not very neat, but it did the job.

**Comment by jrovegno** [comment]
I had upgraded pyproj to 1.9.5.1 using conda default channel, problem solved on windows.

**Comment by joernu76** [comment]
I may have a related, new problem on Anaconda3 Windows with version 1.9.5.1-py36hb98d9bb_1
The value of pyproj.datadir.pyproj_datadir is

"C:/Users/icg174/Anaconda3\share\proj"

while the data is actually located in 

C:/Users/icg174/Anaconda3/Library/share/

so both the formatting of the path seperators is off and the reference to the PROJ_DIR is missing as well as that there is a discrepancy between the listed and actual data path.

The last build version 1.9.5.1-py36_0 has the data files in a subdirectory of the package and also checks on the value of PROJ_DIR.

**Comment by tomalrussell** [comment]
I think can replicate what @joernu76 describes, with miniconda on Windows:
```
pyproj                    1.9.5.1          py36haf3c679_3    conda-forge
```
Copying the files from `...\Library\share` to `...\share\proj` as a workaround seems to fix my install.

**Comment by Sieboldianus** [comment]
Perhaps this is related: I get the same error for pyproj 1.9.6, my `pyproj.datadir.pyproj_datadir` shows an empty string

**Comment by deshmukhps95** [comment]
set the project lib path to the share folder of the conda environment:
import os
os.environ['PROJ_LIB'] =r'C:\Users\{usename}\AppData\Local\Continuum\anaconda3\envs\{conda_environment_name}\Library\share';

**Comment by snowman2** [comment]
Can you try the most recent version of pyproj (>=2.1.0) and check if this issue persists?

**Comment by Sieboldianus** [comment]
At least for me: my problem was related to using MingW64 Console under Windows 7 - this does not work with the conda feedstock (but doesn't affect the pip-package approach)

**Comment by snowman2** [comment]
Related to #216

**Comment by fasvello** [comment]
My solution:
I edited line 152 of ...site-packages/mpl_toolkits/basemap/_init_.py
replaced pyproj_datadir = os.eviron['PROJ_LIB']   with
**pyproj_datadir = '/home/user/anaconda3/lib/python3.7/site-packages/pyproj'**

Worked for me!
