### ISSUE TITLE
Upstream product renamed to PROJ

### ISSUE THREAD

**Issue by sebastic** [pyproj4/pyproj#174]
With the move to version 5, the PROJ.4 product was renamed to just PROJ. The PROJ.4 is now only used for the (community) project, mostly for historic reasons.

From https://github.com/OSGeo/proj.4/issues/735:
> * We are the PROJ.4 project
> * We provide the product PROJ, which is now at version 5.0.0
> * The foundational component of PROJ is the library libproj
> * Other components include the application proj, which provide a command line interface to libproj

Many of the mentions of PROJ.4/proj.4/proj4 in pyproj should be renamed to PROJ because they refer to the product not the (community) project.

**Comment by snowman2** [comment]
The website will soon be proj.org and the repo will be renamed to PROJ soon.
