### ISSUE TITLE
Transform can not find proj.db

### ISSUE THREAD

**Issue by stuart23** [pyproj4/pyproj#176]
I can no longer perform transformations. The minimum (platform independent) example code is:

    docker run -it python bash -c "pip install pyproj && python"
    >>> import pyproj
    >>> pyproj.transform(pyproj.Proj(init='epsg:4326'), pyproj.Proj(init='epsg:3857'), 0, 0)

This returns:
    proj_create_operation_factory_context: Cannot find proj.db
    pj_obj_create: Cannot find proj.db

running with `pip install pyproj==1.9.6` works fine though.

**Comment by jswhit** [comment]
Looks like you need to set the PROJ_LIB environment variable to point to the PROJ.4 data directory (where proj.db lives), or use pyproj.datadir.set_data_dir

**Comment by stuart23** [comment]
Should that be automatically done as a default? What's the benefit of making the user specify it manually?

**Comment by jswhit** [comment]
the proj.4 source and data is no longer bundled with the python module, so it doesn't know where it is installed until you tell it.

**Comment by stuart23** [comment]
Imho that goes against what python is. It either comes bundled or is listed
as a dependancy

**Comment by stuart23** [comment]
ESPECIALLY when used in a containerized environment. Unless its pip
installable, no one will use it.

**Comment by snowman2** [comment]
This will be fixed in the 2.0.1 release coming soon.

**Comment by snowman2** [comment]
Did pyproj==2.0.1 fix this issue?

**Comment by patrickziegler** [comment]
Not at all and I am probably missing how it was supposed to do so anyway.

The default guess on where to find `proj.db` is seen in the following excerpt from `datadir.py`. This results in `/usr/lib64/python3.7/site-packages/pyproj/proj_dir/share/proj` on my system (openSUSE Tumbleweed, pyproj 2.0.1).

```python
internal_datadir = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "proj_dir", "share", "proj"
    )
```

Why should the path to some files of PROJ.4 be relative to pyproj when you say yourself that PROJ.4 is not shipped with it?

If your thinking was to let maintainers create a symlink in `/usr/lib64/python3.7/site-packages/pyproj` pointing to the appropriate folder when he refrains to use the PROJ_LIB variable approach (which actually works btw.), why even bother with demanding those subfolders `"proj_dir"`, `"share"` and `"proj"`?

I would suggest to use default paths like `/usr/share/proj/` and their equivalents on Mac and Windows where there is at least some chance to actually find what we are searching for.

**Comment by jswhit** [comment]
I believe that's where proj.db would live if you installed a binary wheel

**Comment by patrickziegler** [comment]
That is true, thank you for pointing this out.

Running `python3 setup.py build` creates the file structure seen below. This is also what is getting shipped with Tumbleweed right now.

```bash
└── pyproj
    ├── compat.py
    ├── _crs.cpython-37m-x86_64-linux-gnu.so
    ├── crs.py
    ├── datadir.py
    ├── exceptions.py
    ├── _geod.cpython-37m-x86_64-linux-gnu.so
    ├── geod.py
    ├── __init__.py
    ├── _proj.cpython-37m-x86_64-linux-gnu.so
    ├── proj.py
    ├── _transformer.cpython-37m-x86_64-linux-gnu.so
    ├── transformer.py
    └── utils.py
```

The maintainers probably didn't note that either a symlink to the folder containing `proj.db` or a copy of this folder itself is missing. Without this, every user (that didn't use pip or conda) has to fiddle around with environment variables or creating symlinks in folders for which he may have no right to write in.

Therefore I suggest to either change `get_data_dir()` in [`datadir.py`](https://github.com/pyproj4/pyproj/blob/master/pyproj/datadir.py) to also honor system wide installations paths or to extend [`setup.py`](https://github.com/pyproj4/pyproj/blob/master/setup.py) to copy the necessary files to the build directory or just create a symlink directly.

**Comment by snowman2** [comment]
> Therefore I suggest to either change get_data_dir() in datadir.py to also honor system wide installations paths

That is an interesting idea, but there are a lot of paths on different systems to check and would be quite cumbersome to maintain & increase the overhead. I think setting the `PROJ_LIB` environment variable is a good solution for users who don't have the files installed.

**Comment by snowman2** [comment]
Al

**Comment by snowman2** [comment]
Added search on path for data directory in #213. Thanks for the report and idea!
