### ISSUE TITLE
pypi installation errors

### ISSUE THREAD

**Issue by tomkralidis** [pyproj4/pyproj#177]
cc @justb4

Via https://github.com/geopython/GeoHealthCheck/issues/240, looks like with the latest pyproj release on pypi there are install issues:

```bash
Downloading/unpacking OWSLib==0.17.0
  Downloading OWSLib-0.17.0.tar.gz (149kB): 149kB downloaded
  Running setup.py (path:/tmp/pip_build_kralidist/OWSLib/setup.py) egg_info for package OWSLib

    warning: manifest_maker: MANIFEST.in, line 3: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

Downloading/unpacking python-dateutil>=1.5 (from OWSLib==0.17.0)
  Downloading python_dateutil-2.8.0-py2.py3-none-any.whl (226kB): 226kB downloaded
Downloading/unpacking pytz (from OWSLib==0.17.0)
  Downloading pytz-2018.9-py2.py3-none-any.whl (510kB): 510kB downloaded
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0 in /usr/lib/python2.7/dist-packages (from OWSLib==0.17.0)
Downloading/unpacking pyproj (from OWSLib==0.17.0)
  Downloading pyproj-2.0.0.tar.gz (408kB): 408kB downloaded
  Running setup.py (path:/tmp/pip_build_kralidist/pyproj/setup.py) egg_info for package pyproj
    ERROR: Cython.Build.cythonize not found. Cython is required to build from a repo.
    Complete output from command python setup.py egg_info:
    ERROR: Cython.Build.cythonize not found. Cython is required to build from a repo.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /.....
```

**Comment by jswhit** [comment]
Cython is required to build from source.  We need to add "setup_requires" to setup.py so that setuptools will handle the dependency.

**Comment by jswhit** [comment]
Looks like if you have pip >= 10 it works since the dependencies listed in pyproject.toml are loaded before setup.py is run.  Since we import cython in setup.py using setup_requires won't work.

**Comment by jswhit** [comment]
bottom line - the solution is to upgrade pip that you are using in your docker environment, or use pyproj version 1.9.6.

**Comment by justb4** [comment]
@jswhit thanks, but even with upgrading pip the build error remains, the base [Docker Image](https://github.com/geopython/GeoHealthCheck/blob/master/Dockerfile) is `python:2.7.15-alpine3.8`, which is also not very recent (upgrade to Python3 in progress). Tried `apk add proj[4]` but needs `Edge` version. Als adding `apk add cython` did not help.

```
pip install -U pip && pip install  -r requirements.txt
Requirement already up-to-date: pip in ./lib/python2.7/site-packages (19.0.3)
.
.
Collecting pyproj (from OWSLib==0.17.0->-r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/53/4b/21643a93e7d33941498087290636e34c6d534aa8baa1ada54cf0d096ffaa/pyproj-2.0.0.tar.gz (408kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /venv/bin/python /venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkwiSP2:
  Proj executable not found. Please set PROJ_DIR variable.
  
  ----------------------------------------
Command "/venv/bin/python /venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkwiSP2" failed with error code 1 in /tmp/pip-install-pUftm_/pyproj

```
At least for this Docker env we can stick to 1.9.6 (I believe  `proj` is not even used in GHC currently) and first upgrade all base (Python, Alpine) first and then revisit.

**Comment by tomkralidis** [comment]
cc @kalxas

In our cases (many projects) IMHO the safe bet is to keep to 1.9.6.

**Comment by kalxas** [comment]
Is this new pyproj release based on PROJ 6.0 recent changes?

**Comment by jswhit** [comment]
Yes, it is based on 6.0.0. We will release 2.0.1 shortly that some 'proj.db not found' errors, and will include windows, linux and macosx binary wheels.

**Comment by snowman2** [comment]
Well, not the windows wheels yet. But Linux and osx wheels.

**Comment by Uldiniad** [comment]
are windows wheels coming soon?

**Comment by Uldiniad** [comment]
nvm, https://github.com/pyproj4/pyproj-wheels/issues/3

**Comment by jswhit** [comment]
We need help setting up windows wheel builds

**Comment by jswhit** [comment]
I just uploaded windows wheels for python 3  courtesy of @cgohlke

**Comment by snowman2** [comment]
Refer to #216.

**Comment by snowman2** [comment]
Feel free to reopen if the related issue does not match your needs or the latest version of pyproj (2.1.1) does not meet your needs.

**Comment by tomkralidis** [comment]
I just tried `pip install`-ing on OSX (installs 2.1.2) which looks like it works.  Thanks!

**Comment by snowman2** [comment]
Great!

**Comment by tomkralidis** [comment]
FYI I'm getting errors on Travis and Appveyor:

- https://travis-ci.org/woudc/pywoudc/builds/523200226
- https://ci.appveyor.com/project/tomkralidis/pywoudc/builds/24024548

**Comment by snowman2** [comment]
@tomkralidis, It appears that you are using the [deprecated Python 3.4](https://www.python.org/dev/peps/pep-0429/#release-schedule) for your builds. We don't provide wheels for those. If you would like to continue using that python version, you will need to build PROJ from source and then install pyproj (See: https://pyproj4.github.io/pyproj/html/installation.html).

**Comment by tomkralidis** [comment]
Looks like this worked.  Thanks @snowman2 !

**Comment by snowman2** [comment]
Great!

**Comment by bdklahn** [comment]
I'm still not sure what to do to fix this for me, as the above solutions are not relevant or do not work. It seems the error is not useful, as Cython is installed.

Singularity> cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
Singularity> python3 --version
Python 3.6.8
Singularity> pip3 --version
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

I tried pinning the version at pyproj==1.9.6

But then I get the following when a user runs their ipynb.

----> 9 from pyproj import CRS, Transformer 
     10 from shapely.geometry.base import BaseGeometry 
     11  
ImportError: cannot import name 'CRS' 
ImportError: cannot import name 'CRS'

**Comment by snowman2** [comment]
The CRS class was added in pyproj 2.

**Comment by bdklahn** [comment]
Collecting pyproj==2.2.0
  Downloading https://files.pythonhosted.org/packages/73/ef/53a7e9e98595baf4d7212aa731fcec256b432a3db60a55b58a027a4d9d47/pyproj-2.2.0.tar.gz (378kB)
    100% |################################| 378kB 2.6MB/s 
    Complete output from command python setup.py egg_info:
    ERROR: Cython.Build.cythonize not found. Cython is required to build from a repo.

**Comment by snowman2** [comment]
You need pip >= 10.0.1 or you need cython installed before you install pyproj.

**Comment by bdklahn** [comment]
Again . . .
> pip3 --version
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by bdklahn** [comment]
It seems to have been solved by doing the install as a separate pip3 call, rather than installing it along with other packages, or implicitly trusting the package needing pyproj to install it correctly.
