### ISSUE TITLE
Upgrade from 1.9.6 to 2.0.2 gives different results even with preserve_units=False

### ISSUE THREAD

**Issue by ibrewster** [pyproj4/pyproj#195]
I just tried upgrading from pyproj 1.9.6 to 2.0.2, and ran into two issues. The first was apparently the same as reported here: https://github.com/pyproj4/pyproj/issues/187, as a process that had been taking about half a second suddenly started taking around 200 seconds. Hopefully that will be fixed with the introduction of the "Transformer" class in 2.1.0? However, I'm also seeing different results between the two versions.

At first I thought it was due to the change in the default for the preserve_units flag, so I tried again with this being set to False, which did get closer to the original results, but still significantly different. See my test code here:

```
>>> import pyproj
>>> pyproj.__version__
'2.0.2'
>>> pyproj.datadir.set_data_dir('<proper_dir>')
>>> lat_lon_proj = pyproj.Proj(init='epsg:4326')
>>> alaska_aea_Proj = pyproj.Proj(init='epsg:2964')
>>> test = (-179.72638, 49.752533)
>>> pyproj.transform(lat_lon_proj, alaska_aea_Proj, *test)
(-5988031.64856495, 1085071.290141867)
>>> # what units are these?
>>> # Try setting the preserve_units flag to the default from the old version
>>> alaska_aea_Proj = pyproj.Proj(init='epsg:2964', preserve_units=False)
>>> lat_lon_proj = pyproj.Proj(init='epsg:4326', preserve_units=False)
>>> pyproj.transform(lat_lon_proj, alaska_aea_Proj, *test)
(-1825155.69679399, 330730.3906960224)

< reinstall different version >

>>> import pyproj
>>> pyproj.__version__
'1.9.6'
>>> lat_lon_proj = pyproj.Proj(init='epsg:4326')
>>> alaska_aea_Proj = pyproj.Proj(init='epsg:2964')
>>> test = (-179.72638, 49.752533)
>>> pyproj.transform(lat_lon_proj, alaska_aea_Proj, *test)
(-1824924.4953062115, 330822.8000285958)
>>> 
```

Notice that the end results differ by several hundred meters in both the X and Y plane, even though I am using the same data. Why is this? 

As a related question, with preserve_units left at the default of True in the 2.0.2 version, what units am I getting? I would have expected meters, since that is what the Alaska Albers Equal Area projection gives, but those results are WAY off of what I was getting before.

**Comment by jswhit** [comment]
Maybe related to issue #192, which is being addressed by #193

**Comment by ibrewster** [comment]
Just for more fun, I tried 1.9.6 with `preserve_units=True`, which gave me yet another result:

```
>>> lat_lon_proj = pyproj.Proj(init='epsg:4326', preserve_units=True)
>>> alaska_aea_Proj = pyproj.Proj(init='epsg:2964', preserve_units=True)
>>> test = (-179.72638, 49.752533)
>>> pyproj.transform(lat_lon_proj, alaska_aea_Proj, *test)
(-5987273.115017133, 1085374.4697604855)
```

Again, close to the corresponding 2.0.2 output, but not quite the same. Then, I went looking for a third source, and found this webpage: https://epsg.io/transform#s_srs=4326&t_srs=2964&x=-179.7263800&y=49.7525331 which agrees with the results from 1.9.6 with preserve_units set to `True`.

So now not only do I not know what to believe, but I'm thinking I may have been mis-interpreting the results all along, although they *seem* to line up when plotted on the map.

**Comment by ibrewster** [comment]
> Maybe related to issue #192, which is being addressed by #193
Ah, Ok. I didn't look at that bug, since I wasn't getting any errors. Thanks!

**Comment by jswhit** [comment]
Looks like this wasn't fixed by #193.

**Comment by snowman2** [comment]
It should have been. I added a test here:https://github.com/pyproj4/pyproj/blob/master/unittest/test_transformer.py

**Comment by jswhit** [comment]
You're right - it is fixed. My bad.

**Comment by snowman2** [comment]
Phew, gave me a scare for a moment 😅

**Comment by snowman2** [comment]
pyproj==2.1.0 is released with the fix. Feel free to reopen if the issue persists. Thanks for the report!

**Comment by drnextgis** [comment]
Faced with the same issue. Not a big difference but it breaks tests of our library.

The following code:

```
>>> from pyproj import Proj, transform
>>> inProj = Proj(init='epsg:3857')
>>> inProj = Proj(init='epsg:4326')
>>> outProj = Proj(init='epsg:3857')
>>> x1, y1 = 35.9527587890625, 30.93050081760779
>>> x2, y2 = transform(inProj, outProj, x1, y1)
>>> print(x2, y2)
```

Returns:
```
4002242.801011829 3623726.6369436365 #1.9.6
4002242.8010118282 3623726.6369436365 #2.1.0
```

**Comment by snowman2** [comment]
@kbevers @rouault Anything to be concerned about with the minor difference shown by @drnextgis?

**Comment by kbevers** [comment]
> Anything to be concerned about with the minor difference shown by @drnextgis?

Only that the tests are sensitive to a change at the nanometer level. You should set a tolerance and check that the difference between the expected and the returned coordinate is less than the tolerance. Otherwise you are bound to run into errors all the time, especially across various compilers and hardware.
