### ISSUE TITLE
pyproj 1.9.5.1 and 2.0.1 give different result for Lambert conical

### ISSUE THREAD

**Issue by fgro** [pyproj4/pyproj#207]
I have been using it for large topographic data transformations.

Now, I have switched my python IDE and updated pyproj (pip install pyproj) along the way.

For the transformation from 
Morocco, epsg 26191 (E, N, H) -> wgs84, I get three results:
	lat	long
```
http://epsg.io/transform#s_srs=26191&t_srs=4326&x=567623.9310000&y=256422.7870000	

epsq website    32.9021985°	-4.6753453°
spyder, pyproj-1.9.5.1	32.902199035649964	-4.6753455960055135
PyCharm,  pyproj-2.0.2	32.904806501443474	-4.676927631902659
PyCharm, pyproj-2.1.1    32.904806501443474    -4.676927631902659
reverting to 
PyCharm, pyproj 1.9.5.1	32.902199035649964	-4.6753455960055135
```

I run the same script and init the projection as:

    Midelt = pyproj.Proj(init='epsg:26191')
    WGS84 = pyproj.Proj(init='epsg:4326')

    E = 567623.931
    N = 256422.787
    h = 1341.467

    Long1, Lat1, H1 = pyproj.transform(Midelt, WGS84, E, N, h, radians=False)

Do you have an idea where the discrepancy comes from?
Which version is the more trustworthy?

**Comment by snowman2** [comment]
Would you mind upgrading to pyproj>=2.1.0 and checking if this issue still exists in the most recent version?

**Comment by jswhit2** [comment]
Your example is incomplete - how is `WGS84` defined?  epsg:4326?

**Comment by fgro** [comment]
WGS84 = pyproj.Proj(init='epsg:4326')

**Comment by fgro** [comment]
With pyproj 2.1.1:
Long = -4.676927631902659°
Lat = 32.904806501443474°

So, the difference persists.

**Comment by snowman2** [comment]
@kbevers @rouault what are your thoughts on this?

**Comment by kbevers** [comment]
> what are your thoughts on this?

I don't know, the data is incomplete. What is the z-value of the output?

**Comment by fgro** [comment]
pyproj 1.9.5.1
lon -4.675346° E, lat 32.902199° N, H 1392.252 m

pyproj 2.1.1
lon -4.676928° E, lat 32.904807° N, H 1341.467 m

**Comment by kbevers** [comment]
Thanks. It seems about right to me. The transformation between the two CRS is a 3D Helmert transform but the CRS's are both 2D. This is respected in PROJ 6 which preserve the input z value which older versions didn't. This will change the output. Nothig to worry about, this should be more correct.

**Comment by snowman2** [comment]
Thanks @kbevers!

**Comment by rouault** [comment]
I can't really replicate the differences in long / lat. But I concur with @kbevers that the difference on H is expected (no change in PROJ 6)

With proj 5.2.0 (or 4.9.3)
```
$ echo "567623.931 256422.787 1341.467" |   ~/proj/install-proj-5.2.0/bin/cs2cs  -f "%.9f" +init=epsg:26191 +to +init=epsg:4326
-4.675345596	32.902199036 1392.252396794
```
vs proj master
```
even@even-i700:~/proj/proj.4/build_autoconf$ echo "567623.931 256422.787 1341.467" | src/cs2cs -f "%.9f" EPSG:26191  EPSG:4326
32.902199036	-4.675345596 1341.467000000
```

**Comment by snowman2** [comment]
Hmm, definitely something to look into.

**Comment by snowman2** [comment]
```python
>>> from pyproj import *
>>> transformer = Transformer.from_crs(26191, 4326)
>>> transformer.transform(567623.931, 256422.787, 1341.467)
(32.90219903565008, -4.6753455960055135, 1341.467)
>>> transformer_p = Transformer.from_proj(26191, 4326)
>>> transformer_p.transform(567623.931, 256422.787, 1341.467)
(-4.676927631902659, 32.904806501443474, 1341.467)
```

The `from_proj` uses the `PROJ` projection string and the `from_crs` uses the `WKT` projection string to initialize `proj_create_crs_to_crs`. Very strange. Seems the values flipped positions as well.

**Comment by snowman2** [comment]
```python
>>> from pyproj import CRS
>>> crs = CRS("epsg:26191")
>>> crs
<CRS: epsg:26191>
Name: Merchich / Nord Maroc
Ellipsoid:
- semi_major_metre: 6378249.20
- semi_minor_metre: nan
- inverse_flattening: 293.47
Area of Use:
- name: Morocco - north of 31.5°N
- bounds: (-9.85, 31.49, -1.01, 35.97)
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Easting[X] (east) EPSG:9001 (metre)
- Northing[Y] (north) EPSG:9001 (metre)
>>> crs.to_proj4()
'+proj=lcc +lat_1=33.3 +lat_0=33.3 +lon_0=-5.4 +k_0=0.999625769 +x_0=500000 +y_0=300000 +ellps=clrk80ign +units=m +no_defs +type=crs'
>>> crs2 = CRS(crs.to_proj4())
>>> crs2
<CRS: +proj=lcc +lat_1=33.3 +lat_0=33.3 +lon_0=-5.4 +k_0 ...>
Name: unknown
Ellipsoid:
- semi_major_metre: 6378249.20
- semi_minor_metre: 6356515.00
- inverse_flattening: 293.47
Area of Use:
- UNDEFINED
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Easting[E] (east) EPSG:9001 (metre)
- Northing[N] (north) EPSG:9001 (metre)
```

For some reason, converting to `PROJ` string adds in the `semi_minor_metre`.

**Comment by snowman2** [comment]
In PROJ 6.0.0:
```
$ echo "567623.931 256422.787 1341.467" | cs2cs -f "%.9f" '+proj=lcc +lat_1=33.3 +lat_0=33.3 +lon_0=-5.4 +k_0=0.999625769 +x_0=500000 +y_0=300000 +ellps=clrk80ign +units=m +no_defs +type=crs' EPSG:4326
32.904806501    -4.676927632 1341.467000000
$ echo "567623.931 256422.787 1341.467" | cs2cs -f "%.9f" EPSG:26191 EPSG:4326
32.902199036    -4.675345596 1341.467000000
```

**Comment by rouault** [comment]
> For some reason, converting to PROJ string adds in the semi_minor_metre.

This is likely fine. semi_minor_metre and inverse_flattening are different "views" of the ellipsoid parameters

> $ echo "567623.931 256422.787 1341.467" | cs2cs -f "%.9f" '+proj=lcc +lat_1=33.3 +lat_0=33.3 +lon_0=-5.4 +k_0=0.999625769 +x_0=500000 +y_0=300000 +ellps=clrk80ign +units=m +no_defs +type=crs' EPSG:4326
> 32.904806501    -4.676927632 1341.467000000
> $ echo "567623.931 256422.787 1341.467" | cs2cs -f "%.9f" EPSG:26191 EPSG:4326
> 32.902199036    -4.675345596 1341.467000000

This is expected. The PROJ string you use in the first cs2cs invocation has no towgs84 term (you may need to use `proj_crs_create_bound_crs_to_WGS84` from proj_experimental.h to get a Bound CRS with the TOWGS84 term that will be exported as +towgs84 as a PROJ string), and being a PROJ string lacks a proper datum identification, thus this invocation cannot do datum transformation, contrary to the one using EPSG:26191. I want to reiterate that PROJ strings are potentially lossy representation of the complexity of a CRS object. Using the AUTH_NAME:CODE representation is preferable.

**Comment by snowman2** [comment]
Thanks for the update @rouault!

> I want to reiterate that PROJ strings are potentially lossy representation of the complexity of a CRS object. 

I definitely agree 100% with you there. 

There are some various logic pieces that will need to be thought through to resolve this. I will brain dump later.

**Comment by snowman2** [comment]
### Rationale for current initalization behavior in `PROJ`:
The `pyproj.Proj` has a `PJ*` object that performs forward/inverse transformations using `proj_trans`. However, `proj_trans` does not seem to support `PJ*` objects created from WKT strings. 

Example errors without using the conversion:
```
pyproj.exceptions.ProjError: inverse projection undefined
pyproj.exceptions.ProjError: Error creating CRS to CRS.
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
```
That is the main reason for why the conversion to a `PROJ` string occurs to create the `PJ*` object in `pyproj.Proj`. 

However, using the `PJ*` object created from the `PROJ` string can cause loss of projection information, as shown in this issue.

### Potential solution:
Default to using `from_crs` for `itransform` and `transform` & if a `Proj` object is passed in, create an equivalent CRS object from the `Proj` object. Remove the `from_proj` initialization method from `Transformer`.

Insight, thoughts, feedback would be appreciated.

**Comment by snowman2** [comment]
Also, tried with keeping the input raw:
```python
>>> pj = Proj("+init=epsg:4326")
>>> pj(1, 2, errcheck=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/scripts/pyproj/pyproj/proj.py", line 343, in __call__
    self._fwd(inx, iny, errcheck=errcheck)
  File "pyproj/_proj.pyx", line 98, in pyproj._proj.Proj._fwd
    raise ProjError(proj_errno_string(err))
pyproj.exceptions.ProjError: b'no system list, errno: 22\n'
```
But, with current implementation (this is what is going on internally):
```python
>>> pj = Proj(CRS("+init=epsg:4326").to_proj4().replace("+type=crs", ""))
>>> pj(1, 2, errcheck=True)
(0.017453292519943295, 0.03490658503988659)
```

I also was tinkering around with the other implementation I mentioned above, and that one has issues as well.
I guess at this point having both options is good and maybe some documentation for cases like this one where `Transformer.from_crs` would be more appropriate for the transformation.

**Comment by snowman2** [comment]
I have a potential solution in #212.

**Comment by snowman2** [comment]
This will be included in the next release. Thanks for the report!
