### ISSUE TITLE
line length, polygon perimeter

### ISSUE THREAD

**Issue by artttt** [pyproj4/pyproj#210]
Im wondering if a useful addition to pyproj would be geodetic line length for a sequence of points.
An example of the calculation that i wrote recently.
```
from shapely.geometry import LineString
import pyproj
geom = LineString([(2, 0), (2, 4), (3, 4)])
arr = np.asarray(geom)
_geod = pyproj.Geod(ellps="WGS84")
_geod.inv(arr[:-1, 0], arr[:-1, 1], arr[1:, 0], arr[1:, 1])[2].sum()
```
A function built around that last line to support geod inv on a sequence of coordinates rather then pairs of coords is probably whats required.

would also work for polygon perimeters (i wonder how area works on a geod?)
```
from shapely.geometry import Polygon
polygon = Polygon(geom)
#ignoring holes
arr = np.asarray(polygon.exterior)
......
```
I regularly see issues relating to lengths calculated on projections so a nice way to avoid this problem might be well used.

**Comment by snowman2** [comment]
Definitely sounds useful 👍

**Comment by snowman2** [comment]
Looks like it is implemented in cartopy: https://github.com/SciTools/cartopy/blob/1942c7bd0a6d28c78da3d7f0e4c646833287f44a/lib/cartopy/geodesic/_geodesic.pyx#L251-L292

**Comment by snowman2** [comment]
Side note: https://geographiclib.sourceforge.io/html/python/ looks like it has polygon area (https://geographiclib.sourceforge.io/html/python/code.html#geographiclib.polygonarea.PolygonArea.Compute).

**Comment by artttt** [comment]
im sure you are aware of this but just so its noted in this discussion.
proj uses geographiclib c++ library for geodesic calculations
https://proj.org/geodesic.html
Pyproj and cartopy are using geographiclib through proj but are not exposing the polyline length/polygon area functionality built into geographiclib.

The geographiclib python module is i think a pure python module so is probably slower.

**Comment by snowman2** [comment]
Thanks for the info. Looks like a lot of useful functions in geodesic.h. One I think looks particularly useful is: https://github.com/OSGeo/PROJ/blob/3ae09c3ba164728e200a3b930b72ed5fc24ef6ee/src/geodesic.h#L890

**Comment by snowman2** [comment]
I have an implementation that I think resolves this issue.

For line length:
```python
>>> from shapely.geometry import LineString
>>> from pyproj import Geod
>>> ls = LineString([(2, 0), (2, 4), (3, 4)])
>>> geod = Geod(ellps="WGS84")
>>> line_lengths, total_length = geod.line_length(*ls.xy)
>>> line_lengths
array('d', [442304.3119779007, 111050.12397265056])
>>> total_length
553354.4359505512
>>> sum(line_lengths) == total_length
True
```
For area:
```python
>>> area, perimeter = geod.polygon_area_perimeter(*ls.xy)
>>> area, perimeter
(-24569511295.707436, 1009430.2283314321)
>>> from shapely.geometry import Polygon
>>> poly = Polygon(ls)
>>> area, perimeter = geod.polygon_area_perimeter(*poly.exterior.xy)
>>> area, perimeter
(-24569511295.707436, 1009430.2283314321)

```
