### ISSUE TITLE
Proj initialization fails in pyproj-2

### ISSUE THREAD

**Issue by sfinkens** [pyproj4/pyproj#224]
The following projection initialization works fine in pyproj-1.9.6, but fails in 2.1.2

```
>>> import pyproj
>>> pyproj.Proj({'init': 'EPSG:4326', 'units': 'degrees'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cmsaf/nfshome/routcm/Modules_CentOS/pytroll/lib/python3.7/site-packages/pyproj/proj.py", line 295, in __init__
    self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
  File "/cmsaf/nfshome/routcm/Modules_CentOS/pytroll/lib/python3.7/site-packages/pyproj/crs.py", line 224, in from_user_input
    return cls(**value)
  File "/cmsaf/nfshome/routcm/Modules_CentOS/pytroll/lib/python3.7/site-packages/pyproj/crs.py", line 146, in __init__
    super(CRS, self).__init__(projstring)
  File "pyproj/_crs.pyx", line 317, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: +init=epsg:4326 +units=degrees +type=crs: (Internal Proj Error: proj_create: Error -7: unknown unit conversion id)
```

**Comment by snowman2** [comment]
If you are using this with pyproj.transform, the default expected input is degrees, so the additional arg is not needed.

**Comment by snowman2** [comment]
You can export the epsg to a proj string if you need to mess with the units.
https://github.com/pyproj4/pyproj/blob/623cbc8205c420e7f3a0f72a8f0410af430142a2/pyproj/proj.py#L298

But, this is not recommend if you can avoid it as that results in loss of information.

**Comment by snowman2** [comment]
I would recommend making an issue for osgeo/proj.4 about this.

**Comment by snowman2** [comment]
@kbevers @rouault, is this behavior from proj expected?

**Comment by snowman2** [comment]
I think since you are attempting to to a unit conversion in the proj, it is no longer a projection, but a pipeline operation:

```python
>>> from pyproj import Transformer
>>> trans = Transformer.from_pipeline("+proj=pipeline +init=epsg:4326 +step +proj=unitconvert +xy_in=rad +xy_out=deg")
>>> trans.transform(1.2, 2.3)
(68.75493541569878, 131.78029288008932)
```

Additionally, here is the CRS object for EPSG:4326:
```python
>>> CRS("+init=epsg:4326")
<CRS: +init=epsg:4326 +type=crs>
Name: WGS 84
Ellipsoid:
- semi_major_metre: 6378137.00
- semi_minor_metre: 6356752.31
- inverse_flattening: 298.26
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Longitude[lon] (east) EPSG:9122 (degree)
- Latitude[lat] (north) EPSG:9122 (degree)
```

**Comment by rouault** [comment]
+units=degrees has never been supported AFAIK,at most it was silently ignored before
Using init=epsg:XXXX syntax is also deprecated, and will not work in some new code paths. The reason is that it used non-conformant axis order for geodetic CRS (EPSG mandates latitude, longitude order).

**Comment by djhoese** [comment]
@rouault Thanks for the info. What is the preferred way of loading EPSG CRSes now?

**Comment by rouault** [comment]
> What is the preferred way of loading EPSG CRSes now?

use "EPSG:XXXX" in source_crs or target_crs arguments of proj_create_crs_to_crs() when creating a transformation, or as argument of proj_create() to instanciate a CRS object

**Comment by sfinkens** [comment]
@rouault @snowman2 Thank you very much for the quick reply!
