### ISSUE TITLE
Ability to access projection parameters

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#226]
This has been brought up in other repositories in various issues (including the future geoxarray package) and given the new `CRS` object in pyproj I'm curious if this is useful or a possibility for future versions. Is it possible to access individual projection parameters (ex. `lon_0`) from a CRS or Proj object? Something like `Proj("...").proj_params['lon_0']` or maybe the WKT equivalent.

This is something I think @snowman2 or maybe @dopplershift have brought up in the past. Just looking for opinions on this functionality.

**Comment by snowman2** [comment]
You can access many of the projection parameters through the pyproj.CRS class. See: https://pyproj4.github.io/pyproj/html/api/crs.html

Depending on your use case for these parameters, this may help. The Proj class has a `crs` property that you can use to access the equivalent projection.

**Comment by snowman2** [comment]
I think the prime_meridian, ellipsoid, datum, and axis info properties are likely to be useful for you.

**Comment by djhoese** [comment]
@snowman2 I tried to look through those, but I didn't see anything that got me the projection parameters like in:

```python
p = Proj("+proj=lcc +datum=WGS84 +ellps=WGS84 +lat_0=25 +lat_1=25 +lon_0=15 +units=m +no_defs")
```

Is there a pythonic way to get `lon_0` without parsing it out of the string (what we do currently in tools like pyresample).

**Comment by snowman2** [comment]
Not that I am aware of currently. Would probably need to add `to_proj4_dict()` to the CRS class for something like that.

**Comment by snowman2** [comment]
What are your thoughts about addressing this issue with something like a `to_cf()` method on the CRS class that exported the parameters in a dictionary following the [CF naming conventions](http://cfconventions.org/cf-conventions/cf-conventions.html#appendix-grid-mappings)?

**Comment by jswhit** [comment]
I think that we be a great feature - but I bet there isn't a 1:1 mapping for all the fields.

**Comment by snowman2** [comment]
Sounds good. I *think* the ones in this issue should be covered by this. Either way, it will be a useful feature. Maybe a `from_cf` would be useful to add as well.

**Comment by djhoese** [comment]
Do the PROJ or pyproj projects plan on getting away from PROJ.4-style strings (in favor of something like WKT or something) in the future? I wouldn't mind both the proj dict and to_cf methods. And I somehow haven't brought up this related geoxarray issue: https://github.com/geoxarray/geoxarray/issues/3 (scroll down for the CF talk, CC @fmaussion).

**Comment by snowman2** [comment]
> Do the PROJ or pyproj projects plan on getting away from PROJ.4-style strings in the future?

I doubt PROJ strings are going away any time soon, but pyproj will likely follow whatever PROJ does. Their official recommendation for storing CRS data is [here](https://proj4.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems).

> I wouldn't mind both the proj dict and to_cf methods

I have the same opinion.

**Comment by snowman2** [comment]
An attempt is in #244.

**Comment by snowman2** [comment]
I am going to close this as the solution is merged into master. Thanks for bringing up the idea!
