### ISSUE TITLE
Differences in results between 1.9.6 and 2.* versions for GAUSS Transformation

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#235]
https://github.com/pyproj4/pyproj/blob/14a220822992353eee1c78bed4bb88aad2522ffa/test/test_datum_shift.py#L50-L67

Inputs:
```python
GB_x = 2423346.99
GB_y = 5055619.87
WGS84_lat = 45.647188611  # Degrees
WGS84_lon = 13.759554722  # Degrees
WGS84_PROJ = Proj(proj="latlong", datum="WGS84")
GAUSSSB_PROJ = Proj(
    init="epsg:26592", towgs84="-122.74,-34.27,-22.83,-1.884,-3.400,-3.030,-15.62"
)
```

**Comment by snowman2** [comment]
@kbevers @rouault I ran into this and wanted to have verification either way if the updated results here are correct or not.

**Comment by rouault** [comment]
Yes, this is expected. What is the right result might be disputed at length. The main issue is that EPSG:26592 is a deprecated object in the EPSG database. and for EPSG, deprecated == broken. Past PROJ versions have patched the EPSG:26592 definition to be more or less equivalent of the non-deprecated one of EPSG:3003. I have decided not to do so in PROJ 6 and keep the original values of the EPSG database.

The projinfo utility will tell you that a CRS is deprecated (`proj_is_deprecated()` at the API level) and will suggest the replacement
```
$ src/projinfo EPSG:26592
Warning: object is deprecated
Alternative non-deprecated CRS:
  EPSG:3004

PROJ.4 string:
+proj=tmerc +lat_0=0 +lon_0=15 +k=0.9996 +x_0=2520000 +y_0=0 +ellps=intl +pm=rome +units=m +no_defs +type=crs
[...]
```

In previous versions of PROJ, the (patched) PROJ string was 
```
<26592> +proj=tmerc +lat_0=0 +lon_0=2.54766666666666 +k=0.9996 +x_0=2520000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +pm=rome +units=m +no_defs  <>
```
The main difference is the lon_0 value.

I'd suggest that your test does not use EPSG:26592.

**Comment by snowman2** [comment]
That makes sense. Thanks for the clarification! I will update this test later.
