### ISSUE TITLE
pyproj has no attribute pyproj_datadir

### ISSUE THREAD

**Issue by andre-fu** [pyproj4/pyproj#241]
Submitted originally to basemap's github issues page, but I think it fits here better.

Installed basemap via pip
`pip3 install --user git+https://github.com/matplotlib/basemap.git`
```
from mpl_tooklits.basemap import Basemap
```
I get the error module 'pyproj' has no attribute 'pyproj_datadir' 
found here https://imgur.com/QauL5NI

Any advice on how to resolve this? I tried going into the pyproj folder and change the`__init__.py `from `pyproj_datadir `to just `datadir`. That led to more errors, so I reversed that. I'd like to not change the source files too much.

**Comment by jswhit** [comment]
install pyproj 1.9.6 for basemap

**Comment by andre-fu** [comment]
@jswhit 
![image](https://user-images.githubusercontent.com/39042250/55583155-36519700-56ef-11e9-93d3-b0f0e42547b2.png)


Does basemap require pyproj 1.9.6 specifically?

**Comment by andre-fu** [comment]
It requires 1.9.6 specifically, Thanks @jswhit  :)
