### ISSUE TITLE
from_crs() in test_transformer.py

### ISSUE THREAD

**Issue by micahcochran** [pyproj4/pyproj#243]
Since `from_crs()` is deprecated since #233 .

Here's what I did to find the problem from the python console:
```
In [10]: pyproj.test()
/home/micah/.local/lib/python3.6/site-packages/pyproj/transformer.py:92: UserWarning: `from_crs` is deprecated and will be removed in 2.2.0. Please use `from_proj` instead.
  "`from_crs` is deprecated and will be removed in 2.2.0. "
```

There are 3 instances of `from_crs()` in test_transformer.py.  There is also [one here](https://github.com/pyproj4/pyproj/blob/master/pyproj/transformer.py#L144) that is being ran by the doctests. I thought that it might be a good idea to fix those in order to get rid of the warning messages.

**Comment by snowman2** [comment]
I am fine getting rid of them in the doctests. But, until it is removed, the other tests need to remain. You can wrap it with `pytest.warns` to both test the warning exists and hide it.
