### ISSUE TITLE
'pyconfig.h' : No such file or directory

### ISSUE THREAD

**Issue by SygPi** [pyproj4/pyproj#25]
Hello,
I have some troubles when I try to buil pyproj : 
  _proj.c(8): fatal error C1083: Impossible d'ouvrir le fichier include : 'pyconfig.h' : No such file or directory

I am on Windows8 with Python3.5

Can you help me ?

Thanks

SYG

**Comment by micahcochran** [comment]
Did you try to install pyproj using `pip install pyproj`?  On Windows, how did you originally install Python 3.5?

**Comment by aluykx** [comment]
Make sure you have python34-setuptools and python34-devel installed (or the equivalent for python3.5). I got fed up and just installed all python34 packages (`yum install python34-*` on my EC2 instance).

Also, it seems that easy_install-34 works on EC2, but pip-34 didn't work for me.

**Comment by micahcochran** [comment]
@aluykx did you install pip with [git-pip.py](https://pip.pypa.io/en/stable/installing/)?

**Comment by aluykx** [comment]
@micacochran I'm not sure anymore. Python3 on my EC2 instance (with Amazon Linux) was a pain in the butt to set up, the installation of pip was also really screwy.

**Comment by snowman2** [comment]
Refer to #216
