### ISSUE TITLE
CRS.srs attribute is not documented

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#253]
The `srs` attribute is not documented on the API page: https://pyproj4.github.io/pyproj/html/api/crs.html

From looking at the code, it seems this attribute is keeping the original "source" string how the CRS was created (which is then used in eg the repr) ?

**Comment by snowman2** [comment]
You are correct that it is the original "source" string for how the CRS was created. It might be good to add it to the documentation.

**Comment by jorisvandenbossche** [comment]
To take a step back: does this need to be public? (internally it is also only used for the repr and pickling, as far as I can see) 
And in that case, is `srs` a good name?

**Comment by snowman2** [comment]
`srs` is also used in the Transformer class for transformations. It does not have to be public, but it is useful for users to compare what they input to what was used to create their projection. The name was chosen to be consistent with the existing `Proj.srs`.

**Comment by jorisvandenbossche** [comment]
>  The name was chosen to be consistent with the existing Proj.srs.

Ah, that's a good reason (if starting fresh, I would rather go with something more descriptive such as `user_input`, as I find `srs` a bit confusing)

**Comment by jorisvandenbossche** [comment]
But with a good documentation entry, it maybe shouldn't be that confusing. Because as I see, the transformer is actually using this as the actual CRS definition to create the proj pipeline?

**Comment by snowman2** [comment]
I agree with you on the name. But, since it is there, for backwards compatibility, I think a documentation entry would be the way to go.

> the transformer is actually using this as the actual CRS definition to create the proj pipeline?

Yes, it has been the most stable method for creating the proj pipeline.
