### ISSUE TITLE
CRS.proj_version attribute exists but not set or used

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#254]
The `CRS` class has a `proj_version` property that is simply None (or at least for the simple test I am doing):

```
In [25]: crs_utm = pyproj.CRS.from_user_input(26915)   

In [26]: crs_utm.proj_version   

In [27]: print(crs_utm.proj_version) 
None
```

This is declared in the pxd file:

https://github.com/pyproj4/pyproj/blob/02fe9602ebf82fee5f9a2800ad25df5a01119501/pyproj/_crs.pxd#L49

but then never set or used in the actual implementation. Is it a left-over from the reorganisation (I see that the `Proj` class actually has one) ? Can it be removed from the pxd file ?

**Comment by snowman2** [comment]
Ah yes, that was leftovers from an original thought that was never used. It can be removed.
