### ISSUE TITLE
Don't include built documentation in the source files?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#256]
I noticed that the built html documentation files are included in the repo. I suppose this was done to serve them directly with github pages on https://pyproj4.github.io/pyproj ? 

It's certainly not a big deal, but I thought to just mention (without wanting to seem arrogant or so) that from the experience I have with other python projects that use sphinx, they typically only include the source files (what is in the `/sphinx` repo). 
Including the built html files is not that useful I think (or is it to allow people to browse them locally from a git checkout without building them?), and only adds extra stuff to the git tree (although the docs here are small, so that's probably less of a problem than for bigger projects, where the docs can be several MBs and keeping them in the git tree might lead to big repo sizes)

Anyway, just something small I noticed.

**Comment by snowman2** [comment]
I have seen other projects just have the sphinx pages in the repos. This is a good strategy for large projects or ones using readthedocs for document hosting and definitely cleans up the repo.

You are correct that:
1. The html files are in the repo to serve them up on github pages 
2. The number of pages for the project are relatively small
3. It allows for distributing pre-built release docs with the repo

Having it in the repo also simplifies the process for rebuilding release documentation as we can just rebuild the docs in a MR right before the release.

For a relatively small project, keeping the HTML in the repo is likely okay. However, if the number of docs pages ever gets too excessive (or if enough people prefer not to have the pre-built HTML docs in the repo :) ), github pages has an option to move it to another branch specifically for serving the docs.

**Comment by jorisvandenbossche** [comment]
> Having it in the repo also simplifies the process for rebuilding release documentation as we can just rebuild the docs in a MR right before the release.

I see. You can also use a `gh-pages` branch for this (which I personally find cleaner, it is a separate branch in which you don't necessarily need to preserve history). 
But, it is actually not *that* easy to automate this to push the output of sphinx build to a separate branch (so without tools to do this, I agree the current approach is the simplest).

You have `doctr` which automatically does this using Travis (https://drdoctr.github.io/)

Another option is actually also to use readthedocs? (https://readthedocs.org/) Also that one automatically takes care of building your docs for every commit / every release. 

So with regard of simplifying the process, I think it is worth to consider them. I would happy to set it up (either readthedocs or doctr, have experience with both).

**Comment by jorisvandenbossche** [comment]
BTW, something else: what would be the feeling to switch to the readthedocs theme? It is the theme that PROJ is also using, and I personally find their sidebar more useful than the one of the nature theme that is currently used.

**Comment by snowman2** [comment]
I wouldn't mind a theme change.

**Comment by snowman2** [comment]
rtd is nice, but has been unstable for builds for me at least. If you have a stable solution, I am not opposed.

`doctr` looks promising and could be build on tagged releases. I prefer that option at the moment.

Feel free to share opinions on preference.

@jswhit, do you have preferences here?

**Comment by jorisvandenbossche** [comment]
> rtd is nice, but has been unstable for builds for me at least. If you have a stable solution, I am not opposed.

Did you have bad experiences with it? 
I currently have problems with it for the geopandas docs, but there, the problem is that I need to create a big environment (all of fiona (gdal), shapely (geos), pyproj, cartopy, rtree, scipy, ... ) for the examples. That is often crashing (taking too long or too much memory). But for pyproj it would be much smaller (just proj / pyproj should suffice?), so I expect no problems there. But apart from those installation issues with geopandas, I have had good experiences with it.

**Comment by snowman2** [comment]
Yeah, installation issues. It works sometimes (until it breaks). I prefer to not fight with it. That is a big reason why we build docs the way we currently do.  What we have here is pretty stable and does not take away from development time to debug why the `rtd` build failed.

But, if `doctr` is stable, I wouldn't mind that option.

**Comment by jorisvandenbossche** [comment]
> But, if doctr is stable, I wouldn't mind that option.

Well, also with doctr you need to create and install an environment each time you build, so it is not that different as with readthedocs (but that will be the case for any kind of automated solution). It's only on travis, so we have a bit more control over it.

I think one advantage of readthedocs over doctr, is that on readthedocs you can more easily add a version switcher (although doctr can also built and upload different versions).

If there is a preference for doctr, I am happy to give it a try. That way we could also have "dev" docs already publicly visible, before a release is made.

**Comment by snowman2** [comment]
> I think one advantage of readthedocs over doctr, is that on readthedocs you can more easily add a version switcher

I really like the version switcher and many of the great features rtd provides. Just needs more stability in the builds. Not worth the great features if the build process isn't stable IMO.

> Well, also with doctr you need to create and install an environment each time you build, so it is not that different as with readthedocs (but that will be the case for any kind of automated solution). It's only on travis, so we have a bit more control over it.

The major difference is that we control the build environment & we will already have `pyproj` installed in our environment, so most of the documentation build issues would be resolved from  that standpoint.

**Comment by snowman2** [comment]
I agree with doctr FAQ:
```
Why not Read the Docs?

Read the Docs is great, but it has some limitations:

- You are limited in what you can install in Read the Docs. Travis lets you run arbitrary code, which may be necessary to build your documentation.
- Read the Docs deploys to readthedocs.io. Doctr deploys to GitHub pages. This is often more convenient, as your docs can easily sit alongside other website materials for your project on GitHub pages.

In general, you should already be building your docs on Travis anyway (to test that they build), so it seems natural to deploy them from there.
```

**Comment by snowman2** [comment]
> I am happy to give it a try

If you would like to give it a try, that would be great :+1:

**Comment by jorisvandenbossche** [comment]
Another reason to not include this, is that it is quite annoying if you want to build the docs locally (eg when working on the docs, and doing a local doc build). Then you need to undo all the changes to the `docs` directory (as I am experiencing now ..).

**Comment by snowman2** [comment]
> Another reason to not include this, is that it is quite annoying if you want to build the docs locally ...

I don't disagree with you there :smile:. Feel free to rename `sphinx` to `docs` and delete the `docs` folder in #278. Thanks!
