### ISSUE TITLE
CRS.datum.to_epsg() segfaults

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#257]
I am creating a CRS for EPSG:31370 (https://epsg.io/31370), and accessing the `datum` gives again a CRS object, but then accessing the `to_epsg` method of it gives a segfault:

```
In [1]: import pyproj  

In [2]: pyproj.__version__ 
Out[2]: '2.1.2'

In [3]: crs = pyproj.CRS.from_epsg(31370)

In [4]: crs
Out[4]: 
<CRS: epsg:31370>
Name: Belge 1972 / Belgian Lambert 72
Ellipsoid:
- semi_major_metre: 6378388.00
- semi_minor_metre: 6356911.95
- inverse_flattening: 297.00
Area of Use:
- name: Belgium - onshore
- bounds: (2.5, 49.5, 6.4, 51.51)
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Easting[X] (east) EPSG:9001 (metre)
- Northing[Y] (north) EPSG:9001 (metre)

In [5]: crs.datum 
Out[5]: 
<CRS: DATUM["Reseau National Belge 1972",ELLIPSOID["Inte ...>
Name: Reseau National Belge 1972
Ellipsoid:
- semi_major_metre: 6378388.00
- semi_minor_metre: 6356911.95
- inverse_flattening: 297.00
Area of Use:
- UNDEFINED
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- UNDEFINED

In [6]: crs.datum.to_epsg() 
Segmentation fault (core dumped)
```

**Comment by jorisvandenbossche** [comment]
The proj4 docs say that `proj_identify` is implemented for GeodeticCRS, ProjectedCRS, VerticalCRS and CompoundCRS (https://proj4.org/development/reference/functions.html#_CPPv313proj_identifyP10PJ_CONTEXTPK2PJPKcPPCKcPPi). So we might need to do a check on the `self.projobj` first. 
There is a [`proj_is_crs`](https://proj4.org/development/reference/functions.html#_CPPv311proj_is_crsPK2PJ) function, but might not be restrictive enough.

**Comment by snowman2** [comment]
Definitely a good catch here. Some better error handling would be appropriate here.

**Comment by snowman2** [comment]
Probably need to check if `proj_list` is NULL here: https://github.com/pyproj4/pyproj/blob/236538976e3e7193339737ed013c218a5a6d3982/pyproj/_crs.pyx#L523
