### ISSUE TITLE
Provide option to "pretty print" WKT (MULTILINE=YES) ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#258]
When inspecting the WKT of a `CRS` (with `CRS.to_wkt())`, it can sometimes be useful to be able to "pretty print" the WKT instead of having it as one long string (eg in tutorials, explaining the different representations).

[`proj_as_wkt`](https://proj4.org/development/reference/functions.html#_CPPv311proj_as_wktP10PJ_CONTEXTPK2PJ11PJ_WKT_TYPEPPCKc) has a MULTILINE option to get this, but currently this is hardcoded to `NO`:

https://github.com/pyproj4/pyproj/blob/236538976e3e7193339737ed013c218a5a6d3982/pyproj/_crs.pyx#L276

As a test, I set this to `YES`, and then I get something like:

```
In [2]: crs = pyproj.CRS.from_epsg(4326) 

In [3]: crs.to_wkt()
Out[3]: 'GEOGCRS["WGS 84",\n    DATUM["World Geodetic System 1984",\n        ELLIPSOID["WGS 84",6378137,298.257223563,\n            LENGTHUNIT["metre",1]]],\n    PRIMEM["Greenwich",0,\n        ANGLEUNIT["degree",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS["geodetic latitude (Lat)",north,\n            ORDER[1],\n            ANGLEUNIT["degree",0.0174532925199433]],\n        AXIS["geodetic longitude (Lon)",east,\n            ORDER[2],\n            ANGLEUNIT["degree",0.0174532925199433]],\n    USAGE[\n        SCOPE["unknown"],\n        AREA["World"],\n        BBOX[-90,-180,90,180]],\n    ID["EPSG",4326]]'

In [4]: print(crs.to_wkt())
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
```

I think the single string (MULTILINE=NO) is probably a sensible default (although it is not the default of proj4), since that is what you want for programmatic handling of it (eg to write to a file). 
But would there be interest in adding it as an option? Eg that you could do `print(crs.to_wkt(pretty=True))` ?

**Comment by jorisvandenbossche** [comment]
> Eg that you could do print(crs.to_wkt(pretty=True))

Or alternative name: `print(crs.to_wkt(multiline=True))` to keep it closer to the proj4 terminology.

**Comment by snowman2** [comment]
Sounds reasonable to me. I almost prefer `pretty` just because it sounds more pythonic. But, multiline is a good option as well.
