### ISSUE TITLE
Argument order not standard compliant

### ISSUE THREAD

**Issue by gmg8** [pyproj4/pyproj#26]
According to http://pyproj.googlecode.com/svn/trunk/docs/pyproj.Proj-class.html pyproj takes the latitude and longitude input arguments in the order "lon, lat". 

This is not compliant to ISO 6709 (https://en.wikipedia.org/wiki/ISO_6709), which says that the order must always be "lat, lon":

> Order, positive direction, and units of coordinates are supposed to be defined by the CRS. When CRS identification is missing, the data **must** be interpreted by the following conventions:
> - **Latitude comes before longitude**
> - North latitude is positive
> - East longitude is positive

This causes frequent frequent problems when people are used to do geodetic calculations ISO compliant. Many don't even think about that a library with the importance of pyproj might expect a non-standard compliant argument order.

Of course the argument order can't be just changed because of backwards compatibility reasons. But would it be an possible to introduce an option for using an ISO compliant input parameter order?

**Comment by micahcochran** [comment]
> This is not compliant to ISO 6709 (https://en.wikipedia.org/wiki/ISO_6709), which says that the order must always be "lat, lon"

That is an oversimplification.  As you correctly quote the Wikipedia article:

> **Order**, positive direction, and units of coordinates are supposed to be defined by the CRS.

Continuing:

> When CRS identification is **missing**, the data must be interpreted by the following conventions: Latitude comes before longitude...`

I added emphasis to make my point.  It is really a set of rules for how coordinate pairs are ordered.  I would tend to think that the ordering of pairs would be for the storage and transmittal of coordinate pairs.  I could see the point that this could also govern coordinate pairs for functions.  I don't really know.  This will make the code a bit more complicated.  The underlying [PROJ4 API](https://trac.osgeo.org/proj/wiki/ProjAPI)'s pj_transform() uses x, y, z.

PROJ4 as of version 4.8.0 supports a way to change axis order with the [+axis parameter](https://trac.osgeo.org/proj/wiki/GenParms#Axisorientation).

[GDAL seems to have some support (and history) for switching Axis Order](https://trac.osgeo.org/gdal/wiki/FAQCoordinateSystemsAndProjections#WhatAxisOrderisusedinGDALOGR).  I don't know of any other Python libraries that supports reordering parameters based on the CRS or use lat/long ordering for Geographic Coordinate System.  There are Python libraries that don't know/care what CRS is being inputted.

Here is a way to get lat/long ordering for input.  Output will always be lon/lat.
```python
>>> from pyproj import Proj
>>> p = Proj(proj='utm',zone=10,ellps='WGS84')
#  p(y=latitude, x=longitude)
>>> x,y = p(y=34.36116666, x=-120.108)
'x=765975.641 y=3805993.134'
```

All that being said, it would be great to have access to ISO 6709 to read what it actually says, but alas [it is behind a paywall](http://www.iso.org/iso/catalogue_detail.htm?csnumber=39242).

I think it could designed to switch coordinate ordering, but I think it should be designed to allows for backward compatibility of current coordinate ordering (x, y, z).

**Comment by snowman2** [comment]
I think the workaround @micahcochran provided is sufficient for this case. For backward compatibility sake, I think keeping it as is is probably better. If you have a backwards compatible solution and would like to continue the conversation, feel free to reopen.

**Comment by snowman2** [comment]
Apparently it was already swapped in the new version of PROJ for most projections. See #225.
