### ISSUE TITLE
Provide direction / inverse option in Transformer.transform

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#266]
From discussion with @snowman2 

Currently the `Transformer.transform` method only provides the forward transform. But, we could also support the inverse transform. 
The `proj_trans` functions have a `direction` argument (https://proj4.org/development/reference/functions.html#c.proj_trans)

So it could be an `inverse=False|True` to be consistent with `Proj`. Or a `direction='forward'|'inverse'` to be closer to the proj API, but I think the `inverse` is nicer.

**Comment by snowman2** [comment]
Thanks!
