### ISSUE TITLE
anaconda package (v 1.9.6) is broken (ubuntu, py37)

### ISSUE THREAD

**Issue by Chitraketu** [pyproj4/pyproj#268]
The version of pyproj on anaconda is 1.9.6
This is a request to update it to version 2.1.3 (the version pip has)

The workaround is simply to install it using pip, however for some of us we are not even aware that pyproj is getting installed by anaconda so this is actually a request to update anaconda....

Thanks!

**Comment by jorisvandenbossche** [comment]
You will need to ask Anaconda about that (which you can do here: https://github.com/ContinuumIO/anaconda-issues/issues/).

But, this might not happen that fast yet: there are a lot of packages that depend on proj.4, which are not yet all updated to work with proj.4 6 (such as gdal). So they might want to wait on that (but, best ask there). 
Alternatively, you can already install pyproj 2 from the conda-forge channel (https://anaconda.org/conda-forge/pyproj). But again, at this moment, you can't yet install it together with some other packages like gdal (and thus everything that depends on gdal like fiona and geopandas)

**Comment by ocefpaf** [comment]
> Alternatively, you can already install pyproj 2 from the conda-forge channel ([anaconda.org/conda-forge/pyproj](https://anaconda.org/conda-forge/pyproj)). But again, at this moment, you can't yet install it together with some other packages like gdal (and thus everything that depends on gdal like fiona and geopandas)

BTW, conda-forge is migrating to `proj4 6.0.0` and has `pyproj 2.1.3`. Most of the important packages were already rebuilt, including `gdal` :wink:

See https://conda-forge.org/status/ for the migration status.

The only hiccup are the packages that depend on Qt (matplotlib, Jupyter, etc), b/c conda-forge is blocked on a new [Qt build with latest openssl](https://github.com/conda-forge/qt-feedstock/pull/98).

**Comment by jorisvandenbossche** [comment]
Cool! 
A "migration" means that the already built packages are not yet available until all (or enough) are done? (to not break temporarily created environments in the middle of the rebuilding)

**Comment by ocefpaf** [comment]
> A "migration" means that the already built packages are not yet available until all (or enough) are done? (to not break temporarily created environments in the middle of the rebuilding)

Not really. The packages are available right now. We rely on `conda-build 3` package specs to provide conda with enough metadata to do the right thing. For example, b/c of the Qt issue I mentioned above, if you try:

```
conda create --name TEST python=3.7 gdal pyproj jupyter # or anything that depends on qt
```

you will get `gdal 2.4.0`, and `pyproj 1.9.6` with `proj4 5.2.0`, but if you do:

```
conda create --name TEST python=3.7 gdal pyproj
```

you will get `gdal 2.4.1`, and `pyproj 2.1.3` with `proj4 6.0.0`.

Things are getting more stable with `conda` as we move to making `strict` channel default and rebuild everything with `conda-build 3`.

**Comment by jorisvandenbossche** [comment]
Where is the time that I opened bug reports about broken environments because you updated gdal but fiona was still building .. :-)

**Comment by ocefpaf** [comment]
> Where is the time that I opened bug reports about broken environments because you updated gdal but fiona was still building .. :-)

There are some other variables here that I did not mention, like bad pinning and bad package metadata (not to mention environments that are not using `strict`). However, those are "fixable problems" now with `strict`, and we are trying to identify them and fix as soon as possible.

**Comment by snowman2** [comment]
For reference: https://github.com/ContinuumIO/anaconda-issues/issues/11400

**Comment by snowman2** [comment]
pyproj 2.4.1 is now available: https://anaconda.org/anaconda/pyproj
