### ISSUE TITLE
Coordinates outside bounds of area of use now return inf

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#269]
Running the GeoPandas tests with proj 6 / pyproj master, turned up this regression:

```
In [1]: import pyproj 

In [2]: pyproj.__version__ 
Out[2]: '2.1.3'

In [3]: p1 = pyproj.Proj(init='epsg:26918')
   ...: p2 = pyproj.Proj(init='epsg:4326')

In [4]: pyproj.transform(p1, p2, 0, 0)
Out[4]: (inf, inf)
```

vs

```
In [1]: import pyproj

In [2]: pyproj.__version__    
Out[2]: '1.9.6'

In [3]: p1 = pyproj.Proj(init='epsg:26918') 
   ...: p2 = pyproj.Proj(init='epsg:4326')  

In [4]: pyproj.transform(p1, p2, 0, 0)
Out[4]: (-79.48874388438705, 0.0)
```

So the transform now returns `inf` instead of an actual value. The coordinates however are out of the area of use (see bounds here http://epsg.io/26918). But previously it did calculate the transformed values nevertheless. 

Here, it was a dummy test case in geopandas where we did not check that the tested dummy values were actually properly inside the bounds of the tested CRS. So that is easy to edit. But, it still is a breaking change (I don't know that what extent people run into this in practice). 

This seems a bit similar to https://github.com/pyproj4/pyproj/issues/202, but the difference is that here pyproj 1.9.6 actually returned values and not inf.

**Comment by snowman2** [comment]
I think this might need to be tested with PROJ master as well. I believe that they added a fix for that. Did you test it with the latest PROJ?

**Comment by snowman2** [comment]
I think that is what you said already, but just checking to be sure.

**Comment by jorisvandenbossche** [comment]
No, tested only with pyproj master, but released proj.4 from conda-forge (didn't set up yet dev tooling for proj.4)

**Comment by jorisvandenbossche** [comment]
Additional comment, there is now the `errcheck` keyword, which properly raises an error:

```
In [5]: pyproj.transform(p1, p2, 0, 0, errcheck=True)                                                                                                                           
...
ProjError: proj_trans_generic error: no system list, errno: 22
```

but, it's not the most informative error message ... Not sure if we can get more information than that from proj4

**Comment by snowman2** [comment]
Not fixed in the latest version. Probably need to raise issue in PROJ.
```python
>>> import pyproj
>>> p1 = pyproj.Proj(init='epsg:26918')
>>> p2 = pyproj.Proj(init='epsg:4326')
>>> pyproj.transform(p1, p2, 0, 0)
(inf, inf)
>>> pyproj.proj_version_str
'6.1.0'
>>> pyproj.transform(p1, p2, 0, 0, errcheck=True)
....
pyproj.exceptions.ProjError: proj_trans_generic error: no system list, errno: 22

```

**Comment by jorisvandenbossche** [comment]
cc @rouault is this an expected change in proj ?

**Comment by jorisvandenbossche** [comment]
Given the explanation in https://github.com/OSGeo/proj.4/issues/1449 and https://github.com/OSGeo/proj.4/issues/1329, the behaviour of this might have changed again?

**Comment by snowman2** [comment]
Looks like the behavior is restored with the master branch of PROJ:
```
>>> from pyproj import Transformer, proj_version_str
>>> proj_version_str
'6.1.0'
>>> transformer = Transformer.from_proj("+init=epsg:26918", "+init=epsg:4326")
>>> transformer.transform(0, 0, errcheck=True)
(-79.48874388438705, 0.0)
```

**Comment by yxdragon** [comment]
may be it is out of bounds, but I want to stich some map, How can I force to get the result?
gdal.osr give the result I need, (but pyproj is 2 times faster than osr, and my image is very large, so I need pyproj force to count the point outside)

```python
wkt2 = 'PROJCS["China_Lambert_Conformal_Conic",GEOGCS["GCS_Beijing_1954",DATUM["Beijing_1954",SPHEROID["Krassowsky_1940",6378245,298.3,AUTHORITY["EPSG","7024"]],AUTHORITY["EPSG","6214"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",30],PARAMETER["standard_parallel_2",62],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",105],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]'

wkt1 = 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]]'

prj1 = osr.SpatialReference()
prj1.ImportFromWkt(wkt1)
prj2 = osr.SpatialReference()
prj2.ImportFromWkt(wkt2)

ct = osr.CoordinateTransformation(prj1, prj2)
print(ct.TransformPoint(100.20201515, 40))
# -396193.6266314621, 4808582.335950634, 0.0

prj1 = pyproj.CRS(wkt1,preserve_units=True)
prj2 = pyproj.CRS(wkt2, preserve_units=True)
ct = pyproj.Transformer.from_crs(prj1, prj2)
print(ct.transform(100.20201515, 40))
# inf, inf
```

**Comment by snowman2** [comment]
@yxdragon, the good news is that there is a simple solution to your problem. In PROJ 6+, they take the axis order into consideration when doing transformations. 

In your case, `wkt1` has the latitude first longitude second and `wkt2` has the east first and the northing second:
```python
>>> from pyproj import CRS, Transformer
>>> wkt2 = 'PROJCS["China_Lambert_Conformal_Conic",GEOGCS["GCS_Beijing_1954",DATUM["Beijing_1954",SPHEROID["Krassowsky_1940",6378245,298.3,AUTHORITY["EPSG","7024"]],AUTHORITY["EPSG","6214"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",30],PARAMETER["standard_parallel_2",62],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",105],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]'
>>> wkt1 = 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]]'
>>> crs2 = CRS(wkt2)
>>> crs2
<Projected CRS: PROJCS["China_Lambert_Conformal_Conic",GEOGCS["GCS ...>
Name: China_Lambert_Conformal_Conic
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Lambert Conic Conformal (2SP)
Datum: Beijing 1954
- Ellipsoid: Krassowsky_1940
- Prime Meridian: Greenwich

>>> crs1 = CRS(wkt1)
>>> crs1
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
Since this is the case, you need to swap the order of your input so that the latitude is first and longitude is second:
```python
>>> transformer = Transformer.from_crs(crs1, crs2)
>>> transformer.transform(40, 100.20201515)
(-396207.328443438, 4808545.278686934)
```
Or, if you want it to always have the longitude first and latitude second, you can toggle on the `always_xy` argument:
```python
>>> transformer = Transformer.from_crs(crs1, crs2, always_xy=True)
>>> transformer.transform(100.20201515, 40)
(-396207.328443438, 4808545.278686934)
```
For more information about this, I would recommend looking at:
- https://pyproj4.github.io/pyproj/stable/examples.html#transformations-from-crs-to-crs
- https://proj.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent

Hopefully this helps.

**Comment by snowman2** [comment]
Also, `preserve_units=True` is not a valid argument for `pyproj.CRS` and is only meant for `pyproj.Proj`.

**Comment by yxdragon** [comment]
@snowman2 thanks, and another question, as in china, our map could not use "true coordinate", so we must add some kind of offset. This trans is based on wgs84, and I know the transform fomula. So, can I implements a custom CRS or PRJ? and what should I do? can you give me some advice?

**Comment by snowman2** [comment]
@yxdragon, would you mind opening up a separate issue with your question? That would help us track the issue. Also, when you do, would you mind adding the formula as well as some example points?

**Comment by yxdragon** [comment]
@snowman2 It is ok for opening up a new issue, but I think it is not a general question. my question is "does pyproj support custom CRS?" which did not has a geometry meant, just a arbitrary transformation, I think the web Mercator is also not a geometry meaningful prj, just a formula for it could be looking well. So can I specific my prj?

**Comment by snowman2** [comment]
It would be useful to have in another issue so it is easier for someone who has a similar question. I would recommend looking into `Transformer.from_pipeline()`.
