### ISSUE TITLE
Import error no module named pyproj._datadir in pyproj

### ISSUE THREAD

**Issue by Manikandankasi01** [pyproj4/pyproj#273]
Hi,

I'm getting below error while running python .exe file.
![pyproj](https://user-images.githubusercontent.com/30194069/56333710-e1b02080-61b2-11e9-83eb-b40f042e15ba.PNG)

its working fine when i run .py file directly in cmd. but failing when i run .exe file.

Python Version: 3.7
pyproj : 2.1.3
geopandas :0.4

Any help on this much appreciated.
Thanks, 
Mani

**Comment by snowman2** [comment]
Mind sharing installation method & windows version?

**Comment by Manikandankasi01** [comment]
Hi Snowman,

i used pip install pyproj.
Below for installed packages.
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org geopandas
Requirement already satisfied: geopandas in c:\python37\lib\site-packages (0.4.1)
Requirement already satisfied: fiona in c:\python37\lib\site-packages (from geopandas) (1.8.6)
Requirement already satisfied: shapely in c:\python37\lib\site-packages (from geopandas) (1.6.4.post1)
Requirement already satisfied: pandas in c:\python37\lib\site-packages (from geopandas) (0.24.2)
Requirement already satisfied: pyproj in c:\python37\lib\site-packages (from geopandas) (2.1.3)
Requirement already satisfied: six>=1.7 in c:\python37\lib\site-packages (from fiona->geopandas) (1.12.0)
Requirement already satisfied: cligj>=0.5 in c:\python37\lib\site-packages (from fiona->geopandas) (0.5.0)
Requirement already satisfied: attrs>=17 in c:\python37\lib\site-packages (from fiona->geopandas) (19.1.0)
Requirement already satisfied: click>=4.0 in c:\python37\lib\site-packages (from fiona->geopandas) (7.0)
Requirement already satisfied: click-plugins>=1.0 in c:\python37\lib\site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: munch in c:\python37\lib\site-packages (from fiona->geopandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\python37\lib\site-packages (from pandas->geopandas) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\python37\lib\site-packages (from pandas->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.12.0 in c:\python37\lib\site-packages (from pandas->geopandas) (1.16.2)

Thanks,
Mani

**Comment by fabiopicchi** [comment]
I ran into the same problem after packing my project with pyinstaller. I don't really know how to debug this so any help will be very appreciated :)

**Comment by micahcochran** [comment]
I've never used pyinstaller.  Here's what pyinstaller's documentation says about [Cython Support](https://pyinstaller.readthedocs.io/en/stable/feature-notes.html#cython-support).

**Comment by jvstatinydev** [comment]
https://stackoverflow.com/questions/55824830/i-get-error-no-module-named-pyproj-datadir-after-i-made-py-to-exe-with-py

I had the same problem but maybe you can try this..

**Comment by snowman2** [comment]
@Manikandankasi01 did https://github.com/pyproj4/pyproj/issues/273#issuecomment-486249484 or https://github.com/pyproj4/pyproj/issues/273#issuecomment-486517407 resolve your issue?

**Comment by TetyaseDaWina** [comment]
Same error on a notebook. 


![pyproj](https://user-images.githubusercontent.com/14349424/59336091-2f05c580-8cfe-11e9-9cd7-87b7cc6882e8.png)

**Comment by TetyaseDaWina** [comment]
> Almost the same error on a notebook.
> 
> ![pyproj](https://user-images.githubusercontent.com/14349424/59336091-2f05c580-8cfe-11e9-9cd7-87b7cc6882e8.png)
> 
> I open an other issue for unix users ?

my path to PROJ.4 wasn't the right one. After setting it to for me /usr/share/proj, it works.

**Comment by snowman2** [comment]
Feel free to reopen or continue the thread if the suggestions provided didn't provide the solution.

**Comment by AbderrahmenM** [comment]
Anyone got a solution for this please ?

**Comment by snowman2** [comment]
> Anyone got a solution for this please ?

Did you try out either of these solutions: https://github.com/pyproj4/pyproj/issues/273#issuecomment-486249484 or https://github.com/pyproj4/pyproj/issues/273#issuecomment-486517407?

**Comment by allaboutmikey** [comment]
Anyone finding this via a search: pyinstaller v4 has the hooks specifically to address this pyproj issue. All working for me now.

**Comment by pvillacorta-stratio** [comment]
Has something changed in the latest pyproj 3.0.0 that causes trouble again? When runnin pyinstaller I am getting
```
  File "pyproj\crs\__init__.py", line 7, in <module>
  File "pyproj/_crs.pyx", line 1, in init pyproj._crs
ModuleNotFoundError: No module named 'pyproj._compat'
```
but I am new to pyinstaller as well, so it might be my fault :-(

**Comment by snowman2** [comment]
I am wondering if `pyinstaller` needs to add hooks as mentioned here: https://github.com/pyproj4/pyproj/issues/273#issuecomment-717738650?
