### ISSUE TITLE
Add enumeration objects

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#280]
It is always nice to have enumeration objects to not use strings where possible.

Current locations where it would be nice:
- to_wkt version option
- to_proj4 version option
- Transformer direction option

**Comment by micahcochran** [comment]
In Python 3.4+ [enum in the standard library](https://docs.python.org/3/library/enum.html).  You can use the backport of [enum34](https://pypi.org/project/enum34/) for Python versions less than 3.4.  However much longer pyproj supports Python 2.7.
