### ISSUE TITLE
2.2.0 vs 2.1.4 Release

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#284]
@jswhit @jorisvandenbossche @micahcochran

Just want some opinions here on this. So, there are quite a few changes in pyproj for the next release that one could argue would be enough for a minor version bump.

I am currently thinking about using the minor version bump for upgrading and requiring PROJ 6.1.0 as the new axis ordering functionality in #238 is not backwards compatible (how to handle this can also be part of this conversation as it can impact the direction we go in).

Option 1: We release the changes as 2.1.4 so PROJ 6.0.0 users have them.
Option 2: We just make all of the changes in 2.2.0 for clarity sake.
Option 3-?: ?

**Comment by snowman2** [comment]
A couple of thoughts I had in favor of option 1:
- Undoing the from_crs deprecation before 2.2.0 release.
- Somehow warning the users that PROJ 6.1.0 will be required after the 2.2.0 release

But, not sure if these matter enough or not. We didn't have a warning for the 2.0.0 release. Maybe documenting these changes and the version check in the setup.py would suffice.

**Comment by jorisvandenbossche** [comment]
How would you practically do such a warning? 
(I personally think it is also not necessary, the upgrade in proj version in 2.0.0 was much bigger than the 6.0.0 -> 6.1.0 now)

**Comment by snowman2** [comment]
I was thinking about doing a version check on the main import and raising a warning if the version is less than 6.1.0. I would also add in a check to make sure it only happened on the first import so it would not have excessive warnings being raised.

I am currently on the fence about it, so I figured a discussion was warranted to make sure we're all in agreement with how to proceed.

**Comment by snowman2** [comment]
Though, I may be over thinking/complicating it. I think just doing it all in 2.2.0 would be simple, clear, and it would be easy for users to pin a previous version. Any disagreements?

**Comment by jorisvandenbossche** [comment]
> I was thinking about doing a version check on the main import and raising a warning if the version is less than 6.1.0. I would also add in a check to make sure it only happened on the first import so it would not have excessive warnings being raised.

But it would still be a warning that everybody will see, without having a way to act upon it to get rid of it (which should typically be the purpose of the warning).  

So I am also more in favor of your last comment. Eg once geopandas would start using the CRS object, we might want to require pyproj >= 2.2

**Comment by snowman2** [comment]
Sounds good. Based on the comments and reactions, I think a 2.2.0 release is the way to go. Thanks!
