### ISSUE TITLE
API: rename to_geodetic to as_geodetic ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#297]
Currently, the CRS has a `to_geodetic` method to get the underlying geographic CRS. For example:

```
In [9]: crs = pyproj.CRS.from_epsg(31370)

In [10]: crs.type_name
Out[10]: 'Projected CRS'

In [12]: crs.to_geodetic()
Out[12]: 
<Geographic 2D CRS: epsg:4313>
Name: Belge 1972
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: Belgium - onshore
- bounds: (2.5, 49.5, 6.4, 51.51)
Datum: Reseau National Belge 1972
- Ellipsoid: International 1924
- Prime Meridian: Greenwich

In [13]: crs.to_geodetic().type_name
Out[13]: 'Geographic 2D CRS'
```

But, the `to_geodetic` is a bit the "weird duck" in the middle of all other `to_..` methods, which all return *some* representation of the current CRS, while `to_geodetic` returns a *different* CRS. 

Therefore, I was thinking, we could also name it `as_geodetic`. Or `get_geodetic`.

**Comment by snowman2** [comment]
I agree 👍

**Comment by snowman2** [comment]
I think making it a property like `geodetic_crs` would be the way to go. It would match `source_crs` and the `sub_crs_list`.

**Comment by jorisvandenbossche** [comment]
Ah, that's also a good option

**Comment by snowman2** [comment]
Addressed in #299

**Comment by jorisvandenbossche** [comment]
[ @snowman2 github sidenote : if you put "closes" before the issue numbers in the PRs, the issues get closed automatically, and you don't need to go close them yourself ]

**Comment by snowman2** [comment]
Nice, I will try it out.
