### ISSUE TITLE
Usefulness of CRS.is_valid?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#304]
See https://github.com/mapbox/rasterio/issues/1624

**Comment by snowman2** [comment]
I don't use it. Not sure how useful it is.

**Comment by jorisvandenbossche** [comment]
The main thing argued in the other issue is: you can no longer *construct* an invalid CRS, as it will already raise upon construction (in rasterio)

So the question is: is the same true for pyproj? 
Can you make an example of constructing an invalid one? (or do we have a test for that? The one test I saw actually tests that the construction raises an error, not that is_valid returns False)

**Comment by snowman2** [comment]
I don't think an invalid CRS can be created. I am pretty sure that the check that it is the CRS type ensures this.

**Comment by snowman2** [comment]
I think this should be deprecated.
