### ISSUE TITLE
Remove no_defs when initializing with init=epsg...

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#308]
https://github.com/geopandas/geopandas/issues/245#issuecomment-490132059

**Comment by snowman2** [comment]
https://github.com/OSGeo/proj.4/issues/201

Nodefs can be safety removed from all proj strings.

**Comment by jorisvandenbossche** [comment]
@snowman2 and there is no potential difference in behaviour with and without this "+no_defs" flag?

**Comment by jorisvandenbossche** [comment]
(or if I understand correctly, with the new pyproj, you kind if automatically / always get "+no_defs" since the definitions have been removed?)

**Comment by snowman2** [comment]
> with the new pyproj, you kind if automatically / always get "+no_defs" since the definitions have been removed

Yes, that is the case based on what I understand from the issue in PROJ.

**Comment by snowman2** [comment]
Looks like this wasn't really necessary. It doesn't hurt anything, but I am tempted to remove it as it does not really help anything either.
