### ISSUE TITLE
Use case of the pyproj.Proj class

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#320]
Copying part of the discussion in https://github.com/pyproj4/pyproj/issues/271 here:

> > me: it is still not fully clear to me what the usecase of pyproj.Proj is
>
> @snowman2: It is an essential class used for transformations in pyproj 1.9.6 and is there at the very least for backwards compatibility. I think most use cases could simply switch to the pyproj.CRS class instead.

I fully understand its use case and importance in pyproj < 2. But I think it is important to make it clear to users (potentially new users that never used the Proj class before) in the documentation what is recommended now. 

Is it only kept for backwards compatibility? If so, then let's state that in the docs, point to use CRS instead and provide users an explanation how to switch to CRS if they were already using Proj before.

Or are there still use cases where you would use Proj instead of CRS?

**Comment by snowman2** [comment]
> I think it is important to make it clear to users (potentially new users that never used the Proj class before) in the documentation what is recommended now.

Agreed. I can try to take a try on this one later, but I will definitely need a good review from @jswhit.

**Comment by jorisvandenbossche** [comment]
Trying to explain the difference to myself: would it be correct to say that `Proj` is basically a specific case of `Transformer` where the source crs is always WGS84 ?

**Comment by snowman2** [comment]
I would say that `pyproj.Proj` maps to the `proj` command line tool. The docs say: `The proj program is limited to converting between geographic and projection coordinates within one datum.`

So, I would assume that this is equivalent to:
```python
cc = CRS.from_epsg(3857)
proj = Transformer.from_crs(cc.geodetic_crs, cc)
```

But, I would need to verify that to say for sure.

**Comment by snowman2** [comment]
It seems to be the case. I modified the code in `pyproj.Proj` to use the transformer as I posted above, and all seems to work as expected: https://github.com/snowman2/pyproj/commit/3b99e6f1acf8772588956f477256a4cfd7a224d7
