### ISSUE TITLE
Transformer() constructor results in invalid object

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#321]
The `pyproj.Transformer` class constructor takes no arguments, but you can actually create an object. Although then it is not that useful:

```
In [4]: t = pyproj.Transformer()      

In [5]: t
Out[5]: <pyproj.transformer.Transformer at 0x7fd75ff9b860>

In [6]: t.transform(0, 0) 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-65405fa99360> in <module>
----> 1 t.transform(0, 0)

~/scipy/repos/pyproj/pyproj/transformer.py in transform(self, xx, yy, zz, tt, radians, errcheck, direction)
    207             intime = None
    208         # call pj_transform.  inx,iny,inz buffers modified in place.
--> 209         self._transformer._transform(
    210             inx,
    211             iny,

AttributeError: 'Transformer' object has no attribute '_transformer'
```

If there is no use for such an object, I would actually raise an error in the ``__init__`` to say to use one of the other methods.

(or otherwise, give an actual use case to the init)

**Comment by snowman2** [comment]
Ah yes, good catch. Thanks!

**Comment by snowman2** [comment]
I am having memories of this. I need an empty constructor in the other init methods, so raising an exception would not be helpful in init, although I wanted to at one point. Probably need to brainstorm another solution like an argument to skip the exception in the init or checks in the other methods to ensure it is initialized properly.

**Comment by jorisvandenbossche** [comment]
Ah, I see. That's because that in this case, the `Transformer` does not inherit the cython `_Transformer`. Is there a reason for that? 
But with the current layout, I think you can do something like:

```
transformer = object.__new__(Transformer)
transformer._transformer = _Transformer...
```

But maybe we could also think about having an actual constructor that passes the input to `proj_create` and raises an error if the resulting PJ is not a coordinate operation / transformation.

**Comment by snowman2** [comment]
> the Transformer does not inherit the cython _Transformer. Is there a reason for that?

Yes, it is because the `from_crs` is a `staticmethod` that returns a `_Transformer` and not a `Transformer`. I attempted using a `classmethod` but realized that wont work due to the internal nature of the `projobj`. There is probably a way to get the inheritance to work, but hasn't been a priority.

> maybe we could also think about having an actual constructor that passes the input to proj_create

This won't necessarily work as `from_crs` uses `proj_create_crs_to_crs` and `from_pipeline` uses `proj_create`. However, adding a `create` method that accepts the `PJ*` from either of those methods and validates that it is the correct type would probably work.

Definitely needs some thought for this one. Thanks for the ideas!

**Comment by snowman2** [comment]
I went with the `__init__` method as it is consistent with what properties are being initialized and it ensures that the class is initialized properly at the same time.
