### ISSUE TITLE
When I install pyproj, pip returns error 127

### ISSUE THREAD

**Issue by bluems** [pyproj4/pyproj#323]
OS: Raspbian latest version(Kernel 4.19.42)
Python: 3.6.8
Proj: 6.1.0

When I install pyproj, pip returns error 127.

Error Message:
> subprocess.CalledProcessError: Command '['/usr/local/bin/proj']' returned non-zero exit status 127.

run sudo find / -name proj:
> /usr/local/bin/proj

How do I install this?

**Comment by snowman2** [comment]
Interesting, what happens when you execute `/usr/local/bin/proj`? Also, what are the permissions on `/usr/local/bin/proj`?

**Comment by bluems** [comment]
@snowman2 

```
pi@raspberrypi:~ $ /usr/local/bin/proj
Rel. 6.1.0, May 15th, 2019
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

and

```
pi@raspberrypi:~ $ ls -al /usr/local/bin/proj
-rwxr-xr-x 1 root staff 150372 May 28 14:18 /usr/local/bin/proj
```

Currently, it works as normal.
The only action I have taken is to attempt to rebuild venv several times through PyCharm or virtualenv.

**Comment by micahcochran** [comment]
@bluems 

Run this from a python console:
```python
import subprocess
proj_ver_bytes = subprocess.check_output(['/usr/local/bin/', 'proj'], stderr=subprocess.STDOUT)
```

It should give you the same Exception.

Try this one:
```python
proj_ver_bytes = subprocess.check_output('/usr/local/bin/proj', stderr=subprocess.STDOUT)
```

I saw some forum post that were suggesting that the first argument in `subprocess.check_output()` should be a string for Raspberry Pi Python, instead of a list.

When you run `pip`,  the first example is essentially what `setup.py` is doing in `check_proj_version()`.  It is making sure that you have the correct version of PROJ installed.

**Comment by bluems** [comment]
@micahcochran 

> Run this from a python console:

Return Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/'
```

It's interesting.
Because, run /usr/local/bin/proj is correctly return.

```
(venv) pi@raspberrypi:~/lx/python $ /usr/local/bin/proj
Rel. 6.1.0, May 15th, 2019
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```


> Try this one:

But, the above code seems to work normally.
Your thoughts are right.


> One more test. From bash run the following:

Run echo $?:

0. No Error.

**Comment by micahcochran** [comment]
@bluems 

I messed up the my first test.  I should have testing it out before posting. Sorry.   Ignore that one.

So, it sounds like the second test worked.

Does this work (Test 4)? (This is actually what is being run in `setup.py` by `pip`).
```Python
proj_ver_bytes = subprocess.check_output(['/usr/local/bin/proj'], stderr=subprocess.STDOUT)
```

If that reproduces the problem, this should be an easy fix.

**Comment by snowman2** [comment]
@bluems can you try:
```
pip install git+https://github.com/snowman2/pyproj@657cc427
```

**Comment by snowman2** [comment]
Looks like merging the change to master closed this issue. @bluems wr would still appreciate your feedback. Thanks!
