### ISSUE TITLE
latlong versus longlat versus latlon versus lonlat

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#327]
I noticed today that after creating a CRS object with:

```python
crs3 = CRS.from_string('+proj=latlong +datum=WGS84 +ellps=WGS84')
```

then doing:

```python
crs3.to_proj4()
```

I get:

```
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
```

I had no idea that there were aliases for `latlong`. Asking `proj -l=X` I get:

```
$ proj -l=latlong
  latlong : Lat/long (Geodetic alias)
$ proj -l=longlat
  longlat : Lat/long (Geodetic alias)
$ proj -l=latlon
   latlon : Lat/long (Geodetic alias)
$ proj -l=lonlat
   lonlat : Lat/long (Geodetic)
```

So I looked through the pyproj source and couldn't find anything obvious that said "convert to 'longlat'". Could some one explain where the preference for `longlat` came from? Is that coming from PROJ? According to `proj -l`, `lonlat` is the only one marked as not an alias. Not asking for a change, just curious.

**Comment by snowman2** [comment]
I assume it is something internal to the PROJ source code that performs the conversion. It uses the string to generate a `PJ*` object and probably has a default of `longlat` on export to proj4. But, I am not sure where the preference for `longlat` on export comes from.

But, you are correct in your observations that `lonlat` is the only non-alias:
```
python -c "import pyproj, pprint; pprint.pprint(pyproj.get_proj_operations_map())" | grep Lat/long
 'latlon': 'Lat/long (Geodetic alias)',
 'latlong': 'Lat/long (Geodetic alias)',
 'longlat': 'Lat/long (Geodetic alias)',
 'lonlat': 'Lat/long (Geodetic)',
```
But, it is consistently `longlat` on export:
```
>>> from pyproj import CRS
>>> CRS("+proj=latlon").to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
>>> CRS("+proj=lonlat").to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
>>> CRS("+proj=longlat").to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
>>> CRS("+proj=latlong").to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
```

I would recommend asking this on the PROJ gitter channel or mailing list (see: https://github.com/osgeo/proj.4). They can probably provide a better answer.

**Comment by djhoese** [comment]
Mentioned it on gitter. The overall answer was it was an arbitrary choice and doesn't mean anything. I don't have the time to submit a fix on the description so that `longlat` is marked as the non-alias, but it was suggested that it could be done if it mattered that much to me. It doesn't. 😉

**Comment by micahcochran** [comment]
It is in PROJ in the [latlong.cpp](https://github.com/OSGeo/proj.4/blob/master/src/projections/latlong.cpp) file.

Based on the C++ code `latlong` should be real name, and the rest should be aliases.  That's me just being picky.  Perhaps there is good reason for `longlat` being the non-alias.  However, it is all using the exact same code.

**Comment by djhoese** [comment]
@micahcochran I see that the names are defined/used there but where does it map the "aliases" to `longlat`?

**Comment by micahcochran** [comment]
@djhoese 

At the bottom of the file is how the "aliases" are created (I think PROJECTION is a define macro expansion):
```C
PJ *PROJECTION(latlong) {
    return latlong_setup (P);
}


PJ *PROJECTION(longlat) {
    return latlong_setup (P);
}


PJ *PROJECTION(latlon) {
    return latlong_setup (P);
}


PJ *PROJECTION(lonlat) {
    return latlong_setup (P);
}
```
