### ISSUE TITLE
End of Support for Python 2.x

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#331]
Python 2.7 is reaching End Of Life and will no longer be supported by PSF from 1st January, 2020. In addition, `pyproj` does not support Python 2.7 on Windows since `pyproj 2.x`.

https://www.python.org/dev/peps/pep-0373/
python/devguide#344

I am thinking `pyproj 2.2.x` should be the last version(s) to support Python 2.x.

Any opposition?

Related to:
- https://github.com/Toblerity/Fiona/issues/716
- https://github.com/mapbox/rasterio/issues/1613

**Comment by djhoese** [comment]
I'm not sure if I mentioned this elsewhere for this project, but maybe a `python_requires` could be added to the `setup.py` before 2.7 is completely dropped: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

This way python 2 users should be able to accidentally update to a py3-only version of pyproj.

**Comment by snowman2** [comment]
Definitely going to have to happen. Cython is on the list: https://python3statement.org/
