### ISSUE TITLE
Leading spaces in crs strings

### ISSUE THREAD

**Issue by fmaussion** [pyproj4/pyproj#345]
#### Code Sample, a copy-pastable example if possible

```python
import pyproj
crs = '+proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0'
pyproj.Proj(crs)
```

(note the leading spaces after `=` in `+lat_1= 30.0 +lat_2= 35.0`)

Raises: 

```
ProjError: Invalid projection b'+proj=lcc +lat_0=30 +lon_0=87 +lat_1=0 +lat_2=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs'.: (Internal Proj Error: proj_create: Error -21: conic lat_1 = -lat_2)
```

#### Problem description

This used to work fine in earlier pyproj versions (although I can't track which one). 

#### Expected Output

I believe pyproj used to be more robust than this?

**Comment by jorisvandenbossche** [comment]
It *might* also be a change in PROJ. Creating a CRS "works" (at least, an object is returned), but converting it to a proj4 string now included `lat_1=0` instead of `lat_1=30`:

```
In [7]: crs_proj4 = '+proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0'

In [8]: crs = pyproj.CRS(crs_proj4) 

In [9]: crs 
Out[9]: 
<Projected CRS: +proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +l ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Lambert Conic Conformal (2SP)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]: crs.to_proj4()
Out[10]: '+proj=lcc +lat_0=30 +lon_0=87 +lat_1=0 +lat_2=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs'
```

and it is this new proj4 string that fails when creating a `Proj` or `CRS` object from that.

**Comment by snowman2** [comment]
It seems to be a protection added to PROJ.
```
$ proj +proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0
Rel. 6.1.0, May 15th, 2019
<proj>: 
projection initialization failure
cause: conic lat_1 = -lat_2
```
Previous behavior:
```
>>> import pyproj
>>> pyproj.__version__
'1.9.6'
>>> proj = pyproj.Proj('+proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0')
>>> proj.srs
'+units=m +proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0'
>>> proj(10, 10)
(-8303741.774513611, 862069.6350072762)
```
With a fix coming soon:
```
>>> import pyproj
>>> proj = pyproj.Proj('+proj=lcc +lat_1= 30.0 +lat_2= 35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0 +y_0=0')
>>> proj.srs
'+proj=lcc +lat_0=30 +lon_0=87 +lat_1=30 +lat_2=35 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs'
>>> proj(12, 12)
(-7972642.636153826, 888114.2344571035)
```
@fmaussion, I think the results from the previous version were likely incorrect and not telling you about it.

**Comment by fmaussion** [comment]
> so the transformation seems to be correct for both

phew ;-)

Actually, the recent pyproj developments broke quite a few things in [salem](https://github.com/fmaussion/salem) testsuite, I *think* I managed to solve most of them.

**Comment by snowman2** [comment]
PROJ 6.0.0+ has quite a few breaking changes - but they are all good breaking changes. Glad to hear that `salem` is updating :+1:
