### ISSUE TITLE
Add non-versioned endpoint for sphinx documentation

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#347]
Right now the generated documentation includes the package version tag in the URL:

https://pyproj4.github.io/pyproj/v2.2.0rel/

This means it is impossible to link to things in the documentation over a long period of time. Most importantly blog posts or github issues talking about pyproj. The one that is effecting me now is that I would like to reference pyproj's CRS object in my sphinx documentation for satpy (https://satpy.readthedocs.io/en/latest/) where we use the builtin `intersphinx` extension to link to an `objects.inv` database that intersphinx creates for other packages.

So in Satpy I configure my package (`conf.py`) with:

```
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://docs.scipy.org/doc/numpy', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/reference', None),
    'xarray': ('https://xarray.pydata.org/en/stable', None),
    'dask': ('https://docs.dask.org/en/latest', None),
    'pyproj': ('https://pyproj4.github.io/pyproj/v2.2.0rel', None)
}
```

And any links to pyproj in my docs (ex. ``:class:`pyproj.crs.CRS```) will link to the pyproj docs. However, this will break for the next tag or build of the docs where the URL gets updated.

Would it be possible to have a stable or latest URL similar to the ones readthedocs provides to avoid this issue? Sorry if this already exists.

I tested this with:

```
python -m sphinx.ext.intersphinx https://pyproj4.github.io/pyproj/v2.2.0rel/objects.inv
```

**Comment by jorisvandenbossche** [comment]
I remember looking into that we should add a symlink from "html" or "stable" to the latest release when we added the automatic building/hosting of the docs in https://github.com/pyproj4/pyproj/pull/278, but I can't find it directly. And in any case, we forgot that after it was merged. So you are right it would be good to have a stable link.

(on the short term, if you need a stable link, the one to the dev docs should be stable: https://pyproj4.github.io/pyproj/dev)

**Comment by jorisvandenbossche** [comment]
Did a PR what I think should fix this: https://github.com/pyproj4/pyproj/pull/348

**Comment by snowman2** [comment]
The fix from @jorisvandenbossche worked like a charm: http://pyproj4.github.io/pyproj/stable/
