### ISSUE TITLE
Invalid proj results from rasterio CRS in pyproj > 2.0

### ISSUE THREAD

**Issue by fmaussion** [pyproj4/pyproj#350]
#### Code Sample, a copy-pastable example if possible

```python
import pyproj
import rasterio
print('Pyproj version: ', pyproj.__version__)
print('rasterio version: ', rasterio.__version__)

p1 = pyproj.Proj({'init': 'epsg:4326'})
p2 = pyproj.Proj(rasterio.crs.CRS({'init': 'epsg:4326'}))

pout = pyproj.Proj({'init': 'epsg:32632'})

print('Expected: ', pyproj.transform(p1, pout, 10., 46.))
print('With rio CRS: ', pyproj.transform(p2, pout, 10., 46.))
```

#### Problem description

Output with pyproj < 2:

```
Pyproj version:  1.9.6
rasterio version:  1.0.24
Expected:  (577432.1825690205, 5094533.591105094)
With rio CRS:  (577432.1825690205, 5094533.591105094)
```

With latest pyproj:

```
Pyproj version:  2.2.0
rasterio version:  1.0.24
Expected:  (577432.1825690205, 5094533.591105094)
With rio CRS:  (4849477.3819811465, 1378793.4460353532)

```

#### Expected Output

This is a bad bug... I took me ages to debug, because we initialize Proj instances from rasterio Dataset objects.

#### Environment Information

 - pyproj version 2.2.0
 - PROJ version 6.1.0
 - PROJ data directory /home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/pyproj/proj_dir/share/proj
 - Python version 3.5.2
 - Operation System Information Linux-4.15.0-50-generic-x86_64-with-LinuxMint-18.3-sylvia

#### Installation method
 - pip

**Comment by snowman2** [comment]
Hi @fmaussion, you have run into the axis swapping changes in PROJ 6+. When you initialized from the rasterio CRS, it has the axis order swapped, so latitude comes first in the transformation.

```python
>>> from pyproj import Transformer, CRS
>>> from rasterio.crs import CRS as RCRS
>>> pcrs = CRS("+init=epsg:4326")
>>> pcrs
<Geographic 2D CRS: +init=epsg:4326 +type=crs>
Name: WGS 84
Axis Info [ellipsoidal]:
- lon[east]: Longitude (degree)
- lat[north]: Latitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
>>> rcrs = CRS(RCRS(init="epsg:4326"))
>>> rcrs
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

>>> transformer = Transformer.from_crs(RCRS(init="epsg:4326"), 'epsg:32632')
>>> transformer.transform(46, 10)
(577432.1825690205, 5094533.591105094)
```

You can make it so longitude comes first by passing in `always_xy=True`.
```python
>>> transformer = Transformer.from_crs(RCRS(init="epsg:4326"), 'epsg:32632', always_xy=True)
>>> transformer.transform(10, 46)
(577432.1825690205, 5094533.591105094)
```

There are many things that might throw you off in the transition, so I would recommend reading:
https://pyproj4.github.io/pyproj/latest/examples.html
https://pyproj4.github.io/pyproj/latest/gotchas.html
https://proj.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent
https://pyproj4.github.io/pyproj/latest/api/transformer.html

**Comment by fmaussion** [comment]
> There are many things that might throw you off in the transition

OK, but from a user's point of view this is quite a silent backwards incompatible change on valid code (making a pyproj Proj from a rio file). (similarly, yesterday I noticed that `Proj.is_latlong` disappeared, which I believe was silent  - or I missed the deprecation cycle, also possible).

What was the rationale for not keeping `Proj` backwards compatible and introduce a deprecation cycle? This would've brought me to use `CRS` much earlier...

**Comment by snowman2** [comment]
We are definitely doing our best to help with this transition and understand that it will be a little rocky :).

> OK, but from a user's point of view this is quite a silent backwards incompatible change on valid code (making a pyproj Proj from a rio file)

The reason for not raising warnings or errors on the axis order swapping is that `pyproj` chose to follow `PROJ` in defaulting to the axis order of the CRS (so the behavior is now correct and we don't want to raise errors on correct behavior). Additionally, since the `always_xy=True` option was just barely introduced in 2.2.0 (https://pyproj4.github.io/pyproj/stable/history.html) with the support being added in PROJ 6.1.0, the default behavior is consistent with `pyproj` 2+. This will indeed cause troubles for many who are upgrading and we are attempting to address this by documentation.

> I noticed that Proj.is_latlong disappeared

This has been deprecated since pyproj 2.0.0
https://github.com/pyproj4/pyproj/blob/58b4f49da12794989fc8cb397dc0cd2ecd221a6d/pyproj/__init__.py#L375-L382
and was recently removed in pyproj 2.2.0.
