### ISSUE TITLE
Add deprecation warning for +init= syntax

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#355]
From: https://gitter.im/pyproj4-pyproj/community?at=5d13c274b3f22a4b2a4018be

More info about deprecation: https://github.com/pyproj4/pyproj/issues/224#issuecomment-476647824

It probably would be a good idea to add a deprecation warning when users use the `+init=` syntax.

**Comment by snowman2** [comment]
Also related: http://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code

**Comment by snowman2** [comment]
Also:
```
$ projinfo +init=epsg:4326
input string: parsing of user string failed: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
```

**Comment by djhoese** [comment]
Any idea if rasterio already does this? I've seen your last example (`syntax not supported in non-PROJ4`) a lot today but it seemed to be tied to rasterio being imported.

**Comment by snowman2** [comment]
I think it is printed to the terminal by PROJ: https://rasterio.groups.io/g/main/topic/30828038#177. But it doesn't seem to be the desired behavior.

**Comment by snowman2** [comment]
@jorisvandenbossche, currently `+init=` syntax is the only one that works for geopandas at present. So, raising a warning would throw your users off as they can't do it any other way. Thoughts? Maybe adding `warnings.filterwarnings`?

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche, currently +init= syntax is the only one that works for geopandas at present. So, raising a warning would throw your users off as they can't do it any other way. Thoughts? Maybe adding warnings.filterwarnings in geopandas?

Yeah, need to think about it a bit more, but that is probably the best option short term

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche, I think this is going to confuse geopandas users unless geopandas uses the always_xy option when reprojecting.

We should use `always_xy` in geopandas, but I don't think that is strictly related? As with the deprecated 'init=epsg:..' syntax the `always_xy` should not be needed? (as it does not follow the axis order of the EPSG)

**Comment by snowman2** [comment]
This is the scenario I am concerned about:

A user creates or loads in the GeoDataFrame
```python
>>> from shapely.geometry import Point
>>> import geopandas
>>> gsr = geopandas.GeoSeries([Point(12, 51)], crs={"init": "epsg:4326"})
>>> gsr.crs
{'init': 'epsg:4326'}
```
Then the user decides to re-project the data and gets the deprecation warning
```python
>>> gsr.to_crs("epsg:3857")
/home/snowal/scripts/pyproj/pyproj/crs.py:114: ProjDeprecationWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  ProjDeprecationWarning,
0    POINT (1335833.889519283 6621293.722740169)
dtype: object
```
So, because this is deprecated, the user is going to switch to the new syntax
```python
>>> gsr = geopandas.GeoSeries([Point(12, 51)], crs="epsg:4326")
>>> gsr.to_crs("epsg:3857")
0    POINT (5677294.030456952 1345708.408409109)
dtype: object
```
And the input axis order is swapped, so their reprojected data is now incorrect. They may or may not realize this and move along with incorrectly re-projected data.

**Comment by jorisvandenbossche** [comment]
OK, I see:

1) We should definitely start using `always_xy` if available (that will required a check of the pyproj version for now)

2) At the moment, we even create such init-based descriptions if the user pass the `epsg` keyword like `.to_crs(epsg=4326)`. So either we should catch and silence the warnings (or pyproj to raise DeprecationWarning) or also update how we create those epsg based ones (which will also need to be done based on the pyproj version). We need to update this creation anyhow, but, I think we currently also get such init-based ones passed from fiona, so fully getting rid of it is not fully possible I think until fiona is also updated to not use proj dicts.

**Comment by jorisvandenbossche** [comment]
Already pened issue on geopandas for the first item: https://github.com/geopandas/geopandas/issues/1036

**Comment by snowman2** [comment]
I address these issues here: https://github.com/geopandas/geopandas/pull/998. However, if you aren't ready to have the pyproj.CRS class returned, I could modify the CRS property to return a dictionary. But, I guess that would still break things as it doesn't preserve init= syntax. Another option would be to also store the fiona dict and return that instead.

**Comment by jorisvandenbossche** [comment]
About switching to the new pyproj CRS class -> I would like to do that fully at once (meaning: requiring pyproj > 2.1, so that the geopandas user has an consistent interface for `.crs`, not depending on the pyproj version). That was at least my initial idea, maybe I should let that go .. 

And for fully requiring PROJ 6 / pyproj 2, I think we should wait a bit longer (last time I checked fiona / gdal was not yet compatible with the latest PROJ on conda-forge, that might be fixed in the meantime, but it's all still very recent)

**Comment by snowman2** [comment]
> for fully requiring PROJ 6 / pyproj 2, I think we should wait a bit longer

Definitely agree 💯

**Comment by Sieboldianus** [comment]
> This is the scenario I am concerned about:
> 
> A user creates or loads in the GeoDataFrame
> 
> ```python
> >>> from shapely.geometry import Point
> >>> import geopandas
> >>> gsr = geopandas.GeoSeries([Point(12, 51)], crs={"init": "epsg:4326"})
> >>> gsr.crs
> {'init': 'epsg:4326'}
> ```
> 
> Then the user decides to re-project the data and gets the deprecation warning
> 
> ```python
> >>> gsr.to_crs("epsg:3857")
> /home/snowal/scripts/pyproj/pyproj/crs.py:114: ProjDeprecationWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
>   ProjDeprecationWarning,
> 0    POINT (1335833.889519283 6621293.722740169)
> dtype: object
> ```
> 
> So, because this is deprecated, the user is going to switch to the new syntax
> 
> ```python
> >>> gsr = geopandas.GeoSeries([Point(12, 51)], crs="epsg:4326")
> >>> gsr.to_crs("epsg:3857")
> 0    POINT (5677294.030456952 1345708.408409109)
> dtype: object
> ```
> 
> And the input axis order is swapped, so their reprojected data is now incorrect. They may or may not realize this and move along with incorrectly re-projected data.

Haha.. one year later, that was exactly what caused me 6+ hours of headache. It was not related to Geopandas, rather standard use of pyproj in a separate package. Saw the depreciation notice, switched to recommended syntax: projected geometries had switched (wrong) axis because I was using the traditional style of coordinate-order (lng, lat).. too bad I didn't see your comment a couple of hours earlier!

**Comment by Zeitsperre** [comment]
Thanks @Sieboldianus, I've run into this exact problem in one of my projects. Glad to finally know why.
