### ISSUE TITLE
wktext PROJ parameter being removed during conversion

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#357]
I'm updating some code to work better with pyproj 2.0+ and have run in to a small issue. My goal is to make predefined CRS objects available to Satpy/Pyresample users that work with `Proj/CRS` from pyproj and `CRS` from rasterio. The problem projection is:

```python
proj_dict = {'proj': 'ob_tran', 'o_proj': 'eqc', 'o_lat_p': 30.0, 'o_lon_p': 10.0, 'lon_0': -10.0, 'a': 6371000.0, 'b': 6371000.0, 'wktext': True}
```

In the past I never used the `wktext` but found that it was necessary to get rasterio to understand it after doing some googling. Now, I can't find the page that suggested it. I have no idea what it is actually doing. However, when using pyproj's `CRS` object as an intermediate object the `wktext` parameter seems to get lost:

```python
from pyproj import CRS                                                                                                                                                            
from rasterio.crs import CRS as rioCRS                                                                                                                                            

CRS.from_dict(proj_dict).to_dict()                                                                                                                                                
# {'proj': 'ob_tran', 'o_proj': 'eqc', 'o_lat_p': 30.0, 'o_lon_p': 10.0, 'lon_0': -10.0, 'a': 6371000.0, 'b': 6371000.0, 'type': 'crs'}

rioCRS.from_dict(proj_dict)                                                                                                                                                       
# CRS.from_wkt('PROJCS["unnamed",GEOGCS["unnamed ellipse",DATUM["unknown",SPHEROID["unnamed",6371000,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["custom_proj4"],EXTENSION["PROJ4","+proj=ob_tran +o_proj=eqc +o_lat_p=30.0 +o_lon_p=10.0 +lon_0=-10.0 +a=6371000.0 +b=6371000.0 +wktext=True"]]')

rioCRS.from_dict(CRS.from_dict(proj_dict).to_dict()) 
# CRSError: The PROJ4 dict could not be understood. OGR Error code 5

```

Could someone explain the purpose of the `wktext` parameter and whether or not you would consider this a bug in pyproj or in rasterio or neither? Is there something else I can do to make this projection understood to both pyproj and rasterio CRS?

**Comment by snowman2** [comment]
I am thinking 'type': 'crs' is probably causing you issues here. It is new and probably not supported by rasterio.

**Comment by djhoese** [comment]
Nope, rasterio seems ok with it:

```python
new_dict = CRS.from_dict(proj_dict).to_dict()                                                                                                                                                                                                                                                                                                        
# {'proj': 'ob_tran', 'o_proj': 'eqc', 'o_lat_p': 30.0, 'o_lon_p': 10.0, 'lon_0': -10.0, 'a': 6371000.0, 'b': 6371000.0, 'type': 'crs'}

new_dict['wktext'] = True                                                                                                                                                         

rioCRS.from_dict(new_dict)                                                                                                                                                        
# CRS.from_wkt('PROJCS["unnamed",GEOGCS["unnamed ellipse",DATUM["unknown",SPHEROID["unnamed",6371000,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["custom_proj4"],EXTENSION["PROJ4","+proj=ob_tran +o_proj=eqc +o_lat_p=30.0 +o_lon_p=10.0 +lon_0=-10.0 +a=6371000.0 +b=6371000.0 +wktext=True"]]')
```

**Comment by snowman2** [comment]
I am not familiar with the reasoning in rasterio for needing `wktext`. I would post about this issue in `rasterio` or ask in https://rasterio.groups.io/g/main to get better clarity on why it is needed.

As a workaround:
```python
>>> crs = CRS.from_dict(proj_dict)
>>> rcrs = RCRS.from_wkt(crs.to_wkt("WKT1_GDAL"))
>>> rcrs
CRS.from_wkt('PROJCS["unknown",GEOGCS["unknown",DATUM["unknown",SPHEROID["unknown",6371000,0]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["custom_proj4"],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],EXTENSION["PROJ4","+proj=ob_tran +o_proj=eqc +o_lat_p=30.0 +o_lon_p=10.0 +lon_0=-10.0 +a=6371000.0 +b=6371000.0"]]')
```

**Comment by snowman2** [comment]
Looks like this works as well:
```
>>> rcrs = RCRS.from_wkt(crs.to_wkt())
>>> rcrs
CRS.from_wkt('PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",ELLIPSOID["unknown",6371000,0,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["unknown",METHOD["PROJ ob_tran o_proj=eqc"],PARAMETER["o_lat_p",30,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],PARAMETER["o_lon_p",10,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],PARAMETER["lon_0",-10,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]],CS["Cartesian",2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]')
```

**Comment by djhoese** [comment]
Yeah I can try that, but still hard to use. I will point the rasterio people to this issue to see if they have any ideas. @snowman2 Any idea why pyproj/PROJ _drops_ the `+wktext`? Is there a rule somewhere that says "this shouldn't be used any more"?

**Comment by snowman2** [comment]
I did a quick search in the PROJ code and didn't find `wktext` anywhere. I also didn't see it in the code for rasterio. Maybe it is specific to GDAL?

For pyproj, it just uses the input string to create a projection object. Then on export, it converts that object back out to a string. Since `wktext` is not in the PROJ codebase as far as I can tell, I assume it just gets dropped.

**Comment by djhoese** [comment]
Yep, looks like it is an OGR specific thing:

https://github.com/OSGeo/gdal/blob/9f15a2e5f5b15e1eb5a927d8496c23d0d4c3f861/gdal/ogr/ogrspatialreference.cpp#L9508-L9516

**Comment by snowman2** [comment]
Interesting. That makes sense.

It looks like the `wktext` is preserved in the `srs` or user input string of the pyproj object:
```python
>>> crs = CRS({'proj': 'ob_tran', 'o_proj': 'eqc', 'o_lat_p': 30.0, 'o_lon_p': 10.0, 'lon_0': -10.0, 'a': 6371000.0, 'b': 6371000.0, 'wktext': True})
>>> crs.to_string()
'+proj=ob_tran +o_proj=eqc +o_lat_p=30.0 +o_lon_p=10.0 +lon_0=-10.0 +a=6371000.0 +b=6371000.0 +wktext +type=crs'
```
I am wondering if adding a kwarg to `to_proj/to_dict` to help preserve this may help or even makes sense to do. For example, something like:
```python
>>> crs.to_dict(from_input=True)
{'proj': 'ob_tran', 'o_proj': 'eqc', 'o_lat_p': 30.0, 'o_lon_p': 10.0, 'lon_0': -10.0, 'a': 6371000.0, 'b': 6371000.0, 'type': 'crs', '+wktext': True}
```
My main concern with this idea is that it has the potential to propagate potential invalid arguments that users pass in. Due to this. users might assume that they are valid or supported PROJ arguments. But, then again, it is returned on `to_string`. :thinking:

**Comment by jorisvandenbossche** [comment]
I am personally not sure we should add such a keyword. As you said, it propagates invalid arguments that are not understood by PROJ anyway. I am not sure we should therefore keep them in a `to_proj`.

It seems that Sean suggested to use the WKT anyway to interact between pyproj and rasterio, instead of the proj dict (so similar as your suggestion above). @djhoese that doesn't solve the issue? (you mentioned above that this is hard to use, can you clarify that a bit more?)

**Comment by djhoese** [comment]
I think I agree that pyproj probably shouldn't change anything the more I learn about this parameter.

I think @snowman2's suggestion will work fine, but this if for the `pyresample` library which still depends pretty heavily on the PROJ dict. This issue was discovered in my first attempts at switching to the `CRS` object internally, but still providing access to a PROJ dict/str property in `pyresample`. I can see two easy-ish solutions for me:

1. Update the rasterio-based code in my libraries to use the `CRS` WKT if it exists. WKT is able to fully describe *all* CRSes right?
2. Add `+wktext` for `ob_tran` and `nsper` projections whenever a PROJ dict is requested.

I just checked my post on the rasterio community forum/group and @sgillies suggests the same as @snowman2. That is, use WKT for conversion between pyproj and rasterio and not PROJ.

Is there any reason I might use some other WKT version/format instead of pyproj's default of `WKT2_2018`?

**Comment by snowman2** [comment]
> WKT is able to fully describe all CRSes right?

As far as I know it should.

> Is there any reason I might use some other WKT version/format instead of pyproj's default of WKT2_2018?

You would probably need to check when the support was added in GDAL for WKT2_2018. The recent versions support it, but depending on what version of GDAL/rasterio you would like to support, it may fail. So, the `WKT1_GDAL` is also an option.


> I am personally not sure we should add such a keyword.

I think if there is a lot of hesitation on something, probably better not. I think removing that sounds like a good idea.

**Comment by snowman2** [comment]
I believe this is resolved. If you have further questions or feel it needs to be reopened, feet free to reopen or just post further questions.

**Comment by djhoese** [comment]
I need to bring this back up because I ran in to another issue related to converting a pyproj CRS object to a rasterio CRS object.

I have PROJ 6.1.1, pyproj 2.3.1, libgdal 2.4.2, and rasterio 1.0.28 all from conda-forge installed. I'm trying to take any pyproj CRS object and make a geotiff with it using rasterio. From the above discussion I did `crs = rasterio.crs.CRS.from_wkt(pyproj_crs.to_wkt())` but found that this fails for `EPSG:3035`:

```
CPLE_AppDefinedError: Only OGC WKT Projections supported for writing to GeoTIFF.  PROJCRS["ETRS89 / LAEA Europe",BASEGEOGCRS["ETRS89",DATUM["European Terrestrial Reference System 1989",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4258]],CONVERSION["Europe Equal Area 2001",METHOD["Lambert Azimuthal Equal Area",ID["EPSG",9820]],PARAMETER["Latitude of natural origin",52,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",10,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["False easting",4321000,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",3210000,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS["Cartesian",2],AXIS["northing (Y)",north,ORDER[1],LENGTHUNIT["metre",1]],AXIS["easting (X)",east,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["unknown"],AREA["Europe - ETRS89"],BBOX[32.88,-16.1,84.17,40.18]],ID["EPSG",3035]] not supported.
```

If I directly create the rasterio CRS object with the EPSG code then it works fine. If I use `version='WKT1_ESRI'` or `version='WKT1_GDAL'` (which I know you mentioned above @snowman2). I couldn't find an exact answer on when WKT2 was added to GDAL but it is confidently in GDAL 3.0+.

Any suggestions about what version I should use to export the CRS information to rasterio? Does rasterio just not understand WKT2 and that's why my usage fails? Any help is appreciated.

**Comment by snowman2** [comment]
Hmm, sounds like you have done some good investigation so far. I guess you could do a trial and error approach. You could use `to_epsg` and if that fails, the `to_wkt` starting with WKT2 and then fall back to the other versions.

**Comment by djhoese** [comment]
Yeah the issue is I haven't found a good way to test if the geotiff creation will fail without actually trying to create the geotiff. I think even the rasterio CRS object's `wkt` property which I think is documented as producing an OGC compatible version of the WKT still returns a string and then geotiff creation will fail.

**Comment by snowman2** [comment]
Hmmm, do you have a reproducible example? If so, it might be worth it to raise the issue with rasterio.

**Comment by djhoese** [comment]
I do have a reproducible example, but now things are getting even more confusing. Looks like this is only an issue with libgdal <3.0 install (assuming because WKT2 is supported in GDAL). Currently debugging more, will file an issue if I track it down to the actual problem.
