### ISSUE TITLE
Add parallel processing where it makes sense

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#364]
https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html

**Comment by jorisvandenbossche** [comment]
Note that this adds a run and build time dependency on OpenMP. 

sklearn has added this recently, so might give some prior art. See eg https://github.com/scikit-learn/scikit-learn/pull/13053, https://github.com/scikit-learn/scikit-learn/pull/13543 with updates of their setup. They should also have updated their wheel building

**Comment by snowman2** [comment]
I am curious to see if it provides speedups that are worth the added dependency.
