### ISSUE TITLE
Automatically try to find the data directory?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#387]
Fiona has some code (or maybe coming from rasterio originally) to find the data directory of `PROJ`:

https://github.com/Toblerity/Fiona/blob/2cafe743292fb25485a6d320785a5690abfa8eb3/fiona/_env.pyx#L312-L363

and then uses that to automatically set the data directory if not found:

https://github.com/Toblerity/Fiona/blob/2cafe743292fb25485a6d320785a5690abfa8eb3/fiona/_env.pyx#L403-L414

I was wondering if that is functionality we might want to have in pyproj as well.

One caveat, `fiona` only does it if you explicitly use there `Env` context manager (I think), which is eg what other libraries such as geopandas can use, and so fiona does not do it generally by just importing fiona (although I am not fully sure how / if they clean up the set env variables). IN pyproj, we don't really have such concept of context.

One occasion where I regularly bump into the data directory issues is using conda installed pyproj in an environment using a jupyter kernel (where your environment is registered as a kernel, and not running jupyter yourself). In conda, activating an environment sets the env variable, but choosing a kernel in the notebook does not do this, leading to the typical errors if you don't do a `pyproj.set_datapath(..)` manually.

**Comment by snowman2** [comment]
Interesting. For reference, the current implementation: https://github.com/pyproj4/pyproj/blob/c8c8d31178f21a40d95b3e9e777fcaf969148dbf/pyproj/datadir.py#L41-L99

**Comment by snowman2** [comment]
Another note: newer versions of conda should handle resetting the environment variables automatically. Restarting the kernel should work for in that case.

**Comment by jorisvandenbossche** [comment]
What is "newer" here? I have been needing the manual datadir setting very recently. I would think it is more a jupyter issue (as the environment never gets "activated" in the traditional sense)

**Comment by snowman2** [comment]
Not sure the exact version, but if you install a package it should perform the activation script for you. Maybe a jupyter issue as you mentioned.

**Comment by jorisvandenbossche** [comment]
Some related issues: https://github.com/conda-forge/pyproj-feedstock/issues/35, https://github.com/jupyter/notebook/issues/3588

**Comment by snowman2** [comment]
Can you switch kernels and see if `sys.prefix` is updated?

**Comment by snowman2** [comment]
I cannot seem to reproduce by switching kernels:
Kernel 1:
![image](https://user-images.githubusercontent.com/8699967/63067995-1620b880-bed7-11e9-8dd3-d9dc2cab8d63.png)
Kernel 2:
![image](https://user-images.githubusercontent.com/8699967/63068009-2c2e7900-bed7-11e9-82ea-74c186215aa1.png)

**Comment by snowman2** [comment]
Feel free to reopen after 2.3.0 is released and the issue is not resolved.
