### ISSUE TITLE
Difference when removing +init= prefix

### ISSUE THREAD

**Issue by manthey** [pyproj4/pyproj#390]
Removing `+init=` from a projection string (`+init=epsg:4326`) changes the results.

#### Code Sample, a copy-pastable example if possible

```python
import pyproj
pyproj.transform(pyproj.Proj('+init=epsg:4326'), pyproj.Proj('+init=epsg:3857'), [-180, 180], [0, 0])
# returns ([-20037508.342789244, 20037508.342789244], [0.0, 0.0])
pyproj.transform(pyproj.Proj('epsg:4326'), pyproj.Proj('+init=epsg:3857'), [-180, 180], [0, 0])
# returns ([inf, inf], [inf, inf])
```
#### Problem description

I would expect the addition or removal of `+init=` to only affect whether a `FutureWarning` is issued, not the results of a transform.

#### Expected Output

The same (non-infinite) values regardless of whether the `+init=` prefix is added to `epsg:4326`.

#### Environment Information

System:
    python: 3.7.3 (default, Mar 26 2019, 00:55:50)  [GCC 7.3.0]
executable: /home/ubuntu/env37/bin/python
   machine: Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic

PROJ:
      PROJ: 6.1.0
  data dir: /home/ubuntu/env37/lib/python3.7/site-packages/pyproj/proj

Python deps:
    pyproj: 2.2.2
       pip: 19.2.2
setuptools: 41.0.1
    Cython: None
     aenum: (2, 1, 2)

#### Installation method

from source

**Comment by snowman2** [comment]
Your problem is access order and has been and probably will be a problem for many. It can resolved by either of these:
1. Swapping order of input to be latitude first
2. Using `always_xy` as an argument when transforming.

I would recommend reading:
- https://pyproj4.github.io/pyproj/stable/examples.html
- https://proj.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent
- https://pyproj4.github.io/pyproj/stable/api/transformer.html (at the top of the page)

**Comment by manthey** [comment]
Thank you very much.  I'm still surprised that the inclusion of `+init=` affects this.

**Comment by snowman2** [comment]
It is definitely an interesting change. I think this may help with understanding the difference:
https://gis.stackexchange.com/a/326919/144357

**Comment by manthey** [comment]
Thanks again; that helps clarify what is happening.

**Comment by snowman2** [comment]
Not a problem :+1:

**Comment by jorisvandenbossche** [comment]
It might be worth adding some of that content you answered on StackOverflow in the docs (or open an issue to do it, it might be a good starter issue)

**Comment by snowman2** [comment]
> It might be worth adding some of that content you answered on StackOverflow in the docs (or open an issue to do it, it might be a good starter issue)

That's a good idea. I had the thought to do that, but hearing that it might be useful elsewhere make me think making it more of a priority would be a good thing.

**Comment by manthey** [comment]
Part of my confusion was that `pyproj.Proj('epsg:4326') == pyproj.Proj('+init=epsg:4326')` even though `pyproj.Proj('epsg:4326').crs != pyproj.Proj('+init=epsg:4326').crs`.  I now understand how the comparisons are done and why this is the case, but it was part of why I was surprised earlier.
