### ISSUE TITLE
`pyproj.CRS.from_cf` deviates from CF standard guidelines

### ISSUE THREAD

**Issue by benjwadams** [pyproj4/pyproj#401]
#### Code Sample, a copy-pastable example if possible

```python
crs = pyproj.CRS.from_cf({'grid_mapping_name': "lambert_conformal_conic", 'standard_parallel': 25.0, 'longitude_of_central_meridian': 265.0, 'latitude_of_projection_origin': 25.0,
    'crs_wkt': """PROJCS["North_America_Lambert_Conformal_Conic",
       GEOGCS["GCS_North_American_1983",
           DATUM["North_American_Datum_1983",
               SPHEROID["GRS_1980",6378137,298.257222101]],
            PRIMEM["Greenwich",0],
            UNIT["Degree",0.017453292519943295]],
       PROJECTION["Lambert_Conformal_Conic_2SP"],
        PARAMETER["False_Easting",0],
         PARAMETER["False_Northing",0],
         PARAMETER["Central_Meridian",-96],
         PARAMETER["Standard_Parallel_1",20],
         PARAMETER["Standard_Parallel_2",60],
         PARAMETER["Latitude_Of_Origin",40],
         UNIT["Meter",1],
        AUTHORITY["EPSG","102009"]]"""})

print(crs.to_string())
```

> PROJCS["North_America_Lambert_Conformal_Conic",
>     GEOGCS["GCS_North_American_1983",
>         DATUM["North_American_Datum_1983",
>             SPHEROID["GRS_1980",6378137,298.257222101]],
>         PRIMEM["Greenwich",0],
>         UNIT["Degree",0.017453292519943295]],
>     PROJECTION["Lambert_Conformal_Conic_2SP"],
>     PARAMETER["False_Easting",0],
>     PARAMETER["False_Northing",0],
>     PARAMETER["Central_Meridian",-96],
>     PARAMETER["Standard_Parallel_1",20],
>     PARAMETER["Standard_Parallel_2",60],
>     PARAMETER["Latitude_Of_Origin",40],
>     UNIT["Meter",1],
>     AUTHORITY["EPSG","102009"]]

#### Problem description

http://cfconventions.org/cf-conventions/cf-conventions.html#use-of-the-crs-well-known-text-format mentions

> There will be occasions when a given CRS property value is duplicated in both a single-property grid mapping attribute and the crs_wkt attribute. In such cases the onus is on data producers to ensure that the property values are consistent. However, in those situations where two values of a given property are different, then the value specified by the single-property attribute shall take precedence. For example, if the semi-major axis length of the ellipsoid is defined by the grid mapping attribute semi_major_axis and also by the crs_wkt attribute (via the WKT SPHEROID[…​] element) then the former, being the more specific attribute, takes precedence. Naturally if the two values are equal then no ambiguity arises.

`pyproj.CRS.from_cf` instead looks for the `crs_wkt` attribute and if it is found, only returns the CRS generated from that.
https://github.com/pyproj4/pyproj/blob/ca68a2104db55bbf043ae2653f6f731a7a321c48/pyproj/crs.py#L602-L627

This contradicts the CF standard, which states that the individual, more specific parameters should override the `crs_wkt` values if there are differences between the two.

#### Environment Information

 - Output from: `python -c "import pyproj; pyproj.show_versions()"`
```
System:
    python: 3.6.5 (default, Apr 10 2018, 17:08:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
executable: /home/badams/.virtualenvs/cchecker_py3.6/bin/python
   machine: Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core

PROJ:
      PROJ: 6.1.0
  data dir: /home/badams/.virtualenvs/cchecker_py3.6/lib/python3.6/site-packages/pyproj/proj_dir/share/proj

Python deps:
    pyproj: 2.2.1
       pip: 19.2.2
setuptools: 41.1.0
    Cython: 0.29.12
     aenum: None
```

#### Installation method
 - conda, pip wheel, from source, etc...

`pip`

**Comment by snowman2** [comment]
Thanks for the report, we will definitely take this into consideration on future iterations. 

### Current design reasoning:
1. WKT strings are better than PROJ strings for fully representing a CRS [ref](https://proj4.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems).
2. To use the other parameters, we would have to drop the WKT representation and represent the CRS using PROJ parmeters. This could be lossy and not desirable.

### Potential solution:
Use PROJ JSON to modify the CRS with the specified parameters [PROJ JSON PR](https://github.com/OSGeo/PROJ/pull/1547). This will likely need to be a `2.4.0+` update and will need to use `PROJ 6.2.0` or the release that adds PROJ JSON.

**Comment by benjwadams** [comment]
I think it might be worthwhile to issue warnings in future versions.  Even though it's the behavior specified by CF, it might be good to notify the user that the CF grid mapping parameters are overriding what's been provided in the CRS WKT.

**Comment by snowman2** [comment]
This issue is blocked by:
- https://github.com/cf-convention/cf-conventions/issues/222
- #536

**Comment by snowman2** [comment]
@benjwadams, I attempted to make the CRS better represented by using the WKT form of the projection. However, if the CF version of the coordinate system is not properly able to be supported within `pyproj` itself then the WKT form will be more accurate. As things currently are, `pyproj` won't follow the convention mentioned in this issue as it would be unsafe to do so (see #536) .

That being said, I think adding a documentation page about how to be fully CF compliant in respect to this issue would be a good addition and will resolve this issue as sensibly as possible (i.e. how to build the coordinate system yourself and compare the CRS generated from the CF parameters versus the CRS generated from the WKT).

**Comment by snowman2** [comment]
Just had a CF breakout session & we all agreed upon the wording change: https://github.com/cf-convention/cf-conventions/issues/222#issuecomment-642827753

If accepted, that means that the current behavior of `pyproj` is acceptable.

**Comment by snowman2** [comment]
Closing with this comment: https://github.com/cf-convention/cf-conventions/issues/222#issuecomment-643267858
