### ISSUE TITLE
Undo global context

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#408]
Due to #403, I think the solution to #374, is to:
1. Undo: #376 
2. Use fix in PROJ: https://github.com/OSGeo/PROJ/pull/1566

**Comment by jorisvandenbossche** [comment]
The problem with this proposed solution is that it depends on a future release of PROJ, I think? (meaning, problem to solve it now. I don't know when a next PROJ release would occur, and that also would bump the minimal required version?)

**Comment by snowman2** [comment]
The version bump will be necessary for adding support for: 
https://github.com/OSGeo/PROJ/pull/1547

If this fix is merged in soon, the next PROJ release is scheduled for September 1.

**Comment by snowman2** [comment]
I haven't been able to to come up with a clean solution without the change in PROJ. But, if you think of one, I would be happy to give it a go.

**Comment by jorisvandenbossche** [comment]
> The version bump will be necessary for adding support for:
OSGeo/PROJ#1547

But that could be optional? Or is there a reason you need this in pyproj?

> I haven't been able to to come up with a clean solution without the change in PROJ.

Short term, it seems like choosing between segfaults on windows or crashes with many CRS objects? (although I didn't follow both closely) In the last release you fixed the second which caused the first, correct? It could also be chosen the other way around (but again, don't know which of the two affects most end-users)

**Comment by snowman2** [comment]
> But that could be optional? Or is there a reason you need this in pyproj?

Provide pathway to address #401 and #389

> It could also be chosen the other way around 

Yeah, I went ahead with it as is for 2.3.0 so there is at least one version with a fix in it for the second problem.  Next step in the plan is to  undo global context in 2.3.1 (to have fix for first problem) and then in 2.4.0 using the PROJ fix to resolve the second problem.

Side note: Looks like 2.3.0 works fine in windows with conda-forge. Just wheels have issues.

**Comment by snowman2** [comment]
One thought I had was to add an optional kwarg `context` when creating the Proj, CRS, Transformer objects. Then, a user could pass in their own `ContextManager`. This could allow for a semi-global context when many of the objects are being created. But, if it is not passed in, a new ContextManager is created in its stead.

This could be accomplished by making the `ContextManager` public:
https://github.com/pyproj4/pyproj/blob/master/pyproj/_datadir.pyx

This would provide a solution for both use cases and would not require pinning to the new version of PROJ yet. That being said, I am still thinking I might pin to the new version soon due to the new features included.
