### ISSUE TITLE
How can I convert large data with lat and long into X and Y?

### ISSUE THREAD

**Issue by DanAlz** [pyproj4/pyproj#430]
I have 9888562 records in dataframe and I would like to convert my lat, long to UTM x,y. according to my code, I have used pyproj package but because my data are too much it takes a long time and finally, it doesn't work. I wonder whether you know another way that I can use for my data?

def rule(row):
        p = Proj(proj='utm',zone=10,ellps='WGS84', preserve_units=False)
        x,y = p(row["LON"], row["LAT"])
        return pd.Series({"X": x , "Y": y})
My_data = My_data.merge(My_data.apply(rule, axis=1), left_index= True, right_index= True)

![my data](https://user-images.githubusercontent.com/51129237/64486215-602f5c80-d23f-11e9-9489-ce762ce18a49.JPG)

**Comment by jorisvandenbossche** [comment]
From my phone, so a bit brief, but: you can take a look at the Transformer class to speed up the conversion (it does not need to recompute the transformation for each pair of coordinates).

**Comment by snowman2** [comment]
Closing for preference to: https://gis.stackexchange.com/questions/334271/converting-large-data-with-lat-and-long-into-x-and-y

**Comment by snowman2** [comment]
For future reference,the most efficient method for you to transform the coordinates is probably to not use apply but to use the column array.

```python
from pyproj import Proj
pp = Proj(proj='utm',zone=10,ellps='WGS84', preserve_units=False)

xx, yy = pp(My_data["LON"].values, My_data["LAT"].values)
My_data["X"] = xx
My_data["Y"] = yy 
```
Using Transformer
```python
from pyproj import Transformer

trans = Transformer.from_crs(
    "epsg:4326",
    "+proj=utm +zone=10 +ellps=WGS84",
    always_xy=True,
)
xx, yy = trans.transform(My_data["LON"].values, My_data["LAT"].values)
My_data["X"] = xx
My_data["Y"] = yy
```
Also, I would recommend reading this about Proj: https://pyproj4.github.io/pyproj/stable/gotchas.html#proj-not-a-generic-latitude-longitude-to-projection-converter
