### ISSUE TITLE
Best way to get the polar radius

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#457]
I have a `geos` projection CRS object and I want to get the polar radius, but it seems like it is not computed.

```
Out[5]: 
<Projected CRS: +proj=geos +lon_0=-89.5 +a=6378137.0 +b=6356752.31 ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Geostationary Satellite (Sweep X)
Datum: unknown
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [6]: crs = scn['C01'].attrs['area'].crs
In [9]: crs.ellipsoid.semi_major_metre
Out[9]: 6378137.0

In [10]: crs.ellipsoid.semi_minor_metre
Out[10]: nan

In [11]: crs.ellipsoid.is_semi_minor_computed
Out[11]: False
```

Does `nan` mean it wasn't computed? How do I compute it? If this is a property can't it be computed when I ask for it?

**Comment by snowman2** [comment]
This is the method used to get the information: 
[proj_ellipsoid_get_parameters](https://proj.org/development/reference/functions.html?highlight=proj_ellipsoid_get_parameters#_CPPv429proj_ellipsoid_get_parametersP10PJ_CONTEXTPK2PJPdPdPiPd). The docstrings may help get closer to the answers.

**Comment by snowman2** [comment]
> Does nan mean it wasn't computed?

Nan is equivalent to NULL in the docs. So, not computed or in the definition.

> How do I compute it? If this is a property can't it be computed when I ask for it?

Not sure why it wasn't computed. I would ask the PROJ devs about the internal logic for `proj_ellipsoid_get_parameters`.

**Comment by snowman2** [comment]
Can this issue be closed?

**Comment by djhoese** [comment]
I thought I had created an issue for this or brought it up on gitter but now I can't find it. Let's close this here and if it becomes something that is inconvenient enough I'll make an issue with PROJ.

**Comment by snowman2** [comment]
Apologies - just had a huge :man_facepalming: moment when looking into this issue:
https://github.com/OSGeo/PROJ/issues/1842

**Comment by snowman2** [comment]
Fix coming soon.

**Comment by snowman2** [comment]
Workaround for older version is to use `_semi_minor_metre`, but I just removed it in the fix, so you will have to check for it.

**Comment by djhoese** [comment]
Thanks! Now if only I could remember where I wanted to use this... :thinking:
