### ISSUE TITLE
towgs84 parameter makes CRS unequal

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#459]
#### Code Sample, a copy-pastable example if possible

```python
p1 = '+ellps=GRS80 +lat_0=52 +lon_0=10 +no_defs +proj=laea +towgs84=0.0,0.0,0.0,0.0,0.0,0.0,0.0 +type=crs +units=m +x_0=4321000 +y_0=3210000'

p2 = '+ellps=GRS80 +lat_0=52 +lon_0=10 +no_defs +proj=laea +type=crs +units=m +x_0=4321000 +y_0=3210000'

from pyproj import CRS
CRS(p1) == CRS(p2)
# False

CRS(p1.replace('+towgs84=0.0,0.0,0.0,0.0,0.0,0.0,0.0', '')) == CRS(p2)
# True
```
#### Problem description

Would it be possible to consider something with an all 0 `towgs84` to be the same?

#### Expected Output

CRS objects would be equal.

#### Environment Information

pyproj 2.3.1 from conda-forge
proj4 6.1.1 from conda-forge

**Comment by snowman2** [comment]
This is all handled internally by PROJ. Would need to ask them if this makes sense to do.

**Comment by djhoese** [comment]
Darn, I thought that might be your answer.

**Comment by snowman2** [comment]
Looks like the issue has been raised in PROJ: https://github.com/OSGeo/PROJ/issues/1804
