### ISSUE TITLE
Installation failed on Juno for iPad — Installation from source failed

### ISSUE THREAD

**Issue by sjinko** [pyproj4/pyproj#468]
#### Installation method/steps
 - Installation method (conda, pip wheel, from source, etc...)
Juno PyPi package installer: https://juno.sh/juno-pypi-package-installer/

 - How did you install PROJ? Where is it installed?
Using the package installer from Juno app 1.1.0 for iPadOS.

 - Please provide all commands/steps you used to install pyproj and PROJ.
GUI installer

#### Environment Information
 - pyproj version you are attempting to install
2.4.0, 2.3.1, 2.0.0

 - PROJ version (Execute `proj` command and give version here.)
—

 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
Python 3.6.1

 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
iPadOS 13.1.1

**Comment by snowman2** [comment]
Unfortunately, there isn't much we can do here. On the link to the page it says:

> Due to platform restrictions, only pure Python packages are supported — i.e. those that consist exclusively of .py files. 


pyproj is a wrapper for the c/c++ PROJ code, so it doesn't fit that requirement.

I would recommend raising an issue with the Juno project.
