### ISSUE TITLE
2.4.1 version installation with pip does not work

### ISSUE THREAD

**Issue by eeromakiesko** [pyproj4/pyproj#478]
#### Installation method/steps
Installation with pip inside docker container does not work.
pip install pyproj

produces:
Collecting pyproj (from geopandas==0.4.1->-r /requirements_php.txt (line 5))
  Downloading ... (462kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Proj executable not found. Please set PROJ_DIR variable.

This was done inside docker base image:
php:7.3-apache

#### Environment Information
 - pyproj 2.4.1 fails 2.4.0 works fine
 - Python version 3.7
 - Operation System Information docker image php:7.3-apache (alpine based linux)

**Comment by snowman2** [comment]
Likely related to #477. pyproj 2.4.1 uses manylinux 2010 wheels, so I would recommend upgrading your version of pip.

**Comment by snowman2** [comment]
Closing as I am pretty sure it is related to #477

**Comment by snowman2** [comment]
Thanks for the report!

**Comment by eeromakiesko** [comment]
We had this version of pip:
root@1982bb943622:/# python -m pip --version
pip 19.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
root@1982bb943622:/# python -m pip install -U pip
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (19.3.1)

So I doubt that is the root cause.

**Comment by jorisvandenbossche** [comment]
You are using Alpine linux (from the base docker image), and for that platform, there are no binary wheels. This means it will try to install pyproj from source, but that also means that you will need to install PROJ in advance I assume.

**Comment by eeromakiesko** [comment]
Got it working by upgrading pip, thanks.
