### ISSUE TITLE
Raspbian wheel/improved install instructions

### ISSUE THREAD

**Issue by proximous** [pyproj4/pyproj#480]
It would be nice if you could offer a Raspbian wheel.

Barring that, it would be nice if you could update your install instructions to indicate that when installing from pip without a wheel, PROJ needs to be installed and a reference to https://proj.org/install.html provided. 

It would also be nice for a clearer error message about this. I got:

>ERROR: ...
  Proj executable not found. Please set PROJ_DIR variable.

Prehaps something like:
>ERROR: ...
  Proj executable not found. Please install Proj (https://proj.org/install.html) and/or set PROJ_DIR variable.

Further, it would also be nice to list the PROJ version compatibility for the different pyproj releases. After running `apt install proj-bin`, my `pip install pyproj` still failed with:
>ERROR: Minimum supported proj version is 6.2.0, installed version is 4.9.3.

It took a bit of digging through commits to find that I needed `pip install pyproj==1.9.6` for compatibility with 4.9.3. Some simple compatibility chart would be nice.

Anyway, not complaints. Just hoping to inspire some enhanced install instructions to help others with this.

**Comment by snowman2** [comment]
> It would be nice if you could offer a Raspbian wheel.

Sounds useful. Are you familiar with how to generate one?

For reference, here are the current installation instructions:
https://pyproj4.github.io/pyproj/stable/installation.html


Compatibility Matrix:
PROJ <= 5.2, pyproj <= 1.9.6
PROJ 6.0+, pyproj 2.0-2.1
PROJ 6.1+, pyproj 2.2-2.3
PROJ 6.2+, pyproj 2.4+

All good ideas. Would you like to update the docs with this information?

**Comment by snowman2** [comment]
> It would be nice if you could offer a Raspbian wheel.

Looks like they have them here: https://www.piwheels.hostedpi.com/project/pyproj/ for pyproj 1.9.6. However. it looks like builds failed for pyproj 2+ on their wheel page. Submitted an issue: https://github.com/piwheels/packages/issues/60

**Comment by proximous** [comment]
Wow! I didn't even realize I was using piwheels. Thanks for pointing that out and filing the issue!

**Comment by snowman2** [comment]
> Thanks for pointing that out and filing the issue!

Not a problem. Thanks for the suggestions!

**Comment by snowman2** [comment]
Closing for preference to the piwheels issue.
