### ISSUE TITLE
to_epsg() returning `None` in `2.4.1` but same code worked for `2.4.0`

### ISSUE THREAD

**Issue by koshy1123** [pyproj4/pyproj#483]
#### Code Sample, a copy-pastable example if possible

I'm trying to upgrade from pyproj `2.4.0` to `2.4.1` and I see this odd behavior. In `2.4.0`, this works:

```python
>>> import pyproj
>>> test_crs = {'init': 'epsg:4326', 'no_defs': True}
>>> pyproj.crs.CRS.from_dict(test_crs).to_epsg()
4326
```
But in `2.4.1`, I'm getting a `None` for `to_epsg()`

#### Problem description

I needed this roundtrip so that I can use it in a function that takes a geodataframe's `crs` dict attribute and get an EPSG code from it.

#### Environment Information

 - Output from: `python -m pyproj -v`
```
pyproj info:
    pyproj: 2.4.1
      PROJ: 6.2.1
  data dir: /usr/local/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.7.5 (default, Oct 19 2019, 00:03:48)  [GCC 8.3.0]
executable: /usr/local/bin/python
   machine: Linux-4.19.76-linuxkit-x86_64-with-debian-10.1

Python deps:
       pip: 19.3.1
setuptools: 41.4.0
    Cython: 0.29.14
```

#### Installation method
 - pip

**Comment by snowman2** [comment]
I am surprised it used to work. I don't think it should have. See:

https://pyproj4.github.io/pyproj/stable/gotchas.html#why-does-the-epsg-code-return-when-using-epsg-xxxx-and-not-with-init-epsg-xxxx

**Comment by koshy1123** [comment]
Gotcha! Is there a recommended path to grab a `gdf`'s crs and get an EPSG from it then? Reading the gotcha, it seems like I have to set the minimum confidence way down to 20, but that seems counterintuitive when the EPSG code is defined for that one.

I'm closing the underlying issue since it's addressed by documentation.

**Comment by snowman2** [comment]
The good news is that it will be less of an issue after geopandas adds: https://github.com/geopandas/geopandas/issues/1003

In the meantime, this should help. Apologies for the poor formatting (on phone):
```
            epsg_code = None
		            if "init=epsg" in self._crs.to_string().lower():
		                epsg_code = self._crs.to_epsg(0)
		            else:
		                epsg_code = self._crs.to_epsg(100)
		            if epsg_code is not None:
		                proj_dict = {
		                    "init": "epsg:{}".format(epsg_code),
		                    "no_defs": True,
		                }
```
