### ISSUE TITLE
HARN projection round trip yields a non-HARN based projection

### ISSUE THREAD

**Issue by koshy1123** [pyproj4/pyproj#488]
This may be solved when `geopandas` migrates to using `pyproj`'s CRS class (Looking forward to it!: https://github.com/geopandas/geopandas/pull/1101) but I wanted to make sure this isn't a bug.

While migrating our codebase to consistently use `pyproj`'s CRS class for all projection instances, I noticed this odd rountrip issue with a HARN-based DC projection ([EPSG:2926](http://epsg.io/2926)). On the round trip from `dict` to an integer EPSG code, I get [EPSG:2285](http://epsg.io/2285) which is a non-HARN based datum. 

```
>> gdf.crs
{'init': 'epsg:2926', 'no_defs': True}
>> CRS.from_dict(gdf.crs).to_epsg()
2285
```

To me, this looks like a bug but wanted to see if others have thoughts.

Using `pyproj` version 2.3.1

**Comment by snowman2** [comment]
Your question can be answered in part by:
https://pyproj4.github.io/pyproj/stable/gotchas.html#why-does-the-epsg-code-return-when-using-epsg-xxxx-and-not-with-init-epsg-xxxx

When creating the CRS with `+nodefs` it seems to make PROJ interprets it as a PROJ string instead of the EPSG code.

Here is an example of different methods to initialize a CRS with the EPSG code:
```python
>>> from pyproj import CRS
>>> cc = CRS('+init=epsg:2926 +nodefs')
>>> cc
<Projected CRS: +init=epsg:2926 +nodefs +type=crs>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (US survey foot)
- N[north]: Northing (US survey foot)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Lambert Conic Conformal (2SP)
Datum: Unknown based on GRS80 ellipsoid
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

>>> cc.to_epsg(100)
>>> cc.to_epsg(70)
2285
>>> cc = CRS('+init=epsg:2926')
>>> cc
<Projected CRS: EPSG:2926>
Name: NAD83(HARN) / Washington North (ftUS)
Axis Info [cartesian]:
- E[east]: Easting (US survey foot)
- N[north]: Northing (US survey foot)
Area of Use:
- name: USA - Washington - SPCS83 - N
- bounds: (-124.79, 47.08, -117.02, 49.05)
Coordinate Operation:
- name: SPCS83 Washington North zone (US Survey feet)
- method: Lambert Conic Conformal (2SP)
Datum: NAD83 (High Accuracy Reference Network)
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

>>> cc.to_epsg(100)
2926
>>> cc = CRS('epsg:2926')
>>> cc
<Projected CRS: EPSG:2926>
Name: NAD83(HARN) / Washington North (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: USA - Washington - SPCS83 - N
- bounds: (-124.79, 47.08, -117.02, 49.05)
Coordinate Operation:
- name: SPCS83 Washington North zone (US Survey feet)
- method: Lambert Conic Conformal (2SP)
Datum: NAD83 (High Accuracy Reference Network)
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

>>> cc.to_epsg(100)
2926
```

So, until `geopandas` migrates to using the `pyproj.CRS` class directly, I would recommend initializing the `pyproj.CRS` by doing:
```python
CRS.from_user_input(gdf.crs["init"] if "init" in gdf.crs else gdf.crs)
```
Reason: https://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code

Version information:
```
>>> from pyproj import show_versions; show_versions()
pyproj info:
    pyproj: 2.4.1
      PROJ: 6.2.1
  data dir: /home/snowal/scripts/pyproj/pyproj/proj_dir/share/proj

System:
    python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
executable: /home/snowal/miniconda/envs/pyproj/bin/python
   machine: Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid

Python deps:
       pip: 19.2.3
setuptools: 41.2.0
    Cython: 0.29.13
```

Hopefully that helps.

**Comment by koshy1123** [comment]
Got it - thanks for the pointer. I'm closing this one out.
