### ISSUE TITLE
Pyproj 2.4.2[.post1] causes odd multiprocessing error

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#494]
Satpy has recently started crashing and I'm trying to narrow it down. It only happens on python 3.8 from what I can tell so far, but could be simply related to pyproj 2.4.2 and the old python 3.7 environments we have not being updated (like I said still investigating).

This could also be related to how conda-forge is combining the 2.4.2 builds with other libraries but as far as I can tell the only differences between a python 3.8 environment that works and a python 3.8 environment that doesn't is pyopenssl, ipython, and pyproj. Forcing pyproj to 2.4.1 fixes our tests.

Originally working test: https://travis-ci.org/pytroll/satpy/jobs/619073023?utm_medium=notification&utm_source=slack

Failing test (pyproj 2.4.2.post1 from conda-forge): https://travis-ci.org/pytroll/satpy/jobs/619335006?utm_medium=notification&utm_source=slack

Passing test (pyproj 2.4.1 forced from conda-forge): https://travis-ci.org/pytroll/satpy/jobs/619350332

I am having the user who originally reported the issue test out the pip version of pyproj along with the dependencies installed from conda-forge (those pinned to pyproj 2.4.1).

```
Exception ignored in: <function Pool.__del__ at 0x7fd6472faa60>

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__

  File "/home/travis/miniconda/envs/test/lib/python3.8/multiprocessing/queues.py", line 362, in put

AttributeError: 'NoneType' object has no attribute 'dumps'
```

Any idea if there is anything that changed in 2.4.2 or 2.4.2.post1 that may have caused these issues?

**Comment by djhoese** [comment]
Comparing the dependencies installed (from one of the conda install commands), the only package different is the pyproj 2.4.1 (in the passing environment) going to pyproj 2.4.2 (in the failing environment).

**Comment by djhoese** [comment]
Ok interestingly, it seems that the above traceback shows up in both passing and failing environments. The failing environment is caused by something else which I'm looking at now. These failing tests may still be related to pyproj but the exception above seems to be something else. Ugh this is going to be fun.

**Comment by djhoese** [comment]
Ok, here is the actual bug related to pyproj:

```
from pyproj import Proj
proj_dict = {'a': '6378137.0', 'b': '6356752.31414', 'h': '35786023.0', 'lon_0': '-89.5', 'proj': 'geos', 'sweep': 'x', 'units': 'm'}
p = Proj(proj_dict)
p(-5434894.954752679, -5434894.964451744)
# 2.4.1 => (1e+30, 1e+30)
# 2.4.2.post1 => (inf, inf)
```

**Comment by snowman2** [comment]
That was intentional: https://github.com/pyproj4/pyproj/pull/491

It was to make it consistent with the `Transformer` and so you get what was actually returned by PROJ.

**Comment by djhoese** [comment]
Ah ok, great. Is HUGE_VAL defined PROJ/pyproj-wide or is it per-projection?

Also, this seems like a really big change to make in a patch release.

**Comment by snowman2** [comment]
> Is HUGE_VAL defined PROJ/pyproj-wide or is it per-projection?

It is defined in `math.h`:
https://github.com/pyproj4/pyproj/blob/565475313fdc6ae79344853b7fba751b01258d2c/pyproj/base.pxi#L7-L9

> this seems like a really big change to make in a patch release.

Ha. It could be argued either way :).

From my perspective it was a bugfix. Now it is consistent with the Transformer:
```python
>>> from pyproj import CRS, Transformer
>>> proj_dict = {'a': '6378137.0', 'b': '6356752.31414', 'h': '35786023.0', 'lon_0': '-89.5', 'proj': 'geos', 'sweep': 'x', 'units': 'm'}
>>> cc = CRS(proj_dict)
>>> tr = Transformer.from_crs(cc.geodetic_crs, cc)
>>> tr.transform(-5434894.954752679, -5434894.964451744)
(inf, inf)
```

> do I need to worry about other non-inf values showing up for different projections?

It is not projection specific. The `1.e30` was specific to `pyproj` before for any projection.

**Comment by djhoese** [comment]
Ok, good. I think this should only require a few changes in some of my code where for some reason I was doing `==`.

As for the patch change, I think the distinction is that this was accepted and expected behavior for all previous versions of pyproj and now a bug fix has changed it.

**Comment by snowman2** [comment]
Other than tests, did the change break other parts of your code?

**Comment by djhoese** [comment]
I had one piece of code that I've found so far that was doing `val == 1e30` instead of doing something like `>=`. In this case this code would not have found the invalid value and would have used the `inf`as a valid coordinate. It looks like in most of satpy and pyresample we were doing the more correct comparison of `>= 1e30`.

**Comment by snowman2** [comment]
I see. I didn't realize that y'all were depending on `1e30` in your code. Glad to hear that there is a simple fix. I think this issue should remain open to remind me to add a test based on the example you have for the returned values from calling `Proj`.

**Comment by djhoese** [comment]
It looks like the remaining test failures were caused by the new UserWarnings and having tests that are verifying that certain warnings were being raised and not expecting these new ones.

There may be other issues that users have brought up but I think I've figured out all of the issues now. Thanks again.
