### ISSUE TITLE
Wrong coordinates computed if the 'init=' string if removed in pyproj.Proj() definitions

### ISSUE THREAD

**Issue by swiss-knight** [pyproj4/pyproj#504]
I encountered wrong coordinates computed with `shapely.ops.transform()` when given a partial with `pyproj.transform()` if the `'init='` string if removed from `pyproj.Proj()` definitions.

(
If I let the "init=" prefix, I meet this warning, that why I way trying to remove it:    
```/usr/local/lib/python3.6/dist-packages/pyproj/crs.py:422: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.```
)

I'm not 100% sure it's a `pyproj` issue, if not, please let me know.

Here is a complete example:

#### Code Sample, a copy-pastable example if possible

```python
from shapely.geometry import Point
import shapely.ops as sp_ops
import pyproj
import functools
init_str = 'init='
scrs = 4326 # EPSG code (from)
tcrs = 21781 # EPSG code (to)
if False: # Set to True to run the experiment. 
    init_str = ''

project = functools.partial(pyproj.transform, 
                            pyproj.Proj(init_str+'EPSG:'+str(scrs)),
                            pyproj.Proj(init_str+'EPSG:'+str(tcrs)))
#print(project)

my_point_wgs84 = (8.839914681035225, 46.669436346362076, 2388.378981723203)
geom = Point(my_point_wgs84)
geom_transformed = sp_ops.transform(project, geom)
print(geom_transformed.x, geom_transformed.y, geom_transformed.z)

```
#### Problem description
If the `If` trigger is set to False, the output is:
`707227.4416038939 169646.7022298526 2388.378981723203`
Which is what I expect.

If the `If` trigger is set to True, the output computed position is wrong:
`5554005.956645905 -2908770.7917148615 2388.378981723203`

#### Expected Output
`707227.4416038939 169646.7022298526 2388.378981723203`

#### Environment Information
Ubuntu 18.04 64 bit: `5.0.0-37-generic x86_64 GNU/Linux`
Python: `3.6.9 (default, Nov  7 2019, 10:44:02)`
pyproj: `'2.4.2.post1'`

 - Output from: `python3 -m pyproj -v`
```
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
  data dir: /usr/local/lib/python3.6/dist-packages/pyproj/proj_dir/share/proj

System:
    python: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
executable: /usr/bin/python3
   machine: Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic

Python deps:
       pip: 19.3.1
setuptools: 41.2.0
    Cython: 0.26.1

```

 - pyproj version (`python3 -c "import pyproj; print(pyproj.__version__)"`)
`2.4.2.post1`

 - PROJ version (`python3 -c "import pyproj; print(pyproj.proj_version_str)"`)
`6.2.1`

 - PROJ data directory (`python3 -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
`/usr/local/lib/python3.6/dist-packages/pyproj/proj_dir/share/proj`

 - Python version (`python3 -c "import sys; print(sys.version.replace('\n', ' '))"`)
`3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
`
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
`Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic`

#### Installation method
pip

**Comment by snowman2** [comment]
I believe you need to set the kwarg `always_xy=True` when creating the transform.

I would recommend reading:
- https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
- https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1

**Comment by snowman2** [comment]
Based on your expected output, I confirmed that is the case.

EPSG:4326 expects data in the latitude, longitude order. But, you are inputting it in the old form of longitude, latitude. This gives the incorrect results:
```python
>>> from pyproj import Transformer
>>> trans = Transformer.from_crs(4326, 21781)
>>> trans.transform(8.839914681035225, 46.669436346362076, 2388.378981723203)
(5554005.956645905, -2908770.7917148615, 2388.378981723203)
```
However, if you swap it to latitude, longitude you get the expected results:
```python
>>> trans.transform(46.669436346362076, 8.839914681035225, 2388.378981723203)
(707227.4416038939, 169646.7022298526, 2388.378981723203)
```
You can also use the `always_xy` argument to swap it back to longitude, latitude order:
```python
>>> trans = Transformer.from_crs(4326, 21781, always_xy=True)
>>> trans.transform(8.839914681035225, 46.669436346362076, 2388.378981723203)
(707227.4416038939, 169646.7022298526, 2388.378981723203)
```
Good luck!

**Comment by swiss-knight** [comment]
Thanks for the rich explanation, I was stuck with a right-pointing x-axis and the y-axis as the north direction, that's why I always think in the form of (long,lat) point when dealing with WGS84 points.

**Comment by snowman2** [comment]
Not a problem 👍. You are definitely one of many who have run into this and I am sure won't be the last one.
