### ISSUE TITLE
Conversion from EPSG:2451 is not correct

### ISSUE THREAD

**Issue by Isa-rentacs** [pyproj4/pyproj#537]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
>>> from pyproj import Proj, transform
>>> p = Proj("epsg:2451")
>>> p
Proj('+proj=tmerc +lat_0=36 +lon_0=139.833333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs', preserve_units=True)
>>> p2 = Proj("+proj=tmerc +lat_0=36 +lon_0=139.8333333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
>>> p_to = Proj("epsg:4326")
>>> transform(p, p_to, -7000, -35000)
(35.93628025299981, 139.44542437678555)
>>> transform(p2, p_to, -7000, -35000)
(35.68450348643748, 139.7559958666358)
```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

According to https://epsg.io/2451, The Proj4 definition for epsg:2451 is
```
+proj=tmerc +lat_0=36 +lon_0=139.8333333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```
However, when I instantiate a proj as ```p = Proj("epsg:2451")```, it shows
```
+proj=tmerc +lat_0=36 +lon_0=139.833333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs
```
and ```+towgs84=0,0,0,0,0,0,0``` part is missing, which ended up with wrong lat/long after the conversion to epsg:4326.

#### Expected Output
```Proj("epsg:2451")``` creates a Proj object with the correct definition.

#### Environment Information

 - Output from: `python -m pyproj -v`
```
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
```

#### Installation method
 - conda, pip wheel, from source, etc...
  * pip
    * pip install pyproj

**Comment by jorisvandenbossche** [comment]
If you use `CRS` instead of `Proj`, you get:

```
>>> import pyproj
>>> p = pyproj.CRS("epsg:2451")
>>> p_to = pyproj.CRS("epsg:4326")  
>>> transformer = pyproj.Transformer.from_crs(p, p_to, always_xy=True) 
>>> transformer.transform(-7000, -35000)                                                                                                                                                                      
(139.7559958666358, 35.68450348643748)
```

which is similar to your second output (which you think is the correct one?)

The `Proj` object / proj4 string is not optimal to describe a CRS (eg it misses datum information). I don't recall exactly the reasons, but as you noticed, the towgs84 field is now not always present in the proj4 string when converting an EPSG code to proj4 string / Proj object.

**Comment by Isa-rentacs** [comment]
Thanks @jorisvandenbossche for your comment. 
Understood the difference, I will use CRS instead of using ```Proj``` directly.

**Comment by Isa-rentacs** [comment]
Sorry for re-opening this issue, please let me confirm one more thing.
I passed the same CRS object to create transformer, but the transformed coordinates are different with and without ```always_xy```. Is this still an expected (or known) behavior? I thought the option was simply to swap the axis.
```
>>> p = pyproj.CRS("epsg:2451")
>>> p_to = pyproj.CRS("epsg:4326")
>>> t = pyproj.Transformer.from_crs(p, p_to)
>>> t.transform(-7000, -35000)
(35.93628025299981, 139.44542437678555)
>>> t = pyproj.Transformer.from_crs(p, p_to, always_xy=True)
>>> t.transform(-7000, -35000)
(139.7559958666358, 35.68450348643748)
```

**Comment by jorisvandenbossche** [comment]
Yes, that is expected. The EPSG:4326 has officially a (lat, lon) axis order (thus (y, x)). With `always_xy=True`, it is ensure the output is still in (lon, lat) / (x, y) order, otherwise it depends on the axis order of the CRS (which in this case is (lat, lon)).

**Comment by snowman2** [comment]
It seems the values are slightly different in each scenario if you take into account the swapping. I think this issue should remain open for investigation.

**Comment by jorisvandenbossche** [comment]
Whoops, I didn't notice it was about that. That looks indeed fishy

**Comment by snowman2** [comment]
Forwarding to: https://github.com/OSGeo/PROJ/issues/1961

**Comment by snowman2** [comment]
@Isa-rentacs, thanks to the help of @rouault in the PROJ issue, I have the reasoning for you.

If you look at the CRS for `EPSG:2451`, you will notice that it has the `north` coordinate first:
```python
>>> from pyproj import CRS, Transformer
>>> p = CRS("EPSG:2451")
>>> p
<Projected CRS: EPSG:2451>
Name: JGD2000 / Japan Plane Rectangular CS IX
Axis Info [cartesian]:
- X[north]: Northing (metre)
- Y[east]: Easting (metre)
Area of Use:
- name: Japan - zone IX
- bounds: (138.4, 29.31, 141.11, 37.98)
Coordinate Operation:
- name: Japan Plane Rectangular CS zone IX
- method: Transverse Mercator
Datum: Japanese Geodetic Datum 2000
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```
This is also the same for `EPSG:4326`:
```
>>> p_to = CRS("EPSG:4326")
>>> p_to
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
This means that when you don't have `always_xy=True` set, the transformation expects the `north` coordinate first as input and will output the `north` coordinate first: 
```
>>> transformer = Transformer.from_crs(p, p_to)
>>> transformer.transform(-35000, -7000)
(35.68450348643748, 139.7559958666358)
```
This result is consistent with the result with `always_xy=True` activated and you put the `east` coordinate first:
```python
>>> transformer = Transformer.from_crs(p, p_to, always_xy=True)
>>> transformer.transform(-7000, -35000)
(139.7559958666358, 35.68450348643748)
```

It was not immediately obvious that the input coordinates were switched since the output was so close in that scenario.
