### ISSUE TITLE
Incorrect Transformation depending on initialisation on Proj EPSG:4326

### ISSUE THREAD

**Issue by system123** [pyproj4/pyproj#542]
```python
import pyproj

pyproj.transform(pyproj.Proj({"init":"EPSG:4326"}), pyproj.Proj("EPSG:32617"), -76.41920282446627, 43.03112479318123)
>> /lib/python3.7/site-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))
>> (873212.4112437204, 4774463.236922473)

pyproj.transform(pyproj.Proj("EPSG:4326"), pyproj.Proj("EPSG:32617"), -76.41920282446627, 43.03112479318123)
>> (1760709.0560872303, -10857425.102759218)
```
#### Problem description
Depending on how I initialize the 4326 CRS I get different results for the projection of a point in EPSG:4326 to UTM EPSG:32617. The result of the old initialization is correct, while using the new/preferred method yields an incorrect transformation.

#### Expected Output
```>> (873212.4112437204, 4774463.236922473)```

#### Environment Information
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
  data dir: /Users/lloyd/anaconda3/envs/torch/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.7.5 (default, Oct 25 2019, 10:52:18)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /Users/lloyd/anaconda3/envs/torch/bin/python
   machine: Darwin-16.7.0-x86_64-i386-64bit

Python deps:
       pip: 19.3.1
setuptools: 42.0.2.post20191203
    Cython: None

#### Installation method
 - conda, pip wheel, from source, etc...

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
proj                      6.2.1                hfd5b9e3_0  
pyproj                    2.4.2.post1              pypi_0    pypi
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : torch
    active env location : /Users/lloyd/anaconda3/envs/torch
            shell level : 1
       user config file : /Users/lloyd/.condarc
 populated config files : 
          conda version : 4.8.0
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __osx=10.12.6
       base environment : /Users/lloyd/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/lloyd/anaconda3/pkgs
                          /Users/lloyd/.conda/pkgs
       envs directories : /Users/lloyd/anaconda3/envs
                          /Users/lloyd/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.6.8 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by snowman2** [comment]
This is expected, see: https://github.com/pyproj4/pyproj/issues/538
