### ISSUE TITLE
Keyword arguments to Proj() are silently ignored when projparams are specified

### ISSUE THREAD

**Issue by gberardinelli** [pyproj4/pyproj#552]
I came across this when trying to initialize a `Proj()` and include `geoidgrids`:

```
proj = pyproj.Proj('EPSG:3162', geoidgrids='CGG2013an83.gtx')
proj.crs.is_vertical
>>> False
```

This is confusing.  Why is it not taking my geoidgrids?  Did I get the file name/path wrong?

Turns out the positional argument `projparams` is mutually exclusive with any passed `**kwargs`:

https://github.com/pyproj4/pyproj/blob/632c39818e77f8226bbec0db2a3fbe7fc02f7d33/pyproj/proj.py#L143

Yet there is no indication that this is not a valid way to initialize it.

In my opinion it should throw an exception, and it could perhaps be made clearer in the documentation as well.  It's a minor user experience thing, but still something I had to spend time troubleshooting.  Happy to attempt a PR if others agree.

[(stackexchange thread that spawned this)](https://gis.stackexchange.com/q/352277/64255)

**Comment by snowman2** [comment]
> Happy to attempt a PR if others agree.

I think that would be a nice addition. A PR would be welcome 👍

**Comment by snowman2** [comment]
@gberardinelli are you still interested in attempting this fix?

**Comment by gberardinelli** [comment]
Thanks for the reminder, proposed my dinky lil' change with https://github.com/pyproj4/pyproj/pull/570

I wasn't sure if it would be appropriate to attempt to merge projparams and kwargs, but that could be another option if so (within the CRS object?)

**Comment by snowman2** [comment]
Thanks for getting started on this :+1:

> I wasn't sure if it would be appropriate to attempt to merge projparams and kwargs, but that could be another option if so (within the CRS object?)

It wouldn't hurt. If it is invalid, PROJ will raise an exception. So, if you would like to make that change, I would do it in the `CRS.__init__` method.

**Comment by gberardinelli** [comment]
I gave it a shot but I'm not really sure what I'm doing at this point, feels a bit kludgey.  Tests in `test_proj` all pass...

**Comment by snowman2** [comment]
Looks good. Mind adding a test for the CRS class as well?
