### ISSUE TITLE
transform yielding different results for same Proj parameters

### ISSUE THREAD

**Issue by moon63** [pyproj4/pyproj#556]
#Issue:

Python    3.7.3
IPython   7.4.0
pyproj     2.5.0 [PROJ verion: 6.3.1]

Not sure what I'm doing wrong but I'm trying to convert longlat Nad83 to KY State Plane South Nad83.  If set the input Prog to pyproj.Proj(proj='longlat', datum ='NAD83') I get a different result than if I set it to pyproj.Proj('epsg:4269').  These should be the same and when i print them out , the are the same.  However I'm getting much different results.

#Code:

import pyproj

inProj1        = pyproj.Proj(proj='longlat', datum ='NAD83')     
inProj2        = pyproj.Proj('epsg:4269')      

outProj  = pyproj.Proj("epsg:6474") 
   
print('\ninProj1 = ',inProj1,'\ninProj2 = ',inProj2)
    
long, latt = -83.88259259, 36.49333333

x1,y1 = pyproj.transform(inProj1, outProj ,long ,latt)
x2,y2 = pyproj.transform(inProj2, outProj ,long ,latt)
    
print('\nx1 = ', x1, 'y1 = ', y1,
      '\nx2 = ', x2, 'y2 = ', y2)

#Results:  

inProj1 =  Proj('+proj=longlat +datum=NAD83 +no_defs', preserve_units=True) 
inProj2 =  Proj('+proj=longlat +datum=NAD83 +no_defs', preserve_units=True)

x1 =  667315.2681430576 y1 =  519409.6151513982           
x2 =  72927331.14729036 y2 =  -11599224.291812904

**Comment by snowman2** [comment]
@moon63, you are running into axis order changes introduced with PROJ 6:

Traditionally, the order has been east(x) north(y) as shown in the PROJ param version:
```python
>>> from pyproj import CRS
>>> CRS("+proj=longlat +datum=NAD83")
<Geographic 2D CRS: +proj=longlat +datum=NAD83 +type=crs>
Name: unknown
Axis Info [ellipsoidal]:
- lon[east]: Longitude (degree)
- lat[north]: Latitude (degree)
Area of Use:
- undefined
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```
But, in the EPSG version, it is North(y), East(x) order:
```python
>>> CRS("EPSG:4269")
<Geographic 2D CRS: EPSG:4269>
Name: NAD83
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: North America - NAD83
- bounds: (167.65, 14.92, -47.74, 86.46)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```
So, if you want it to give the correct output, either:

1. Switch the order of input:
```python
>>> transformer = Transformer.from_crs("EPSG:4269", "epsg:6474")
>>> long, latt = -83.88259259, 36.49333333
>>> transformer.transform(latt, long)
(667315.2681430576, 519409.6151513982)
```
2. Use `always_xy`:
```python
>>> transformer_xy = Transformer.from_crs("EPSG:4269", "epsg:6474", always_xy=True)
>>> transformer_xy.transform(long, latt)
(667315.2681430576, 519409.6151513982)
```

**Comment by snowman2** [comment]
I would also recommend reading:
https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6

**Comment by moon63** [comment]
Thanks for the quick response.
