### ISSUE TITLE
numpy.bool_ comparison yields incorrect results

### ISSUE THREAD

**Issue by jranalli** [pyproj4/pyproj#564]
#### Code Sample, a copy-pastable example if possible
```python
from pyproj import Proj  # pyproj 2.5.0
import numpy as np  # numpy 1.18.1

south = np.array(50) < 0

p = Proj(proj='utm', zone=32, ellipsis='WGS84', datum='WGS84', units='m', south=south)
print(p)
```
Outputs
```Proj('+proj=utm +zone=32 +south +datum=WGS84 +units=m +no_defs', preserve_units=True)```

#### Problem description

When passing numpy.bool_(False) to Proj( ... ,south=south), it activates the south flag anyway. I believe this relates to [CRS.py Line 51-56](https://github.com/pyproj4/pyproj/blob/65105c8f5e8ac76dcca5a19c8e227c9c2eb0fd19/pyproj/crs/crs.py#L51). I think this is because comparing numpy.bool_ types with ```is``` [results in unexpected results](https://github.com/numpy/numpy/issues/5942). 

#### Expected Output
No +south flag
``Proj('+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs', preserve_units=True)``

#### Environment Information
```python
    pyproj: 2.5.0
      PROJ: 6.3.1
  data dir: <>

System:
    python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
executable: <>
   machine: Windows-10-10.0.17763-SP0

Python deps:
       pip: 19.2.3
setuptools: 41.2.0
    Cython: 0.29.15

```
#### Installation method
 - pip wheel

**Comment by snowman2** [comment]
Interesting. Will need to think on this since we don't use `numpy` directly as a dependency.

I would recommend doing this in the meantime:
```python
>>> south = (np.array(50) < 0).item()
>>> type(south)
<class 'bool'>
>>> south is True
False
```

**Comment by jranalli** [comment]
It works with casting as well: ```bool(np.bool_(False))```

I thought about this all through dinner and maybe came up with a solution. This evaluates True for both bool representations at question here (and hopefully any other random reimplementations of False):
```53: if str(value) == 'False'```

The only bad outcome I could think of was if somehow the user entered a parameter value that was a string 'False'. You could check for that by testing if the string representation is equal to the value itself. This would also catch weird string types like a numpy array housing a string:

```53: if not str(value) == value and str(value)=='False':```

**Comment by snowman2** [comment]
That sounds like a good implementation to me. False isn't used by PROJ as far as I know, so catching the string version should be fine. If you would like to submit a PR, that would be helpful, but not required. Just let me know. Either way, I will add this to the 2.6 release.
