### ISSUE TITLE
problem pip installing under msys2

### ISSUE THREAD

**Issue by tjwilli58** [pyproj4/pyproj#579]
#### Installation method/steps
 - Installation method: pip
   I also tried downloading the wheel from [ Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj)  , but  I got

`ERROR: pyproj-2.6.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.`

- How did you install PROJ? Where is it installed?
I didn't. I was hoping pip would handle that.

 - Please provide all commands/steps you used to install pyproj and PROJ.

`pip install pyproj --no-color`

#### Environment Information
 - pyproj version you are attempting to install
2.6.0
 - PROJ version (Execute `proj` command and give version here.)

 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
`3.7.4 (default, Aug 15 2019, 18:17:27)  [GCC 9.2.0 64 bit (AMD64)]`
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
```
$ python -c "import platform; print(platform.platform())"
Windows-10-10.0.18362-SP0
```

Result of pip install:

```
$ pip install pyproj --no-color
Collecting pyproj
  Using cached https://files.pythonhosted.org/packages/c0/c2/8c7f27e57835782563715970ec73da41dffc5bb93622f86cc7c3626a9317/pyproj-2.6.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Complete output from command C:/msys64/mingw64/bin/python3.exe C:/msys64/mingw64/lib/python3.7/site-packages/pep517/_in_process.py get_requires_for_build_wheel C:/Users/Tim/AppData/Local/Temp/tmpc_uc3hgi:
  ERROR: C:/Users/Tim/AppData/Local/Temp/pip-build-env-5i2z1bc4/overlay/lib/python3.7/site-packages\Cython\Distutils\old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
    "Cython.Distutils.old_build_ext does not properly handle dependencies "
  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command "C:/msys64/mingw64/bin/python3.exe C:/msys64/mingw64/lib/python3.7/site-packages/pep517/_in_process.py get_requires_for_build_wheel C:/Users/Tim/AppData/Local/Temp/tmpc_uc3hgi" failed with error code 1 in C:/Users/Tim/AppData/Local/Temp/pip-install-r417pjmi/pyproj

```

I guess the bottom line is, how do I get this installed under msys2 (MINGW64)

```
$ uname -a
MINGW64_NT-10.0-18362 TIM-ACER-E15 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys

```

**Comment by snowman2** [comment]
I would recommend trying `conda` if it an option for you ([instructions](https://pyproj4.github.io/pyproj/stable/installation.html)).

Otherwise, I wonder if you would have better luck posting this on one or both of these sites?
- gis.stackexchange.com
- stackoverflow.com

**Comment by tjwilli58** [comment]
I'd like to use conda , but there are other packages I need for my application like [gstreamer](https://github.com/conda-forge/gstreamer-feedstock) Notice that this isn't built for Windows.  I've tried to modify the recipe to get this built, but gave up. Not my expertise.

pyproj is probably overkill for what I need to do, All I really need is to be able to convert Lat/Long dectimal degrees to DMS (degree,minute,second) and back, and also convert to UTM.

There is a [python utm module on :PyPi](https://pypi.org/project/utm/), and I'm looking at that, but I saw a post about [Inaccuracy of the UTM to/from lat, lon conversion](https://github.com/Turbo87/utm/issues/36) . One of the reponses on that thread was to replacy utm with pyproj. The error in converting back and forth is on the order of centimeters, so I may just say that's good enough.

**Comment by snowman2** [comment]
@tjwilli58, you could also see if `pyproj==1.9.6` works for you.

**Comment by tjwilli58** [comment]
@snowman2 , I tried it, but I have the same problem installing this on msys2.
I found something on [stackoverflow ](https://stackoverflow.com/questions/2579535/convert-dd-decimal-degrees-to-dms-degrees-minutes-seconds-in-python) that works for me.
That, and the utm module on PyPi.

Thanks,

**Comment by tjwilli58** [comment]
Actually, [geopy](https://pypi.org/project/geopy/) works for me. 
```
pt=geopy.Point(39.332876, -76.294984)
pt.format()
'39 19m 58.3536s N, 76 17m 41.9424s W'
pt.format(None, min_char='', sec_char='')
'39 19 58.3536 N, 76 17 41.9424 W'

```
