### ISSUE TITLE
Use from_epsg and from_proj4, coordinate must be reversal, why?

### ISSUE THREAD

**Issue by guyanf** [pyproj4/pyproj#581]
# epsg:4547
# +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs 

from pyproj import Transformer, CRS

x, y = 520652.4602542225, 2433813.9805720625
tar = CRS.from_epsg(4326)

crs1 = CRS.from_epsg(4547)
t_cs1 = Transformer.from_crs(crs1, tar) 
new_x1, new_y1 = t_cs1.transform(y, x)
print(new_x1, new_y1)

print('-'*80)
crs2 = CRS.from_proj4("+proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs")
t_cs2 = Transformer.from_crs(crs2, tar)
new_x2, new_y2 = t_cs2.transform(x, y)
print(new_x2, new_y2)

When is used t_cs1, coordinate is y x, but t_cs2, coordinate must x y?
Why the coorinate must be reversal?
How can I do?

TKS.

**Comment by snowman2** [comment]
I would recommend looking at #538

**Comment by snowman2** [comment]
I would also recommend reading:
https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6

**Comment by guyanf** [comment]
@snowman2 is correct.
The reason that the EPSG code does not appear with the CRS initialized with the init= syntax is that the CRS are different. The difference is in the axis order.

TKS!
