### ISSUE TITLE
Alpine with proj executable not found. Please set the PROJ_DIR variable

### ISSUE THREAD

**Issue by maynewong** [pyproj4/pyproj#582]
Dockerfile

```
FROM python3.7-alpine

RUN apk add proj proj-dev
RUN pip install pyproj
```
get error
```
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_8k0qhw3
       cwd: /tmp/pip-install-zzif953y/pyproj
  Complete output (1 lines):
  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_8k0qhw3 Check the logs for full command output.
```

`apk add proj` installed PROJ sucessful, but I can‘t get PROJ_DIR

**Comment by snowman2** [comment]
What happens when you run `which proj`?

**Comment by maynewong** [comment]
> which proj

can't get  proj location
```
/code # which proj
/code #
```

**Comment by snowman2** [comment]
Hmmm, seems like you will need to manually find where PROJ was installed then.

What about `echo $PROJ_LIB`?

**Comment by maynewong** [comment]
@snowman2 

can’t get $PROJ_LIB 
```
/code # echo $PROJ_LIB

```

only find proj in there paths:
```
/usr/share # find / -mtime -5 | grep proj
/usr/lib/libproj.so.15
/usr/lib/libproj.so
/usr/share/proj
/usr/include/proj
```

**Comment by snowman2** [comment]
This may not work without the `proj` executable, but you can try: `PROJ_DIR=/usr/ pip install pyproj`

**Comment by maynewong** [comment]
Fail to find `proj` executable file in `/usr/bin/`

```
    File "/tmp/pip-build-env-pjq69dmf/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 243, in <module>
      ext_modules=get_extension_modules(),
    File "setup.py", line 147, in get_extension_modules
      proj_dir = get_proj_dir()
    File "setup.py", line 60, in get_proj_dir
      check_proj_version(proj_dir)
    File "setup.py", line 20, in check_proj_version
      proj_ver_bytes = subprocess.check_output(proj, stderr=subprocess.STDOUT)
    File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
      restore_signals, start_new_session)
    File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/proj': '/usr/bin/proj'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1fb53as2 Check the logs for full command output.
```

apk install `proj` successful, but did not generate the executable file

**Comment by snowman2** [comment]
is there a `proj-bin` package?

**Comment by maynewong** [comment]
@snowman2, found the solution by install proj-utl, Thanks

```
apk add proj-util

/code # which proj
/usr/bin/proj
```

**Comment by snowman2** [comment]
@maynewong I am going to assume that you were able to successfully install pyproj. If you are still having issues, feet free to reopen and post comments.

**Comment by mkdthanga** [comment]
> @snowman2, found the solution by install proj-util, Thanks
> 
> ```
> apk add proj-util
> 
> /code # which proj
> /usr/bin/proj
> ```
 I was not able to follow the solution suggested in this post. How to set the directory **/usr/local/bin/proj** in Dockerfile? Could you hep me solve the following error? It is the same problem I think!

**#################### Dockerfile ###################**
FROM alpine:latest

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PROJ_DIR=/usr/local

RUN addgroup -S appuser ; adduser -S appuser -G appuser -h /app ;\
    chown appuser:appuser /app

WORKDIR /app
COPY --chown=appuser:appuser / /app

RUN apk add --update --no-cache python3 libpq uwsgi-python3;\
    apk add --no-cache python3-dev py3-pip alpine-sdk postgresql-dev postgresql;\
	apk add proj proj-dev;\
	apk add proj-util;\
	/usr/bin/proj;\
    pip3 install --upgrade pip ;\
	pip3 install --upgrade setuptools;\
    pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5432

CMD ["python3", "/app/subscriber_db.py"]
CMD ["python3", "/app/resolver.py"]


**####################### Requirements.txt ################**
numpy==1.19.0
pandas==1.0.5
sqlalchemy==1.3.16
paho-mqtt==1.5.0
psycopg2==2.8.5
six==1.14.0
requests==2.24.0
cython
pyproj
scipy==1.5.0
statistics==1.0.3.5
matplotlib

**###################### Error #####################**
`Collecting pyproj
  Downloading pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp406to7y8
       cwd: /tmp/pip-install-v2uzfrtq/pyproj
  Complete output (34 lines):
  PROJ_DIR is set, using existing proj4 installation..

  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-_7zppa_r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-_7zppa_r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-_7zppa_r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-_7zppa_r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 243, in <module>
      ext_modules=get_extension_modules(),
    File "setup.py", line 147, in get_extension_modules
      proj_dir = get_proj_dir()
    File "setup.py", line 60, in get_proj_dir
      check_proj_version(proj_dir)
    File "setup.py", line 20, in check_proj_version
      proj_ver_bytes = subprocess.check_output(proj, stderr=subprocess.STDOUT)
    File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
`

  **FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/proj'**
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp406to7y8 Check the logs for full command output.
