### ISSUE TITLE
What does "accuracy" mean for a Transformer or CoordinateOperation?

### ISSUE THREAD

**Issue by alpha-beta-soup** [pyproj4/pyproj#586]
- [pyproj.crs.CoordinateOperation.accuracy](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html?highlight=accuracy#pyproj.crs.CoordinateOperation.accuracy)
- [pyproj.transformer.Transformer.accuracy](https://pyproj4.github.io/pyproj/stable/api/transformer.html?highlight=accuracy#pyproj.transformer.Transformer.accuracy)

The documentation is unclear (to me) about what "accuracy" refers to in these contexts. All that is stated is that the value is of type float and that it represents:
>  The accuracy (in metre) of a coordinate operation.

I understand that the accuracy is used as part of the sorting algorithm to find the best available transformation. But for what else can I use this value? Is it useful to help identify false precision resulting from a transformation?

An example:
- Input: `POINT(174.8 -41.3)` (interpreted via `shapely.wkt.loads` - I can add code if requested) 
- Input CRS: `EPSG:4326`
- Output CRS: `EPSG:2193`
- pyproj-generated transformation description: `axis order change (2D) + Inverse of NZGD2000 to WGS 84 (1) + New Zealand Transverse Mercator 2000 + axis order change (2D)`
- **Transformation accuracy: 1.0 metres**
- Output: `POINT (1750697.5213341913186014 5426376.6231682747602463)` (`shapely.ops.transform` with a `pyproj.transformer.Transformer` then `shapely.wkt.dumps`)

I can limit the output to a particular precision using `rounding_precision` when calling the transformation computation, but my underlying query is whether I can use the reported accuracy of the transformation to help decide whether/how I should truncate the output to avoid reporting false precision, i.e. precision which is not supported by the input's precision — or is this based on some faulty interpretation of `accuracy` in this context?

In any case, it would be valuable to have a bit more text about what the accuracy property means in practical   terms

**Comment by snowman2** [comment]
This might provide some clarity:

http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#122

```
Operation accuracy is an optional attribute which indicates the typical error the application of a coordinate operation will introduce into transformed target CRS coordinates assuming input of errorless source CRS coordinates. It is an approximate figure for the area of applicability of the coordinate operation as a whole, given in metres.
```

**Comment by snowman2** [comment]
I am going to assume your question has been answered and am going to close this issue. If I am wrong, feel free to reopen.
