### ISSUE TITLE
CRS conversion between PROJ and WKT loses lat_ts parameter

### ISSUE THREAD

**Issue by djhoese** [pyproj4/pyproj#592]
I have a case where I'm converting from a PROJ dict to a CRS object then storing it as WKT. When I then request the PROJ back from the WKT (WKT -> CRS object -> PROJ dict) I lose the `+lat_ts` parameter.

#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
from pyproj import CRS
crs = CRS({'a': '6378144.0', 'b': '6356759.0', 'lat_0': '50.00', 'lat_ts': '50.00', 'lon_0': '8.00', 'proj': 'stere'})
crs.to_proj4()
# '+proj=stere +a=6378144.0 +b=6356759.0 +lat_0=50.00 +lat_ts=50.00 +lon_0=8.00 +type=crs'
CRS(crs.to_wkt()).to_proj4()
# '+proj=stere +lat_0=50 +lon_0=8 +k=1 +x_0=0 +y_0=0 +a=6378144 +rf=298.253168108487 +units=m +no_defs +type=crs'

crs.to_wkt()
# 'PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",ELLIPSOID["unknown",6378144,298.253168108487,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["unknown",METHOD["Stereographic"],PARAMETER["Latitude of natural origin",50,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",8,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",1,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]'
```
#### Problem description

The `lat_ts` parameter disappears. I think this is a valid PROJ definition but the WKT seems to lose the parameter.

#### Expected Output

Keep the `lat_ts` parameter.

#### Environment Information

 - Output from: `python -m pyproj -v`

```
pyproj info:
    pyproj: 2.5.0
      PROJ: 6.3.1
  data dir: /home/davidh/miniconda3/envs/satpy_py37/share/proj

System:
    python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)  [GCC 7.3.0]
executable: /home/davidh/miniconda3/envs/satpy_py37/bin/python
   machine: Linux-5.3.0-7642-generic-x86_64-with-debian-buster-sid

Python deps:
       pip: 20.0.2
setuptools: 46.0.0.post20200311
    Cython: 0.29.15
```

#### Installation method
conda with conda-forge

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "proj|aenum"

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mraspaud** [comment]
In the first example, `lat_ts` and `lat_0` are the same, which can't work in this projection. Setting these to different values solves the problem.

**Comment by snowman2** [comment]
This logic is handled by PROJ. It seems to have the same behavior:
```
projinfo '+proj=stere +a=6378144.0 +b=6356759.0 +lat_0=50.00 +lat_ts=50.00 +lon_0=8.00 +type=crs'
PROJ.4 string:
+proj=stere +a=6378144.0 +b=6356759.0 +lat_0=50.00 +lat_ts=50.00 +lon_0=8.00 +type=crs

WKT2:2019 string:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["unknown",
            ELLIPSOID["unknown",6378144,298.253168108487,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Stereographic"],
        PARAMETER["Latitude of natural origin",50,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",8,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```
Same parameters lost when WKT is used:
```
projinfo -o PROJ 'PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",ELLIPSOID["unknown",6378144,298.253168108487,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["unknown",METHOD["Stereographic"],PARAMETER["Latitude of natural origin",50,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",8,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",1,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]'
PROJ.4 string:
+proj=stere +lat_0=50 +lon_0=8 +k=1 +x_0=0 +y_0=0 +a=6378144 +rf=298.253168108487 +units=m +no_defs +type=crs
```

**Comment by snowman2** [comment]
> In the first example, lat_ts and lat_0 are the same, which can't work in this projection. Setting these to different values solves the problem.

@mraspaud do you have an example?

**Comment by djhoese** [comment]
I'm not seeing this:

```
In [4]: crs = CRS({'a': '6378144.0', 'b': '6356759.0', 'lat_0': '50.00', 'lat_ts': '40.00', 'lon_0': '8.00', 'proj': 'stere'})

In [5]: CRS(crs.to_wkt()).to_dict()
/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pyproj/crs/crs.py:539: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
Out[5]:
{'proj': 'stere',
 'lat_0': 50,
 'lon_0': 8,
 'k': 1,
 'x_0': 0,
 'y_0': 0,
 'a': 6378144,
 'rf': 298.253168108487,
 'units': 'm',
 'no_defs': None,
 'type': 'crs'}
```

**Comment by mraspaud** [comment]
```python
In [2]: from pyproj import CRS 
   ...: crs = CRS({'a': '6378144.0', 'b': '6356759.0', 'lat_0': '90.00', 'lat_ts': '50.00', 'lon_0': '8.00', 'proj': 'stere'}) 
   ...: crs.to_proj4()                                                                                                                       

Out[2]: '+proj=stere +lat_0=90 +lat_ts=50 +lon_0=8 +x_0=0 +y_0=0 +a=6378144 +b=6356759 +units=m +no_defs +type=crs'

In [3]: CRS(crs.to_wkt()).to_proj4()                                                                                                         

Out[3]: '+proj=stere +lat_0=90 +lat_ts=50 +lon_0=8 +x_0=0 +y_0=0 +a=6378144 +rf=298.253168108487 +units=m +no_defs +type=crs'

```

**Comment by djhoese** [comment]
If you change `lat_0` to anything other than 90 I think it drops the lat_ts. So maybe lat_ts only makes sense with lat_0 being a pole?

**Comment by mraspaud** [comment]
Ok, there is definitively some interaction between `lat_0` and `lat_ts`. Setting `lat_0` to something different than 90 or -90 discards `lat_ts`. Setting `lat_0` to -90 and `lat_ts` to 50 reverts back `lat_0` to 90.

**Comment by mraspaud** [comment]
> If you change `lat_0` to anything other than 90 I think it drops the lat_ts. So maybe lat_ts only makes sense with lat_0 being a pole?

Ah, yes, of course. If you set the pole to somewhere else, then the true scale can't be defined as a latitude, since we're rotation the entire system.

**Comment by snowman2** [comment]
In WKT, there are three stereographic choices to create a `stere` operation currently in `pyproj`:

- [PolarStereographicAConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#polarstereographicaconversion)
- [PolarStereographicBConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#polarstereographicbconversion)
- [StereographicConversion](https://pyproj4.github.io/pyproj/stable/api/crs/coordinate_operation.html#stereographicconversion)

The only one with `lat_ts` as an input is `PolarStereographicBConversion`

**Comment by djhoese** [comment]
Ok so are we calling these two cases (the stereographic and lat/lon) invalid in the way we are using them? Both of these cases were tests that someone had written in to pyresample so they weren't necessarily real world use cases. I can fix our tests to be more real-world-ish.

Bottom line: These aren't bugs in your opinion, right @snowman2?

**Comment by snowman2** [comment]
> These aren't bugs in your opinion, right?

I definitely don't claim to be an expert on this. Just digging around for clues for if the behavior is expected or not. Might be worth raising an issue upstream in the PROJ repo to see what the devs have to say about it.

**Comment by snowman2** [comment]
Sounds like this has been resolved/clarified upstream if I understand correctly. If I am incorrect, feel free to reopen.
