### ISSUE TITLE
Add CRS.to_rasterio()

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#593]
Related to:
- https://github.com/mapbox/rasterio/issues/1898
- https://github.com/corteva/rioxarray/issues/92

It would only work if you have `rasterio` installed (import rasterio in the method). Essentially, it would return a `rasterio.crs.CRS` object using the WKT format based on the `__gdal_version__`.

**Comment by jorisvandenbossche** [comment]
Wouldn't it be more logical to improve rasterio to ensure it can handle pyproj CRS (and properly converts to their own CRS) wherever it accepts a CRS in their API?
