### ISSUE TITLE
Undefined symbol: proj_context_set_autoclose_database

### ISSUE THREAD

**Issue by Nqabz** [pyproj4/pyproj#597]
In trying to install and work with [sentinelhub](https://pypi.org/project/sentinelhub/#files) there is a dependency to `pyproj` package. Any tips to what could be going wrong with `pyproj`
```
from pyproj import _datadir
ImportError: lib/python3.6/site-packages/pyproj-2.6.0-py3.6-linux-ppc64le.egg/pyproj/_datadir.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: proj_context_set_autoclose_database
```

```
from sentinelhub.common import BBox, CRS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/sentinelhub-3.0.2-py3.6.egg/sentinelhub/__init__.py", line 5, in <module>
    from .data_request import WmsRequest, WcsRequest, FisRequest, GeopediaWmsRequest, GeopediaImageRequest, \
  File "lib/python3.6/site-packages/sentinelhub-3.0.2-py3.6.egg/sentinelhub/data_request.py", line 13, in <module>
    from .ogc import OgcImageService
  File "/lib/python3.6/site-packages/sentinelhub-3.0.2-py3.6.egg/sentinelhub/ogc.py", line 11, in <module>
    from .constants import ServiceType, DataSource, MimeType, CRS, SHConstants, CustomUrlParam
  File "/lib/python3.6/site-packages/sentinelhub-3.0.2-py3.6.egg/sentinelhub/constants.py", line 12, in <module>
    import pyproj
  File "lib/python3.6/site-packages/pyproj-2.6.0-py3.6-linux-ppc64le.egg/pyproj/__init__.py", line 51, in <module>
    from pyproj import _datadir
ImportError: lib/python3.6/site-packages/pyproj-2.6.0-py3.6-linux-ppc64le.egg/pyproj/_datadir.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: proj_context_set_autoclose_database
```

**Comment by snowman2** [comment]
Can you provide:

#### Installation method/steps
 - Installation method (conda, pip wheel, from source, etc...)
 - How did you install PROJ? Where is it installed?
 - Please provide all commands/steps you used to install pyproj and PROJ.

#### Environment Information
 - pyproj version you are attempting to install
 - PROJ version (Execute `proj` command and give version here.)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

**Comment by Nqabz** [comment]
Installation and environment information are as follows:

**PROJ installation**
- `conda install -c anaconda proj`
- `conda install -c conda-forge proj-data`

**Installation method**
- `export CC=gcc`
- `pip install pyproj`

**SENTINELHUB Installed from source**
- `tar -xzvf` sentinelhub-3.0.2.tar.gz 
- cd sentinelhub-3.0.2/
- `python3 setup.py build`
- `python3 setup.py install`

All installed in a Conda environment. Environment information:

- proj : `Rel. 7.0.0, March 1st, 2020`
- Python version: `3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:47:07)  [GCC 7.3.0]`
- Operating system info: `Linux-4.14.0-115.14.1.el7a.ppc64le-ppc64le-with-redhat-7.6-Maipo`

**Comment by snowman2** [comment]
I think the issue is likely mixing where you are installing `PROJ` from. With your current method, you are getting two different versions of PROJ.

I would recommend instead of:

~`conda install -c anaconda proj`~
~`conda install -c conda-forge proj-data`~
~`pip install pyproj`~

To just do:
`conda install -c conda-forge proj-data pyproj`

**Comment by Nqabz** [comment]
Great, I uninstalled and ran as above and that got me past the previous issue. However this I hit 
 this new issue:
```
>>> import pyproj
>>> 
>>> pyproj.CRS(4326)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyproj' has no attribute 'CRS'
>>> 
```

**Comment by snowman2** [comment]
> This is pyproj version 1.9.5.1

The CRS class only exists in `pyproj>=2`

**Comment by Nqabz** [comment]
I should have paid more attention to what is available and in what package. Thank you!

**Comment by snowman2** [comment]
Not a problem :+1:
