### ISSUE TITLE
'proj executable not found'

### ISSUE THREAD

**Issue by veenstrajelmer** [pyproj4/pyproj#616]
#### Installation method/steps
 - Installation method: ``pip install pyproj>=1.9.6`` from commandline in activated conda environment
 - How did you install PROJ? I did not, this was previously solved by pip

#### Environment Information
 - pyproj version you are attempting to install: latest
 - Python version: 3.7.7
 - Operation System Information: Windows-10-10.0.17134-SP0

My issue is solved when I ``pip install pyproj==2.6.0`` instead of ``pip install pyproj>=1.9.6`` (fetches 2.6.1), so this issue has occured in the last stable version.

Collecting pyproj==2.6.1
  Using cached pyproj-2.6.1.tar.gz (528 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\veenstra\Anaconda3\envs\hatyan2_env\python.exe' 'C:\Users\veenstra\Anaconda3\envs\hatyan2_env\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\veenstra\AppData\Local\Temp\tmpi19fhhbs'
       cwd: C:\Users\veenstra\AppData\Local\Temp\pip-install-zs4h6bx4\pyproj
  Complete output (1 lines):
  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\veenstra\Anaconda3\envs\hatyan2_env\python.exe' 'C:\Users\veenstra\Anaconda3\envs\hatyan2_env\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\veenstra\AppData\Local\Temp\tmpi19fhhbs' Check the logs for full command output.

**Comment by snowman2** [comment]
We just made a release and it takes time to get all of the parts ready and uploaded. The Windows wheels for 2.6.1 are not uploaded yet. Once they are uploaded this will all be resolved.

Side note: Why not use `conda install -c conda-forge pyproj`?

**Comment by veenstrajelmer** [comment]
Thanks for the reply, good to know.

pyproj is a dependency of a package I wrote on github. Installing from a git url is not supported by conda-forge as far as I know (I could be wrong), so I use pip for that. In order to streamline the installation process of my package for me and other users, I prefer to use a requirements.txt that is called by setup.py, which causes the dependencies to also be installed via pip. Any tips on transfering this to conda are of course appreciated.

**Comment by snowman2** [comment]
Interesting. That makes sense. You could look into adding your package to conda-forge: github.com/conda-forge/staged-recipes/

**Comment by snowman2** [comment]
> ERROR: Minimum supported PROJ version is 8.0.0, installed version is 7.2.1.
is this constrain really required? It takes a lot of effort to install it from source.

See the "version compatibility matrix" here:
https://pyproj4.github.io/pyproj/stable/installation.html#installing-from-source
