### ISSUE TITLE
Install pyproj-1.9.5.1 on windows 8

### ISSUE THREAD

**Issue by FarihaZg** [pyproj4/pyproj#62]
I need to install pyproj-1.9.5.1 module for Python 2.7 on Windows 8. I have used this link (https://github.com/jswhit/pyproj), I found only pyproj-1.9.5.1.tar.gz. How can I install it on my machine please?

**Comment by micahcochran** [comment]
If you have pip installed you can install it from the command line by doing this.  Pip will download and install pyproj for you.
`C:\..> pip install pyproj`

Alternatively, download [the zip](https://github.com/jswhit/pyproj/archive/v1.9.5.1rel.zip).  Uncompress the archive.  Then follow the README instruction that 

```commandline
C:\..> python setup.py build
C:\..> python setup.py install
```

If the installation complains about not having "vcvarsal.bat".  Install [Visual C++ for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

**Comment by YosraZg** [comment]
Thank you for your response, I tried the second solution but I had another error. 

![image](https://cloud.githubusercontent.com/assets/5756600/13771477/6f9ed912-ea8e-11e5-9e4b-2d2412cda319.png)

**Comment by georgeouzou** [comment]
Pyproj contains some additional c files that need to be compiled. Download this https://www.microsoft.com/en-us/download/details.aspx?id=44266. And try building and installing again

**Comment by YosraZg** [comment]
I downloaded the VCForPython27 and I when I tried building it gives me this error. What should I do please?

![image](https://cloud.githubusercontent.com/assets/5756600/13772562/1ac94682-ea95-11e5-88b8-be8aa5e17b15.png)

**Comment by georgeouzou** [comment]
The files are compiled but cannot be linked. Can you try upgrading setuptools and doing this again? Maybe it has something to do with the linking. https://pypi.python.org/pypi/setuptools

**Comment by YosraZg** [comment]
I installed setuotools-20.2.2.zip. What should I type in the command line to upgrade it (ez_setup.py)?
And should I add the environment variable of python?

**Comment by georgeouzou** [comment]
You run `C:/python27/python.exe ez_setup.py` from the command line. Also its nice to add python to your environment path so you can quickly `python ez_setup.py` from anywhere.

**Comment by YosraZg** [comment]
Thank you I upgraded setuptools and when I typed again:  C:/Python27/python.exe setup.py build it gives me: mt.exe stopped working.

![image](https://cloud.githubusercontent.com/assets/5756600/13774143/a8e5caf0-ea9d-11e5-8ea6-a297042fc71c.png)

**Comment by georgeouzou** [comment]
Can you printscreen another image with the errors on the commandline?

**Comment by YosraZg** [comment]
![image](https://cloud.githubusercontent.com/assets/5756600/13774467/8305173a-ea9f-11e5-9194-2160d39f9fc3.png)

**Comment by georgeouzou** [comment]
I tried it on my windows 8 and had the same results. But when i added python to the PATH, all the files compiled and linked nicely. So try this:
- Hold Win/Start and press Pause or go to System.
- Click Advanced System Settings.
- Click Environment Variables.
- Append C:\Python27\; to the Path variable.
-  Restart Command Prompt.
-  Type `python setup.py build` and wait a little.
-  If all is done, then `python setup.py install`

**Comment by YosraZg** [comment]
Thank you very much George, it worked :)

**Comment by georgeouzou** [comment]
:) Nice!

**Comment by geographika** [comment]
I downloaded the wheel file from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj - pyproj-1.9.5-cp27-none-win_amd64.whl

The following was failing: 

`pip install pyproj-1.9.5-cp27-none-win_amd64.whl `
 
With:

`ValueError: ('Expected version spec in', 'C:\\Installation\\Python\\pyproj-1.9.5-cp27-none-win_amd64.whl', 'at', ':\\Installation\\Python\\pyproj-1.9.5-cp27-none-win_amd64.whl')`

However once I updated pip then it succeeded. 

`pip install pip -U`

The original pip version was 1.2.1 the updated one was 8.1.0

**Comment by luky1984** [comment]
Hi, i have Windows8 and neither one method works for me. Neither WHL work neither the official way.

Neither pip install. If i run pip install it does very long and fast output ending with #cleaning lines but pyproj is not installed.

I have python path in env variable both in PATH and Path.

I have no clue what could be problem.

If i run the officall installation  python setup.py build and install it should automatically add folder to my Python/Lib folder? How can i check what is wrong?

Thx

**Comment by georgeouzou** [comment]
Do you know if you have the required c compiler installed? If not try installing [VC++ for python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266)

**Comment by luky1984** [comment]
I will try, thanks George

**Comment by micahcochran** [comment]
pyproj doesn't have a wheel (WHL) release as you can see on [pypi](https://pypi.python.org/pypi/pyproj/1.9.5.1).

Appveyor could be made to generate a Wheel on Windows.  Binary wheels are a bit harder to configure than universal wheels (python source only).

Patches are welcome.

**Comment by johnmisquita** [comment]
what does build mean? how do i do it?

**Comment by johnmisquita** [comment]
All i did was install this https://www.microsoft.com/en-us/download/details.aspx?id=44266. and then use pip install and it worked

**Comment by fenchu** [comment]
Please create a windows64 binary wheel for python3. I do not want to have 8GB+ of visual studio bloat around just for compiling this.

**Comment by snowman2** [comment]
Refer to #216
