### ISSUE TITLE
Is this suspicious code correct?

### ISSUE THREAD

**Issue by mmodenesi** [pyproj4/pyproj#622]
One would expect this line to make no references to `x`. I am not sure, though.

https://github.com/pyproj4/pyproj/blob/f3156505d91ab05aca418c049d40be9f00ecbdc5/pyproj/transformer.py#L437

**Comment by mmodenesi** [comment]
Also

https://github.com/pyproj4/pyproj/blob/f3156505d91ab05aca418c049d40be9f00ecbdc5/pyproj/geod.py#L220

https://github.com/pyproj4/pyproj/blob/f3156505d91ab05aca418c049d40be9f00ecbdc5/pyproj/proj.py#L191

**Comment by snowman2** [comment]
@mmodenesi would you be interested in submitting a PR to fix this?

**Comment by mmodenesi** [comment]
sure thing
