### ISSUE TITLE
How long does one have to be subjected to Future Warnings?

### ISSUE THREAD

**Issue by OldSubSailor** [pyproj4/pyproj#626]
I tried searching for this but did not get a return.

Example of problem

I get a full terminal window of these comments when I start Ortho4XP.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=:' syntax is deprecated. ':' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6 projstring = _prepare_from_string(" ".join((projstring, projkwargs)))

 #### Problem description
This has been going on for a long time now.   I had expected it to be fixed(?)  How long does one have to be subjected to Future Warnings?

if in_crs_string.startswith(("+init", "init")):
            warnings.warn(
                "'+init=<authority>:<code>' syntax is deprecated. "
                "'<authority>:<code>' is the preferred initialization method. "
                "When making the change, be mindful of axis order changes: "
                "https://pyproj4.github.io/pyproj/stable/gotchas.html"
                "#axis-order-changes-in-proj-6",
                FutureWarning,
                stacklevel=2,

#### Expected Output
No warnings

#### Environment Information
 - pyproj     2.6.1
- proj Rel. 7.0.0, March 1st, 2020
 - macOS Catalina 10.15.4

#### Installation method
 - I think that proj was installed when using the ruby based homebrew master install(?)

Thank you

**Comment by snowman2** [comment]
@OldSubSailor is there a reason you cannot stop using `+init=` syntax?

**Comment by snowman2** [comment]
Related: #538

**Comment by snowman2** [comment]
Other references that may be useful:
- https://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code
- #355

**Comment by OldSubSailor** [comment]
I most likely was not clear in what I was doing. When we launch Ortho4XP the terminal screen fills with this warning. The program does come up and run, but I am getting concerned.




And shows this path(?);  I am not a programmer here and mostly fumbling my way through this.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs

I do not know who wrote it, hopefully these will help:

**Comment by snowman2** [comment]
Well, the good news is that it likely won't be removed anytime soon. However, if you would like the warnings removed, I think you will need to raise an issue here: https://github.com/oscarpilote/Ortho4XP. If that is the correct repository, they should be able to make the changes in the code to make the warnings go away.

**Comment by OldSubSailor** [comment]
Howdy,
I hoped that I was able to send you two files that you could take a quick look at in our last message.  One was Oscars Ortho installer and the other was the file, if I understood the error message path that was generating the warnings.  I don’t know where that one came from or who wrote it.   
Hence, I don’t know who we would contact. 

In Mac Gui the folder looks like this

**Comment by snowman2** [comment]
@OldSubSailor I didn't see any files in the last message.

Mind raising an issue at https://github.com/oscarpilote/Ortho4XP and checking if they are the right ones to assist? It seems like a very likely candidate.

**Comment by OldSubSailor** [comment]
I can try

**Comment by OldSubSailor** [comment]
Done. I hope that I was able to state my concern in a clear manner.

**Comment by snowman2** [comment]
Going to close for preference for: https://github.com/oscarpilote/Ortho4XP/issues/126

If that is not the right place, we can reopen here.

**Comment by OldSubSailor** [comment]
Thank you

**Comment by inactivist** [comment]
If you want to suppress warnings temporarily, you can wrap the offending methods in a `catch_warnings` context handler and ignore them:

```python
import warnings
def to_meters(lon_degrees, lat_degrees):
    # Suppress warnings
    # https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        P3857 = Proj(init='epsg:3857')
        P4326 = Proj(init='epsg:4326')
        x,y = transform(P4326, P3857, lon_degrees, lat_degrees)
        return (x,y)
```

(Tested in Python 3.8.5)
