### ISSUE TITLE
Southern Hemisphere Convergence Angle

### ISSUE THREAD

**Issue by wg1562** [pyproj4/pyproj#654]
This pertains to an issue noticed by  @kimollivier also in issue #503 

I compared results obtained with the NGS NCAT tool: [https://www.ngs.noaa.gov/NCAT/index.xhtml ]
for points in the southern hemisphere, and I too am getting a UTM convergence angle with opposite sign of what that tool provides.

Maybe this is just how proj is setup, or maybe this is a legitimate bug? 

I am using pyproj version 2.6.1post

Thanks.

**Comment by snowman2** [comment]
The values produced by `pyproj` match what is in `PROJ`:
```
$ echo 178.0 -38.0 | ./proj -SV '+init=epsg:2193'
#Transverse Mercator
#	Cyl, Sph&Ell
#	approx
# +init=epsg:2193 +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000
# +y_0=10000000 +ellps=GRS80 +units=m +no_defs
#--- following specified but NOT used
# +type=crs
#Final Earth figure: ellipsoid
#  Major axis (a): 6378137.000
#  1/flattening: 298.257222
#  squared eccentricity: 0.006694380023
Longitude: 178dE [ 178 ]
Latitude:  38dS [ -38 ]
Easting (x):   2039122.41
Northing (y):  5782371.76
Meridian scale (h) : 1.00197576  ( 0.1976 % error )
Parallel scale (k) : 1.00197576  ( 0.1976 % error )
Areal scale (s):     1.00395542  ( 0.3955 % error )
Angular distortion (w): 0.000
Meridian/Parallel angle: 90.00000
Convergence : -3d4'59.618" [ -3.08322728 ]
Max-min (Tissot axis a-b) scale error: 1.00198 1.00198
```
I would recommend raising this issue upstream: https://github.com/osgeo/proj

**Comment by wg1562** [comment]
Bug issue created: [https://github.com/OSGeo/PROJ/issues/2253](url)

**Comment by snowman2** [comment]
Thanks for following up on that 👍. Closing here for preference to the other issue.
