### ISSUE TITLE
CRS.to_dict()  for 'tmerc'   got key 'k' instead of 'k_0

### ISSUE THREAD

**Issue by phisan-chula** [pyproj4/pyproj#656]
#### Code Sample, a copy-pastable example if possible

(Pdb++) CRS.to_dict()
{'proj': 'tmerc', 'lat_0': 15, 'lon_0': 100, 'k': 1, 'x_0': 0, 'y_0': 0, 'a': 6378137, 'b': 6356752.3142, 'units': 'm', 'no_defs': None, 'type': 'crs'}

 '+proj=tmerc +lat_0={lat_0} +lon_0={lon_0} +k_0={k_0} +x_0=0 +y_0=0 +a=6378137.0 +b=6356752.3142 +units=m +no_defs'

#### Problem description
I have define CRS with proj4 string.    'k_0" was well defined , but when is dump back
using CRS.to_dict() .... then i got  'k' instead of 'k_0'

#### Expected Output
got  'k' instead of 'k_0'

#### Environment Information
Pdb++) pyproj.__version__
'2.6.1'

**Comment by snowman2** [comment]
From what I understand, k/k_0 are equivalent.

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/issues/1067

**Comment by snowman2** [comment]
I would recommend asking PROJ devs if you have more questions as the parameters generated with the PROJ c/c++ code: https://github.com/OSGeo/PROJ
