### ISSUE TITLE
Setting `accuracy` parameter in the `pyproj.Transformer` class

### ISSUE THREAD

**Issue by anisotropi4** [pyproj4/pyproj#657]
This is a question about how to set the `accuracy` parameter in the `Transformer` class.

I have UK Northing/Easting (EPSG:27700) data held in the variable `DATA` and would like to project this to WGS 84 (EPSG:4326) to a given level of accuracy using `pyproj` as set out in the following code snippet:

``` 
from pyproj import Transformer, CRS
from shapely.ops import transform
transformer = Transformer.from_crs(DATA.crs, CRS.from_epsg(4326), always_xy=True)
```
From the API I understand that the `Transformer` accuracy parameter is in metres and defaults to `-1.0`. If I wanted to set this accuracy to an arbitrary distance, say, 0.5m, how do I do this?

My naïve attempts to set the value as below fail with a `can't set attribute` error:
```>>> transformer.accuracy
-1.0
>>> transformer.accuracy = 0.5
Traceback (most recent call last):
  AttributeError: can't set attribute
>>> transformer['accuracy'] = 0.5
Traceback (most recent call last):
  AttributeError: can't set attribute
```
I have looked and couldn't see answer in the usual places.

**Comment by snowman2** [comment]
The accuracy of a transformation is a read-only property of the transformer. It is read in from the database and is informative in nature. Out of curiosity, why do you want to change it?

**Comment by anisotropi4** [comment]
Good question it is based on two ideas:

First is my wish to understand `pyproj` better given that it underpins `geopandas` and a number of other key application. Given this, I was unaware that this is read in from the database and in my case I would have to then ask, what database? But that is probably more due to my lack of knowledge on my part.

Then, the second thought, albeit likely a misunderstanding on my part, is as follows:

I have a dataset that is in Northing/Easting (EPSG:27700) at tolerance of no more that 0.1m, if I transform this to WGS 84 (EPSG:4326) I then under up with points with 15-decimal-places, e.g. POINT (-1.356251776938934, 53.073162191357319). By my calculations something akin to the diameter of an electron.

This has two issues:  

The ability to compare equivalence of points. For example, given two points, say POINT (-1.35625177693893**4**, 53.073162191357319) and POINT (-1.35625177693893**9**, 53.073162191357319). These are different at the 15-significant figure level but equal at a rough-hand-wavy five-significant figure POINT (-1.356251, 53.07316) or 1m(ish). 

My first question is does an accuracy parameter of say 0.5m address this?

Then about output file-size bloat. I realize this is an interface hygiene issue and is arguably not a `pyproj` issue at all[*]. If I try to output the data to a text file at this level of accuracy this tends to a 260% increase in file size as a a point at five-significant figures can be represented in a 20-byte file whereas the 15-significant figure representation takes 39-bytes.

Again, this might be my misunderstanding, but would setting the accuracy to say, 0.5m, change this too?

[*] I then have an rather _inelegant  kludge_ to get around this using `shapely.transform` and `round`...

**Comment by snowman2** [comment]
I understand your problem much better now. So, the reason for all of those decimal places is because the data type is always going to be a double. It doesn't necessarily mean that all of the decimal places are important. If you wanted to round the decimal places where it makes sense, that would definitely be just fine.

If it is geographic, usually 7 decimal places gives you plenty of accuracy. However, it depends on what your needs are. If it is projected & the units are meters, usually 3-4 decimal places is plenty depending on your needs.

The accuracy of the transformation is dependent on the nature of the transformation calculation itself and/or datum grids. So, the value from the database is just there to let you know that when you transform from one projection to another, this is the error you can expect. Also, the database is in the data directory.

**Comment by snowman2** [comment]
https://www.explainxkcd.com/wiki/index.php/2170:_Coordinate_Precision

**Comment by anisotropi4** [comment]
Thanks for this. 

This then prompts the following questions, and then I'm done:

Does the accuracy parameter change behaviour or is it for information, and if it does what is the mechanism to set this? 
More generally within `pyproj` is there a way to define a **precision** within which it is possible to define equality or output format?

(I'm kind of interested in national or international rail traffic for which 5m is "good-enough" for to-the-second movement data....)

Thanks again

**Comment by snowman2** [comment]
The accuracy is just for information. So, no behavior change.

numpy can help with the decimal precision: https://numpy.org/devdocs/reference/generated/numpy.around.html#numpy.around
