### ISSUE TITLE
Qgis crash when importing pyproj from plugin or console

### ISSUE THREAD

**Issue by jbeilin** [pyproj4/pyproj#659]
I installed on ubuntu 18.04 : 
- Qgis 3.12.3
- pyproj 2.6.1.post1 using pip3 

Each time I try to import pyproj in a plugin or in a console script in Qgis console, Qgis crashes. This code works in spyder3. 

```
import pyproj
#print(pyproj.proj_version_str, pyproj.show_versions())
crs4326 = pyproj.CRS.from_epsg(4326)
crs2154 = pyproj.CRS(2154)
p = pyproj.Proj(crs2154)
transformer = pyproj.Transformer.from_crs(crs2154, crs4326, always_xy=True)
lo, la, h = transformer.transform(700000, 6600000, 0)
mu = p.get_factors(lo, la).meridional_scale
print(mu)
```

**Comment by snowman2** [comment]
Did you also ask the question here: https://github.com/qgis/QGIS?

**Comment by snowman2** [comment]
@jbeilin mind providing these details:

 - Installation method (conda, pip wheel, from source, etc...)
 - How did you install PROJ? Where is it installed?
 - Please provide all commands/steps you used to install pyproj and PROJ.
 - pyproj version you are attempting to install
 - PROJ version (Execute `proj` command and give version here.)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

**Comment by snowman2** [comment]
Also, how did you install QGIS?

**Comment by jbeilin** [comment]
> @jbeilin mind providing these details:
> 
>     * How did you install PROJ? Where is it installed?

Proj seems to be installed twice. Once with Qgis (v4.9.3) and one with pyproj (6.3.1)

> 
>     * Please provide all commands/steps you used to install PROJ.

Proj on Qgis was installed with apt commands from official servers.
pyproj was installed with pip3

> 
>     * PROJ version (Execute `proj` command and give version here.)
$ proj

Rel. 4.9.3, 15 August 2016

> 
>     * Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)

python3 -c "import sys; print(sys.version.replace('\n', ' '))"
3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]

>     * Operation System Information (`python -c "import platform; print(platform.platform())"`)

python3 -c "import platform; print(platform.platform())"
Linux-5.3.0-59-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by jbeilin** [comment]
> Also, how did you install QGIS?

Qgis was installed using the standard process on https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by jbeilin** [comment]
> Did you also ask the question here: https://github.com/qgis/QGIS?

not yet

**Comment by jbeilin** [comment]
> Did you also ask the question here: https://github.com/qgis/QGIS?

I have just submitted the issue : https://github.com/qgis/QGIS/issues/37289

**Comment by snowman2** [comment]
Looks like it was answered in the QGIS issue.

One thought I had was you could try to install both with conda and see if it works:

```
conda -c conda-forge qgis pyproj
```

**Comment by jbeilin** [comment]
I put a solution in qgis/QGIS#37289
