### ISSUE TITLE
Problem while building Alpine Docker Image with pyproj module

### ISSUE THREAD

**Issue by mkdthanga** [pyproj4/pyproj#668]
I am trying to buid an docker image with pyproj module.

**Here is my requirements.txt:**

numpy==1.18
pandas==1.0.3
sqlalchemy==1.3.16
paho-mqtt==1.5.0
psycopg2==2.8.4
requests==2.23.0
pyproj
scipy==1.4.1
statistics==1.0.3
matplotlib== 3.2.1

**Here is my Dockerfile:**

FROM alpine:3.9 

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PROJ_DIR=/usr/local

RUN addgroup -S appuser ; adduser -S appuser -G appuser -h /app ;\
    chown appuser:appuser /app
	
WORKDIR /app
COPY --chown=appuser:appuser / /app

RUN apk add --update --no-cache python3 libpq uwsgi-python3;\
    apk add --no-cache python3-dev py3-pip alpine-sdk postgresql-dev postgresql;\
	apk add proj proj-dev;\
	apk add proj-util;\
    pip3 install --upgrade pip ;\
	pip3 install pyproj;\
    pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5432

CMD ["python3", "/app/subscriber_db.py"]
CMD ["python3", "/app/resolver.py"]

**I get the following error while building the docker image:**

Collecting pyproj
  Downloading pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpacqi_fim
       cwd: /tmp/pip-install-3lriikt9/pyproj
  Complete output (34 lines):
  PROJ_DIR is set, using existing proj4 installation..

.....
.....
.....
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 /usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpacqi_fim Check the logs for full command output.

Can someone help me, please?

**Comment by snowman2** [comment]
Related:
- #621
- #582

**Comment by snowman2** [comment]
Closing with: https://github.com/pyproj4/pyproj/issues/582#issuecomment-650134083
