### ISSUE TITLE
Configuring it with ECLIPSE PyDev

### ISSUE THREAD

**Issue by farrukhqayum** [pyproj4/pyproj#68]
I wasn't able to configure pyproj with ECLIPSE. However, I was able to do it with standalone Py IDE.

Did any one try? What do I have to do it to properly run it in Eclipse.
I did properly add the source folders & eggs in pythonpath. I always get this error:

console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.
Traceback (most recent call last):
  File "X:\Eclipse_Java_Workspace\CoordConv\src\subset.py", line 11, in <module>
    from pyproj import Proj, transform
  File "C:\Python27\Lib\site-packages\pyproj-1.9.5.1-py2.7-win32.egg\pyproj__init__.py", line 51, in <module>
    from pyproj import _proj
  File "C:\Python27\Lib\site-packages\pyproj-1.9.5.1-py2.7-win32.egg\pyproj_proj.py", line 7, in <module>
    __bootstrap__()
  File "C:\Python27\Lib\site-packages\pyproj-1.9.5.1-py2.7-win32.egg\pyproj_proj.py", line 6, in **bootstrap**
    imp.load_dynamic(**name**,**file**)
ImportError: No module named pyproj._proj

**Comment by micahcochran** [comment]
It is choking on [this line](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/__init__.py#L51),  `from pyproj import _proj`.  This is where pyproj imports the Cython portion (which in C code interfaces with the C library PROJ.4).

**Comment by farrukhqayum** [comment]
Thanks Micah for a swift reply.

I did this and the standalone Python works fine. It is only the ECLIPSE issue. It does not recognize the pyproj path.

![image](https://cloud.githubusercontent.com/assets/13673770/14335277/4ce8d0a2-fc5a-11e5-9009-e4c618c92e86.png)

**Comment by micahcochran** [comment]
I don't have ECLIPSE installed.  I've got two questions that \*might* help.

What is the value of the variable `pyproj.pyproj_datadir` ?
 
Where is PROJ.4 installed on your box?

**Comment by farrukhqayum** [comment]
Following your e-mail I used the pip installation without setting the PROJ.4. So, I assume it is using the src. Thus, I should not link it to the environment variable PROJ_DIR. With this installation, Python IDLE works fine as shown in the previous attachmen (bottom left). Eclipse does not!

However, I also have a standalone installation of PROJ.4 located under: 

C:\Python27\Lib\site-packages\proj.4

The datadir file has the following contents.

if 'PROJ_DIR' in os.environ:
    pyproj_datadir = os.environ['PROJ_DIR']
else:
    pyproj_datadir = os.sep.join([os.path.dirname(__file__), 'data'])

![image](https://cloud.githubusercontent.com/assets/13673770/14365587/eb372164-fd0e-11e5-962a-2aa2e7010ae7.png)

Eclipse setup is like this:

![image](https://cloud.githubusercontent.com/assets/13673770/14365685/4c3cb10e-fd0f-11e5-81da-9fa8ac9c6898.png)

**Comment by farrukhqayum** [comment]
Resolution:

The main problem was the compilation of the PROJ.4. It was using ./configure in the cygwin.

Then I ran the preinstalled MSVC 8 command prompt via the start menu and ran nmake. It created the share/ folder in the installation path (set by editing the nmake*.opt file (INSTDIR = c:\Proj). After this, the eggs of pyproj were correctly build by running the pyproj (using python setup.py pyproj).

This solved the issue.

**Comment by micahcochran** [comment]
I'm glad you figure it out. Thanks for sharing the solution.

**Comment by snowman2** [comment]
Closing as solution found. Thanks for sharing!
