### ISSUE TITLE
geodesiclinestogis.geodesicline2gisfile.ExportGeodesicLineError

### ISSUE THREAD

**Issue by Kris-wu-glut** [pyproj4/pyproj#685]
how should i solve this problem
![image](https://user-images.githubusercontent.com/66007137/87871069-1c20f280-c9e0-11ea-8a82-d604760e204a.png)

**Comment by snowman2** [comment]
Looks like the error is coming from Fiona. I am going to close and recommend that you raise an issue at: https://github.com/Toblerity/Fiona
