### ISSUE TITLE
Incorrect transformation

### ISSUE THREAD

**Issue by vishalmhjn** [pyproj4/pyproj#711]
#### Code 
```python
import pyproj as proj
crs_wgs = proj.CRS('epsg:4326') 
crs_bng = proj.CRS('epsg:4815') 
x, y = proj.Transformer.from_crs(crs_wgs, crs_bng, always_xy=True).transform(23.731412, 37.992575)
print(x,y)
0.013301631303052536 37.99160393249527
```
#### Expected Output
<img width="991" alt="Screen Shot 2020-09-24 at 00 09 27" src="https://user-images.githubusercontent.com/42190624/94075000-adef1680-fdfa-11ea-8eca-88eb9c0a4c25.png">

#### Environment Information
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
  data dir: /Users/mac/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
executable: /Users/mac/bin/python
   machine: Darwin-19.5.0-x86_64-i386-64bit

Python deps:
       pip: 20.2.3
setuptools: 45.1.0
    Cython: 0.29.15

#### Installation method
 -pip wheel

**Comment by snowman2** [comment]
The output of pyproj matches PROJ:
```
echo "37.992575 23.731412" | cs2cs -d 8 'epsg:4326' 'epsg:4815'
37.99160393	0.01330163 0.00000000
```
I would recommend raising the issue upstream to verify which one is correct. https://github.com/osgeo/proj

**Comment by rouault** [comment]
http://epsg.io output is not necessarily normative. Contrary to what its name suggests, it is not officially affiliated with EPSG from IOGP and may use older releases than PROJ does

So I could replicate epsg.io output with this simple pipeline which only applies the Athens prime meridian shift
```
echo  "37.992575 23.731412 0" | src/cct -d 8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=longlat +ellps=bessel +pm=athens +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  37.99257500     0.01507450    0.00000000           inf
```

whereas PROJ applies the EPSG:6844 concatenated operation "Greek (Athens) to WGS 84 (1)" which chains a Helmert transformation to go from WGS84 to GGRS87, a longitude/latitude offset shift to go from GGRS87 to "Greek" datum and finally the Athens prime meridian shift:
```
echo  "37.992575 23.731412 0" | src/cct -d 8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=199.87 +y=-74.79 +z=-246.62 +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=geogoffset +dlat=5.86 +dlon=-0.28 +step +proj=longlat +ellps=bessel +pm=athens +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  37.99160393     0.01330163    0.00000000           inf
```

So not a bug for me.

**Comment by snowman2** [comment]
Thanks @rouault :+1:
