### ISSUE TITLE
Ecef2Ned Conversion

### ISSUE THREAD

**Issue by scorp08** [pyproj4/pyproj#713]
Hello All
I was looking for a library to convert ECEF to NED or ENU . Searched but currently I am not sure in Proj, is it possible. I know pymap3d but I will build some .dll and C++ libs would be better.

**Comment by snowman2** [comment]
I would recommend cross-posting this question in a couple of places:
 -    https://gis.stackexchange.com/ (add pyproj & PROJ tags)
 -    https://lists.osgeo.org/mailman/listinfo/proj/

**Comment by snowman2** [comment]
Related: https://github.com/OSGeo/PROJ/issues/500

**Comment by scorp08** [comment]
> Related: [OSGeo/PROJ#500](https://github.com/OSGeo/PROJ/issues/500)

I saw this posts before but honestly I do not know much depth in transformations so I was looking for built-in functions like ecef2enu....

**Comment by Jochem-L** [comment]
With the right parameters, it is possible to use a PROJ command.

Transformation from geocentric coordinates to ENU coordinates:
``cct -I +proj=pipeline +step +proj=axisswap +order=3,1,2,4 +step +proj=helmert +ry=%latitude% +rz=-%longitude% +x=%XYZ[1]% +y=%XYZ[2]% +z=%XYZ[3]% +convention=coordinate_frame +exact``
with:
`%latitude%` and `%longitude%` coordinates of central point in arcseconds
`%XYZ[1]%`, `%XYZ[2]%` and `%XYZ[3]%` geocentric coordinates of central point

The transformation in opposite direction from ENU coordinates to geocentric coordinates can be done by just removing the `-I` parameter. The conversion to arcseconds and the computation of the geographic coordinates can be put in a script (see todays post in https://github.com/OSGeo/PROJ/issues/500 ). Optionally, azimuth, scale and false easting and northing can be added as extra steps in the pipeline (see last line of scripts).

**Comment by snowman2** [comment]
That pipeline can be used with [Transformer.from_pipeline](https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.from_pipeline).

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/pull/2444
