### ISSUE TITLE
Python3.9 on macos fails to install pyproj

### ISSUE THREAD

**Issue by RakibFiha** [pyproj4/pyproj#729]
After opening a issue here: https://github.com/sentinel-hub/sentinelhub-py/issues/148, I realised, that Python3.9 on macos is failing to install pyproj.

Here is the details:

#### Installation method/steps
```
$ pip install pyproj
Collecting pyproj
  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/bin/python3 /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/tmp81c238v8
       cwd: /private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-install-snuzrap2/pyproj
  Complete output (1 lines):
  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/bin/python3 /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/tmp81c238v8 Check the logs for full command output.
```

#### Environment Information
 - pyproj version you are attempting to install: 2.6.1
 - Python version 
```bash
$ python -c "import sys; print(sys.version.replace('\n', ' '))"
3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0 (clang-1200.0.32.21)]
```
 - Operation System Information:
```bash
$ python -c "import platform; print(platform.platform())"
macOS-10.15.4-x86_64-i386-64bit
```

**Comment by ocefpaf** [comment]
If you look at the artifacts on PyPI there are no wheels, ready to install binaries, for Python 3.9:

https://pypi.org/project/pyproj/2.6.1.post1/#files

That is expected b/c Python 3.9 is quite new. What `pip` is trying to do there is a source install, which requires you to follow the instructions on installation documents. According to the error message,

```
proj executable not found. Please set the PROJ_DIR variable.For more information see:
https://pyproj4.github.io/pyproj/stable/installation.html
```

you'll have to install PROJ, setup the PROJ_DIR, and try to compile it. However, I do recommend a pre-built binary. The documentation has instructions on how to use the conda-forge package, it already has a Python 3.9 version of pyproj.

**Comment by RakibFiha** [comment]
```brew install proj``` solved the problem. Thank you.
