### ISSUE TITLE
Test requirements not documented

### ISSUE THREAD

**Issue by sebastic** [pyproj4/pyproj#733]
`pandas` is now required for `test/test_utils.py` but is not included in `requirements-dev.txt` like `xarray` is.

`certifi` is required for `test/test_network.py` but is only included in `install_requires` in `setup.cfg`.

**Comment by snowman2** [comment]
> pandas is now required for test/test_utils.py but is not included in requirements-dev.txt like xarray is.

That sounds like a good idea to be more explicit.

> certifi is required for test/test_network.py but is only included in install_requires in setup.cfg.

Where would be the most helpful location to put the requirements?

**Comment by jorisvandenbossche** [comment]
I would personally also recommend to use those optional test dependencies behind a pytest "skip if not installed" (you can use eg `pytest.importorskip`, to be read as "import or skip")

**Comment by sebastic** [comment]
> Where would be the most helpful location to put the requirements?

`tests_require` or `extras_require: {'test': []}` in `setup()` and/or `requirements-tests.txt` are likely good options.

**Comment by snowman2** [comment]
@sebastic, what about `certifi`?

**Comment by sebastic** [comment]
As `certifi` is not only required for tests `install_requires` is probably sufficient.
