### ISSUE TITLE
Test failures without network

### ISSUE THREAD

**Issue by sebastic** [pyproj4/pyproj#734]
The Debian package for 3.0-rc0 fails to build due to test failures. This seems to be caused by the lack of network in the build environment.

```
------------------------------ Captured log call -------------------------------
DEBUG    pyproj:crs.py:965 PROJ_ERROR: proj_crs_get_sub_crs: Object is not a CompoundCRS
DEBUG    pyproj:crs.py:965 PROJ_ERROR: proj_crs_get_sub_crs: Object is not a CompoundCRS
DEBUG    pyproj:transformer.py:81 PROJ_ERROR: proj_coordoperation_get_method_info: Object is not a DerivedCRS or BoundCRS
=============================== warnings summary ===============================
.pybuild/cpython3_3.9_pyproj/build/test/test_transformer.py::test_transformer_group__get_transform_crs
  /build/python-pyproj-3.0~rc0+ds/.pybuild/cpython3_3.9_pyproj/build/pyproj/transformer.py:81: UserWarning: Best transformation is not available due to missing Grid(short_name=nl_nsgi_rdtrans2018.tif, full_name=, package_name=, url=https://cdn.proj.org/nl_nsgi_rdtrans2018.tif, direct_download=True, open_license=True, available=False)
    super().__init__(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============= 41 failed, 292 passed, 1 warnings in 133.00 seconds ==============
```

Failure output: [pyproj.txt](https://github.com/pyproj4/pyproj/files/5472940/pyproj.txt)

**Comment by snowman2** [comment]
There are several issues there, but here are the ones that stand out to me:
1. Does your build run without a network connection?
2. Do you have the PROJ_NETWORK=ON without a network connection? If so, I would recommend changing PROJ_NETWORK=OFF during the tests.
3. The pyproj CLI is not found for some reason. `pyproj -v` doesn't require a network connection and it is failing.

**Comment by sebastic** [comment]
1.  The build environment has no outside networking, loopback is available.
1. `PROJ_NETWORK` is not set in the environment, and `/usr/share/proj/proj.ini` has the defaults:
    ```
   ; Network capabilities disabled by default.
   ; Can be overridden with the PROJ_NETWORK=ON environment variable.
   ; network = on
   ```
1. The `pyproj` seems to be expected in the `PATH` but as it's not installed it cannot be found.
    Commands like `/usr/bin/python3.9 -m pyproj` fail likewise when the build directory has not been added to `PYTHONPATH`.
   It seems that the tests expect that the `install` target has been executed already.

**Comment by snowman2** [comment]
@sebastic are there any datumgrids included? If so, which ones?

**Comment by sebastic** [comment]
Only [the (old) ones from proj-datumgrid-1.8](https://salsa.debian.org/debian-gis-team/proj/-/raw/debian/7.2.0-1/debian/datumgrids.list), none of the (new) GeoTIFF ones from proj-data-1.3.

proj-data cannot be included in Debian due to [license issues for the BETA2007 grid](https://github.com/OSGeo/PROJ/pull/383#issuecomment-622246695).

**Comment by snowman2** [comment]
That is the problem for those tests. `pyproj` does not check the existence of the old grids for the tests.

Is there anything preventing you from including proj-data minus the grids that have license issues?

**Comment by snowman2** [comment]
Okay. Here are some temporary options since the PROJ_NETWORK=ON option is not available:
1. Download the grids needed for the tests only (don't package it)
2. Don't include any grids with the tests
