### ISSUE TITLE
No manpage for /usr/bin/pyproj

### ISSUE THREAD

**Issue by sebastic** [pyproj4/pyproj#735]
The new `pyproj` commandline tool has no manpage, the triggers a lintian warning for the Debian package.

`docs/cli.rst` is not very informative either.

**Comment by snowman2** [comment]
Thanks for trying it out. I haven't attempted to make man pages. Will have to look into that. Here are the CLI docs: https://pyproj4.github.io/pyproj/latest/cli.html

**Comment by sebastic** [comment]
That looks much better, and would be good to have sphinx also build a manpage from.
