### ISSUE TITLE
3.0 Release

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#739]
https://github.com/pyproj4/pyproj/releases/tag/3.0.rc1

The plan is to release with PROJ 7.2 in the wheels and without any datumgrids (see: https://pyproj4.github.io/pyproj/latest/transformation_grids.html).

Release Candidate 1 Status:
- [x] Linux/OSX wheels (https://github.com/pyproj4/pyproj-wheels/pull/30)
- [ ] Windows wheels (ping @cgohlke)
- [x] Conda Forge (https://github.com/conda-forge/pyproj-feedstock/pull/80)
- [ ] Debian (ping @sebastic)

Plan to release when testing is completed or Wednesday, Nov 4th. Testing is always appreciated, but definitely not required.

**Comment by snowman2** [comment]
https://github.com/pyproj4/pyproj/releases/tag/3.0.rc2

Release Candidate 2 Status:
- [x] Linux/OSX wheels (https://github.com/pyproj4/pyproj-wheels/pull/30)
- [ ] Windows wheels
- [x] Conda Forge (https://github.com/conda-forge/pyproj-feedstock/pull/80)
- [ ] Debian

**Comment by sebastic** [comment]
The Debian package is available in experimental, see: https://tracker.debian.org/pkg/python-pyproj

There is still a test failure on i386:
```
=================================== FAILURES ===================================
_______________________________ test_get_factors _______________________________

    def test_get_factors():
        transformer = Proj(3717)
        factors = transformer.get_factors(-120, 34)
        assert_almost_equal(factors.meridional_scale, 1.0005466)
        assert_almost_equal(factors.parallel_scale, 1.0005466)
        assert_almost_equal(factors.areal_scale, 1.00109349)
>       assert_almost_equal(factors.angular_distortion, 0)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 1.1091199041546423e-06
E        DESIRED: 0

test/test_proj.py:478: AssertionError
============= 1 failed, 275 passed, 58 deselected in 55.49 seconds =============
```
([Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=python-pyproj&arch=i386&ver=3.0%7Erc2-1%7Eexp1&stamp=1604468827&raw=0))

But because test failures on i386 are ignored for PROJ as well, it is likewise ignored for pyproj.

**Comment by jdkloe** [comment]
Hi Bas, as pyproj packager for fedora I would like to send you a big thank you for all your testing work here. I really appreciate your efforts to get pyproj in a state that it can be packaged  including execution of all tests.
I am sorry that I cannot help here. Fedora does not yet provide proj7, and I have to wait for that before I can start upgrading pyproj to the new version.

**Comment by jorisvandenbossche** [comment]
@snowman2 I would like to test the release candidate with geopandas, but are there wheels of the rc available? (on PyPI, I only see wheels of a dev3 version of beginning of October)

**Comment by jorisvandenbossche** [comment]
Tested the rc with geopandas tests, all passing! 
(with PROJ 7.2 from conda, build pyproj from source, and fiona wheel, since conda has not yet PROJ 7.2 support throughout. The strict requirement on PROJ versions makes this a bit annoying)

**Comment by snowman2** [comment]
> because test failures on i386 are ignored for PROJ as well, it is likewise ignored for pyproj.

You can probably skip that test if the rest are passing.

**Comment by lpechacek** [comment]
I like the recent addition of test markers, @snowman2. However, shouldn't `pytest.ini` be included in `MANIFEST.in` so that the config propagates to the distribution tarball?

**Comment by snowman2** [comment]
> shouldn't pytest.ini be included in MANIFEST.in

Thanks for catching that :+1:

**Comment by snowman2** [comment]
@cgohlke, I noticed the wheels for Windows were ~20MB, so I assume you are including the datum grids. This is no longer necessary for the 3.0 wheels and not including them should make the wheels smaller. Thanks!

**Comment by cgohlke** [comment]
Thanks for the heads up. I noticed that the wheels contain a "top-level" `test` package. I don't think that is a good idea since it conflicts with several other wheels containing "top-level" `test` packages. Is this package indented or required?

**Comment by snowman2** [comment]
Definitely not supposed to be there. Thanks for the fix 👍

**Comment by snowman2** [comment]
`3.0.0.post1` is now released with the patch from @cgohlke.
