### ISSUE TITLE
CI: Migrate to GitHub Actions

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#743]
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://github.com/Toblerity/Fiona/issues/975
- https://github.com/geopandas/geopandas/pull/1576
- https://github.com/OSGeo/PROJ/pull/2377

**Comment by brendan-ward** [comment]
Also [pygeos/pygeos#222](https://github.com/pygeos/pygeos/pull/222), in case it helps as a reference point.  Note: this is focused exclusively on Conda environments at the moment.

**Comment by snowman2** [comment]
I wonder how docker rate limits (https://docs.docker.com/docker-hub/download-rate-limit/) will impact GitHub Actions?

**Comment by snowman2** [comment]
Also relevant: https://github.com/drdoctr/doctr/issues/351
