### ISSUE TITLE
Re-projection problem?

### ISSUE THREAD

**Issue by hec10r** [pyproj4/pyproj#746]
#### Code Sample, a copy-pastable example if possible

```python
import geopandas as gpd
import shapely
from pyproj import Transformer

world_shape = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
old_crs = world_shape.crs
new_crs = 'epsg:6842'

brazil = world_shape[world_shape["name"] == "Brazil"].geometry.values[0]
# I tried using both alwaysxy=True and alwaysxy=False
transformer = Transformer.from_crs(crs_from=old_crs, crs_to=new_crs, alwaysxy=True)

new_brazil = shapely.ops.transform(transformer.transform, brazil)
```
#### Problem description

I am trying to use Transformer to do some reprojections. When I use [Cylindrical Equal Area Projection](https://en.wikipedia.org/wiki/Cylindrical_equal-area_projection): `new_crs='epsg:6933'`, the result is as expected:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/53947956/98559669-e47ed480-2274-11eb-86b2-8ca0aeb7c150.png">

But, when I try to use [Sinusoidal projection](https://en.wikipedia.org/wiki/Sinusoidal_projection): [`new_crs='epsg:6842'`](https://spatialreference.org/ref/sr-org/modis-sinusoidal-3/), it doesn't look well

<img width="333" alt="image" src="https://user-images.githubusercontent.com/53947956/98559817-12fcaf80-2275-11eb-872c-fababbaa7318.png">

#### Expected Output

The output that I expect is obtained with this code:

```python
import math
# Sinusoidal Projection formula
f = lambda long, lat: (long * math.cos(math.radians(lat)), lat)

shapely.ops.transform(f, brazil)
```

<img width="117" alt="image" src="https://user-images.githubusercontent.com/53947956/98561699-3294d780-2277-11eb-92ec-02ba24df6698.png">

Am I doing something wrong?

#### Environment Information

 - Output from: `python -m pyproj -v`
```bash
pyproj info:
    pyproj: 2.6.1.post1
      PROJ: 7.0.1
  data dir: /opt/anaconda3/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
executable: /opt/anaconda3/bin/python
   machine: Linux-5.4.0-1028-aws-x86_64-with-debian-buster-sid

Python deps:
       pip: 20.2.3
setuptools: 50.3.0.post20201006
    Cython: 0.29.21
```

 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
`7.0.1`
 - PROJ data directory (`python -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
`/opt/anaconda3/lib/python3.7/site-packages/pyproj/proj_dir/share/proj`
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
`3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]`
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
`Linux-5.4.0-1028-aws-x86_64-with-debian-buster-sid`

#### Installation method
 - Installed using pip

**Comment by snowman2** [comment]
The main problem is the area of use:
```
<Projected CRS: EPSG:6842>
Name: NAD83(2011) / Oregon Coast zone (m)
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: United States (USA) - Oregon - coastal area.
- bounds: (-124.84, 41.89, -123.35, 46.4)
Coordinate Operation:
- name: Oregon Coast zone (meters)
- method: Hotine Oblique Mercator (variant A)
Datum: NAD83 (National Spatial Reference System 2011)
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```

You are using a projection in Brazil that is meant to be used in Oregon.

**Comment by hec10r** [comment]
Is there an EPSG code for a _correct_ Sinusoidal Projection?

Is there a guideline for all the possibles EPSG values?

Thanks in advance

**Comment by snowman2** [comment]
I would recommend looking at: https://pyproj4.github.io/pyproj/stable/api/database.html#pyproj-database-query-crs-info
