### ISSUE TITLE
Transformation grid management

### ISSUE THREAD

**Issue by JuliusFE** [pyproj4/pyproj#747]
```python
from pyproj import CRS, Transformer
from pyproj.transformer import TransformerGroup
from pyproj.crs import CompoundCRS, VerticalCRS, Ellipsoid
from pyproj.crs.coordinate_system import VerticalCS


crs_in = CRS('EPSG:8719')
crs_out = CRS('EPSG:4978')

tg = trans_group = TransformerGroup(crs_in, crs_out)
tg.download_grids(verbose=True)

print(tg)

transformer = Transformer.from_crs(crs_in, crs_out)

coord = [6452293.98, 1803484.19, 2319.5]
print('Start coord:')
print(coord)
print('Forward:')
coord_res = transformer.transform(coord[0], coord[1], coord[2])
print(coord_res)

print('Back:')
transformer_back = Transformer.from_crs(crs_out, crs_in)
coord_res = transformer_back.transform(coord_res[0], coord_res[1], coord_res[2])
print(coord_res)
```
#### Problem description

I am experimenting with pyproj to transform some coordinate from 'EPSG:8719' to 'EPSG:4978'.
My start coordinate is:
[6452293.98, 1803484.19, 2319.5]
I would expect the pyproj result to be identical (or at least very close to proj result). I build two docker images to install the needed packages and test the coordinate transformations. One image is based on osgeo/proj:7.2.0 (ubuntu 18.04). The second image is build with identical Docker file as osgeo/proj:7.2.0 but is based on ubuntu 20.04 instead of 18.04 (i.e. FROM ubuntu:20.04 as builder and FROM ubuntu:20.04 as runner).
If I run proj transformation for this coordinate in both images I get the following result:

docker run pyproj:3.0.0 echo 6452293.98 1803484.19 2319.5 | cs2cs +init=epsg:8719 +to +init=epsg:4978
-2408580.14	-4808738.49 3418372.07
docker run pyproj20.04:3.0.0 echo 6452293.98 1803484.19 2319.5 | cs2cs +init=epsg:8719 +to +init=epsg:4978
-2408580.14	-4808738.49 3418372.07

The results are identical in both cases. Now if I run the above provided pyproj code in both containers I get the following result:
ubuntu18.04 pyproj3.0.0:
-2408580.7005495424, -4808737.14588357, 3418372.097367031
ubuntu20.04 pyproj3.0.0:
-2408592.3930761744, -4808762.950210186, 3418389.578611745

#### Expected Output
I would expect to at least get result that is similar to proj result in ubuntu20.04.
The result of the ubuntu18.04 version is not identical but at least it is close to proj result.

#### Environment Information
Environment for ubuntu20.04:
pyproj -v
pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /usr/local/lib/python3.8/dist-packages/pyproj/proj_dir/share/proj
user_data_dir: /root/.local/share/proj

System:
    python: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable: /usr/bin/python3
   machine: Linux-5.4.0-53-generic-x86_64-with-glibc2.29

Python deps:
       pip: 20.0.2
setuptools: 45.2.0
    Cython: 0.29.21
----------------------------------------------------------------------------------------
Environment for ubuntu18.04:
pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /usr/share/proj
user_data_dir: /root/.local/share/proj

System:
    python: 3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0]
executable: /usr/bin/python3
   machine: Linux-5.4.0-53-generic-x86_64-with-Ubuntu-18.04-bionic

Python deps:
       pip: 9.0.1
setuptools: 39.0.1
    Cython: 0.29.21

#### Installation method
All the experiments were performed in docker container.
The docker file for creating the container is as follows:

```
FROM osgeo/proj:7.2.0 # this one is ubuntu18.04, created custom for ubuntu20.04

# install the required packages
RUN apt update && apt install -y software-properties-common
RUN apt update && apt install -y python3 python3-pip

RUN pip3 install Cython
RUN pip3 install pyproj

ADD . /packages

CMD python3 /packages/proj_test.py
```

**Comment by snowman2** [comment]
I would recommend ensuring that you ensure everything is as consistent as possible. To do so, I would recommend compiling pyproj against the PROJ in the docker container instead of using the version provided in the wheel. The version of PROJ in the docker container is more aware of the location of the transformation grids as that is added when compiling PROJ.

```bash
pip3 install pyproj --no-binary pyproj
```

From what I found on my machine with Ubuntu 20.04 (not the docker), and the pyproj wheel, if I added:
```python
import pyproj

pyproj.network.set_network_enabled(True)
```
The results were closer to expected:
```
(-2408580.7005495424, -4808737.14588357, 3418372.097367031)
```
But, when I didn't do that, then the results were:
```
(-2408592.332679458, -4808762.992329043, 3418389.5620289254)
```
This leads me to believe that the transformation grids are not being found:
https://pyproj4.github.io/pyproj/stable/transformation_grids.html

You can either add the `PROJ_LIB` environment variable or in python:
https://pyproj4.github.io/pyproj/stable/api/datadir.html

This may also be helpful for you when debugging:
https://pyproj4.github.io/pyproj/stable/advanced_examples.html#debugging-internal-proj

**Comment by snowman2** [comment]
The results from `pyproj` with `PROJ_NETWORK=ON` match the results I get from PROJ:
```bash
$ echo 6452293.98 1803484.19 2319.5 | cs2cs 'epsg:8719' 'epsg:4978'
-2408580.70	-4808737.15 3418372.10
$ echo 6452293.98 1803484.19 2319.5 | cs2cs +init=epsg:8719 +to +init=epsg:4978
-2408580.70	-4808737.15 3418372.10
```

**Comment by JuliusFE** [comment]
Hi, thanks for the reply.

The suggested corrections did solve the issue to some extent.
I only needed to do this:
pip3 install pyproj --no-binary pyproj
Adding this did not improve things:
pyproj.network.set_network_enabled(True)


So now in both containers I get this when performing transformation with pyproj:
(-2408580.7005495424, -4808737.14588357, 3418372.097367031)

There is still however a small difference between this and what I get from proj:
docker run pyproj:3.0.0 echo 6452293.98 1803484.19 2319.5 | cs2cs 'epsg:8719' 'epsg:4978'
-2408580.14	-4808738.49 3418372.07

Not sure how significant this difference is or why it happens.

Also not sure if its possible but would be nice that TransformerGroup would return some error when it can't find the files. This is of course just a suggestion.

**Comment by snowman2** [comment]
> Not sure how significant this difference is or why it happens.

I think the best way to figure out what is happening is to use the debugging options available:
https://pyproj4.github.io/pyproj/stable/advanced_examples.html#debugging-internal-proj

Here is what I see:
```
$ echo 6452293.98 1803484.19 2319.5 | PROJ_DEBUG=2 cs2cs 'epsg:8719' 'epsg:4978'
,,,
pj_open_lib(us_noaa_cshpgn.tif): call fopen(.../share/proj/us_noaa_cshpgn.tif) - failed
pj_open_lib(cshpgn.gsb): call fopen(.../share/proj/cshpgn.gsb) - failed
Using https://cdn.proj.org/us_noaa_cshpgn.tif
pj_open_lib(us_noaa_g1999u05.tif): call fopen(.../share/proj/us_noaa_g1999u05.tif) - failed
pj_open_lib(g1999u05.gtx): call fopen(.../share/proj/g1999u05.gtx) - failed
Using https://cdn.proj.org/us_noaa_g1999u05.tif
-2408580.70	-4808737.15 3418372.10
```

> Also not sure if its possible but would be nice that TransformerGroup would return some error when it can't find the files

Currently it shows a warning if the best transformation is not found, the `repr` shows a summary of the transformations available, and this is something you can check with the `best_available`, `transformers`, and `unavailable_operations` properties:

```python
>>> from pyproj.transformer import TransformerGroup
>>> tg = TransformerGroup('epsg:8719', 'epsg:4978')
~/pyproj/transformer.py:81: UserWarning: Best transformation is not available due to missing Grid(short_name=us_noaa_cshpgn.tif, full_name=, package_name=, url=https://cdn.proj.org/us_noaa_cshpgn.tif, direct_download=True, open_license=True, available=False)
  super().__init__(
>>> tg
<TransformerGroup: best_available=False>
- transformers: 2
- unavailable_operations: 12
>>> tg.best_available
False
```

**Comment by JuliusFE** [comment]
Hi,

Sorry for the delay.
So I have tried running the cs2cs in the container with the debug flag and I get this:
echo 6452293.98 1803484.19 2319.5 | PROJ_DEBUG=2 cs2cs 'epsg:8719' 'epsg:4978'
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
pj_open_lib(us_noaa_azhpgn.tif): call fopen(/usr/share/proj/us_noaa_azhpgn.tif) - succeeded
pj_open_lib(us_noaa_cshpgn.tif): call fopen(/usr/share/proj/us_noaa_cshpgn.tif) - succeeded
pj_open_lib(nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b): call fopen(/usr/share/proj/nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b) - failed
pj_open_lib(nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b): call fopen(/usr/share/proj/nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b) - failed
pj_open_lib(us_noaa_conus.tif): call fopen(/usr/share/proj/us_noaa_conus.tif) - succeeded
pj_open_lib(nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b): call fopen(/usr/share/proj/nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b) - failed
pj_open_lib(nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b): call fopen(/usr/share/proj/nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b) - failed
pj_open_lib(us_noaa_g2018u0.tif): call fopen(/usr/share/proj/us_noaa_g2018u0.tif) - succeeded
pj_open_lib(us_noaa_geoid03_conus.tif): call fopen(/usr/share/proj/us_noaa_geoid03_conus.tif) - succeeded
pj_open_lib(us_noaa_geoid09_conus.tif): call fopen(/usr/share/proj/us_noaa_geoid09_conus.tif) - succeeded
pj_open_lib(us_noaa_vertconw.tif): call fopen(/usr/share/proj/us_noaa_vertconw.tif) - succeeded
pj_open_lib(us_noaa_g1999u05.tif): call fopen(/usr/share/proj/us_noaa_g1999u05.tif) - succeeded
pj_open_lib(us_noaa_cshpgn.tif): call fopen(/usr/share/proj/us_noaa_cshpgn.tif) - succeeded
pj_open_lib(us_noaa_g1999u05.tif): call fopen(/usr/share/proj/us_noaa_g1999u05.tif) - succeeded
-2408580.70	-4808737.15 3418372.10

So the result of cs2cs in my case is identical to yours. Sorry for the confusion in my last post. There I was calling the docker command incorrectly and therefore not getting the result from the container but from local. I had to run docker internal bash and then my proj result is identical to yours.

Thank you very much for the help.

**Comment by JuliusFE** [comment]
So I double checked the setup again.
If I install pyproj in the normal way i.e.:
pip3 install pyproj

And run the following proj code:
```
from pyproj import CRS, Transformer
from pyproj.transformer import TransformerGroup
from pyproj.crs import CompoundCRS, VerticalCRS, Ellipsoid
from pyproj.crs.coordinate_system import VerticalCS
import pyproj

#pyproj.network.set_network_enabled(True)


crs_in = CRS('EPSG:8719')
crs_out = CRS('EPSG:4978')

crs_in = CompoundCRS('Test', components=['EPSG:2230', 'EPSG:6360'])


tg = trans_group = TransformerGroup(crs_in, crs_out)
tg.download_grids(verbose=True)

print(tg)

transformer = Transformer.from_crs(crs_in, crs_out)

coord = [6452293.98, 1803484.19, 2319.5]
print('Start coord:')
print(coord)
print('Forward:')
coord_res = transformer.transform(coord[0], coord[1], coord[2])
print(coord_res)

print('Back:')
transformer_back = Transformer.from_crs(crs_out, crs_in)
coord_res = transformer_back.transform(coord_res[0], coord_res[1], coord_res[2])
print(coord_res)
```

This is what I get:
```
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:81: UserWarning: Best transformation is not available due to missing Grid(short_name=us_noaa_cshpgn.tif, full_name=, package_name=, url=https://cdn.proj.org/us_noaa_cshpgn.tif, direct_download=True, open_license=True, available=False)
  super().__init__(
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:156: UserWarning: Skipped: 
  warnings.warn(f"Skipped: {grid}")
Downloading: https://cdn.proj.org/us_noaa_cshpgn.tif
Downloading: https://cdn.proj.org/us_noaa_conus.tif
Downloading: https://cdn.proj.org/us_noaa_azhpgn.tif
<TransformerGroup: best_available=False>
- transformers: 2
- unavailable_operations: 12
Start coord:
[6452293.98, 1803484.19, 2319.5]
Forward:
(-2408592.3930761744, -4808762.950210186, 3418389.578611745)
Back:
(6452293.980000002, 1803484.1899998568, 2319.50000000659)
```

To me the 'Downloading' messages here seem to be quite confusing.
If I enable the networking:
pyproj.network.set_network_enabled(True)

I get the correct result:
```
<TransformerGroup: best_available=True>
- transformers: 8
- unavailable_operations: 6
Start coord:
[6452293.98, 1803484.19, 2319.5]
Forward:
(-2408580.7005495424, -4808737.14588357, 3418372.097367031)
Back:
(6452293.980000105, 1803484.1899999636, 2319.5000003879395)
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:156: UserWarning: Skipped: nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b
  warnings.warn(f"Skipped: {grid}")
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:156: UserWarning: Skipped: nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b
  warnings.warn(f"Skipped: {grid}")
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:156: UserWarning: Skipped: nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b
  warnings.warn(f"Skipped: {grid}")
/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py:156: UserWarning: Skipped: nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b
  warnings.warn(f"Skipped: {grid}")
```

So the conclusion is either install with `pip3 install pyproj --no-binary pyproj` or install standard and enable network.
Not sure how important the Downloading message but if you think that it can be as it is now then feel free to just close this issue.
Thank you very much again for the help.

**Comment by snowman2** [comment]
Unfortunately, those grids cannot be downloaded via `TransformerGroup`.

Here is the relevant code:
https://github.com/pyproj4/pyproj/blob/e3c05dd0e3f3583d610741d484c14cdeba1ca7f0/pyproj/transformer.py#L141-L156

If you look at the grids not downloaded:
```python
tg = TransformerGroup("EPSG:2230+6360", "EPSG:4978")
>>> for unavailable_operation in tg.unavailable_operations:
...     print(unavailable_operation.name)
...     for grid in unavailable_operation.grids:
...         print(repr(grid))
... 
```
Then you see the URL is missing and cannot be retrieved by pyproj:
```
Inverse of SPCS83 California zone 6 (US Survey feet) + NAD83 to NAD83(HARN) (47) + NAD83(HARN) to WGS 84 (3) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Inverse of SPCS83 California zone 6 (US Survey feet) + NAD83 to NAD83(HARN) (47) + NAD83(HARN) to WGS 84 (1) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Inverse of SPCS83 California zone 6 (US Survey feet) + Inverse of NAD27 to NAD83 (7) + NAD27 to WGS 84 (79) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=us_noaa_conus.tif, full_name=~/.local/share/proj/us_noaa_conus.tif, package_name=, url=https://cdn.proj.org/us_noaa_conus.tif, direct_download=True, open_license=True, available=True)
Inverse of SPCS83 California zone 6 (US Survey feet) + Inverse of NAD27 to NAD83 (7) + NAD27 to WGS 84 (6) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Inverse of SPCS83 California zone 6 (US Survey feet) + Inverse of NAD27 to NAD83 (7) + NAD27 to WGS 84 (4) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Inverse of SPCS83 California zone 6 (US Survey feet) + Inverse of NAD27 to NAD83 (7) + NAD27 to WGS 84 (18) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lat.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)
Grid(short_name=nadcon5.nad27.nad83_1986.conus.lon.trn.20160901.b, full_name=, package_name=, url=, direct_download=False, open_license=False, available=False)

```
In that scenario, the best way to determine the grids you need to download via PROJ_DEBUG as shown in your comment: https://github.com/pyproj4/pyproj/issues/747#issuecomment-730658338

**Comment by snowman2** [comment]
If you have the correct version of PROJ installed in your system, I would use `--no-binary pyproj` instead of the wheels.

**Comment by snowman2** [comment]
> To me the 'Downloading' messages here seem to be quite confusing.

What is the confusing part?

**Comment by JuliusFE** [comment]
Well at first glance my ignorant assumption was that if the message says that its 'Downloading' it will be downloaded and will work out of the box. In any case I think we can now close this issue. My problem was solved. Thanks very much for all the help.

**Comment by snowman2** [comment]
@JuliusFE, thanks for raising this issue and for being thorough. I think adding some warnings in the documentation for `download_grids` would be appropriate to highlight that it might not download all of the grids you may need.
