### ISSUE TITLE
Cannot see transform definition following #377 and #378

### ISSUE THREAD

**Issue by rsbivand** [pyproj4/pyproj#753]
```python
import pyproj
pyproj.show_versions()
from pyproj import Transformer
transformer = Transformer.from_crs(27700, 4326, always_xy=True)
transformer
transformer.operations
transformer.transform(0, 0)
```
#### Problem description

#377 and #378 suggest that the tranform descriptions and definitions should now be available when building from main/master. I see:

```
pyproj info:
    pyproj: 3.0.1.dev0
      PROJ: 7.2.0
  data dir: /usr/local/share/proj
user_data_dir: /home/rsb/.local/share/proj

System:
    python: 3.9.0 (default, Oct  6 2020, 00:00:00)  [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
executable: /usr/bin/python3
   machine: Linux-5.9.11-200.fc33.x86_64-x86_64-with-glibc2.32

Python deps:
       pip: 20.2.2
setuptools: 49.1.3
    Cython: 0.29.21
<Unknown Transformer: unknown>
Description: unavailable until proj_trans is called
Area of Use:
- undefined
()
(-7.557159806905192, 49.76680723514262)
```

#### Expected Output

From the comments to #377 and #378, I would expect the tuple () not to be empty. The definition returned by R package **rgdal** for 'EPSG:27700* to 'OGC:CRS84* (vis-order and as used by geojson) and used by **sf** (which does not return its pipeline) is:

```
"+proj=pipeline +step +inv +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +step +proj=push +v_3 +step +proj=cart +ellps=airy +step +proj=helmert +x=446.448 +y=-125.157 +z=542.06 +rx=0.15 +ry=0.247 +rz=0.842 +s=-20.489 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg"
```

**rgdal**, **sf** and pyproj return the same output coordinates for the sam input, but I'd thought that #378 corrected the omission.

My source and installed transformer.py do not have self.operations (as far  as I can tell) - did #378 make it through to  the main branch, or should I be looking at a different branch?

#### Environment Information

See above

#### Installation method
pip from source

**Comment by snowman2** [comment]
You may find the transformer group will better enable you to see what is going on:
```python
>>> from pyproj.transformer import TransformerGroup
>>> tg = TransformerGroup(27700, 4326, always_xy=True)
>>> tg
<TransformerGroup: best_available=True>
- transformers: 9
- unavailable_operations: 0
>>> tg.transformers[0]
<Concatenated Operation Transformer: pipeline>
Description: Inverse of British National Grid + OSGB 1936 to WGS 84 (9) + axis order change (2D)
Area of Use:
- name: United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.
- bounds: (-9.0, 49.75, 2.01, 61.01)

```

**Comment by snowman2** [comment]
The `Transformer` class does not show what transformations are used because there are several to choose from and it chooses the one it thinks it is best for each coordinate.

**Comment by rsbivand** [comment]
Thanks, this clarifies. The R **sf** package `st_transform()` methods do the same as `Transformer.transform()`, while **rgdal** methods assign the last used pipeline in a package specific environment outside the scope of the method function, so that subsequent operations can use the discovered pipeline. I needed to do this to see whether on-demand downloaded grids were actually being used. Now:
```
from pyproj.transformer import TransformerGroup
tg = TransformerGroup(geodf.crs, 'OGC:CRS84', always_xy=True)
tg.transformers[0].definition
tg.transformers[0].transform(0, 0)
```
aligns as expected with the R package methods.
