### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [pyproj4/pyproj#756]
**Summary**
Installing pyproj on aarch64 via pip using command "pip3 install pyproj" tries to build wheel from source code

**Problem description**
pyproj doesn't have wheel for aarch64 on PyPI repository. So, while installing pyproj via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pyproj. Making wheel available for aarch64 will benefit aarch64 users by minimizing pyproj installation time.

**Expected Output**
Pip should be able to download pyproj wheel from PyPI repository rather than building it from source code.

@pyproj-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pyproj wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by snowman2** [comment]
Feel free to submit a PR to https://github.com/pyproj4/pyproj-wheels/

**Comment by odidev** [comment]
@snowman2 Thanks for your quick response, I will start working on it and will raise a PR.
