### ISSUE TITLE
projection parameters from grib file

### ISSUE THREAD

**Issue by nikhil003** [pyproj4/pyproj#759]
I am trying to process some grib files, where I need to get the projection information from the file. When doing so, I extract the `projparams` for the grib message, which is a dictionary with projection parameters. Afterwards, I try to instantiate a `Proj` object but get error when try to do so.

```python
import pygrib
import pyproj
fin = pygrib.open('./IDY25026.APS3.wind.10m.2019092412.006.surface.grb2')
grbs = [grb for grb in fin]
pyproj.Proj(grbs[0].projparams)
```

I have tried this with pyproj version **1.9.6** and pygrib version **2.0.3**

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gar305/Documents/geostack/pyinstall/lib/python3.7/site-packages/pyproj/__init__.py", line 362, in __new__
>     return _proj.Proj.__new__(self, projstring)
>   File "_proj.pyx", line 129, in _proj.Proj.__cinit__
> RuntimeError: b'unknown projection id'
> 

The projparams are 

> {'a': 6371229, 'b': 6371229, 'proj': 'cyl'}

The files I am testing with is **ftp://ftp.bom.gov.au/register/sample/access/grib2/ACCESS-G3/IDY25026.APS3.wind.10m.2019092412.006.surface.grb2**.

I have also tested it with a pyproj version **2.4.2.post1** and the results aren't much different. Here is the traceback from version **2.4.2.post1**

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pyproj/proj.py", line 146, in __init__
>     self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pyproj/crs.py", line 456, in from_user_input
>     return cls(value)
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pyproj/crs.py", line 312, in __init__
>     super(CRS, self).__init__(projstring)
>   File "pyproj/_crs.pyx", line 1738, in pyproj._crs._CRS.__init__
> pyproj.exceptions.CRSError: Invalid projection: +proj=cyl +a=6371229 +b=6371229 +type=crs: (Internal Proj Error: proj_create: Error -5: unknown projection id)
>

**Comment by snowman2** [comment]
`cyl` is not currently a supported projection in PROJ.

```python
from pyproj.list import get_proj_operations_map
pj_map = get_proj_operations_map()
>>> pj_map["cyl"]
...
KeyError: 'cyl'
```
I am going to close this and recommend you go upstream and ask your question here: https://github.com/osgeo/PROJ, They may be able to help you figure our where `cyl` came from and/or how to get it added.
