### ISSUE TITLE
Update error handling

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#760]
https://github.com/OSGeo/PROJ/pull/2487

This will be a breaking change. Previous behavior is deprecated.
```
As of PROJ 8.0.0, this function is deprecated as potentially thread-unsafe.  Users should use `proj_context_errno_string` instead.
```

**Comment by rouault** [comment]
> This will be a breaking change

What exactly do you see as deprecated (apart proj_errno_string()) ?

**Comment by snowman2** [comment]
I should clarify that it will be a change that will break things in the future and pyproj should make changes now to be ready for it.
