### ISSUE TITLE
from pyproj._network import ( # noqa: f401 importerror: dll load failed while importing _network: the specified module could not be found.

### ISSUE THREAD

**Issue by Saidsp19** [pyproj4/pyproj#770]
#### Installation method/steps
 - Installation method (conda, pip wheel, from source, etc...)
         ans: Downloaded file from download files
  
 - How did you install PROJ? Where is it installed?
       ans: , install using:  pip install filename(which i downloaded from download file) and it is install inside site-packages in Lib in Python39
 - Please provide all commands/steps you used to install pyproj and PROJ.
     pip install pyproj-3.0.0.post1-cp38-cp38-win_amd64.whl
                     
#### Environment Information
 - pyproj version you are attempting to install
        3.0.0.post1
 - PROJ version (Execute `proj` command and give version here.)
      3.0.0.post1
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
     3.8
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
  windows 10

**Comment by snowman2** [comment]
Please fill out the form so we can help you. Thanks :+1:

**Comment by Saidsp19** [comment]
please share form , then i will fill

**Comment by snowman2** [comment]
The form is in the initial comment of this issue. You just need to edit it and add in the information relevant to your issue.

**Comment by Saidsp19** [comment]
please check form

**Comment by snowman2** [comment]
The windows wheels come from: https://www.lfd.uci.edu/~gohlke/pythonlibs/. Please follow the instructions at the top of the page to see if that helps.

**Comment by Saidsp19** [comment]
I'm using pip version 20.3.3 , as per instruction it is correct and I followed like below

pip install pyproj-3.0.0.post1-cp38-cp38-win_amd64.whl

**Comment by snowman2** [comment]
Looks like you are using `cp38` with Python 3.9. I recommend trying the `cp39` with Python 3.9.

**Comment by Saidsp19** [comment]
No, I'm using cp38 with python 3.8

**Comment by Saidsp19** [comment]
I  think that is correct only

**Comment by snowman2** [comment]
@cgohlke, do you have any insight or recommendations?

**Comment by cgohlke** [comment]
Try installing the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0).

**Comment by snowman2** [comment]
@Saidsp19 did installing the Microsoft Visual C++ Redistributable work?

**Comment by Saidsp19** [comment]
I need to work with offline mode , so please suggest me way to install Microsoft Visual C++ Redistributable without internet . I need to install from local downloaded files.

**Comment by Saidsp19** [comment]
@cgohlke @snowman2  I looking for your valuable Information regarding my query

**Comment by Saidsp19** [comment]
Wow ... finally, My issue get resolved using Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019.


Thank you very much and really appreciate your responses to this issue @snowman2 @cgohlke

**Comment by grgmiller** [comment]
I was experiencing this same issue, and tried this proposed fix without success. What ended up fixing this for me was: https://github.com/Toblerity/Fiona/issues/944#issuecomment-917454817
