### ISSUE TITLE
Incorrect transform from epsg 27200 to epsg4326

### ISSUE THREAD

**Issue by dennisgoo** [pyproj4/pyproj#771]
Using Transformer.from_crs() to transform a coordinate from epsg 27200 to epsg4326 or to epsg 2193 does not return the correct result.

**Comment by snowman2** [comment]
Please fill out the bug report template using [this](https://github.com/pyproj4/pyproj/issues/new?assignees=&labels=bug&template=bug_report.md) workflow. The information provided is not sufficient for us to be able to assist you.

**Comment by dennisgoo** [comment]
Thanks. I just figured out that it's the my environment issue. The Transformer.from_crs() does its job.
