### ISSUE TITLE
BUG: query_utm_crs_info segfaults with NaN area of interest

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#788]
#### Code Sample, a copy-pastable example if possible

From https://github.com/geopandas/geopandas/issues/1868

When passing (invalid) NaN values as area of interest, the utm query crashes:

```python
In [1]: from pyproj.aoi import AreaOfInterest

In [2]: area_of_interest = AreaOfInterest(np.nan, np.nan, np.nan, np.nan)

In [3]: from pyproj.database import query_utm_crs_info

In [4]: query_utm_crs_info(datum_name="WGS 84", area_of_interest=area_of_interest)
Segmentation fault (core dumped)
```

#### Environment Information

pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /home/joris/miniconda3/envs/geopandas09/share/proj
user_data_dir: /home/joris/.local/share/proj

System:
    python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46)  [GCC 9.3.0]
executable: /home/joris/miniconda3/envs/geopandas09/bin/python
   machine: Linux-5.4.0-66-generic-x86_64-with-glibc2.31

Python deps:
       pip: 21.0.1
setuptools: 49.6.0.post20210108
    Cython: None

**Comment by snowman2** [comment]
Running low on Travis credits for wheel building (will need to request more OSS credits). Going to wait for 3.1 for this fix.
