### ISSUE TITLE
"What is the best format to store the CRS information?" in FAQ is not answering the question

### ISSUE THREAD

**Issue by matkoniecz** [pyproj4/pyproj#789]
https://pyproj4.github.io/pyproj/latest/gotchas.html#what-is-the-best-format-to-store-the-crs-information is explaining that PROJ strings are a bad idea, but provide no answer what is the proper format

Answer seems to be in https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems

Not making PR as I am unsure whatever it would be better to change question "Why PROJ strings are a bad idea?" or add an aswer.

**Comment by snowman2** [comment]
@matkoniecz, you can submit a PR based on what is used by geopandas:
https://geopandas.readthedocs.io/en/latest/docs/user_guide/projections.html#what-is-the-best-format-to-store-the-crs-information
