### ISSUE TITLE
FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6   projstring = _prepare_from_string(" ".join((projstring, projkwargs))

### ISSUE THREAD

**Issue by Saidsp19** [pyproj4/pyproj#796]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here
```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Environment Information

 - Output from: `pyproj -v`

 - Output from: `python -m pyproj -v`

 - Output from: `python -c "import pyproj; pyproj.show_versions()"`

 - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
 - PROJ data directory (`python -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

#### Installation method
 - conda, pip wheel, from source, etc...

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by snowman2** [comment]
Not enough information. Closing soon if clarity is not added to this issue.

**Comment by Saidsp19** [comment]
After the Execution of the complete code, then the following message came in the terminal in vs code

**Comment by snowman2** [comment]
This is the desired behavior. Please read: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6 for how to update.

**Comment by snowman2** [comment]
Essentially replace `+init=epsg:4326` with `EPSG:4326` and be careful of axis order changes (#538).
