### ISSUE TITLE
'Geod' object has no attribute 'geometry_length'

### ISSUE THREAD

**Issue by qli341519** [pyproj4/pyproj#804]
Tried the example code provided in the documentation page: https://pyproj4.github.io/pyproj/stable/api/geod.html#pyproj.Geod.geometry_length

Error: 'Geod' object has no attribute 'geometry_length'

pyproj version: 3.0.0

**Comment by snowman2** [comment]
Please add the output of `pyproj -v`

**Comment by snowman2** [comment]
Unfortunately, we won't be able to help you without more information. From the docs, you need version `2.3.0+` for this to work. I suspect you are having installation issues. If you are able to provide the output of `python -m pyproj -v`, please add another comment with this information.
