### ISSUE TITLE
would it be possible to have the CRS bounds in its original unit ? 

### ISSUE THREAD

**Issue by 12rambau** [pyproj4/pyproj#809]
Let's assume I want to get the bounds of the projection 'EPSG:3857' in meters (unit of the 3857 projection)

In the current implementation of pyproj and with my little knowledge I would do the following : 
```python
from pyproj import CRS, Transformer

in_crs = CRS.from_epsg(4326)
out_crs = CRS.from_epsg(3857)
x_min, y_min, x_max, y_max = out_crs.area_of_use.bounds

proj = Transformer.from_crs(4326, 3857, always_xy=True)
bl = proj.transform(x_min, y_min)
tr = proj.transform(x_max, y_max)
```

that's a lot of steps just to extract the bounds in the original proj unit. 
Would it be possible to add a method to retrieve the projection in its original unit ? 

I would be happy to PR this very code in PR if you agree with this way of computing it. 

> maybe I'm foolish and there is already a way to retrieve the bounds...

**Comment by snowman2** [comment]
To transform the boundary properly, would likely need a method similar to:
https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.transform_bounds

**Comment by snowman2** [comment]
PROJ does something similar:
https://github.com/OSGeo/PROJ/blob/5fb47f125c25751bd1b1018849de9e7ee69107f4/src/4D_api.cpp#L974-L1043

**Comment by snowman2** [comment]
How to get projected bounds with #810:
```python
from pyproj import CRS, Transformer
crs = CRS("EPSG:3857")
transformer = Transformer.from_crs(crs.geodetic_crs, crs, always_xy=True)
transformer.transform_bounds(*crs.area_of_use.bounds)
```

**Comment by 12rambau** [comment]
awesome ! thanks a lot

**Comment by snowman2** [comment]
Release is coming soon. Hopefully by the end of the week 🤞
