### ISSUE TITLE
Proj() slowing down with PROJ 7.2.1+

### ISSUE THREAD

**Issue by ravi-nallapu** [pyproj4/pyproj#827]
### The `Proj()` function in pyproj 3.0.1 appears to be slower that its counterpart in version 3.0.0. 

 **The following test script can be used to demonstrate this issue:**

    from pyproj import Proj
    import time
    
    test_crs = {"proj": "omerc",
    "lat_0": 45.0,
    "lonc": 45.0,
    "k": 1,
    "alpha": -45.0,
    "gamma": 0.0,
    "units": "m",
    "ellps": "WGS84",
    "no_defs": True,
    }
    n_runs = 100
    
    t0 = time.time()
    for i in range(n_runs):
        Proj(test_crs, preserve_units=True)
    
    t_exec = time.time()-t0
    
    print(f"Execution time: {t_exec} secs")

**The following console outputs were noted when running with different versions of the Pyproj library:**
- When using Version 3.0.1, the output was:
`Execution time: 3.026028871536255 secs`

- When using version 3.0.0, the output was:
`Execution time: 0.12688589096069336 secs`

In this case, the `Proj()` function in 3.0.0 Appears to be ~20x faster than its counterpart in 3.0.1.

**Comment by snowman2** [comment]
Output of `pyproj -v` for both versions?

**Comment by ravi-nallapu** [comment]
**For 3.0.1, it was:**

    pyproj info:
        pyproj: 3.0.1
          PROJ: 7.2.1
      data dir: /Users/ravi.nallapu/Library/Python/3.8/lib/python/site-packages/pyproj/proj_dir/share/proj
    user_data_dir: /Users/ravi.nallapu/Library/Application Support/proj
    
    System:
        python: 3.8.2 (default, Dec 21 2020, 15:06:04)  [Clang 12.0.0 (clang-1200.0.32.29)]
    executable: /Library/Developer/CommandLineTools/usr/bin/python3
       machine: macOS-11.2.3-x86_64-i386-64bit
    
    Python deps:
           pip: 21.0.1
    setuptools: 41.2.0
        Cython: None

**For 3.0.0, it is:**

    pyproj info:
        pyproj: 3.0.0
          PROJ: 7.2.0
      data dir: /Users/ravi.nallapu/Library/Python/3.8/lib/python/site-packages/pyproj/proj_dir/share/proj
    user_data_dir: /Users/ravi.nallapu/Library/Application Support/proj
    
    System:
        python: 3.8.2 (default, Dec 21 2020, 15:06:04)  [Clang 12.0.0 (clang-1200.0.32.29)]
    executable: /Library/Developer/CommandLineTools/usr/bin/python3
       machine: macOS-11.2.3-x86_64-i386-64bit
    
    Python deps:
           pip: 21.0.1
    setuptools: 41.2.0
        Cython: None

**Comment by snowman2** [comment]
Have you tried using PROJ 7.2.0 with both versions?

**Comment by ravi-nallapu** [comment]
No, I have not, is there a way to use PROJ 7.2.0 with 3.0.1?

**Comment by snowman2** [comment]
The simplest method is to use conda:

```
conda create -n proj720 -c conda-forge proj=7.2.0 pyproj=3.0.1
conda activate proj720
```

**Comment by ravi-nallapu** [comment]
**The code is fast when using Proj 7.2.0**

- Here is the execution time:

`Execution time: 0.11581015586853027 secs`

- And here is the output for `pyproj -v`:

      pyproj info:
          pyproj: 3.0.1
            PROJ: 7.2.0
        data dir: /Users/ravi.nallapu/anaconda3/envs/proj720/share/proj
      user_data_dir: /Users/ravi.nallapu/Library/Application Support/proj
      
      System:
          python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
      executable: /Users/ravi.nallapu/anaconda3/envs/proj720/bin/python
         machine: macOS-11.2.3-x86_64-i386-64bit
      
      Python deps:
             pip: 21.0.1
      setuptools: 49.6.0.post20210108
          Cython: None

**Comment by snowman2** [comment]
I wonder how it is with PROJ 8?

Here is are the changes in 7.2.1: https://github.com/OSGeo/PROJ/releases/tag/7.2.1

**Comment by davidghiurco** [comment]
I have just tested `pyproj==3.1.0` and it has the same exact runtime problem as `pyproj==3.0.1`

**Comment by snowman2** [comment]
PROJ 7.2.0 is faster than  PROJ 7.2.1+ regardless of the version of pyproj.

**Comment by snowman2** [comment]
Git bisect says: `42fa3b5791d7a53988afe9d97f52dcea41918f40 is the first bad commit`

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/pull/2474

**Comment by snowman2** [comment]
Forwarded: https://github.com/OSGeo/PROJ/issues/2734

**Comment by snowman2** [comment]
Also, as a note for those with single threaded applications, this can improve the speed: https://pyproj4.github.io/pyproj/stable/api/global_context.html

**Comment by snowman2** [comment]
3.3.0 should have this resolved.
