### ISSUE TITLE
Adding new projection - Cupola

### ISSUE THREAD

**Issue by dkapitan** [pyproj4/pyproj#839]
Recently Weia Reinboud defined a new asymmetric equal area projection, named Cupola, see [this journal paper here](https://www.tandfonline.com/eprint/EE7Y8RK4GXA4ITWUTQPY/full?target=10.1080/23729333.2020.1862962).

She has actually written the code herself and I offered to help contribute the Cupola projection to the open source community. Now I am quite proficient with Python, but not that experienced with geodata processing.

I thought that I could implement a projection directly in WKT, but apparently that's not the case? Basically the pseudo-code below is what I want to implement.

```python
# parameters for Cupola
c1 = 0.5253 # part of the equator on intermediate sphere, default = 1
c2 = 0.7264 # sin of angle of polarline; default = 1
c3 = 0.4188 # height of the equator, can be negative, default = 0
c4 = 22.00 # phi of centre projection in degrees, default = 0
c5 = 0.9701 # strech in plane, default = 1

# constants
c6 = 11.023  # central meridian 11.023 degrees, also defines border of the map
c7 = 180.00 # degrees to the right of c6, default = 180
grid = 30 # grid distance in degrees
r2 = 1.61885660611815
w123 = 0.258701109423297
c4r = 0.383972435438752
pc = 0.559562341761853


def cupola_projection(u , v, c1, c2, c5, r2, w123, spc, cpc, qc):
    """
    (phi, lambda) as (lat, lon) in degrees --> (u, v) in radians --> (p, q) in radians on intermediate sphere --> (x, y) cartographic projection.
    """
    spc = sin(pc)
    cpc = cos(pc)
    c6 = c6+(180-c7)
    c6r = pi * c6/180  # c6 in [rad], v of center of projection
    qc = c1*c6r

    # calculate (p, q)
    p = asin(c2*sin(u)+w123)
    sp = sin(p)
    cp = cos(p)
    q = c1*v

    qqc = q-qc
    sqqc = sin(qqc)
    cqqc = cos(qqc)
    
    # k is Snyder's constant, taken as product with r2:
    r2k = r2 * sqrt(2/(1+spc*sp+cpc*cp*cqqc));
 
    return (r2k*cp*sqqc*c5, r2k*(cpc*sp-spc*cp*cqqc)/c5)
```

Can anyone point me in the right direction what the best way is to implement this for the Python geostack. My main aim is to be able to use this projection for drawing choropleth maps.

**Comment by snowman2** [comment]
The best way to get the projection added to pyproj is to add it to PROJ: https://github.com/osgeo/PROJ/. In doing so, you will get it added to GDAL/QGIS/etc.

**Comment by dkapitan** [comment]
@snowman2 
Thanks, that was my second guess. Have posted a request there, too. https://github.com/OSGeo/PROJ/issues/2706.

**Comment by snowman2** [comment]
Closing for preference to the PROJ issue.
