### ISSUE TITLE
3.1 Release

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#853]
https://github.com/pyproj4/pyproj/releases/tag/3.1rc1

The plan is to release with PROJ 8.0.1 in the wheels.

Release Candidate 1 Status:
- [x] Linux/OSX wheels (https://github.com/pyproj4/pyproj-wheels/pull/35)
- [ ] Windows wheels (ping @cgohlke)
- [x] Conda Forge (https://github.com/conda-forge/pyproj-feedstock/pull/91)
- [x] Debian (ping @sebastic)

Plan to release when testing is completed or Monday, May 24th. Testing is always appreciated, but definitely not required.

**Comment by snowman2** [comment]
Actually, pause on the testing... I may delay the release.

**Comment by snowman2** [comment]
Nevermind, all good to go.

**Comment by sebastic** [comment]
With the fix for #849 the Debian package builds successfully on all release architectures:

 https://buildd.debian.org/status/package.php?p=python-pyproj&suite=experimental

Due to the freeze in preparation of the bullseye stable release it won't be moved to unstable any time soon.

**Comment by snowman2** [comment]
Thanks for testing @sebastic 👍

**Comment by snowman2** [comment]
Thanks for building the wheels @cgohlke :+1:
