### ISSUE TITLE
ValueError: array.array size changed, may indicate binary incompatibility on PyPy

### ISSUE THREAD

**Issue by cgohlke** [pyproj4/pyproj#854]
Importing pyproj 3.0.1 on PyPy for Windows raises the following error:
```Python-traceback
Python 3.7.10 (77787b8f4c49, May 15 2021, 11:51:36)
[PyPy 7.3.5 with MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pyproj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "X:\pypy3\site-packages\pyproj\__init__.py", line 64, in <module>
    from pyproj.proj import Proj, pj_list  # noqa: F401
  File "X:\pypy3\site-packages\pyproj\proj.py", line 21, in <module>
    from pyproj._transformer import Factors, _Transformer
  File "pyproj\_transformer.pyx", line 1, in init pyproj._transformer
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject
```

The issue is that there is "no clean C interface to the array.array object in Python". See discussion at https://github.com/h5py/h5py/issues/1514 and https://github.com/h5py/h5py/pull/1515 for a possible fix.

**Comment by snowman2** [comment]
Related: https://github.com/conda-forge/pyproj-feedstock/pull/90

**Comment by stonebig** [comment]
hope ?

**Comment by snowman2** [comment]
This may be useful: https://github.com/python/cpython/blob/a045991f60b51636a784623dda7ad84b5b2c6b73/Include/tupleobject.h#L30

**Comment by snowman2** [comment]
For reference: https://foss.heptapod.net/pypy/pypy/-/issues/3039 (from: https://github.com/conda-forge/pyproj-feedstock/pull/90#issuecomment-795674854)

**Comment by cgohlke** [comment]
> I have lot of (new ?) problems of messageless crash with PyPy-3.7-7.3.6 just released (and rc3, and rc2).

That is also my experience.  I get reproducible crashes in numpy's `_multiarray_umath` extension. Unfortunately pypy does not ship with debug symbols. The `PyErr_SetFromWindowsErr` function seems to have changed ABI. Not sure that is causing these problems. I'll skip PyPy-3.7-7.3.6 for now. Recompiling is not an option.

**Comment by stonebig** [comment]
there seems to be a hint from https://libera.irclog.whitequark.org/pypy/2021-10-18
"more fallout from the release: it seems CPython on windows moved to linking with libffi-8 when we link with libffi-7"

**Comment by mattip** [comment]
@cgohlke PyPy-3.7-7.3.6 broke binary compatibility with previous versions. I released 7.3.7 to revert the breaking changes. Sorry for the mess.

**Comment by cgohlke** [comment]
Thank you! Do you think it is safe to start building for pypy3.8-v7.3.7?

**Comment by mattip** [comment]
I think so. it would be nice to get some feedback. Issues of failures can be opened on the [PyPy bug tracker](https://foss.heptapod.net/pypy/pypy/-/issues)

**Comment by stonebig** [comment]
Hi. I'm a bit lost in thoughts, 

On My PC, with pypy3.7-v7.3.7-win64.zip and re-downloaded pyproj-3.2.1-pp37-pypy37_pp73-win_amd64.whl wheel ,  this basic test from first cells of https://github.com/pyproj4/pyproj/blob/master/docs/advanced_examples.rst fails:

````
import numpy as np
from pyproj import Transformer, transform

transformer = Transformer.from_crs(2263, 4326)
x_coords = np.random.randint(80000, 120000)
y_coords = np.random.randint(200000, 250000)
````

````
Python 3.7.12 (44db26267d0a, Oct 24 2021, 14:22:11)
[PyPy 7.3.7 with MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
========== RESTART: C:/WinP/bd37/buPyPy/WPy64-37120/notebooks/test.py ==========
Traceback (most recent call last):
  File "C:/WinP/bd37/buPyPy/WPy64-37120/notebooks/test.py", line 2, in <module>
    from pyproj import Transformer, transform
  File "C:\WinP\bd37\buPyPy\WPy64-37120\pypy3.7-v7.3.7-win64\site-packages\pyproj\__init__.py", line 49, in <module>
    import pyproj.network
  File "C:\WinP\bd37\buPyPy\WPy64-37120\pypy3.7-v7.3.7-win64\site-packages\pyproj\network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
  File "pyproj\_network.pyx", line 1, in init pyproj._network
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject
>>> 
````

**Comment by mattip** [comment]
The only binary wheel for PyPy on https://pypi.org/project/pyproj/#files is one for windows. Perhaps somehow it missed the change in #883?

**Comment by snowman2** [comment]
@cgohlke creates the Windows wheels. The wheels for Linux & OSX are built here: https://github.com/pyproj4/pyproj-wheels/. Contributions welcome =).

**Comment by stonebig** [comment]
@cgohlke made another wheel, so problem moved down to rtree wheel now, that seems a bit lost with pypy3.7-v7.3.7 old way of things 
![image](https://user-images.githubusercontent.com/4312421/139585245-05df7d1e-8ec6-48c0-b8ec-2e901d4f5d71.png)

pypy3.8-v7.3.7 is clother to cPython standard, so unmaintained rtree may feel better.

see also rtreee issue

**Comment by stonebig** [comment]
after copying around rtree DLLs, another tree hit

````
Python 3.7.12 (44db26267d0a, Oct 24 2021, 14:22:11)
[PyPy 7.3.7 with MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: C:\WinP\bd37\buPyPy\WPy64-37120\notebooks\sea.py ==========

================================ RESTART: Shell ================================
>>> 
========= RESTART: C:/WinP/bd37/buPyPy/WPy64-37120/notebooks/pyproj.py =========
Traceback (most recent call last):
  File "C:/WinP/bd37/buPyPy/WPy64-37120/notebooks/pyproj.py", line 2, in <module>
    from pyproj import Transformer, transform
  File "C:/WinP/bd37/buPyPy/WPy64-37120/notebooks\pyproj.py", line 2, in <module>
    from pyproj import Transformer, transform
ImportError: cannot import name 'Transformer'
>>> 
````

**Comment by stonebig** [comment]
transformer.py seems lowercase on Windows

**Comment by stonebig** [comment]
Back to this problem on PyPy-3.8rc1+nightly....
... it's the only binary problem I still detect, as PyPy-3.8 has now roughly as much compatible packages as PyPy-3.7

**Comment by mattip** [comment]
@stonebig could you confirm you are using pyproj 3.3 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj, and that this line fails?
```
>>>> import pyproj
```

**Comment by cgohlke** [comment]
I have once again recompiled the pyproj package for PyPy and it is importing again.  I think this issue is due to Cython producing incompatible versions of C files when cythonizing on CPython vs PyPy, which makes it hard and error prone to build CPython and PyPy wheels from the same copy of the source without removing the cythonized files in between builds.

**Comment by mattip** [comment]
Thanks @cgohlke. It seems this [cython-translation time directive](https://github.com/pyproj4/pyproj/blob/acaee8e06f05525cfc3ad43b20c87488304367b2/pyproj/_compat.pyx#L20), which was added in #883, means that the cython c-code will indeed change depending on implementation. Over at cython/cython#3448, the discussion of this problem ended with 
> I think it's ok to consider the array.array internals CPython specific. Using them is not (currently) compatible with PyPy. The decision is then up to the users.

and cython HEAD emits a warning when using array.array on PyPy. 

In [h5py](https://github.com/h5py/h5py/pull/1515/files#diff-127ecfd93b1377842f09e180a5bc7ede2b200f7d9bf8846203d36820636b1354R495) a similar problem was solved by replacing a local variable that used `array.array('B', n)` with `<char *>emalloc(n)`, but it seems replacing `create_array` with something that requires a deallocation step will be more intrusive for pyproj, since the returned named tuple from GeodIntermediateReturn has  `array.array` for `lons`, `lats`, and `azis` (sp?).

Perhaps the translation time directive could be replaced with a runtime check for `sys.implementation.name == 'pypy'`. This would work because the cython code `from cpython cimport array; cdef array.array` compiles on PyPy but would not run at runtime so the warning would not be emitted (the alternative code path is slightly slower).

**Comment by stonebig** [comment]
Aaaaegh, I get à 404 trying to download New pypy wheel, the 24h before I was getting a "site not responsive in time"
