### ISSUE TITLE
pyproj  3.1.0 build fails for python 3.10.0b1

### ISSUE THREAD

**Issue by jdkloe** [pyproj4/pyproj#855]
#### Problem description

For the next Fedora cycle all packaged python packages are currently being tested against a preliminary version of python 3.10.0. 
The build is performed in a mock sandbox environment. During this testing it was found that the pyproj package release 3.1.0 fails to build in this environment.

For details of the reported crash see: https://bugzilla.redhat.com/show_bug.cgi?id=1964955

The cause has been tracked down to the pyproj/enum.py module. This one sub-classes enum.IntFlag to create GeodIntermediateFlag, and it seems it is no longer allowed to define this sub-class using a non-consecutive range of bits.
This is an intended change in python 3.10, and was introduced with this commit: 
https://github.com/python/cpython/commit/7aaeb2a3d682ecba125c33511e4b4796021d2f82 but it seems not well documented yet.

A possible solution is to define additional constants that fill the gap between the 3 defined groups of bits in this class.
This patch has been submitted now for Fedora to let the pyproj build pass again. For details see: https://src.fedoraproject.org/rpms/pyproj/blob/rawhide/f/pyproj-enums.patch

If you wish I can provide a pull request that fixes the issue, but as stated in the bugzilla bug report, this seems a backwards incompatible change in Python, so it could as well be reverted before he final python 3.10.0 release. So maybe it is better to wait for that one to happen before modifying the pyproj code here on github.

**Comment by snowman2** [comment]
Thanks for testing and raising the issue 👍. After 3.10 is released a PR with a fix would definitely be welcome and appreciated if it is still needed.

**Comment by snowman2** [comment]
@jdkloe did you submit a report to cpython to see what their thoughts on this behavior change are?

**Comment by jdkloe** [comment]
Not myself, but my fedora colleague Miro Hrončok did. See his bug-report: https://bugs.python.org/issue44242
As I understand from the discussion in this topic, the behavior change was reverted again.
So if we are lucky no change is needed in pyproj afterall.
