### ISSUE TITLE
Pyproj logs PROJ_ERROR at debug level

### ISSUE THREAD

**Issue by adybbroe** [pyproj4/pyproj#873]
This is equivalent to #822 
But while the message "PROJ_ERROR: proj_crs_get_sub_crs: Object is not a CompoundCRS" is now gone I see this

#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
from pyproj import Proj
import logging
logging.basicConfig(level=logging.DEBUG)

p = Proj("+proj=stere +a=6370000 +b=6370000 +lat_0=90 +lat_ts=60 +lon_0=10 +units=m +no_defs")

p.crs.source_crs
# DEBUG:pyproj:PROJ_ERROR: proj_crs_get_coordoperation: Object is not a DerivedCRS or BoundCRS
```
#### Problem description

Pyproj ouputs the following error message on debug log level:

`DEBUG:pyproj:PROJ_ERROR: proj_crs_get_coordoperation: Object is not a DerivedCRS or BoundCRS`

I have started seeing this with Pyproj 3.1.0, whereas the one reported in #822 is now gone. I tested with pyproj 2.6.1 and PROJ 7.1.1 and it is not there.

#### Expected Output

No log message or at least not a DEBUG message with a PROJ_ERROR.

#### Environment Information

 - Output from: `pyproj -v`

```
pyproj info:
    pyproj: 3.1.0
      PROJ: 8.0.1
  data dir: /home/a000680/miniconda3/envs/pps_imagery-0.2.38/share/proj
user_data_dir: /home/a000680/.local/share/proj

System:
    python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0]
executable: /home/a000680/miniconda3/envs/pps_imagery-0.2.38/bin/python
   machine: Linux-4.18.0-305.7.1.el8_4.x86_64-x86_64-with-glibc2.10

Python deps:
   certifi: 2021.05.30
       pip: 21.1.3
setuptools: 49.6.0.post20210108
    Cython: None
```

 - Output from: `python -m pyproj -v`

 - Output from: `python -c "import pyproj; pyproj.show_versions()"`

 - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
 - PROJ data directory (`python -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

#### Installation method

conda-forge

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by snowman2** [comment]
@adybbroe is this something you are interested in submitting a fix for?

**Comment by snowman2** [comment]
Thanks for the report 👍
