### ISSUE TITLE
ValueError for TransformDirection

### ISSUE THREAD

**Issue by rgeologist** [pyproj4/pyproj#894]
I get a ValueError when I run a simple transformation:

from pyproj import Transformer
transformer = Transformer.from_crs("EPSG:4326", "EPSG:26917")
transformer.transform(50, -80)

ValueError: Invalid value supplied 'TransformDirection.FORWARD'. Only ('FORWARD', 'INVERSE', 'IDENT') are supported.

#### Environment Information
>>>pyproj.show_versions()

pyproj info:
    pyproj: 3.1.0
      PROJ: 8.0.1
  data dir: C:\Users\.....\Anaconda3\envs\Work202101\Library\share\proj
user_data_dir: C:\Users\....\AppData\Local/proj

System:
    python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\......\Anaconda3\envs\Work202101\python.exe
   machine: Windows-10-10.0.19042-SP0

Python deps:
   certifi: 2021.05.30
       pip: 21.1.3
setuptools: 49.6.0.post20210108
    Cython: None

#### Installation method
 - conda

>>>conda list proj
# Name                    Version                   Build  Channel
proj                           7.2.0                h1cfcee9_2    conda-forge
pyproj                       3.1.0                py38h31072cf_3    conda-forge

**Comment by snowman2** [comment]
Unfortunately, the only thing I have to re-produce this is the CI pipelines and they all are working fine for windows. Are you able to provide the exact steps you used to install pyproj?

https://pyproj4.github.io/pyproj/latest/installation.html
The best success usually comes when you have conda configured with these commands:
```
conda config --prepend channels conda-forge
conda config --set channel_priority strict
```
And then create a new environment:
```
conda create -n test pyproj
```

**Comment by rgeologist** [comment]
I re-installed pyproj and the error message disappeared. Now it's working properly.
Sorry for the inconvenience.
