### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by stdavis** [pyproj4/pyproj#9]
When I try to install via pip I get:
![image](https://cloud.githubusercontent.com/assets/1326248/7237297/d06b80a0-e757-11e4-8ef8-303a8ae58d96.png)

I get a similar error when I try to run `python setup.py build` after manually downloading the project.

What am I doing wrong?

**Comment by micahcochran** [comment]
First, try installing [Microsoft Visual C++ Compiler for Python 2.7](http://www.microsoft.com/en-us/download/details.aspx?id=44266).

If that doesn't work, I'd suggest installing a different python environment such as [OSGeo4W](http://wiki.osgeo.org/wiki/OSGeo4W) which can easily install the Proj.4 library from its setup and the gcc compiler.  It is focused on software for GIS.

**Comment by ChrisBarker-NOAA** [comment]
Note:  if you use the "Microsoft Visual C++ Compiler for Python 2.7.", then ``pip install`` should work. but plain old ``setup.py build`` probably won't. That compmiler needs setuptools, which the setup.py does not use, but pip monkey-patches in. I'll be raising an issue / pull request on this soon.

Also - this is using ArcGIS's Python -- is that what you want? -- just making sure. And it may not sork right with that compiler, either :-(

**Comment by snowman2** [comment]
Related to #216
