### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by shane17** [pyproj4/pyproj#91]
$ python setup.py build
nad2bin.c
nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
pj_malloc.c
using bundled proj4..
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
  File "C:\Python27\lib\distutils\ccompiler.py", line 700, in link_executable
    debug, extra_preargs, extra_postargs, None, target_lang)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 669, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\Users\shane\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\WinSDK\Bin\x64\mt.exe' failed with exit status 31

Phyton 2.7
Visual C 2.7

**Comment by micahcochran** [comment]
I do not think I have enough information to help you.

I assume based your issue that "Visual C 2.7" means that you have installed [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

You might try installing pyproj using pip,  `C:\...> pip install pyproj`

Out of curiosity, what version of setuptools are you running? `C:\...> pip list | find "setuptools"`, which you could try upgrading.

**Comment by shane17** [comment]
Yes, i meant Microsoft Visual C++ Compiler for Python 2.7. 
If you need any more kind of information, I will be happy to prove it.

Trying to install pyproj using pip gives the exact same error unfortunately :(

I am running setuptools 25.1.6, 

But trying to check the version of setuptools using C:\...> pip list | find "setuptools" gives the following result:

$  pip list | find "setuptools"
find: ‘setuptools’: No such file or directory
Traceback (most recent call last):
  File "c:\python27\lib\logging\__init__.py", line 882, in emit
    stream.write(fs % msg)
  File "c:\python27\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\python27\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\python27\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 175, in write_plain_text
    self.wrapped.flush()
IOError: [Errno 22] Invalid argument
Logged from file list.py, line 202

**Comment by micahcochran** [comment]
Another shot in the dark.  What version of pip are you running?  `C:\...> pip --version`

**Comment by shane17** [comment]
Wow, interesting ... 

This is what is showed yesterday:

$ python --version
Python 2.7.12
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

This is what it shows today 

$ pip --version
Access is denied.

as well as a pop-up saying "this app cant run on your PC"

strange ..

**Comment by Br3ttl3y** [comment]
I had this exact same problem.  Did you ever find an answer?

```
$ pip install -U pyproj
Collecting pyproj
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\brett\appdata\local\temp\pip-build-xysdqt\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "c:\python27\lib\distutils\ccompiler.py", line 700, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 669, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Users\\brett\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\mt.exe' failed with exit status -1073741819

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\brett\appdata\local\temp\pip-build-xysdqt\pyproj\
```
I have the same versions as mentioned above.

**Comment by micahcochran** [comment]
What shell are you using under Windows with a $ prompt?  Is it bash?

**Comment by Br3ttl3y** [comment]
I was able to get it working.  The problem that I faced is that I was following a stupid tutorial.  The tutorial told me to remove the slash from the end of the Python PATH Environment variable.  Once I added it back on, everything was gravy.

**Comment by snowman2** [comment]
Refer to #216
