### ISSUE TITLE
Set PROJ_DIR variable - Streamlit and Heroku

### ISSUE THREAD

**Issue by bryanvallejo16** [pyproj4/pyproj#963]
#### I am having the next error while trying to deploy streamlit app in Heroku. Can you help to solve this issue?
I have installed in my conda environment pyproj 2.6.1 and proj 6.2.1. But I don't know how to proceed.
```
Collecting pyproj==2.6.1.post1
         Downloading pyproj-2.6.1.post1.tar.gz (545 kB)
         Installing build dependencies: started
         Installing build dependencies: finished with status 'done'
         Getting requirements to build wheel: started
         Getting requirements to build wheel: finished with status 'error'
         ERROR: Command errored out with exit status 1:
          command: /app/.heroku/python/bin/python /app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpuon0t3u5
              cwd: /tmp/pip-install-ngmj79vl/pyproj
         Complete output (1 lines):
         proj executable not found. Please set the PROJ_DIR variable
```

#### I have the file setup.sh
```
mkdir -p ~/.streamlit/
echo "\
[server]\n\
headless = true\n\
port = $PORT\n\
enableCORS = false\n\
\n\
" > ~/.streamlit/config.toml
```
#### I have requirements.txt
```
pyproj==2.6.1.post1
Shapely==1.7.1
pandas==1.3.2
streamlit==0.88.0
geopandas==0.8.1
matplotlib==3.3.2
requests==2.26.0
Pillow==8.3.2
```
#### and Procfile.txt
```
web: sh setup.sh && streamlit run myapp.py
```

**Comment by snowman2** [comment]
Sounds like you need to conda install `conda install -c conda-forge pyproj=2.6.1.post1`

**Comment by bryanvallejo16** [comment]
Hi. Actually I have it already installed.
![image](https://user-images.githubusercontent.com/56689972/134768527-575ffc6d-d35b-483f-9227-3382a5d04b9b.png)

Seems the problem is that it is not defined the variable PROJ_DIR  that specifies the URL of the PROJ executable. I have the PROJ executable in the local. Is that I have to define it in the .sh file? How can I do so?
I would appreciate support.

**Comment by snowman2** [comment]
It looks like it is not finding your conda environment. You probably need to activate it before running the application.

**Comment by bryanvallejo16** [comment]
It is activated. It fails in deploying and asks me to define PROJ_DIR and I am lost in this step.
![image](https://user-images.githubusercontent.com/56689972/134816961-c0c52846-5cfd-49e7-aec2-cc9905c4ef60.png)
