### ISSUE TITLE
Can use project in AWS lambda with zappa, with version <= 2.6.0. Can't with 2.6.1 and above

### ISSUE THREAD

**Issue by Cameronsplaze** [pyproj4/pyproj#977]
#### Code Sample, a copy-pastable example if possible

I can't think of how, but I'd be happy to add something if you can.

#### Problem description

Personally using this package through GeoPandas. zappa==0.53.0 to update AWS lambda.

- If I bump this package to 2.6.1 to install it's dependencies, zappa's last step will throw a HTTP 503 when checking if the lambda got deployed correctly. 
- If I delete this package but NOT it's dependencies, the lambda is able to deploy.
   - If I install 2.6.0 with those same dependencies, it still deploys.
- I reinstalled my virtualenv after each of these checks:
```bash
rm -rf ~/Devel-env
virtualenv --python=python3 ~/Devel-env
source ~/Devel-env/bin/activate
```

#### Expected Output

For versions to support lambda like pyproj<=2.6.0

#### Environment Information

 - Output from: `python -m pyproj -v`
```
pyproj info:
    pyproj: 2.6.0
      PROJ: 6.3.1
  data dir: /home/victor/SearchAPI-env/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
executable: /home/victor/SearchAPI-env/bin/python
   machine: Linux-5.11.0-36-generic-x86_64-with-glibc2.29

Python deps:
       pip: 21.2.4
setuptools: 44.0.0
    Cython: None

```

 - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
 - PROJ data directory (`python -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
/home/victor/SearchAPI-env/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
Linux-5.11.0-36-generic-x86_64-with-glibc2.29

#### Installation method
 - conda, pip wheel, from source, etc...
 `pip install -r requirements.txt` for everything

**Comment by snowman2** [comment]
Without the Zappa config file, It is hard to tell. Here are some thoughts to help you debug.

Have you tried the latest pyproj (3.2.1)?

The AWS Lambda size limit is 50 MB, you should check the size of your zipped lambda file if you are using wheels:
pandas 12 MB
numpy 16 MB
fiona 15 MB
pyproj (3,2.1 = 7 MB; 2.6.0 = 11 MB; 2.6.1 = 11 MB)
shapely 1 MB
geopandas 1 MB

Also, if you aren't using this already, you may be interested in https://github.com/lambgeo.
