### ISSUE TITLE
Installation with Anaconda fails

### ISSUE THREAD

**Issue by lambichr** [pyproj4/pyproj#980]
#### Installation method/steps
```
conda config --prepend channels conda-forge
conda config --set channel_priority strict
conda install pyproj
```

#### Environment Information
 - pyproj version you are attempting to install: 
   ->3.2.1
 - PROJ version (Execute `proj` command and give version here.): 
   -> Rel. 8.1.1, September 1st, 2021
usage: proj.exe [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
   -> 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
   -> Windows-10-10.0.19042-SP0

When I try to use `pyproj`, with `from pyproj import CRS` I get the following:

    C:...\Miniconda3\envs\geo_env\lib\site-packages\pyproj\__init__.py:89: UserWarning: pyproj unable to set database path.
     _pyproj_global_context_initialize()

**Comment by snowman2** [comment]
I think you need to activate the specific environment: `conda activate geo_env`

**Comment by lambichr** [comment]
@snowman2 The way I solved it now:

    conda remove --force pyproj

This removes the library from the `conda environment` and then 

    pip install pyproj

Now I do not get the error upon calling `from pyproj import CRS`.
