### ISSUE TITLE
pyproj fails to install for python 3.10.0

### ISSUE THREAD

**Issue by patrickleclair-GORDONFN** [pyproj4/pyproj#981]
#### Code Sample, a copy-pastable example if possible
A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
pip install pyproj --no-cache-dir
```
#### Problem description
When trying to pip install pyproj with the most up-to-date version of pip (21.3) and python (3.10.0) it fails by not being able to access one of the files in  `~Python\Python310\lib\subprocess.py`. 

`line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`

#### Environment Information
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
  3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)
Windows-10-10.0.19042-SP0

#### Installation method
 - conda, pip wheel, from source, etc...
pip install

**Comment by snowman2** [comment]
Python 3.10 windows wheels can be found here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj

**Comment by snowman2** [comment]
pyproj 3.3.0 wheels are available now: https://github.com/pyproj4/pyproj/discussions/998#discussioncomment-1661943
