### ISSUE TITLE
Correct way to convert to EPSG:4326 with given central longitude

### ISSUE THREAD

**Issue by tovogt** [pyproj4/pyproj#988]
Let's suppose I want to convert from EPSG:26917 to EPSG:4326, but with longitude ranging from 0 to 360. Here is how I would do this:
```
>>> from pyproj import Transformer
>>> transformer = Transformer.from_crs(26917, "+init=epsg:4326 +lon_wrap=180", always_xy=True)
$CONDA_PREFIX/lib/python3.8/site-packages/pyproj/crs/crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
>>> transformer.transform(571666, 5539109)
(279.999993604676, 49.999992723193955)
```
As you see, this works as expected, but it produces a `FutureWarning`. If I'm not mistaken, there is no "correct" way how to do this kind of transformation without this warning. This feature request is to ask for a "correct" (not deprecated) way to do this kind of transformation with pyproj.

**Comment by snowman2** [comment]
Related: https://github.com/OSGeo/PROJ/pull/2914

**Comment by snowman2** [comment]
This would have to be implemented in PROJ. Either that or just add 180 to longitude:
```python
lon, lat = transformer.transform(571666, 5539109)
lon += 180
```

**Comment by tovogt** [comment]
Thanks for your quick response! However, I really want to specify an arbitrary central longitude, not 180 (this was just an example).

**Comment by snowman2** [comment]
Does this meet your needs? `+proj=lonlat +lon_wrap=180`

**Comment by tovogt** [comment]
Ah, seems to work well. Is this equivalent with `+init=epsg:4326 +lon_wrap=180`?

**Comment by snowman2** [comment]
> Is this equivalent with +init=epsg:4326 +lon_wrap=180

Yes, it should be.

**Comment by tovogt** [comment]
Okay, then this solves this issue for me. Thanks for your great support!
