### ISSUE TITLE
Incorrect result and unable to build PROJ string for MGA 55 to WGS 84 transform in pyproj v3.1

### ISSUE THREAD

**Issue by EpicWink** [pyproj4/pyproj#989]
I'm getting different results between PyProj v3.0.1 and v3.1 for the MGA 55 (EPSG 28355) to WGS 84 (EPSG 4326) transformation; in addition, the transformer in v3.1 can't produce a PROJ string

I feel like this is an issue with PROJ v8

#### Code sample
```python
import pyproj
t = pyproj.Transformer.from_crs("epsg:28355", "epsg:4326")
print(repr(t))
print(str(t))
print(t.transform(800000,6000000))
```

#### Problem description
The output from PyProj v3.1 is incorrect (as far as I can tell)

#### Expected output
Output from PyProj v3.0.1
```
<Concatenated Operation Transformer: pipeline>
Description: Inverse of Map Grid of Australia zone 55 + GDA94 to WGS 84 (1)
Area of Use:
- name: Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.
- bounds: (93.41, -60.56, 173.35, -8.47)

proj=pipeline step inv proj=utm zone=55 south ellps=GRS80 step proj=unitconvert xy_in=rad xy_out=deg step proj=axisswap order=2,1

(-36.098349196454585, 150.33217717123762)
```

#### Actual output
Output from PyProj v3.1
```
<Unknown Transformer: unknown>
Description: unavailable until proj_trans is called
Area of Use:
- undefined

unavailable until proj_trans is called

(-36.09833644723916, 150.33218243077053)
```

##### PyProj v3.1
 - pyproj version: 3.1.0
 - PROJ version: 8.0.1
 - PROJ data directory: /media/linux-data/venvs/eggs/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

##### PyProj v3.0.1
 - pyproj version: 3.0.1
 - PROJ version: 7.2.1
 - PROJ data directory: /media/linux-data/venvs/spam/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

##### Common
 - Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
 - Operation System Information: Linux-5.11.0-38-generic-x86_64-with-glibc2.29

#### Installation method
pip wheel

**Comment by snowman2** [comment]
The underlying EPSG database changes between versions, so that could impact what operations are available.

The TransformerGroup is helpful to check what operations are available: https://pyproj4.github.io/pyproj/stable/advanced_examples.html#transformation-group

Also, the transformation results can change based on the presence/absence of the transformation grids:
https://pyproj4.github.io/pyproj/stable/transformation_grids.html

**Comment by EpicWink** [comment]
@snowman2 thanks. The group has two transformers:
```python
import pyproj.transformer
g = pyproj.transformer.TransformerGroup("epsg:28355", "epsg:4326")

print(repr(g.transformers[0]))
# <Concatenated Operation Transformer: pipeline>
# Description: Inverse of Map Grid of Australia zone 55 + GDA94 to WGS 84 (2)
# Area of Use:
# - name: Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.
# - bounds: (93.41, -60.55, 173.34, -8.47)

print(str(g.transformers[0]))
# proj=pipeline step inv proj=utm zone=55 south ellps=GRS80 step proj=push v_3 step proj=cart ellps=GRS80 step proj=helmert x=0.06155 y=-0.01087 z=-0.04019 rx=-0.0394924 ry=-0.0327221 rz=-0.0328979 s=-0.009994 convention=coordinate_frame step inv proj=cart ellps=WGS84 step proj=pop v_3 step proj=unitconvert xy_in=rad xy_out=deg step proj=axisswap order=2,1

print(g.transformers[0].transform(800000, 6000000))
# (-36.09833644723916, 150.33218243077053)

print(repr(g.transformers[1]))
# <Concatenated Operation Transformer: pipeline>
# Description: Inverse of Map Grid of Australia zone 55 + GDA94 to WGS 84 (1)
# Area of Use:
# - name: Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.
# - bounds: (93.41, -60.55, 173.34, -8.47)

print(str(g.transformers[1]))
# proj=pipeline step inv proj=utm zone=55 south ellps=GRS80 step proj=unitconvert xy_in=rad xy_out=deg step proj=axisswap order=2,1

print(g.transformers[1].transform(800000, 6000000))
# (-36.098349196454585, 150.33217717123762)
```

I guess for some reason PROJ 8 is recommending some Helmert projection over the simplier transformation pipeline, as the second transformer seeems to give the same result as `pyproj` v3.0

**Comment by snowman2** [comment]
This might also be a useful reference: https://proj.org/operations/operations_computation.html

**Comment by snowman2** [comment]
@EpicWink, I am going to close this as I think the issue has been resolved.

If you want to ensure a specific operation is used instead of relying on the order determined by PROJ, you can always use `Transformer.from_pipeline`:
```python
>>> tr = Transformer.from_pipeline("+proj=pipeline +step +inv +proj=utm +zone=55 +south +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1")
>>> tr.transform(800000, 6000000)
(-36.098349196454585, 150.33217717123762)
```

**Comment by onewhaleid** [comment]
I believe this issue is related to the change from the Geocentric Datum of Australia (GDA94 to GDA2020). There is more information available here:
https://www.spatial.nsw.gov.au/surveying/geodesy/gda2020

The specific issue with transformations to and from WGS84 is discussed here:
https://www.spatial.nsw.gov.au/__data/assets/pdf_file/0008/224396/WGS84_and_Australias_misaligned_web-maps_Information_Sheet.pdf
